### ISSUE TITLE
helmpack/tiller v2.16.12

### ISSUE THREAD

**Issue by fhuitelec** [helm/helm#10015]
Hi :wave:

The [v2.16.12](https://github.com/helm/helm/releases/tag/v2.16.12) image tag on Docker hub's helmpack/tiller is missing [[tag](https://hub.docker.com/r/helmpack/tiller/tags?page=1&ordering=last_updated&name=v2.16.12)]

Would it be possible to have make it available?

**Comment by bridgetkromhout** [comment]
Hi, @fhuitelec - it's possible that one is missing because it was a hotfix. Meanwhile, [v2.17.0](https://github.com/helm/helm/releases/tag/v2.17.0) is the final release of Helm v2; would that meet your current needs?

Also, Helm v2 contains CVEs that will never be patched, as [support of Helm v2 ended in November 2020](https://helm.sh/blog/helm-v2-deprecation-timeline/). Can you help us understand what barriers are in the way of your move to Helm v3? Thanks!

**Comment by bacongobbler** [comment]
As far as I understand, the migration of any old docker tags was a manual process prior to Helm 2.16.12's release, so it's possible it was missed. Automated builds were published starting with Helm 2.17.0.

Helm 2.16.12's deploy steps:

https://github.com/helm/helm/blob/47f0b88409e71fd9ca272abc7cd762a56a1c613e/.circleci/deploy.sh#L64-L65

Compared to Helm 2.17.0's deploy steps:

https://github.com/helm/helm/blob/v2.17.0/.circleci/deploy.sh#L71-L81

I'll see what I can do to publish Helm 2.16.12 to DockerHub - that's the only image that does not appear to be available there.

In the meantime, I'd highly suggest migrating to Helm 3 as @bridgetkromhout suggested earlier - Helm 2 has been unsupported for nearly a full year by now, and many CVEs have been flagged against Helm 3, and by extension those same exploits are unpatched for Helm 2. So you're running a very significant risk running Helm 2 in production.

**Comment by bacongobbler** [comment]
Fixed. Closing.

**Comment by fhuitelec** [comment]
Thank you for your responsiveness @bacongobbler, much appreciated!
