### ISSUE TITLE
tiller image gcr.io/kubernetes-helm/tiller:v2.15.2 no longer available

### ISSUE THREAD

**Issue by genisd** [helm/helm#10011]
Hi everyone, our tiller went offline and the image can no longer be pulled.
https://console.cloud.google.com/gcr/images/kubernetes-helm/GLOBAL/tiller?gcrImageListsize=30

Are we forced to upgrade or is it possible to have the tiller 2.15.2 image back available?

**Comment by genisd** [comment]
As per notes here: https://helm.sh/blog/new-location-stable-incubator-charts/
Tiller can now be pulled from github repo:
https://github.com/orgs/helm/packages/container/package/tiller

Here 2.15.2 is available

**Comment by hickeyma** [comment]
Related ticket: #10004 #10005

@genisd Google cloud storage support was announced to be dropped in 2020 and @bacongobbler describe this in https://github.com/helm/helm/issues/10005#issuecomment-894487872.

We strongly urge you to migrate to Helm 3 as Helm 2 went EOL on 13th of November 2020. Several major CVEs were discovered since then and are fixed in Helm 3 only.

Refer to [Helm 2 and the Charts Project Are Now Unsupported](https://helm.sh/blog/helm-2-becomes-unsupported/) for more details about EOL.
