### ISSUE TITLE
helm upgrade --wait does not wait on newer versions

### ISSUE THREAD

**Issue by haljin** [helm/helm#10061]
When running `helm upgrade --install --wait --timeout 5m0s <release>` on a `StatefulSet` with just one replica helm doesn't wait for pods to redeploy and become ready and just moves on. That causes the automated tests running afterwards to immediately fail as the pod redeploys in the middle of testing. 

This seems to happen on version 3.6.3, but works and waits correctly 3.2.4. We can downgrade helm for now, but it'd be nice not to have to micro-manage helm versions on our build agents. :(

**Comment by haljin** [comment]
As I mentioned, the operation seems to correctly wait until the pods become ready on `3.2.4` but on `3.6.3` it does not.

**Comment by mattfarina** [comment]
What version of Kubernetes are you using with this version of Helm? The changes have been in packages provided by the Kubernetes project. I wonder if there is a supported version mismatch.

**Comment by haljin** [comment]
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"95881afb5df065c250d98cf7f30ee4bb6d281acf", GitTreeState:"clean", BuildDate:"2021-04-25T08:15:25Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:00:37Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by grazius** [comment]
same problem on 3.4.2

**Comment by shwetanshu-cldcvr** [comment]
Current Behavior: 
I have the same issue and it is happening with Deployments. I provided an incorrect repo to the helm chart, upgrade it using helm and the helm chart gets deployed successfully. However, since I provided incorrect repo, the the pod fails to start with ErrImagePull. 

Expected Behavior: 
If the image is incorrect (or for any reason, pod fails to go into Running status), the Helm Upgrade/Install should fail. 

Command Used:
helm upgrade --install test . -f test.yaml --timeout 300s --atomic

Version:
`➜  helm version

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
➜  kubectl version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.2101", GitCommit:"05fc1fdacb292655c77a2058a32ecc6a82cd71b0", GitTreeState:"clean", BuildDate:"2021-08-18T23:13:48Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by hobbytp** [comment]
Any new update here?

**Comment by agates4** [comment]
Any new update here?

**Comment by muang0** [comment]
Potentially related: https://github.com/helm/helm/issues/10859

**Comment by hudzy** [comment]
Same here, --wait argument failed to work on some of our CI/CD pipelines, however --atomic argument works fine.

Tested with version 3.8.2, 3.7.2, 3.6.3 and 3.5.4. Oddly, --wait argument is only working correctly on v3.5.4.

**Comment by hobbytp** [comment]
From the latest info here, the issue is still there. Can we re-open this issue?

**Comment by psblah** [comment]
I'm also seeing this.

Helm version 3.8.1

Kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1100", GitCommit:"20da4c21b3a6b1a56ff6ad5ecb7dee013aaf1b83", GitTreeState:"clean", BuildDate:"2022-04-01T09:40:07Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
