### ISSUE TITLE
Proposal: Support global variable for cases like Release.time

### ISSUE THREAD

**Issue by Siegfriedk** [helm/helm#10074]
Hi,

we have a use case were i would like to use the template function now to generate a unique datetime and being able to add it to multiply locations in our chart.

In helm 2 there was a Release.Time which got deprecated with helm3 (https://github.com/helm/helm/issues/5732) and as a solution the template function 'now' was mentioned.

Unfortunate this can't work as now is generating a new datetime whenever it is called and therefore does not have the same behaviour than the previously existing Release.Time.

There is also this issue https://github.com/helm/helm/issues/6456 were someone was looking into a solution for a global random string and it was closed with a remark that it needs to be in one file to work.

I tried myself calling 'now' in values.yaml which is not allowed and i was playing around with trying to set a variable in a template function which also doesn't work.

I would propose therefore to provide basic support for a 'global' variable construct which can be used for those usecases.

Potential ideas:
- allow basic templating in values.yaml (was declined here https://github.com/helm/helm/issues/2492 due to complexity)
    `creationDate:"{{ now | date "2000-01-02 15:39"}}"`
- global variable support in templating
```Smarty
    {{- define "creationDate" -}}
      {{- if not $creationDate -}}
        {{ $creationDate := now | date "2000-01-02 15:39"}}
      {{- end -}}
      {{- $creationDate -}}
    {{- end -}}
```
- annotation for singleton which is interpreted once and then only the output is used
```Smarty
    {{- define "creationDate":@global,@once,@singleton -}}
      {{- if not $creationDate -}}
        {{ $creationDate := now | date "2000-01-02 15:39"}}
      {{- end -}}
      {{- $creationDate -}}
    {{- end -}}
```
- add global version of templating function like gnow which would then return the same value (this would not solve all issues of this type automatically but would probably much easier to implement) a global random function could have a unique seed to allow for multiply calls of it for other use cases.
    - now
    - ago
    - rand*
    - shuffle
    - uuidv4
    - ?
- something much smarter and easier than my ideas :-)

**Comment by krancour** [comment]
Adding a +1 to this.

This was a major source of frustration for me recently.

I have a chart that, on install, generates secure random values for things like passwords. Each such value is typically used in two places-- 1. a Secret template, 2. a Deployment template will _also_ render the secret and pipe it into `sha25sum` and use that as the value of an annotation in the pod template. This is a common work around to ensure Deployments roll their pods when relevant secrets are updated.

Because generating random value is non-deterministic, the checksum I end up with doesn't match the actual secret.

This forced me to put my secrets and deployments in the same file. 🤮 

If there were some way to dynamically initialize variables that would be accessible throughout the entire chart, that would solve the OP's issue, mine, and many others of this ilk.

@mattfarina I understand the limitations of the Go template package...

I am wondering if a clean approach to solving this might be to have the template rendering begin with a new step that pre-renders certain templates and then makes their values available to the remainder of the templates.

**Comment by krancour** [comment]
After more thought, I can be more specific about how my idea might work.

We could introduce a new template file named (something like) `dynamic-values.yaml`.

Rendering would be done in two passes.

The first pass would render the `dynamic-values.yaml` down into plain yaml.

In the second pass, values from `dynamic-values.yaml` would become available to all the other templates as (something like) `.DynamicValues`.

I'd be happy to PR this if there were buy-in.

**Comment by krancour** [comment]
@technosophos how would you control the order in which templates are rendered?

**Comment by krancour** [comment]
I don't believe this should be closed. Also, I'm still willing to PR what I suggested if there is buy-in from maintainers.

**Comment by krancour** [comment]
Still don't think this should be stale... still willing to implement if there's any buy-in.
