### ISSUE TITLE
Proposal: apply action.List.Selector in secrets.impl.List

### ISSUE THREAD

**Issue by mtt0** [helm/helm#10087]
Helm List procedure:

1. Use k8s client to download secrets, filtered by lable `owner`

https://github.com/helm/helm/blob/3d1bc72827e4edef273fb3d8d8ded2a25fa6f39d/pkg/action/list.go#L161-L168

https://github.com/helm/helm/blob/3d1bc72827e4edef273fb3d8d8ded2a25fa6f39d/pkg/storage/driver/secrets.go#L81-L88

https://github.com/helm/helm/blob/3d1bc72827e4edef273fb3d8d8ded2a25fa6f39d/pkg/action/lazyclient.go#L99-L104

2. Decode(decode base64 string and unzip if compressed)

https://github.com/helm/helm/blob/3d1bc72827e4edef273fb3d8d8ded2a25fa6f39d/pkg/storage/driver/secrets.go#L94-L95

https://github.com/helm/helm/blob/3d1bc72827e4edef273fb3d8d8ded2a25fa6f39d/pkg/storage/driver/util.go#L58-L67

3. Filter releases(Latest, StateMask, Selector)

https://github.com/helm/helm/blob/3d1bc72827e4edef273fb3d8d8ded2a25fa6f39d/pkg/action/list.go#L181-L194

And if we have large amount of releases, then `helm list` will be very slow. Because helm must download releases first and then apply filters.

Note that, the **release.Labels** comes from this release's **Secret**
https://github.com/helm/helm/blob/3d1bc72827e4edef273fb3d8d8ded2a25fa6f39d/pkg/storage/driver/secrets.go#L101

And the Secret of this release also has a lable `status`:

![image](https://user-images.githubusercontent.com/17849741/131655817-461170bd-8969-4114-a7d2-27247b0f3db1.png)

So why not add action.List.Selector for gaining higher performance

https://github.com/helm/helm/blob/3d1bc72827e4edef273fb3d8d8ded2a25fa6f39d/pkg/storage/driver/secrets.go#L85

If helm add more labels(Uninstalled, Superseded, Uninstalling, Deployed, Failed, Pending) like `action.List` definition, then we are able to apply State filter before download.

What's more, if `helm install` and `helm upgrade` could set customer labels to the helm release then users can group/search their releases as they want.

ConfigMap Driver is simillar to Secret Driver.

**Comment by mattfarina** [comment]
@mtt0 You're asking a good question. I'll try to add some context here.

First, I would love for this to be more performant. So, I am open to suggestions and ideas on doing that.

Second, in addition to the secrets and configmap mechanism for storage there are the memory and SQL storage backends. Both are in use and both would need to be modified for a new mechanism which should be possible.

Third, the APIs as they are today would not work. Instead of a filter function we would need to pass the details to the driver so it could use them appropriately.

Fourth, the release records would need to be updated to have the metadata needed. This is possible to do in a **backwards compatible** manner. Backwards compatibility is a major thing. That means that older Helm clients can use the newer records and newer helm clients can work with the older records. Across all the drivers.

I think all of this is possible in Helm v3 but it's a bit of work and no one has signed up to do it. I would likely need to start with a [Helm Improvement Proposal](https://github.com/helm/community/tree/main/hips). Someone would need to be interested in carrying this to completion on the code side.
