### ISSUE TITLE
Support streams in values files

### ISSUE THREAD

**Issue by raphink** [helm/helm#10125]
It would be useful if single values files could contain multiple documents. This way, a single file with multiple hashes could be provided.

This would be useful for example when passing ad-hoc values to ArgoCD Applications, as they are passed as a single string.

When implemented, passing a single values files containing:

```
---
image: "foo"
---
image: "overridden-foo"
```

should result in ` .Values.image` with value `overridden-foo`.

**Comment by bacongobbler** [comment]
I'm not sure I fully understand the use case, especially since this is already handled through passing multiple --values flags on the command line. Couldn't ArgoCD parse the single file into multiple documents, looping over each file and passing those as `--values` arguments?

I am concerned that by providing this functionality, we introduce security risk to downstream projects. Helm has always expected a single YAML document as valid input to `--values`. By extension, any project that consumes Helm's CLI to re-use the `--values` flag also expects that behavior. Changing that expectation could introduce potential mis-handling of a document stream... Or at worst a security issue.

**Comment by bacongobbler** [comment]
I think this idea [warrants a HIP](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea).

**Comment by raphink** [comment]
Thanks for reviewing @bacongobbler.

ArgoCD has various ways of dealing with helm values:
- an array of values files (taken from the repository)
- a string that contains a single additional values file

In our case, we pass values using this second option. However, we often need to pass multiple values and we would like to avoid merging the values on our sides, as it would mean mimicking helm's merge functionality. Since ArgoCD only allows a single file there, the only option (besides changing ArgoCD's Application interface, which would be much heavier) is to pass allow streams.

What security issues do you foresee with this feature?
