### ISSUE TITLE
Set default image pull policy to "Always"

### ISSUE THREAD

**Issue by mcandre** [helm/helm#10140]
In order to reduce caching mistakes, it would be helpful if Helm used a default image pull policy of `"Always"`, instead of `"IfNotPresent"`. Any users who wish to override this can provide an explicit image pull policy.

**Comment by bacongobbler** [comment]
On the other hand... Others want to remove the value entirely. See #8567.

I can understand why some users would offer differing opinions on the default values of `helm create`. Really, `helm create` is there to generate a very basic chart to help the user get started without offering too much in the way of flexibility. However, users can craft their own [starter charts](https://helm.sh/docs/topics/charts/#chart-starter-packs) which can be used to craft alternative workflows for their clients.

We opted to choose the default as "IfNotPresent" because that is the default value of a Pod when it is undefined by the user.

We'd accept a PR that removes the value entirely if not set by the user. That way Kubernetes can provide its dynamic default behavior as mentioned in #8567. This was not always the case, though I guess future Kubernetes updates now provides this feature.

Hope this helps provide some clarification on the decisions made in Helm's code base.

Thanks.
