### ISSUE TITLE
regression with global values in Helm 3.7.0

### ISSUE THREAD

**Issue by bcollard** [helm/helm#10154]
Given a chart with a subchart as visible here: https://github.com/bcollard/helm-3.7.0-global-values-issue
When I use a global value in a parent-level template that exists in the subchart values but not in the parent values,
I expect the subchart value to be used

That doesn't work anymore with Helm v3.7.0

------

Template example:

```go
{{- $menu := merge $.Values.menu $.Values.global.menu -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cfgmap2
data:
  dessert: {{ $menu.dessert }}
```

parent values:
```yaml
global:
  menu:
    main: salad

menu: {}

```

subchart values:
```yaml
global:
  menu:
    dessert: choco-subchart
```

Helm 3.6.4:
```bash
$ /usr/local/bin/helm3.6 template foo . -s templates/myconfigmap.yaml
```
Output:
```yaml
---
# Source: foo/templates/myconfigmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo-cfgmap2
data:
  dessert: choco-subchart
```

------
Helm 3.7.0:
```bash
helm template foo . -s templates/myconfigmap.yaml
```

```yaml
---
# Source: foo/templates/myconfigmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo-cfgmap2
data:
  dessert:
```
The value for `dessert` is empty.

--------
Output of `helm version`:
`version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.9-gke.701", GitCommit:"5f13de0910e4eb40c1c6b3b44704b25313a2c80c", GitTreeState:"clean", BuildDate:"2021-08-18T17:05:42Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

**Comment by bacongobbler** [comment]
Sign... It seems like a regression with coalescing values is introduced every other point release. Someone identifies an issue with how helm coalesces values for their chart, then a "fix" is introduced that happens to break it for someone else. This has occurred multiple times in the past.

I'm considering whether we should stop attempting to address any further coalescing issues until Helm 4 because I'm tired of regressions being (re)introduced every other point release.

@bcollard are you able to identify which commit caused the regression?

**Comment by bcollard** [comment]
Looking for commits about "subcharts" and "coalesce", I can see this particular commit: https://github.com/helm/helm/commit/3b68afc1c820d456e8281a6e6911af59c4b661c8
But I'm not sure at all!

**Comment by bacongobbler** [comment]
Thanks for looking into that. I pinged the author of #9756 to look into this.

Based on #9749, the author was looking fixing into a "potential bug". I cannot tell whether this was an actual fix or a theoretical one, introducing a regression in the process.

I even mentioned this could introduce bugs during review... https://github.com/helm/helm/pull/9756#pullrequestreview-672437719

I would definitely investigate that commit further by reverting it and re-compiling Helm to see if that fixes your issue.

**Comment by bcollard** [comment]
so yeah, I switched to tag 3.7.0, reverted this [commit](https://github.com/helm/helm/commit/3b68afc1c820d456e8281a6e6911af59c4b661c8) and now I have the expected result.

**Comment by bacongobbler** [comment]
Adding to the 3.8.0 milestone so we don't lose track of this.

**Comment by codeJack** [comment]
@bcollard @bacongobbler 

Indeed this is what #9756 aims fixing : the [ConfigMap template](https://github.com/bcollard/helm-3.7.0-global-values-issue/blob/master/templates/myconfigmap.yaml) is at parent chart level whereas the [dessert global value](https://github.com/bcollard/helm-3.7.0-global-values-issue/blob/master/charts/mysubchart/values.yaml#L7) is *only* set at sub chart level.

With Helm 3.6 sub chart global values would have "leaked" upstream affecting any other sub chart (as if the value had been explicitly set at parent level) and I'm not sure this is the expected behaviour.

**Helm 3.7 make sure that global values are only propagated downstream.**

To provide more context: in my case I had many sub charts some of which needed DB access.
With helm 3.6 behaviour setting the value `global.database: true` in one of the sub charts was enough to have it propagated everywhere else - including the sub charts that didn't actually need it !
With helm 3.7 behaviour the value `global.database: true` can be activated specifically for the sub charts that actually need it without affecting the rest of the hierarchy.

Hope this helps, let me know If you need further details.

**Comment by bacongobbler** [comment]
While I understand and appreciate what you were fixing, it does appear that a regression was introduced.

Can you please investigate this further and either come up with a fix. Otherwise we will have to revert the change. As per our [contributing policy on semantic versioning](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#semantic-versioning) we do take regressions quite seriously.

From the policy:

> - Any chart that worked on a previous version of Helm 3 MUST work on a new version of Helm 3 (barring the cases where (a) Kubernetes itself changed, and (b) the chart worked because it exploited a bug)

I don't think the use case @bcollard provided above can be construed as "exploiting a bug". Rather an expectation that the system worked in a certain way, and indeed it did until Helm 3.7.0.

**Comment by codeJack** [comment]
> I don't think the use case @bcollard provided above can be construed as "exploiting a bug".

I respectfully disagree. IMHO the above use case is exploiting a bug.

One of the reasons why it qualifies as a bug is simply that, if you have multiple sub charts defining the exact same global parameter - but with different values, a single child value will win and will be propagated everywhere else.

It  doesn't seem like an healthy behaviour to me and it can get extremely dangerous as well as tricky to investigate when you have a complex chart hierarchy.

Is the example clear or shall I back it up with a sample chart ? (do not hesitate to ask if that can help)

> Can you please investigate this further and come up with a fix?

There is no fix I can come up with: we have to stick with one behaviour or the other, it is a mere functional choice.

I fully trust your judgement here and will thereby accept the revert of the change. 
That being said it seems to me that reverting the change is simply the the easiest thing to do (being the coalesce values an historically regression-prone module etc etc) rather than being the right thing to do.

How many issues - that could be linked with my change - have been raised since its release ?

**Comment by bacongobbler** [comment]
Okay, I think I understand where the confusion is coming from. Sorry about that.

I thought the template @bcollard suggested was in the subchart. However looking [at the example](https://github.com/bcollard/helm-3.7.0-global-values-issue) more closely, it is in the parent chart. The code samples in the OP were not clear with this distinction.

I would expect the value to be null because a child's values should not influence how a parent's templates are rendered. In other words, Helm 3.7's behaviour is correct.

@bcollard why would you expect values from a subchart take precedence when a parent's templates are being rendered? I'm curious why you think it should work that way.

In other words I am starting to agree with @codeJack here. This does appear to qualify as an exploitation of a bug. Which in this case would mean we should close this out as intentional behavior.

**Comment by codeJack** [comment]
FYI I have extended @bcollard example with another subchart that sets the `global.menu.dessert` value to `vanilla-subchart`. Visible here : https://github.com/codeJack/helm-3.7.0-global-values-issue

This is how the ConfigMap renders now with helm 3.6

```sh
$ helm template foo . -s templates/myconfigmap.yaml
```

Output:
```yaml
---
# Source: foo/templates/myconfigmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo-cfgmap2
data:
  dessert: vanilla-subchart
```

**Comment by bcollard** [comment]
> @bcollard why would you expect values from a subchart take precedence when a parent's templates are being rendered? I'm curious why you think it should work that way.

That was not exactly the point. It was useful when the parent chart was missing this particular value. Then it was picked from the subchart.

Anyway, I also agree with @codeJack's [reasoning](https://github.com/helm/helm/issues/10154#issuecomment-923120990). 
So I think we will change our Helm charts without this _exploit_.

**Comment by tibcoplord** [comment]
Is there an alternative to share globals between subcharts ?

**Comment by brutus333** [comment]
> Is there an alternative to share globals between subcharts ?

I used import of values from subcharts into umbrella chart under a specific global key (https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies).
However, I have some hard to understand behavior - I am able to loop over the global dictionary from some subcharts but the result is not the same in all subcharts - some of them have incomplete view of the modified global dictionary.
