### ISSUE TITLE
`helm registry login` cannot use existing config file for authentication

### ISSUE THREAD

**Issue by SimonAlling** [helm/helm#10156]
Output of `helm version`:

    version.BuildInfo{Version:"v3.7+unreleased", GitCommit:"9fafb4ad6811afb017cc464b630be2ff8390ac63", GitTreeState:"clean", GoVersion:"go1.16.7"}

Output of `kubectl version`:

(N/A)

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

(N/A)

## Problem

Since `helm registry login` is so very similar to `docker login`, I'd expect the former's `--registry-config` flag to resemble the latter's `--config` one with respect to authentication. That is, one should be able to do `helm registry login` with an existing config file without having to enter authentication credentials again.

However, unlike `docker login`, it doesn't seem like `helm registry login` makes any attempt at using existing credentials.

### Config files

```console
$ tree config-files/
config-files/
├── docker
│   └── config.json
└── helm
    └── registry.json

2 directories, 2 files
$ cat config-files/docker/config.json # 🐋
{
  "auths": {
    "https://artifacts.example.com/": {
      "auth": "YWxpY2U6bW9ua2V5NDI="
    }
  }
}
$ cat config-files/helm/registry.json # ☸️
{
  "auths": {
    "https://artifacts.example.com/": {
      "auth": "YWxpY2U6bW9ua2V5NDI="
    }
  }
}
$ jq -r '.auths[].auth' config-files/docker/config.json | base64 -d && echo # 🐋
alice:monkey42
$ jq -r '.auths[].auth' config-files/helm/registry.json | base64 -d && echo # ☸️
alice:monkey42
```

### Logging in

```console
$ docker --config config-files/docker login https://artifacts.example.com/ # 🐋
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in config-files/docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
$ helm --registry-config config-files/helm/registry.json registry login https://artifacts.example.com/ # ☸️
Username:
```

**Comment by bacongobbler** [comment]
oops... Going to re-mark this as a support question until we confirm this is a behavioural bug in `helm registry login`'s behavior or an intentional design choice. cc @jdolitsky

**Comment by lindhe** [comment]
Did we come to a conclusion regarding this being a behavioral bug or intended design?

**Comment by hobti01** [comment]
As a user I thought this was strange at first, but now I follow this logic:

* Collect or overwrite credentials with `helm registry login` and use argument `--registry-config somefile.json` to indicate a non-standard location to save the credentials.  Because `login` collects credentials, it should always prompt.

* To use existing credentials, specify the argument `--registry-config authfile.json`, e.g. `helm pull --registry-config $DOCKER_CONFIG/config.json oci://localhost:5000/helm-charts/mychart --version 0.1.0`

**Comment by scottrigby** [comment]
Thank you @hobti01 

@lindhe Yes:
> Did we come to a conclusion regarding this being a behavioral bug or intended design?

This is the plan as I understand it:

1. The config file should be called “config.json” vs “registry.json” in order for Docker compatibility. See https://github.com/helm/helm/issues/10122#issuecomment-933548319. Env var `DOCKER_CONFIG` points to a directory containing a config.json (directory vs a file)
2. We also discussed the “helm env” output should maybe provide the dir containing config.json vs the JSON file itself (since it is not consumable by Docker-compatible software in any way)

Currently, when neither `HELM_REGISTRY_CONFIG` or `--registry-config` are specified, the config file defaults to `$HELM_CONFIG_HOME/registry.json`. Should we change `HELM_REGISTRY_CONFIG` to `HELM_REGISTRY_CONFIG_HOME` (and `--registry-config` to `--registry-config-home`) so this is clear the config is for an alternative directory containing a `config.json` when users don't want to use one in `HELM_CONFIG_HOME`?
