### ISSUE TITLE
helm --api--versions with resource included does not render and Capabilities.APIVersions.Has $version without resource included

### ISSUE THREAD

**Issue by thernstig** [helm/helm#10189]
Output of `helm version`: `version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

Using `helm template chart/ --api-versions=apps/v1/Deployment` does not render a template that has this check:
```yaml
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
```

I would think that specifying `--api-versions=apps/v1/Deployment` would implicitly mean that `--api-versions=apps/v1` also exists. I cannot see how that could not be the case.

Is there a bug in `--api-versions` here?

**Comment by zonggen** [comment]
I believe `apps/v1` is added by default in the `.Capabilities.APIVersions` list (confirmed by `{{ print .Capabilities.APIVersions }}`):

`apiversions: [v1 admissionregistration.k8s.io/v1 admissionregistration.k8s.io/v1beta1 internal.apiserver.k8s.io/v1alpha1 apps/v1 apps/v1beta1 apps/v1beta2 authentication.k8s.io/v1 authentication.k8s.io/v1beta1 authorization.k8s.io/v1 authorization.k8s.io/v1beta1 autoscaling/v1 autoscaling/v2beta1 autoscaling/v2beta2 batch/v1 batch/v1beta1 certificates.k8s.io/v1 certificates.k8s.io/v1beta1 coordination.k8s.io/v1beta1 coordination.k8s.io/v1 discovery.k8s.io/v1 discovery.k8s.io/v1beta1 events.k8s.io/v1 events.k8s.io/v1beta1 extensions/v1beta1 flowcontrol.apiserver.k8s.io/v1alpha1 flowcontrol.apiserver.k8s.io/v1beta1 networking.k8s.io/v1 networking.k8s.io/v1beta1 node.k8s.io/v1 node.k8s.io/v1alpha1 node.k8s.io/v1beta1 policy/v1 policy/v1beta1 rbac.authorization.k8s.io/v1 rbac.authorization.k8s.io/v1beta1 rbac.authorization.k8s.io/v1alpha1 scheduling.k8s.io/v1alpha1 scheduling.k8s.io/v1beta1 scheduling.k8s.io/v1 storage.k8s.io/v1beta1 storage.k8s.io/v1 storage.k8s.io/v1alpha1 apiextensions.k8s.io/v1beta1 apiextensions.k8s.io/v1]`

Did you mean to `helm template chart/ --api-versions=apps/v1` and then `{{- if .Capabilities.APIVersions.Has "apps/v1/Deployment" }}`? Since from the [K8s official documentation](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-groups-and-versioning), an API version stops at a version, `v1` in this case, not the resource type, e.g. `Deployment`.

Reference: https://helm.sh/docs/chart_template_guide/builtin_objects/

**Comment by thernstig** [comment]
Actually, I think my example was bad then. The fault really occurs for a CRD definition. So apiVersion is something like `custom.resource.com/v1/ResourceFoo`. In that scenario, `helm template chart/ --api-versions=custom.resource.com/v1/ResourceFoo` does not render a template with this check `{{- if .Capabilities.APIVersions.Has "custom.resource.com/v1" }}`

**Comment by bacongobbler** [comment]
`--api-versions` explicitly adds these API versions to the list. There is no knowledge of "parent" API versions as far as I remember. Kubernetes populates each and every API version. So in your case you may need to use `helm template chart/ --api-versions=custom.resource.com/v1/ResourceFoo --api-versions=custom.resource.com/v1` for your use case to work.

**Comment by thernstig** [comment]
@bacongobbler I am not sure I understand.

1. If I do `--api-versions=custom.resource.com/v1/ResourceFoo` it _**does not**_ render this `{{- if .Capabilities.APIVersions.Has "custom.resource.com/v1" }}`.

2. If I do `--api-versions=custom.resource.com/v1/ResourceFoo` it _**does**_ render this `{{- if .Capabilities.APIVersions.Has "custom.resource.com/v1//ResourceFoo" }}`.

3. If I do `--api-versions=custom.resource.com/v1` it _**does**_ render this `{{- if .Capabilities.APIVersions.Has "custom.resource.com/v1" }}`.

Why does 1. above not work? The logic is `API-GROUP/VERSION/RESOURCE`. If I include `API-GROUP/VERSION` in `--api-versions` then for me it means it should render both `.Capabilities.APIVersions.Has "custom.resource.com/v1"` and `.Capabilities.APIVersions.Has "custom.resource.com/v1/ResourceFoo"` since a resource has to be part of a `API-GROUP/VERSION`.

**Comment by bacongobbler** [comment]
Kubernetes populates this list with each and every version as well as each and every resource. So if you want both `custom.resource.com/v1` and `custom.resource.com/v1/ResourceFoo` to work, you need to use both:

```
helm template chart/ --api-versions=custom.resource.com/v1 --api-versions=custom.resource.com/v1/ResourceFoo
```

The ApiVersions field is a dumb object that only understands whether a string is available. There is no "smart" lookup.

https://github.com/helm/helm/blob/8f4989054cfc1bbbd5d25b5d8e19c9179d3e338d/pkg/chartutil/capabilities.go#L101-L126

**Comment by thernstig** [comment]
Would it not make sense for it to actually understand case 1. above as explained? So this is a feature/bug report on how it currently is implemented. Doesn't the reasoning of `GROUP/VERSION/RESOURCETYPE` make perfect sense?

See https://kubernetes.io/docs/reference/using-api/api-concepts/#standard-api-terminology
