### ISSUE TITLE
"make test" has linter errors and a warning to use revive in place of golint(deprecated)

### ISSUE THREAD

**Issue by mmulholla** [helm/helm#10205]
Output of `helm version`:  version.BuildInfo{Version:"v3.7+unreleased", GitCommit:"993040d15897cfabd1e4a4b8b0e6a49c2045fdcc", GitTreeState:"dirty", GoVersion:"go1.17.1"}

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

I cloned the repository on my mac and ran ```make test``` - the build fails quickly with linter errors including, for example:
- ```pkg/helmpath/lazypath_darwin.go:13: File is not `gofmt`-ed with `-s` (gofmt)```
- ```cmd/helm/install.go:258:2: sigchanyzer: misuse of unbuffered os.Signal channel as argument to signal.Notify (govet)```

I also got a warning:
- ```WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.```

As a result of the warning I changed the build to use revive instead of golint and then got a few more lint errors including, for example:
- ```cmd/helm/repo_update.go:136:10: errorf: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...) (revive)```

I have also created a branch which switches to use revive and  fixes all of the linter problems and can make a pull request if wanted.

**Comment by dperaza4dustbit** [comment]
I have verified I see the same:

`dperaza@dperaza-mac helm % make test-style
GO111MODULE=on golangci-lint run
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
cmd/helm/root_unix.go:1: File is not `gofmt`-ed with `-s` (gofmt)
// +build !windows
cmd/helm/root_unix_test.go:1: File is not `gofmt`-ed with `-s` (gofmt)
// +build !windows
cmd/helm/install.go:258:2: sigchanyzer: misuse of unbuffered os.Signal channel as argument to signal.Notify (govet)
	signal.Notify(cSignal, os.Interrupt, syscall.SIGTERM)
	^
cmd/helm/upgrade.go:191:4: sigchanyzer: misuse of unbuffered os.Signal channel as argument to signal.Notify (govet)
			signal.Notify(cSignal, os.Interrupt, syscall.SIGTERM)
			^
pkg/helmpath/lazypath_darwin.go:13: File is not `gofmt`-ed with `-s` (gofmt)

make: *** [test-style] Error 1`

**Comment by mmulholla** [comment]
Existing builds pass because the build is using golang_cli version 3.60. As a new user I cloned the helm repo, installed the pre-req's inlcuding golang_cli and ran ```make test``` and saw what is reported in this issue. As a result I think updating to the latest golang_cli version is important.
