### ISSUE TITLE
Helm upgrade does not remove label

### ISSUE THREAD

**Issue by gionapaolini** [helm/helm#10220]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68e3e47dad98b808ba41087c0c62e80cd4fcec36", GitTreeState:"clean", BuildDate:"2021-05-25T02:41:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
AKS
```

I have a release for a deployment, which had the following label: `sidecar.jaegertracing.io/injected=jaeger`
I have removed it, and upgraded the release with no errors.
When describing the deployment, the label is still there.

If I uninstall the deployment and re-install it, then it works as expected (no label).

**Comment by mattfarina** [comment]
How did you remove the label? What kind of resource is this happening on?

I ask because Helm creates a patch to update a resource. For core kinds it does a 3 way merge patch but for CRDs it does something simpler (the 3 way merge patch wasn't available for CRDs when Helm 3 came out). There are situations where removing the label via an outside tool could cause it to be added back when Helm updated the resource again.
