### ISSUE TITLE
Helm semantic semverCompare check doesn't work as expected with ">" condition.

### ISSUE THREAD

**Issue by pranayk01** [helm/helm#10322]
I have the following environment in my lab,
helm version: v2.17.0
kubectl version: v1.19.5

I have the following template of my pdb which is being rendered,
`{{- if (semverCompare ">1.19.3" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
`

The expectation is that the pdb should be rendered with "policy/v1" but the pdb is getting rendered with
`apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
`

**Comment by pranayk01** [comment]
Hi @bacongobbler 
Can you please have a look at this issue?

**Comment by britoaldan** [comment]
Helm template function renders a fake template irrespective of the underlying kubernetes version, it takes into account the helm clients kubernetes version.
references: https://github.com/helm/helm/issues/7991 
using: helm install --dry-run -debug to be used to render the actual template file 

This ticket can be converted as a bug for helm template function.

**Comment by hickeyma** [comment]
@britoaldan is correct in saying that `helm template` doesn't need connection to a cluster.  Therefore, don't think that this is a bug.

@pranayk01 Just wondering does this work as expected with `--dry-run` flag for `helm install`?

I am asking because I tried to reproduce using `helm template` on a scaffold chart (`helm create`) and ingress enabled. Each time it returned the first part of the if statement:

```yaml
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
```

I would have expected it to follow same as in your case.

**Comment by pranayk01** [comment]
Hi @hickeyma,
Yes, it works as expected with --dry-run flag for helm install.

Thanks for the support.
