### ISSUE TITLE
Rollout checksum annotation for different folder chart configmap or secret

### ISSUE THREAD

**Issue by jprecuch** [helm/helm#10346]
Hi,
I'm fighting with annotations to auto-rollout pod restart when there is change happening in configmap/secret.
Problem is the structure of my chart is not the default.

I need to configure somehow for deployment in first-chart to restart if configmap in second-chart is changed.

- kubernetes
- - first-chart
- - - templates
- - - - configmap.yaml
- - - - deployment.yaml
- - second-chart
- - - templates
- - - - configmap.yaml

This annotation works fine for first-chart restart of first-chart configmap.yaml changes.
```
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```
How to make this work (is it even supported) so first-chart can restart if second-chart configmap.yaml change?

Output of `helm version`:
3.7.1
Output of `kubectl version`:
1.20.4
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Any

**Comment by mattfarina** [comment]
You're not going to be able to do this from within Helm. Helm is a package manager rather than a configuration manager. So, the checksum annotation works because you're dealing with a single chart and and updating the cluster for that. It's not going to work across packages.

There are 3rd party tools that can be setup to watch a configmap and then reload a deployment. You may want to look into one of those.

**Comment by jprecuch** [comment]
Thanks @mattfarina . It's enough for me to know this is not supported

**Comment by MohamedShaj** [comment]
Hi  @mattfarina 

i ll take above question as ref:

![image](https://github.com/helm/helm/assets/102578451/a81d9b12-9005-44d4-8497-45b0e738debf)

Here second chart, deployment or any k8s resource can take or use the first chart configmap ?

is there is possibility ?

if so let me know the annotation for that !!
