### ISSUE TITLE
Hi team we were  using helm chart export earlier but now with 3.7.1 its removed can you let us know what is the substitute for helm export  

### ISSUE THREAD

**Issue by qnxrahul** [helm/helm#10343]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by qnxrahul** [comment]
helm chart export reponame/chartname -destination 'path'

**Comment by mattfarina** [comment]
Without knowing your workflow, this is a little difficult. But, here are some ideas...

If you have pushed the chart to a repository you can then pull the chart from that repository. In that case, `helm pull`.

If you have the chart on the local file system you can work with it there.

The need for `helm chart export` was because you had put the chart/version into Helm and had it there. The current functionality doesn't have a place where you've built but not pushed the chart.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!
