### ISSUE TITLE
pkg/action: needs a way to use cached(once) kube client 

### ISSUE THREAD

**Issue by scbizu** [helm/helm#10374]
## Background

In latest  v3.7.1 release codebase , when helm [inits the action Configuration](https://github.com/helm/helm/blob/v3.7.1/pkg/action/action.go#L365) helm also [inits the kubeClient Factory](https://github.com/helm/helm/blob/v3.7.1/pkg/kube/client.go#L92) provided by the kubectl there . For using helm as cli for most scenario ，it's ok because the process will return and the [CachedOpenAPIParser](https://github.com/kubernetes/kubectl/blob/v0.22.4/pkg/util/openapi/openapi_getter.go#L56) created by kubectl will be released at mostly once .

However , for using helm as SDK(library) scenario , we Init the `action.Configuration` at every deployment reached , we saw that the memory grows rapidly when we have some more concurrent deploy tasks(use helm action `upgrade` and `install`) but the Go[^1] GC follows slowly , so our build pipeline service OOMed and then exited.

Here is the (alloc_space) pprof (related part): 

> The memory spike should be bigger , sorry I lost the most spike one and replaced with the middle one :( 

![CleanShot 2021-11-19 at 11 55 31](https://user-images.githubusercontent.com/8732481/142562325-50db53f8-222d-405f-ac6e-869723b6f3b8.png)

## Just-work-solution 

we now work out a solution that make the per **[cluster,namespace] as keyed Configuration** cached at our pipeline service side . So that it will just create one kubectl Factory per [cluster,namespace].

And it just works , but since we cannot init the kubectl Factory by ourself , the duplicate kubectl Factory created by `Configuration.Init` still exists .

## Suggestion for helm codebase

It's better that Configuration.Init can let sdk developer to pass the cached kubectl Factory in or package action can provide us the self cached kubectl Factory . Something maybe like this:
```go
func InitWithKubeClient(c *kube.Client,namespace, helmDriver string, log DebugLog) error {
	if c == nil {
		return errors.New("kube client is nil")
	}
	c.Log = log
	
	lazyClient := &lazyClient{
		namespace: namespace,
		clientFn:  c.Factory.KubernetesClientSet,
	}
	...
}
```

Let me know if you need more additional details  and I am free for raising PRs these days if you need . 

[^1]: Go version: 1.16.1

**Comment by bacongobbler** [comment]
Hi @scbizu. A similar question was asked in https://github.com/helm/helm/issues/9913.

The code path you identified comes from packages produced by the Kubernetes project that Helm imports in order to interact with Kubernetes clusters. It looks like they have to do with one of two things:

1. Loading the OpenAPI schema
2. Validating manifests against the OpenAPI schema

If it's 1), then yes, re-using a cached OpenAPIParser may reduce the overall memory footprint.

If it's 2)... Then the memory spike occurs when the manifests are being validated against the schema. Not much you can do there except optimize the validation code.

Disabling OpenAPI schema validation altogether with the `--disable-openapi-validation` flag may also reduce the memory footprint, but then your manifests would not be validated before sending it to the cluster which can result in very odd edge cases.

An alternative approach may be to limit the number of concurrent jobs your build pipeline service can run at any given time to ensure it will not run out of memory. Not ideal, but it would prevent these issues from occurring.

> we now work out a solution that make the per [cluster,namespace] as keyed Configuration cached at our pipeline service side . So that it will just create one kubectl Factory per [cluster,namespace].

I'm curious... If you run the profiler with those changes intact (re-using a cached OpenAPI client), what's the result?

**Comment by scbizu** [comment]
> I'm curious... If you run the profiler with those changes intact (re-using a cached OpenAPI client), what's the result?

we optimize these changes last week and the spike goes down ,  we haven't analyzed the pprof since then , but after this approach tested in my local test env ,via pprof this should work (not perfectly as I expected) .

> An alternative approach may be to limit the number of concurrent jobs your build pipeline service can run at any given time to ensure it will not run out of memory.

Yep , we do this at once . But the 「limit number」 should be differ from every manifests size , we can not determine a right 「magic number」to cover it .
---
I think I can self-follow this topic and work out a version to see whether it's worth to cache the parser at helm side ?
