### ISSUE TITLE
List HELM dependencies of an installed chart

### ISSUE THREAD

**Issue by AssafKatz3** [helm/helm#10434]
Hi,
I have the same requirement as is written in [this article](https://stackoverflow.com/questions/66062090/list-helm-dependencies-of-an-installed-chart). I suggest adding the option of helm show dependency.
Thanks

**Comment by giovannirco** [comment]
yeah I wanted to grab the information of dependencies that is currently installed because other people on the team can change the charts.yml file on their local setup and install, so using `helm pull/fetch` wouldn't work here I guess as it would download the chart from the internet and not the cluster

**Comment by AssafKatz3** [comment]
Still needed

**Comment by AssafKatz3** [comment]
I don't know Golang enough to open a pull request.

**Comment by AssafKatz3** [comment]
Does anyone have a plan to implement? Thanks

**Comment by AssafKatz3** [comment]
Is anyone working on it?
