### ISSUE TITLE
helm test --filter unexpected behaviour

### ISSUE THREAD

**Issue by mateinavidad** [helm/helm#10433]
Let me start by describing my scenario and the issue I am facing.
In my CD pipeline I am deploying an umbrella chart with multiple subcharts. I have recently updated each subchart to contain a test hook/job.

In the pipeline, after running `helm upgrade` I wish to run multiple `helm test --filter` commands that are each scoped to one of the subcharts. I chose this approach for the following reasons:
- instead of using the `hook-delete-policy` annotation, i will use the `ttlSecondsAfterFinished` so that I may extract some generated test results files from each job pod after test completion.
- it allows me to retrigger a failed test.
- it allows the tests to be run in parallel.

I checked the `helm test` source code and if the `--filter` is provided it seems to be actually [altering the test hooks collection ](https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/action/release_testing.go#L69) of the release object right before calling [`execHook`](https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/action/release_testing.go#L91).

I am not familiar with the internals of helm, but this seems to be a bad practice:
- it modifies the state of the object and reverts it after execution, effectively limiting only one `helm test` action at a time.
- it's an unexpected side-effect.
- in case of an unexpected error in the test, the hooks might not be reattached. [Already reported](https://github.com/helm/helm/pull/9400). 

I would propose to move the hook filtering inside the [`execHook` method](https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/action/hooks.go#L36), where a new `executingHooks` collection is created, in that case the release is not being modified on each `helm test --filter` call.
From my investigation this should have a minimal ripple effect, but would open the possiblity of running multiple `helm test` commands in parallel, and in some cases might be an acceptable workaround even for [this HIP](https://github.com/helm/helm/issues/4118).

Before preparing a PR, I wanted to get a contributors input, I might be missing something.

**Comment by mattfarina** [comment]
I like the idea of refactoring this code so we don't update the release object and restore it. The methods that need to be changed are internal (not public) so it would be ok to change them. `execHook` is used in many places where there is no filter.

I can think of a few ways to handle this situation...
- Add an argument to pass filters to execHook. In most cases this would be empty.
- Clone the release object and alter the hooks on the clone. The codebase already has a deep clone package imported that we use for something else.
- Create a new function that handles filtering and executing the hook (e.g., `execFilteredHook`) so that only the cases that use filtering need to pass it. `execHook` could be refactored so these could work together.

I wonder if @adamreese, @bacongobbler, or @technosophos has an opinion on this.

**Comment by mateinavidad** [comment]
My vote would go to either 1 or 3, Since there isn't any feedback yet, I'd like to submit an initial PR just to get the ball rolling. @mattfarina do you have any preference on which approach to implement?

**Comment by lheinlen** [comment]
I see that the PR was referenced above in the "Already reported" link but I just wanted to mention that I believe that #9400 implements @mattfarina's first suggestion above (as well as adding some tests).

**Comment by mateinavidad** [comment]
@lheinlen Great stuff! I actually did take a look at the commits for the PR but mistakenly only saw the initial implementation, which didn't fit my requirements. I took a second look and i think your PR is the way to go. I'll close this issue in favour of #9400. Just hope to see it merged asap.
