### ISSUE TITLE
Provide `--verify-images` flag to support built-in image verifying

### ISSUE THREAD

**Issue by Dentrax** [helm/helm#10436]
Helm has provenance tools which help chart users verify the integrity and origin of a package. [^1]

---

**Proposal**
 
What we (@developer-guy) propose is that similar to `--verify` flag,  but for _images_. Maybe we can implement it as a string flag such as `--verify-images=(none|cosign|notary)` so that we can eventually add other verifiers easily.

**Implementation**

As a first step, we probably want to gather all the images in the entire helm chart (templates). Like the following:
* daemonset: containers[*]: image
* deployment: containers[*]: image
* ...

We can create a [--cosign-key](https://github.com/sigstore/cosign/blob/6d8cec1c599b3ca56514129890bf75f30cfc4bfc/cmd/cosign/cli/verify.go#L49-L72) flag to pass public key into helm. UX would be:

```
# Following commands should verify the images first, and install the charts afterwards
$ helm install falco falcosecurity/falco --verify-images --cosign-key k8s://falco/pubkey
$ helm upgrade falco falcosecurity/falco --verify-images --cosign-key k8s://falco/pubkey
```

We can call cosign binary under the hood.

As a reference: we implemented the similar thing at https://github.com/containerd/nerdctl/pull/556/files.

References:
* https://github.com/sigstore/cosign/issues/1118 by @developer-guy
* https://github.com/sigstore/cosign/pull/1144 (helm plugin)

[^1]: https://helm.sh/docs/topics/provenance/

Your feedback would be appreciated!

cc: @dlorenc

**Comment by mattfarina** [comment]
Let me first say, I like the idea of signing and verifying images. I would like to see more of this.

That being said, where is the right place to do that?

Helm is an SDK and CLI that interacts with the Kubernetes API. Wouldn't doing this kind of validation in Helm be similar to doing client side content validation in web forms? Someone could bypass the HTML and send a malicious request. Wouldn't it be more appropriate to have this kind of functionality server side?

If this were in Helm rather than an admission webhook it would be trivial for someone to use kubectl to push the unsigned image and bypass validation.

Signing and even who you accept as a valid signature is a policy issue. For example, some clusters aren't just going to look for a valid signature but look for the signature to be from a certain set of certificates.

If someone has this server side in order to catch all images from all clients, what is the benefit of having it in Helm?

I am a proponent of signing and verification. I just want to make sure the effort is put into doing it in the best places. Can you provide a case for doing it here?

Also, this is the soft of thing we would ask to go into a [Helm Improvement Proposal (HIP)](https://github.com/helm/community/tree/main/hips).
