### ISSUE TITLE
Getting all values of a chart without deploying

### ISSUE THREAD

**Issue by delthas** [helm/helm#10435]
Hi,

I'd like to get all the values ("COMPUTED VALUES") of a chart (and its dependencies) without deploying it:
- Like `helm template`, but to get the values instead of the manifests.
- Like `helm get values --all`, but as if I was using `helm template`, working on an undeployed chart with a list of passed `--set`, `--values`, instead of a deployed release.

eg `helm <command> --namespace bar chartname ./path/to/chart --values baz.yaml` that would return
```
COMPUTED VALUES:
global:
 ...
subchart1:
 enabled: true
 ...
```

Is there a way to do this in Helm?

**Comment by delthas** [comment]
Note that this is not the same as `cat baz.yaml` nor `cat ./path/to/chart/values.yaml` because I also want values of chart dependencies (and their dependencies).

**Comment by hickeyma** [comment]
@delthas You could use the `--dry-run` `--debug` flags with `helm install`. Check out [Debugging](https://helm.sh/docs/chart_template_guide/debugging/) and docs for more details.

**Comment by delthas** [comment]
OK, that's close enough to what I need! Thanks.

**Comment by donatelloOo** [comment]
> [@delthas](https://github.com/delthas) You could use the `--dry-run` `--debug` flags with `helm install`. Check out [Debugging](https://helm.sh/docs/chart_template_guide/debugging/) and docs for more details.

I'm afraid the provided workaround does not gives the initial requirement which is provide the full computed values (including dependencies) of a helm chart.

That means retrieving all `.Values.*` that can be found in templates (recursively on sub charts), and rebuild the full values.yaml file.

The `helm install --dry-run` command does not help, since it does not produce any values.yaml file, so we need anyway to parse everything to produce such complete computed values.yaml.
