### ISSUE TITLE
Exact dependency versions are ignored

### ISSUE THREAD

**Issue by Cybermaxke** [helm/helm#10487]
Unable to specify exact versions in Chart.yaml dependencies, the same issue as https://github.com/helm/helm/issues/7563

Example versions in repo:
```
1.0.0-abranch
1.0.0-bbranch
```

```
dependencies:
   - name: myproject
     repo: myrepo
     version: 1.0.0-abranch
```

Run `helm dependency update myproject`
Expected result: a dependency with version 1.0.0-abranch
Actual result: a dependency with version 1.0.0-bbranch

Everything after major.minor.patch is ignored and the "latest" version according to semver is pulled instead.

Manually pulling with `helm pull myrepo/myproject --version 1.0.0-abranch` works correctly

Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS, Docker Desktop

**Comment by josephvano** [comment]
This appears to be expected based on SemVer with pre-release following ASCII ordering.

Helm is using this golang package to handle semver and you can see the topic on pre-release.
https://github.com/Masterminds/semver#checking-version-constraints

As specified in the other issue thread, you could append some type of auto-increment number such as number of commits within the branch to help keep track of which package.

So it would be `1.0.0-abranch.1` then `1.0.0-abranch.2` in sequence.

Then you could specify a range to lock down your dependencies to that specific chart.

```yaml
dependencies:
   - name: myproject
     repo: myrepo
     version: "1.0.0-abranch.0 - 1.0.0-abranch.999"
```

That type of constraint should only pull down the correct dependency based on the range given.

I've tested using some form of a sha on the branch name to make it consistent with the number of chars and number of commits from the default branch.

Branch name `$current_branch | sha1sum | head -c 6`
Commit number `git rev-list --count $default_branch...$current_branch`

This would give you something like 1.0.0-$branch_sha.$commit

HTH

**Comment by lallinger-arbeit** [comment]
I just stumbled across this while automating a testsetup for a custom helm chart and after having read the linked and auto closed threads i do not understand why this is handled as "works as designed/expected".

Yes SemVer specifies that `Build metadata MUST be ignored when determining version precedence` but when i EXPLICITLY state a specific build of a version i expect to get that exact version if it's available and not just another one with the same precedence. The other way round you wouldn't expect getting 1.0.0+1 when specifying 1.0.0 just because they have the same precedence, would you?

Also SemVer explicitly states that `Build metadata MAY be denoted by appending a plus sign`, this means build metadata may be specified but if it is specified it therefore MUST only appear after a `+`. Moving the build metadata to the front as a pre-release flag this would create precedence where none should be. If the build metadata is a commit sha it makes no sense that 1.0.0-alpha.b0135827 has precedence over 1.0.0-alpha.a3873496

So please fix this that when i want version 1.0.0+xyz i get version 1.0.0+xyz not something which may be or may not be the same.

**Comment by lallinger-arbeit** [comment]
this is still a valid problem

**Comment by joejulian** [comment]
Please track this upstream https://github.com/Masterminds/semver/issues. This is not a helm issue.
