### ISSUE TITLE
How to pass an int type string such as "123"

### ISSUE THREAD

**Issue by su-houzhen** [helm/helm#10518]
This is my helm chart:
**values.yaml**
port: "123"

**templates/pods.yaml**
apiVersion: v1
kind: Pod
metadata:
  name: pod-base
spec:
  containers:
    - name: busybox
      image: busybox:1.30
      env:
        - name: PORT
          value: {{ .Values.port | default "123"  }}

Then do helm install, and kubernetes throws an error:
Error: INSTALLATION FAILED: Pod in version "v1" cannot be handled as a Pod: v1.Pod.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 1, error found in 10 byte of ...|,"value":123}],"imag|..., bigger context ...|","name":"nginx"},{"env":[{"name":"PORT","value":123}],"image":"busybox:1.30","name":"busybox"}]}}
|...

It looks like `string "123"` becomes `integer 123` in pods.yaml. What should I do to make it work?

Thanks.

Output of `helm version`:
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): QKE

**Comment by hatati** [comment]
It's weird that the `port` key would be read as an integer if it's quoted. Nonetheless, try this:
```
- name: PORT
value: {{ .Values.port | default "123" | quote }}
```
`quote` makes sure that it will always be a string that gets rendered

**Comment by mattfarina** [comment]
I can see the confusion here. It took me a second to understand what's going on.

When `port` in the `values.yaml` file is read it is read as a string. So, the value of `.Values.port` is a string.

Then the string is being written out in a template. When strings are written out they are written out as is. So, the string of `123` is being written out as `123` into a template. No quotes because strings aren't written out with quotes.

Then the YAML manifest created from the template is parsed. If quotes weren't put in around it this parsing step will parse it as an integer.

So, using the `quote` function, like @hatati pointed out, is the way to make sure it's quoted.

**Comment by su-houzhen** [comment]
It works. thanks.
