### ISSUE TITLE
Add shell completion for OCI feature

### ISSUE THREAD

**Issue by marckhouzam** [helm/helm#10553]
The new OCI commands and charts should have shell completion when possible.

**Comment by marckhouzam** [comment]
I can take care of this but I need to clarify something.

Before using an OCI registry, does the user have to do a `helm registry login` or is that only for the registries that require authentication?

I'm asking because I want to know if helm has a list of registries the user can use in a command (we could suggest the registry address) or can any registry be used (we can only suggest the "oci://" prefix).

/cc @jdolitsky @scottrigby @mattfarina

**Comment by scottrigby** [comment]
Hey Marc you only need to helm registry login if the registry requires auth to do your operation.

Most common is probably helm push, because auth is needed to do that even for publicly available registries.

The registries config is in HELM_CONFIG_HOME/registries/config.json and/or DOCKER_CONFIG/config.json, but i'm not certain about their persistence when logged out

**Comment by scottrigby** [comment]
Yes any registry can be used, including localhost (the helm docs registries page example), or custom domains. There are commonly known registry domains though - idk, maybe it would make sense to autocomplete those? 

Also one note - in Helm registries don't currently have an equivalent to a helm repo concept. Because for example a container registry could hold helm charts, other non-container artifacts, and also (more commonly for now) other containers. Because of that it doesn't make sense to query the ORAS API for all the images/artifacts within a repo, because helm would have to parse them all to know whether each is a chart or not. But once Helm knows the chart artifact path, it gets the list of available versions for that chart.

**Comment by marckhouzam** [comment]
Thanks for the info @scottrigby.  So I think the best we can do is:
1. suggest the prefix "oci://" as a possibility when specifying a chart (`install`, `template`, `upgrade`, `show` and `pull`)
2. suggest the prefix "oci://" as the second parameter to `helm push`.  That would be the only suggestion.
3. `helm registry login`, no completion choices (turn off file completion)
4. `helm registry logout`, suggest the registries that the user is currently logged into. This one is not part of the PR as I think it should use some ORAS object that would return that list.  I haven't had time to look if there exists such an API.
