### ISSUE TITLE
`helm uninstall --wait` doesn't actually wait for pods to be terminated

### ISSUE THREAD

**Issue by jerguslejko** [helm/helm#10586]
I'm running `helm uninstall --wait` for two charts (first uninstalling redis client, then redis server). However, the `--wait` flag does not actually wait for pods to be properly terminated (eg. `helm uninstall --wait` returns and the pods are still in `Terminating` state). This results in "client" erroring with "server is gone" even though I do `helm uninstall --wait client && helm uninstall --wait server` (note: uninstalling server faster than uninstalling client).

---

Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
```
AWS
```

**Comment by joejulian** [comment]
Can you provide a link to the charts? I'd be interested in seeing what's happening.

**Comment by matthjes** [comment]
Same here, `--wait` seems to do nothing, the call to `helm` returns but `kubectl` still shows Pods / Services in the `Terminating` state.

**Comment by czi** [comment]
It appears that pods aren't added to the ResourceList used by waitForDeletedResources. 

When waitForDeletedResources in pkg/kube/wait.go goes through it's checks for my test case, it's only looking at the StatefulSet which is deleted immediately.

```
version.BuildInfo{Version:"v3.8+unreleased", GitCommit:"12f1bc0acdeb675a8c50a78462ed3917fb7b2e37", GitTreeState:"clean", GoVersion:"go1.17.6"}
```

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-release bitnami/redis
```
```
helm uninstall my-release --wait --debug && kubectl get statefulset && kubectl get pods
uninstall.go:95: [debug] uninstall: Deleting my-release
client.go:299: [debug] Starting delete for "my-release-redis-replicas" Service
client.go:299: [debug] Starting delete for "my-release-redis-headless" Service
client.go:299: [debug] Starting delete for "my-release-redis-master" Service
client.go:299: [debug] Starting delete for "my-release-redis-replicas" StatefulSet
client.go:299: [debug] Starting delete for "my-release-redis-master" StatefulSet
client.go:299: [debug] Starting delete for "my-release-redis-configuration" ConfigMap
client.go:299: [debug] Starting delete for "my-release-redis-scripts" ConfigMap
client.go:299: [debug] Starting delete for "my-release-redis-health" ConfigMap
client.go:299: [debug] Starting delete for "my-release-redis" Secret
client.go:299: [debug] Starting delete for "my-release-redis" ServiceAccount
wait.go:66: [debug] beginning wait for 10 resources to be deleted with timeout of 5m0s
uninstall.go:144: [debug] purge requested for my-release
release "my-release" uninstalled
No resources found in default namespace.
NAME                          READY   STATUS        RESTARTS   AGE
my-release-redis-master-0     1/1     Terminating   0          107s
my-release-redis-replicas-0   1/1     Terminating   0          107s
my-release-redis-replicas-1   1/1     Terminating   0          72s
my-release-redis-replicas-2   1/1     Terminating   0          46s
```

**Comment by joejulian** [comment]
Looks like this behavior comes from https://github.com/helm/helm/blob/292368a64d6c9794b4573afa5a8dc6e940a21045/pkg/kube/client.go#L423

Since changing this to foreground (which I personally feel should have been the default when using the wait flag) will change existing behavior, this would need to be handled by adding a new flag (`--cascade` like kubectl?) and making the default, `background`.

**Comment by jerguslejko** [comment]
@joejulian to clarify, you mean something like `helm uninstall --wait --cascade` where the `--cascade` flag changes `policy := metav1.DeletePropagationBackground` to `policy := metav1.DeletePropagationForeground`?

**Comment by joejulian** [comment]
That's my opinion, yes.

**Comment by stackkrocket** [comment]
Has this been fixed yet? From the suggestion above made by @joejulian. I'll be interested to have a pop at it.

**Comment by kg-mpg** [comment]
hey @stackkrocket any updates on this? I'm hunting for low-hanging fruits.

**Comment by keremgocen** [comment]
I'm looking for a low-hanging fruit to contribute if no one else is on it

**Comment by bormm** [comment]
My opinion as I disagree with @joejulian opinion here because:
This behavior is a bug as its not working as everyone would expect and its also not working as defined ["It removes all of the resources associated with the last release of the chart as well as the release history, freeing it up for future use. [...] will wait until all the resources are deleted before returning"](https://helm.sh/docs/helm/helm_uninstall/#options).

If assuming people rely on wrong behavior, every bugfix would be a breaking change. 
In this case here also nobody could even really rely on pods are still running, because even that contains a timing component and would often not work.

I don't think any effort should invested in preserving the current misbehavior and enforce the same time everyone use a additional parameter to get a meaningful wait operation. You could call it also "--wait-really" then.
Who would use the wait then not with that additional parameter? If you want to wait that all resources are deleted, you want exactly that, not that most are deleted.

**Comment by jwenjian** [comment]
Due to this bug, the following scenario not working:

1. install a helm chart with a pod that have a PVC-PV volume
2. when the pod is running and ready, uninstall with `--wait` 
3. install the helm chart right after the uninstall command returned

The PVC will not re-created since it is being terminating in step 3 which should be terminated and removed by using `--wait` parameter in step 2.

The final result is , new created pod will be in pending status forever since the PVC is missing.

Just like this [Stack overflow issue](https://stackoverflow.com/questions/70052368/helm-delete-and-reinstall-deployment-wait-or-not-to-wait) described.

please correct me for my understanding if any wrong.

**Comment by shukra-in-spirit** [comment]
Hey @joejulian , I would like to contribute. I have faced this issue while doing a simultaneous uninstall of interdependent helm charts.

My take on it:
The only usage of `--wait` is a scenario where the user would like the process to wait until all resources are removed, and there are no further traces of the chart left.

It does not seem like the change will cause breakage in existing deployment; as no scenario seems to depend exclusively on `--wait`'s current behaviour.
Better to treat it as a bug and modify current behaviour.

I can assign the issue to myself and start work. If it seems okay to fix it this way.

**Comment by MichaelMorrisEst** [comment]
Hi @joejulian 
I am interested in contributing a fix for this issue as per your suggestion. I will create a PR with the code changes.
This is my first contribution to the helm project so if I am missing anything in terms of the process for contributing then please let me know

**Comment by joejulian** [comment]
Also if you need any help, normally I'd suggest coming to the developer meeting but this week is cancelled because most everyone's at Kubecon. Next week should be good though.
