### ISSUE TITLE
Managing CRDs & chart dependendies

### ISSUE THREAD

**Issue by tomkerkhove** [helm/helm#10585]
[KEDA](http://keda.sh/) provides CRDs for their end-users as part of the Helm installation.

Initially we followed the guidance to use `crds/` folder to let Helm manage it, but we've noticed that the CRD is not being updated and moved away from it.

Instead, we have added them to the `templates` folder with [an option to skip them](https://github.com/kedacore/charts/blob/main/keda/templates/02-crd-clustertriggerauthentications.yaml#L1) if need be.

The only issue that has come up now is when our Helm chart is a dependency of another Helm chart. The issue is that Helm does not wait until KEDA has been installed so the main chart tries to use a CRD that was not installed yet.

What is Helm's guidance on this? Because using `crds/` is not an option since it does not update CRDs.

Repro is available on https://github.com/tomkerkhove/keda-helm-dependency.

Relates to https://github.com/kedacore/charts/issues/226

**Comment by joejulian** [comment]
Unfortunately, Helm does not provide any support around upgrading CRDs . See [HIP 11](https://github.com/helm/community/blob/main/hips/hip-0011.md) for more details.

The way our company has worked around this is to include the CRDs into ConfigMaps and use pre-install,pre-update jobs to apply them. Here's an [example](https://github.com/mesosphere/charts/blob/master/staging/gatekeeper/templates/crds.yaml)

**Comment by tomkerkhove** [comment]
Thank you for the example, I will take a look but most probably this has the same issue - The job will not be guaranteed to be completed before the dependent chart gets installed.

I will have a look at the HIP, but this seems to be a gap in Helm for doing CRD lifecycle management :/

**Comment by tomkerkhove** [comment]
Bumping as this is still a problem.

**Comment by hickeyma** [comment]
@tomkerkhove The [policy on CRDs](https://github.com/helm/community/blob/main/hips/hip-0011.md) was provided by @joejulian above.  The document explains the reasoning behind the limited support for CRDs by Helm.

I re-opened this issue but not sure how this can be progressed further.

**Comment by tomkerkhove** [comment]
Given how many people struggle with this I believe it would be beneficial to provide a better story in Helm but that is easily said.

If that is not possible, then having guidance in the documentation on how to manage CRDs through workaround such as the above would be a huge help.

Would that make sense?

**Comment by hickeyma** [comment]
The bottom line is that Helm has: "no support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss."

There are some suggestions given [here](https://github.com/helm/community/blob/main/hips/hip-0011.md#nobody-is-blocked-on-this) and also [here](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource). If you need more capability outside of CRD install then Helm recommends using [separate charts](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts). In essence it is saying that you need to manage your CRDs yourself and @joejulian provided the way they do it in https://github.com/helm/helm/issues/10585#issuecomment-1018042390. It is a case of which way suits your setup.

**Comment by ldemailly** [comment]
re 
> "Nobody is "Blocked" 
[...]

> First, there are widely documented patterns and work-arounds for how to handle CRDs. The most common is the pattern of separating CRDs into a separate chart that then treats these CRDs as standard resources."

How does having another chart changes that CRDs aren't being updated anyway after the first application?

I would love any solution (a flag or anything) that avoids https://github.com/helm/helm/issues/7735#issuecomment-875819039

**Comment by xashr** [comment]
I understand that the CRDs are difficult to integrate into the Helm concept. But then Helm should not provide unusable features like the crds/ folder, which allows CRDs to be installed, but not upgraded. Who actually uses that?

**Comment by tomkerkhove** [comment]
We used to use it, and later on noticed that all our CRDs had gone stale for a few releases..
