### ISSUE TITLE
helm lint should allow specifying --kube-version flag

### ISSUE THREAD

**Issue by antoinedeschenes** [helm/helm#10664]
We're currently using `helm lint` to find deprecated API versions in our charts, failing CI on warnings. However, helm assumes that the target Kubernetes version is the one specified through the k8sVersionMajor/k8sVersionMinor vars. The only way to work around this is rebuilding helm with LDFLAGS, or using a Helm release with the proper defaults.

The command-line flag `--kube-version` currently exists with `helm template`, `helm lint` should replicate the behaviour:
https://github.com/helm/helm/pull/9040

**Comment by yxxhero** [comment]
@antoinedeschenes The PRs is welcome. Thanks very much.

**Comment by antoinedeschenes** [comment]
bump, pr updated

**Comment by KlavsKlavsen** [comment]
bump.. why is this nice fix being ignored? :(

**Comment by yxxhero** [comment]
sorry. I will review the PR of this issue later.

**Comment by davidgwps** [comment]
any update on this? For our use case we are linting using `--strict`, currently we are getting failures because the beta version of the HPA API is deprecated in v1.23+, however we have a couple of kube clusters running v1.22 so we don't want them to fail. The `autoscaling/v2` API doesn't exist in v1.22 so I can't see a solution apart from removing the `--strict` from the linter until we use v1.23 everywhere.

```
Warning:  templates/hpa.yaml: autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler

Error: Process completed with exit code 1.
```

**Comment by antoinedeschenes** [comment]
@davidgwps Each helm minor version matches a k8s minor version. You can run lint with different helm versions  as a workaround.

**Comment by sstarcher** [comment]
@antoinedeschenes that does not really seem feasible to me.  
Example
* K8S 1.23
* Helm 3.8.0

Helm lint will still respond with 
`batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob`

Even though batch/v1beta1 cronjob will work fine in 1.23.  Any deprecation will fail.  You are not suggesting a person should run with Helm that supports 1.21 even though they are running 1.23 are you?  If so that could cause other issues and unsupported features.

Capabilities.APIVersion would certainly work though in this case.

**Comment by joejulian** [comment]
All the bits are there to do this. It should be a fairly easy task. See https://github.com/helm/helm/pull/8608/files#diff-ff8663c8d26f14679a0274ccb7dab29b04bd17084581c573ca06d8fb82d1d154R63-R65 where I call the upstream deprecation library.

**Comment by joejulian** [comment]
Sorry, I totally missed that there's a PR open already.

**Comment by sstarcher** [comment]
Please keep this open
