### ISSUE TITLE
Error: helm concurrent deployments fail with UPGRADE FAILED

### ISSUE THREAD

**Issue by dialogue-shreyas** [helm/helm#10723]
Currently, we have a use case where multiple developers are deploying an application via CircleCI. When two CircleCI jobs are running concurrently to perform `helm upgrade`, the job fails with `Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress`. This used to work perfectly fine with  helm version `3.3.4`. However, the newer versions of helm do not support this feature. 

We would like to request an option where we still allow developers to run `helm upgrade` concurrently without getting `UPGRADE FAILED` error. This can be an optional flag in `helm upgrade`.

Output of `helm version`:
``` 
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"} 
```

Output of `kubectl version`:
```Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
See https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea - with concurrent jobs in-progress I feel there may be certain scenarios we may need to accomodate. Things like:

- do we block and wait until the existing update has completed before issuing another upgrade?
- what happens if there's a deadlock? How do we reconcile that?

The HIP process should help answer those questions. I'd suggest forming a working group with other like-minded individuals with similar issues to help shape the proposal.

**Comment by tpoindessous** [comment]
Hi

Yes, it would be like a good idea to have "a retry" option for example.

How could we contribute to this path ? I don't think I can write a HIP 😢 

Thanks !
