### ISSUE TITLE
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: IngressClass "nginx" in namespace "" exists  and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "ingress-public": current value is "ingress"

### ISSUE THREAD

**Issue by repository4poc** [helm/helm#10736]
I am working on upgrade helm chart ingress-nginx from version 3.34.0 to 4.0.17 and getting below error

Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: IngressClass "nginx" in namespace "" exists 
and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "ingress-public":
current value is "ingress"

**Comment by yxxhero** [comment]
@repository4poc which helm version?

**Comment by yxxhero** [comment]
@repository4poc can you provide the chart address?

**Comment by bacongobbler** [comment]
We need more information in order to better understand your situation. But from what I can gathher, you have two releases: `ingress` and `ingress-public`. Your IngressClass named `nginx` is owned by the release called `ingress`, and you are upgrading `ingress-public`, which also contains an IngressClass named `nginx`.

In Helm, a resource cannot be claimed by multiple releases. For example, you cannot have two charts that install `postgresql` in the default namespace because Helm cannot determine who "owns" that resource at any given time. Instead, when a resource is installed, a label is attached to the resource to state that it has been claimed by a particular release so that future installations do not attempt to claim or "adopt" a resource that already exists.

Hope this helps.
