### ISSUE TITLE
How to Roll Deployment on an external resource not managed by the chart.

### ISSUE THREAD

**Issue by lordigon** [helm/helm#10757]
I would like to know if it possible to apply Automatic Roll Deployment (https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) on a Secret that is not created with a template inside the helm chart but with a secret installed by another application.  Any idea how to solve it?

TIA

**Comment by bacongobbler** [comment]
The strategy relies on several template functions found in Helm. So to answer your question, no, it is not possible to apply the same strategy outside of Helm because the template functions only exist in Helm's template engine.

That being said, it is entirely possible for you to perform the exact same steps yourself.

The equivalent of

```
{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```

In bash would be

```
cat configmap.yaml | sha256sum | awk '{ print $1 }'
```

Hope this helps.
