### ISSUE TITLE
Does helm delete pods that are not in chart

### ISSUE THREAD

**Issue by moluzhui** [helm/helm#10839]
Because of my carelessness, after deploying the chart, I found a pod that is not in the chart through `helm status`. 
```
==> v1/Deployment
myproject-release-mysql         1h

==> v1/Pod(related)

NAME                                                     READY  STATUS   RESTARTS  AGE
myproject-release-mysql-12x135w8dc-e7dwx                  1/1    Running  0         1h
otherproject-release-mysql-259a7d691e-y1543               1/1    Running  3         109d
```
This should be caused by label matching.  I would like to know if deleting the release via the `helm delete --purge <release name>` command will **delete the pods in this non-chart**. 
It would be very bad if it would delete non-chart pods, is there any way to fix it.

Output of `helm version`:
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
When you invoke `helm uninstall`, Helm looks up the list of resources in the latest release and submits them to Kubernetes. I do not remember whether pods related to the deployment would be deleted when the deployment is deleted.

For reference:

https://github.com/helm/helm/blob/e9a2e42ab1b16b435fcc6f74fceeaac24fe4bf98/pkg/kube/client.go#L290-L324

https://github.com/helm/helm/blob/e9a2e42ab1b16b435fcc6f74fceeaac24fe4bf98/pkg/kube/client.go#L422-L427

> helm version
> Client: &version.Version{SemVer:"v2.11.0",

Helm 2's support lifecycle ended on November 2020. See [the blog post](https://helm.sh/blog/helm-2-becomes-unsupported/) for more details. Because of this, I am closing this ticket as we are not providing further support for Helm 2.
