### ISSUE TITLE
Helm latest version breaks with json schema

### ISSUE THREAD

**Issue by LijieZhou** [helm/helm#10904]
Output of `helm version`: v3.8.2

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

We have seen `helm lint` fails to validate with json schedma in the latest version. To reproduce that: 

Running on v3.0.1:  

![image (2)](https://user-images.githubusercontent.com/4102387/165583147-c6871e49-9860-420d-b4e1-e659d1746297.png)
![image (3)](https://user-images.githubusercontent.com/4102387/165583197-5c74dcbc-2b3a-4c40-aee5-d1417e75e7e6.png)

Running on v3.8.2: 
Both helm template and helm lint passes the check on the same code:

<img width="1126" alt="Screen Shot 2022-04-27 at 10 20 09 AM" src="https://user-images.githubusercontent.com/4102387/165583542-20f0f2a6-5d2f-4bc8-b5ad-e479e24fffd0.png">
<img width="948" alt="Screen Shot 2022-04-27 at 10 20 21 AM" src="https://user-images.githubusercontent.com/4102387/165583549-9e4c1af2-3c0c-4506-a3a6-d141c3d1ae96.png">

cc @stevenlaigusto

**Comment by bacongobbler** [comment]
gojsonschema has not seen any activity since October 2020. It is likely out of date and unlikely to receive any fixes or changes. So if the issue stems from that package, there's nothing we can do except replace it.

We discussed replacing it with something that is more well maintained in https://github.com/helm/helm/issues/10732, but I haven’t seen anyone pick up the work.

**Comment by bacongobbler** [comment]
Can you please provide a sample chart to help reproduce this issue?

**Comment by bacongobbler** [comment]
ping.
