### ISSUE TITLE
Feature: Helm values.json.schema in library charts

### ISSUE THREAD

**Issue by thernstig** [helm/helm#10955]
It would be great if library charts (https://helm.sh/docs/topics/library_charts/) would support sharing a values.schema.json that can be used with `$ref` from within a Helm charts schema.

**Use case**
In big organizations etc. it would be great to share JSON schemas for all products developed.

**Comment by bacongobbler** [comment]
Are you planning on contributing this? If so, have you had a chance to read through https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea?

**Comment by bacongobbler** [comment]
For reference, gojsonschema (the library Helm uses for JSON Schema support) has not seen any activity since October 2020. It is likely out of date and unlikely to receive any fixes or changes. So if you're proposing new feature requests for JSON Schemas, it is unlikely to be accepted unless you fork the project and agree to continue maintaining it.

We discussed replacing gojsonschema with something that is more well maintained in https://github.com/helm/helm/issues/10732, but I haven’t seen anyone pick up the work.

**Comment by thernstig** [comment]
@bacongobbler I would probably not be the one as my Go-fuu is not great. I wholeheartedly agree that focusing on replacing the json schema lib used should be priority #1 before anything like this is done.

(I have admittedly missed https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea)

**Comment by nicdard** [comment]
Has this been implemented? I would really like to have such feature

**Comment by bentatham** [comment]
Sharing schema definitions across charts would be amazing for us. Way too much duplication across the board. I wouldn't limit it to just a single file necessarily.  Likely related to https://github.com/helm/helm/issues/13490 to make that work.

Now that https://github.com/helm/helm/pull/13283 is almost merged, does this become more likely (even if only when the new json schema library is invoked)? (I would love to try to contribute as well, but things feel very much in flux at the moment with both these schema changes as well as the v3/v4 dev happening, so probably not a good time to jump in - but happy to have some help getting started to make it happen).

As an added bonus, helm could define some top-level definitions (eg `resources`) that match the kubernetes schemas themselves. So many helm charts allow basically free-form yaml for things like that, and it would be great to enforce that as early as possible - ie in the values.yaml itself.  (Pulling that in directly from the kubernetes version at runtime is likely a step too far at this point, I imagine).

**Comment by Xitric** [comment]
I am trying to write up a HIP for using Helm chart JSON schemas across charts and to integrate with external tooling as well, such as IntelliSense in modern IDEs.

I would very much like to see something like this supported in Helm natively (we wrote a plugin at my company to do it already, and it works great btw!). But I am also quite keen on not implementing a solution that is super Helm specific, such that it can work with external tooling as well.

One idea I am airing (and which is what we do at my company today) is that when you author an umbrella chart and you run `helm dependency update`, all schemas of your subcharts are extracted and placed inside the `schemas/` directory of your umbrella chart. Then the umbrella chart (and your IDE for that matter) can reference these subchart schemas and provide IntelliSense when authoring `values.yaml` files. The sub-schemas automatically reflect any updates to your subcharts this way.

This also doesn't require any special changes to the JSON schema engine used by Helm.

We should consider #10481 and the PR #12553 in order to support extracting schemas of subcharts that contain their own local schema references, either by extracting all schemas of the subchart, or by baking all subchart schemas into a single, self-contained schema file either during publishing or extraction.

**Comment by cwrau** [comment]
This would still be pretty awesome, there is just sooo much deuplication going on right now, just as @bentatham already said.
