### ISSUE TITLE
Helm unable to find the custom values yml file when installing the chart from remote

### ISSUE THREAD

**Issue by rameshar16** [helm/helm#10988]
$ helm install -n dev app repo/app-f values.dev.yaml
Error: open values.dev.yaml: no such file or directory

» helm version                                                                                                        
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}

**Comment by hickeyma** [comment]
@rameshar16 Is `values.dev.yaml` in the patch you are running the `helm install`?

**Comment by alan-czajkowski** [comment]
I'm having a similar issue with:
```shell
$ helm install "${helm_name}" "${helm_chart}" --values values-${DEPLOY_ENV}.yaml --version "${DEPLOY_VERSION}" --replace --repo "${helm_repo_url}" --kube-context "${k8s_context}" --kubeconfig "${KUBECONFIG_PATH}"
```

- there are multiple values YAML files bundled inside of Helm package (tgz), I would like to reference one of them during install
- the `--values` param only looks on the file system for the values YAML file, it does not look inside of the package (this is the underlying problem), it should first look inside of the package, then on the filesystem

**Comment by alan-czajkowski** [comment]
any updates on this?

**Comment by alan-czajkowski** [comment]
@hickeyma has this been resolved in a newer version of Helm?

**Comment by hickeyma** [comment]
@alan-czajkowski You issue looks different to @rameshar16 issue. @rameshar16 looks like the file might not be present on the files system  but can't be sure without more details.

The `--values` flag is working as expected. It is not designed to look for multiple values files bundled inside of a Helm package. The idea is that you override the default values file depending on how you want the package to be installed and the environment you are installing on (dev, prod etc.). In other words you control the configuration separate from the templates/chart. It seems counter intuitive to bundle value files within a package.

**Comment by alan-czajkowski** [comment]
@hickeyma I strongly disagree that bundling non-sensitive environment-specific values within a package is bad practice

here's 2 scenarios:

option 1: do not bundle environment-specific values inside package
- you must explicitly provide these environment-specific values outside of the package

option 2: bundle environment-specific values inside package
- have the option to reference which values file to use within the package

you can debate for a long time which option is better

my argument is, why bother arguing which one is better, why not get the best of both worlds? :)

allow bundling of environment-specific values within a package in order to treat them as "default" environment values for each environment _and_ also allow specifying external values files in order to _override_ those default values ... many frameworks work like, including the Java Spring Boot framework, which allows you to embed environment-specific values inside of the application binary _and_ also optionally reference an external environment-specific value in the event that you need to override those "baked in" defaults (for any reason, emergency or not)

**Comment by joejulian** [comment]
Happy to have a contribution to address this. Probably should start with a [HIP](https://github.com/helm/community/blob/main/hips/hip-0001.md) also take a look at the [contributing](https://github.com/helm/helm/blob/main/CONTRIBUTING.md) doc.

**Comment by joejulian** [comment]
Since there seems to be no movement on this and this issue falls outside of how helm is designed, I'm going to go ahead and close  this. If you have this need and the ability or wherewithal to contribute to this change, leave a comment and we can reopen it.

There is a workaround: document the place where you host alternative values files and reference them by url:
```
helm install mychart -n mynamespace --values http://myhost.domain.dom/mychart/examples/specific_values.yaml
```
