### ISSUE TITLE
Adding chart READMEs to the repository index

### ISSUE THREAD

**Issue by prydonius** [helm/helm#1098]
When discussing potential UI projects for Helm, one of the issues that comes up is where to get the chart READMEs from, as it's useful to display them when browsing charts from a repository in the UI.

Currently, a UI would need to download a chart's tarball and extract the README and then store it somewhere. Should chart repositories store the READMEs in a special way to prevent the need to download the chart's tarball?

One option would be to have the README in the repository index (could be base64 encoded), but this could drastically increase the size of indexes.

Another option would be to store the READMEs separately from the tarball of the chart. For example:

```
nginx-0.1.0.tar.gz
nginx-0.1.0.README.md
```

and the chart index could provide a `readme_url` that points to this.

Thoughts?

/cc @jackfrancis @migmartri @michelleN

**Comment by jackfrancis** [comment]
Thank you for capturing this in an issue.

While sourcing `README.md`s from distinct storage scales better for any services that would otherwise extract data by consuming the entire chart, it has the disadvantage of duplicating authority for the contents of the readme (part of the chart itself, and also in a dedicated namespace for just readme consumption).

After seeing your cutting-edge PaaS-like demo today, @prydonius, it's clear that eventually someone will innovate something fierce like including binary data in a chart, and then any chart consumers better be ready to consume real data. ;)

Another option to consider would be to add chart-specific resource endpoints to the repositories API spec. E.g., in addition to `/index.yaml` a chart repository would respond to `/{:chartName}/README.md` with just the readme.

So now we're at three ideas that all have demonstrable drawbacks...

**Comment by migmartri** [comment]
Assuming that an entry in the index.yaml file looks similar to the one below which includes a `home` entry (enforced by the linter).

Another way would be that the UI data ingestor pulls the README.md from `[home]/README.md`.

This will take the latest version of the file from the repository, which has the problem that it is not versioned. Problem that might not a big deal since we will import the current state of the readme file at the moment of the import. This is the way DockerHub imports the Readme files after an automated build.

I am not convinced of this solution either, but it seems that could work out of the box if we enforce at the linter and repository publishing level the existence and proper value of the home value.

```redis-2.0.0:
  name: redis
  url: https://storage.googleapis.com/kubernetes-charts/redis-2.0.0.tgz
  created: 2016-05-26 11:23:44.087939192 +0000 UTC
  checksum: 2cea3048cf85d588204e1b1cc0674472b4517919
  chartfile:
    name: redis
    description: Port of the replicatedservice template from kubernetes/charts
    version: 2.0.0
    home: https://github.com/example-charts/redis
```

**Comment by jackfrancis** [comment]
O.K., so now we have at least three creative alternatives. Because they all have rough edges, and arguably all of them add at least a wee bit to the architectural complexity of the repository or chart spec.

I am now leaning towards simply keeping things as-is, and pushing the problem to the UI API. Specifically, I think just extracting the entire chart for the `README.md` is the best long-term solution (in the absence of a perfect one). Primarily I am in favor of this because:

- Relying on the chart data itself for authoritative metadata means we can design our `README.md` ingestor generically, and anticipate future metadata extraction, rather than having a distinct tactic for each piece of chart metadata that we want the API to have a representation of.
- We are not entirely helpless against the scaling issue. As chart sizes grow as a result of feature progress in the project, and as the number of charts delivered by repositories increases, we can tune a cache layer in the API's implementation to represent an appropriate amount of data freshness in response to real-world I/O conditions.

Having spent a few days thinking about this, I think this strategy gets us the most bang for our buck over the long haul.

@technosophos @viglesiasce Any contradictory, supporting, or novel thoughts?

**Comment by technosophos** [comment]
My preference would be to leave the README in the tgz file and selectively extract it (tar is a decent format for that). I'm worried that inlining the README would have two consequences: First, it would easily double the size of the index. Second, it would introduce some escaping issues.

Honestly, neither of these are showstoppers.

**Comment by jackfrancis** [comment]
@prydonius If you agree that leaving the README inside the tarball is the best tradeoff, all things considered, why don't you close this issue. If not, please comment further!

**Comment by technosophos** [comment]
I'm closing, since I think we all agree at this point.

**Comment by itaysk** [comment]
Just wanted to say that IMO, the readme is as much metadata as other fields that are captured in the chart (perhaps the most practical piece of metadata). I would expect that either a readme link will be implied from home+'/readme.md', or added to the chart spec.

**Comment by prydonius** [comment]
Reopening this issue based on discussions with @itaysk.

Some concerns I have with specifying the README url in the Chart.yaml:

- Boilerplate: in kubernetes/charts all the URLs to the README will be with https://github.com/kubernetes/charts/tree/master/stable/<chart>/README.md. This will also be one more thing reviewers need to verify (on the plus side, it would be easy to lint in CI).
- Burden on user: when maintaining your own chart repository, the burden is on you to ensure you upload the versioned readmes somewhere and point to them from the Chart.yaml correctly. This essentially moves the processing from server side to client side. Since it's easy for a user to not do this properly, it limits the ability of tools like Monocular to show READMEs for all chart repos.
- Not just READMEs: I'll soon be adding support in Kubeapps for viewing values.yaml files and editing these when installing charts in the UI. This means we'll need to extract another file from the tarball, and I doubt we also want to add a field for this too.
- gRPC message size limit: IIUC chart tarballs cannot exceed the gRPC message size limit so this restriction actually keeps chart tarballs small enough to be quickly downloaded and processed. This means that it's not a very intensive task for the server to undertake.

**Comment by itaysk** [comment]
Thanks prydonius for re-opening this issue, I look forward to hearing the community's thoughts on this.

Today when a chart is packaged, most of the medatada is in the Chart.yaml and still it's required to copy this metadata over into the index.yaml. We don't extract the Chart.yaml from packages for obvious reasons, and for the same reasons I think it's unreasonable to read the readme that way.
The readme is another piece of metadata that omitted, and not being captured in this process.
One could argue that the readme is not that important as the other metadata, or that not every chart has a readme, but after looking at most public repos you'll notice that all of them have readme and the readme has the most useful information for the user.

So far as to explain the problem, now solving it is not easy. Here are 2 options that comes in mind:

1. configuration: add a `readme` field to the Chart.yaml spec
2. convention: look for readme in `sources[0]+"/readme.md"`

There are pros and cons to every alternative, including those 2, and I agree with all of what prydonius says, however I think any choice we'll make is better then current state.

**Comment by prydonius** [comment]
I think the only solution to including the README in metadata that would not require an extra step in the process would be to have `helm package` embed the whole README (base64'd) into the chart index. Since we know it's a text file, I don't think the size of the index will be a concern. We could also do the same for values.yaml as per my note above.

E.g.:
```
- version: 0.5.0
  embeddedFiles:
    readme: <base64>
    values: <base64>
```

**Comment by kfox1111** [comment]
I think there may be two different things being tied up in readme in this discussion.

For ui's, perhaps what is needed is a long description. That should probably be in the Charts.yaml and included in the repo metadata. This is used for the user to help select a chart, if its unclear by the short description that the chart is what they want. Kind of an extension of the "What solves my problem" use case.

The second use case is documentation specifying details about the deployment options of the specific chart. The user does not need to see that information until they have chosen to deploy the chart. Info like, what options they may want to set. This is more info of the "How do I deploy it" use case.

I've also argued that a bunch of the "how" docs need to be autogenerated as its currently a large burden to keep in sync 3 different possible sets of values as a chart developer. Readme, values.yaml and notes.

**Comment by bacongobbler** [comment]
closing as having been stale for over a year.
