### ISSUE TITLE
Helm diff always shows up as different values (quote/unquote) after upgrading a chart. Rendered chart and deployment history doesn't match.

### ISSUE THREAD

**Issue by Dunge** [helm/helm#11144]
I have an issue with the `[bitnami/rabbitmq]` chart when trying to use the helmfile tool which relies on `helm diff` for its operation.

I asked on bitnami/charts#10985 (see there for more details) but they recommended relaying the question here.

Steps to reproduce:
1: Install the chart with a values.yaml file (see above link for content) specifying an `auth.rabbitmq-password` value and requesting an older revision of the chart.
2: helm upgrade to the latest revision of the chart.
3: run `helm diff upgrade rabbitmq bitnami/rabbitmq --values ./values/rabbitmq.yaml --show-secrets`

```diff
  # Source: rabbitmq/templates/secrets.yaml
---   rabbitmq-password: amFtbG9naWM=
+++   rabbitmq-password: "amFtbG9naWM="

---   rabbitmq-erlang-cookie: QkF4VFRsNGh2aWozVmtpdkZhQnRZdHpaTE5sTzd0dE4=
+++   rabbitmq-erlang-cookie: "QkF4VFRsNGh2aWozVmtpdkZhQnRZdHpaTE5sTzd0dE4="

# Source: rabbitmq/templates/statefulset.yaml
---         checksum/secret: 388f011111c4fa426600c2adddaed1d58b04ee8cf7cc47961484be93aa805c6d
+++        checksum/secret: 7f0e27773fe4b7e51f4e31ac4755b5a7edbf714b0a8e4000daa7562e95d094bd
```

After that, no matter how many times you call "upgrade", it will always present the same diff output, as if it doesn't apply it.

The statefulset is computed from the secrets so it make sense it changed. The question is why does the helm history contains the password without quote, but the rendered helm chart have some?

Using helm `--dry-run --debug` or `helm template`, you can see it render the chart with quotes for these values (in all revisions). So why is it that what is saved in the helm history used by the diff plugin presents the values without quotes?

I'm using 15 other different helm charts in the cluster, some with overridden auth values too, and bitname/rabbitmq is the only one showing that behaviour, so I'm pretty sure something is wrong in their chart, but what could it be?

This is extremely annoying since it prevents me from using the `helmfile` tool since every time I call apply it always says it needs to upgrade this chart, which isn't true.

Output of `helm version`:
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
KinD

**Comment by mattfarina** [comment]
This sounds annoying. I would be frustrated if I encountered this.

I'm not entirely sure what is going on here but I can add some context. There are 3 projects here by 3 different groups. There is Helm, Kubernetes, and the [helm diff](https://github.com/databus23/helm-diff) plugin.

I installed the bitnami rabbitmq chart into k8s 1.24. With both Helm v3.8.2 and the tip of main I ran some tests. I looked at a dry-run template generation and I installed the chart then looked at its manifests. In both cases what came back was quoted. Helm appears to be consistent here.

The [Helm diff plugin is based on Helm v3.6.1](https://github.com/databus23/helm-diff/blob/ac48eca953a541aef9be10ed438991f543e935c7/go.mod#L22). I think [helm-diff makes calls out to the Helm CLI to get the manifests Helm used last time](https://github.com/databus23/helm-diff/blob/ac48eca953a541aef9be10ed438991f543e935c7/cmd/helm3.go#L45-L52). Those manifests are later [parsed into instances](https://github.com/databus23/helm-diff/blob/ac48eca953a541aef9be10ed438991f543e935c7/cmd/upgrade.go#L236) by Kuberentes packages (transitively through Helm 3.6.1) for v1.21.0. [Manifests for diffing are generated from there](https://github.com/databus23/helm-diff/blob/ac48eca953a541aef9be10ed438991f543e935c7/cmd/upgrade.go#L244).

I would look into helm-diff as the next step. I suspect it's something in there since the output from Helm is consistently quoted in my tests. helm-diff might need to be bumped to a newer version of Helm to pick up newer Kubernetes packages.

**Comment by alex-bes-ccl** [comment]
any updates on this?

**Comment by etutuit** [comment]
Still an issue, `kubectl diff` doesn't have such behaviour.
