### ISSUE TITLE
Request: Backport of `CVE-2022-36055` to Helm `3.6.x`

### ISSUE THREAD

**Issue by t-eckert** [helm/helm#11342]
We are using Helm `3.6.3` to power our CLI for installing Consul on Kubernetes. We recently updated to `3.9.4` to address CVE-2022-36055 and caught an issue when installing onto EKS (not showing up on AKS, GKE, or Kind): `Error initializing Kubernetes client: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"`.

We plan to address the core issue here once we understand it better, but for now, are you able to release the patch to the CVE as a backport to a `3.6.4` version to unblock us?

**Comment by bacongobbler** [comment]
As per [our release schedule](https://github.com/helm/community/blob/main/hips/hip-0002.md#patch-releases), we will not be backporting fixes to older releases of Helm. This has been requested in the past and we decided that we do not have enough engineering time to backport/patch older releases beyond the latest minor release.

Let's figure out the issue and attempt to address the root cause with the most recent version of Helm.

A similar issue was reported here: https://github.com/aws/aws-cli/issues/6920

Thanks.

**Comment by t-eckert** [comment]
@bacongobbler, thank you for your response. I will look into that issue and see if it is related. I'll let you know what I find.

**Comment by joejulian** [comment]
@t-eckert the problem is with the kubeconfig you're using for EKS. It's using an old deprecated api. Update the config file to solve that.
