### ISSUE TITLE
stop using stale bot

### ISSUE THREAD

**Issue by clintmod** [helm/helm#11474]
There are a bunch of issues that are valid that get "closed" by stale bot

**Comment by joejulian** [comment]
If we could get some more folks to manage the issue queue and answer questions and follow up on stale issues, I'd be happy to champion that. Right now we have two volunteer that do issue triage in our spare time and it's hard to just keep up with the new issues of the day.

Come on in! Join the weekly meeting, say hi! We're nice folks and happy to help you help us, even if it's as little as one issue a month, that's one more person getting helped that might not otherwise. Bring your expertise and experience!
