### ISSUE TITLE
helm package removes quote from version

### ISSUE THREAD

**Issue by martinounap** [helm/helm#11505]
Hi

We would like to use semver for our versions. 
Inside Chart.yaml we have version: "X.Y.Z+SOMETHING.Y" but after helm package (version 3.10.1) in side tgz file it is version: X.Y.Z+SOMETHING.Y

It might be bug?

**Comment by joejulian** [comment]
This is normal. The quoted string unmarshals to a string. Unless there's ambiguity about it being a string, the yaml marshaller will not wrap it in quotes. 1.2 could be a float, so that would be wrapped in quotes. 1.2.3 could not be a number, it can only be a string. No quotes are necessary for that.

Your semver cannot be anything but a string, so the yaml marshal function will not wrap it in quotes.
