### ISSUE TITLE
Three way merge for configmap data

### ISSUE THREAD

**Issue by parak** [helm/helm#11520]
Hey all,

I'm trying to figure out if three way merge is supposed to work in any manner for live changes to configmap data values. For example, if I have some starting data populated via a helm template in a configmap such as:

```
data:
  somefile.json: |
    {
      "somefield": {
        "somedata": "somevalue"
      }
    }
```

I then via `kubectl edit` change this in live deployment to something like so:

```
data:
  somefile.json: |
    {
      "somefield": {
        "somedata": "somevalue2"
      }
    }
```

During a helm upgrade, the data appears to get reset to the first example. If I add a new field via `kubectl edit` of some sort to the configmap itself such as a metadata label, that does get preserved. 

Is this normal functionality, and therefore a file stored in a configmap data that is generated via a helm template not intended to be modified manually?

Thanks!

**Comment by joejulian** [comment]
That is correct, helm is the owner of that file and any changes should be overwritten by what's in your templates.

If you look at the output of `helm template`, you'll see the resources that are applied. The updater creates a patch for any resources that differ from what's expected and applies that patch to repair those entries. See [pkg/kube/client.go updateResource](https://github.com/helm/helm/blob/9a5eb70320c1c1b7b6f1c5a6f0f5420cb1c934a0/pkg/kube/client.go#L486-L526)

As you can see in that code, if you use the `--force` flag, rather than patching it replaces the entire resource.

**Comment by parak** [comment]
Thanks @joejulian - I'm still a bit confused though as to whether or not three way merge is happening at all. I'm not using --force, and it does work when I add something like a label via edit, leaving that label in place. Or is my particular scenario where configmaps are modified manually after initial deployment, and expected to stay that way during upgrades, not a functionality that is currently supported/expected?

Much appreciated!

**Comment by joejulian** [comment]
Perhaps this is a better answer? https://helm.sh/docs/faq/changes_since_helm2/#improved-upgrade-strategy-3-way-strategic-merge-patches

**Comment by parak** [comment]
Yeah, I've seen that documentation, and that's exactly what I'm trying to understand better. Specifically the section "Upgrades where live state has changed". Why does this functionality seem to work as intended and as documented for something like a change to a label or annotation, but not to a data section of a configmap?

**Comment by joejulian** [comment]
because `data["somefield.json"]` is a defined field in the template. When the change is applied, it overwrites the string in that key. If you added `data["someotherfield.json"]`, which is not in the template, that key wouldn't be replaced and that would be used in the merge.
