### ISSUE TITLE
helm3 deleted CRDs with uninstall

### ISSUE THREAD

**Issue by DanTulovsky** [helm/helm#11564]
Hi,

The docs (https://helm.sh/docs/topics/charts/#limitations-on-crds) say:

```CRDs are never deleted. Deleting a CRD automatically deletes all of the CRD's contents across all namespaces in the cluster. Consequently, Helm will not delete CRDs.
```

I just did a `helm delete` on a chart (kubernetes-external-secrets) and it completely deleted the CRDs (which then deleted the ExternalSecrets - these themselves are in a different chart).

I did this via the lens ide (https://k8slens.dev/) by clicking their delete button under helm releases. (I am assuming this simply does a `helm delete`)

Can you please clarify if this is in fact working as intended or not?

**Comment by hickeyma** [comment]
@DanTulovsky Helm doesn't automatically delete CRDs in Helm 3. It did in Helm 2. 

This would only be possible if configured in the chart(s) that you used or perhaps from the environment you are running on. I suggest checking the chart you ran or with the chart maintainers.

**Comment by hickeyma** [comment]
It could be a number of things:

- The CRDs maybe created a templates in the chart `template` directory instead of the `crds/` directory. If this is the case and the CRD chart is a dependency on the chart you `helm uninstall` with then it will remove the CRD.  
- If you are using Helm v2
- The environment you are using. For example, this "lens ide"
