### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by chzhyang** [helm/helm#11594]
`helm version`: version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

`kubectl version`: v1.24.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  k8s locally

Steps:
```shell
$ helm repo add openfunction https://openfunction.github.io/charts/
$ helm repo update
$ kubectl create namespace openfunction
$ helm install openfunction openfunction/openfunction -n openfunction

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1"
```

How to solve this problem?

**Comment by hickeyma** [comment]
@chzhyang I wonder are you using a Kubernetes cluster v1.25? I ask because Kubernetes removed the `PodSecurityPolicy` in 1.25. See [kuberentes doc](https://kubernetes.io/docs/concepts/security/pod-security-policy/) for more details.

When you run `kubectl version` you should get the client and server version as follows:

```
$ kubectl version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:19:24Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+k3s1", GitCommit:"a8e0c66d1a90a2bbc4ffa975129ca35756cc7c14", GitTreeState:"clean", BuildDate:"2022-09-28T17:00:51Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/arm64"}
```

It is the server version that counts here.

**Comment by chzhyang** [comment]
> 

Thanks, I checked the version, 
```
$ k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

Do you means I should update k8s to 1.25, and try to re-install in helm?

**Comment by hickeyma** [comment]
> Do you means I should update k8s to 1.25, and try to re-install in helm?

Your Kubernetes cluster is version 1.25. `PodSecurityPolicy` object was removed from Kubernetes version 1.25.
As your Helm chart uses the `PodSecurityPolicy` object, then it will not install in this version of Kubernetes.

If you want to use the current version of the chart as is then you would need to install it in a Kubernetes cluster version < 1.25. Otherwise, you would need the chart to be updated to the alternatives as described in the [Kubernetes doc](https://kubernetes.io/docs/concepts/security/pod-security-policy/).

**Comment by chzhyang** [comment]
@hickeyma Got it, thank you!
