### ISSUE TITLE
Encountered CVE-2020-8552, CVE-2023-3978, CVE-2023-28840

### ISSUE THREAD

**Issue by SasmitaSahooTR** [helm/helm#12419]
Output of `helm version`: v3.12.3

Could you please confirm the date for the release of 3.13.3 and also include a update for golang/x/text in this release?

We are waiting for this release to fix CVEs found in three packages:

github.com/docker/docker v23.0.3+incompatible - already in 3.13.3-rc1
k8s.io/apiserver v0.28.2 - already in 3.13.3-rc1.
golang.org/x/text v0.13.0 - Fixed in [this commit](https://github.com/helm/helm/commit/58ccfc0501cdb222e33f431d868fe4a010f612e9) but not in 3.13.3-rc1

We thought 3.13.3 was being release on September 13th and would like to get a confirmation on the release date.

Thank you in advance

**Comment by mattfarina** [comment]
@SasmitaSahooTR Here is what I found...

- CVE-2023-28840 is for github.com/docker/docker which is not in 3.13.0-rc.1. This was due to libnetwork and the code path was not used by Helm.
- CVE-2020-8552 is for the k8s API and is not in 3.13.0-rc.1. This one was fixed more than 3 years ago.
- CVE-2023-3978 is a networking issue related to Go. The Go networking package is at a new enough version as to not have this CVE.

A scan of 3.13.0-rc.1 with trivy found no CVEs...

```
~/code/helm/helm #v3.13.0-rc.1 ·················································································································································· 10:00:08
❯ trivy filesystem .       
2023-09-25T10:00:10.602-0400	INFO	Vulnerability scanning is enabled
2023-09-25T10:00:10.602-0400	INFO	Secret scanning is enabled
2023-09-25T10:00:10.602-0400	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-09-25T10:00:10.602-0400	INFO	Please see also https://aquasecurity.github.io/trivy/v0.45/docs/scanner/secret/#recommendation for faster secret detection
2023-09-25T10:00:10.692-0400	INFO	Number of language-specific files: 1
2023-09-25T10:00:10.692-0400	INFO	Detecting gomod vulnerabilities...
```

3.13.0 was supposed to be released earlier but was delayed. It is expected this Wenesday.

**Comment by SasmitaSahooTR** [comment]
Thank you so much, Matt. The information is really helpful. Much appreciated. I'm looking forward to the release of 3.13.0.
