### ISSUE TITLE
Helm values.yaml validation with sub-chart and null isn't working correctly

### ISSUE THREAD

**Issue by sumo-drosiek** [helm/helm#12417]
I have experienced linting error, while I'm using `null` as value for subchart. I would expect that validation will be made after fallback to default sub-chart value

Error:

```
 helm install sumo1695302553314 sumologicdev/sumologic -f values.yaml --devel --version 3.14.0-46-g543a433e2f             
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/drosiek/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/drosiek/.kube/config
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-operator:
- manager: env is required
```

[Chart.yaml](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/543a433e2ff7856342b04162256f8df77a7564cf/deploy/helm/sumologic/Chart.yaml)

`values.yaml`:

```
opentelemetry-operator:
  manager:
    env: null
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}
```

Output of `kubectl version`:
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.23.17-2+40cc20cc310518
WARNING: version difference between client (1.28) and server (1.23) exceeds the supported minor version skew of +/-1
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
[microk8s](https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/c04f4a6d770c1c53440bbe5698b96bb97771e154/vagrant)

**Comment by alitta-german** [comment]
I also just bumped into an issue that probably has the same root cause.

helm template custom-release-name integration/ --set subchart.resources.limits.**_memory=null_**
```
           limits:
             cpu: "1"
             memory: "3Gi"
             ephemeral-storage: "100Mi"
```
It does not remove that item from the values.

While in this format it does:
helm template custom-release-name integration/ --set subchart.resources.limits.**memory=**
```
           limits:
             cpu: "1"
             ephemeral-storage: "100Mi"
```

And both ways work if I do it directly on the subchart:
helm template custom-release-name integration/charts/subchart/ --set resources.limits.**memory=**
```
           limits:
             cpu: "1"
             ephemeral-storage: "100Mi"
```

helm template custom-release-name integration/charts/subchart/ --set resources.limits.**memory=null**
```
           limits:
             cpu: "1"
             ephemeral-storage: "100Mi"
```

**Comment by sumo-drosiek** [comment]
The issue seems to be resolved in the newest helm chart
