### ISSUE TITLE
 Need to upgrade golang.org/x/net for CVE-2023-39325

### ISSUE THREAD

**Issue by srxmsft** [helm/helm#12497]
Output of `helm version`: 3.13.0

Output of `kubectl version`: 1.27.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

New CVE 2023-39325 was published 2 days ago. 
https://github.com/advisories/GHSA-4374-p667-p6c8

We need helm team to upgrade package and found a [dependabot](https://github.com/apps/dependabot) PR below.
But it is still in open status. 
https://github.com/helm/helm/pull/12481

**Comment by srxmsft** [comment]
Helm binary is flagged vulnerable in our CVE scanning. We need helm to be compliant in our product.

**Comment by reitzig** [comment]
What I don't understand is how [helm/helm@2745909d:go.mod#145](https://github.com/helm/helm/blob/2745909d3d753d68b7205c1f0a1153f50eb795b3/go.mod#L145) (the current trunk) already references 0.17 (which, according to the adivsory, contains a fix), and _has_ been since at least Oct 12th, but still v3.13.1 which was released _after_ that change occured still contains 0.13. 

Was there an accident in release preparation or is this "as expected"?

**Comment by reitzig** [comment]
Can't reproduce with 3.14.0
![image](https://github.com/helm/helm/assets/4246780/a9e1c761-1ae9-493f-8553-5967ce784f9b)
