### ISSUE TITLE
Broken Helm Rollback Command

### ISSUE THREAD

**Issue by sollidy** [helm/helm#12681]
I use local helm installation on fedora 38 with minikube.
It is copy of this closed issue - https://github.com/helm/helm/issues/11712

Output of `helm version`:
version.BuildInfo{Version:"v3.11", GitCommit:"", GitTreeState:"", GoVersion:"go1.20.1"}

Output of `kubectl version`:
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

Output of `linux version`:
Linux 6.6.8-100.fc38.x86_64

**Problem:**
helm rollback cmd breaks the deployment. Hence, corresponding deployments are deleted...everythins is gone after rollback with cli. 
Rollback is normal when i use it on vs code extention.

**Comment by MichaelMorrisEst** [comment]
Im not familiar with how the fedora builds its helm rpm, but looking at the source code rpm:
https://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/source/tree/Packages/g/golang-helm-3-3.11.1-1.fc38.src.rpm
it contains a 'revert-k8s-bump.patch' that appears to revert the change https://github.com/helm/helm/pull/11720 that @mattfarina implemented to fix #11712 so this appears to be a fedora issue rather than helm

**Comment by rathann** [comment]
Hi! Fedora package co-maintainer here. Thanks for the pointers, we'll try to fix this on Fedora side. Sorry for the trouble.

**Comment by herman-ounapuu-ep** [comment]
I can confirm that doing `helm rollback` with `helm` version 3.11 from Fedora Linux 39 official repos breaks the service by completely deleting all resources (including the deployment). Very glad to see that I know know why that was the case. :)

**Comment by toddejohnson** [comment]
Adding some links to help with visibility:
https://src.fedoraproject.org/rpms/golang-helm-3

https://src.fedoraproject.org/rpms/golang-helm-3/blob/rawhide/f/revert-k8s-bump.patch
