### ISSUE TITLE
Why does CheckDependencies function only compares the name and not the version?

### ISSUE THREAD

**Issue by raz-amir** [helm/helm#12765]
Hello,

Output of `helm version`:
```
version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.20.11"}
```

I noticed that, if, when running `helm template` or `helm install` commands, a dependency chart version inside the `Chart.yaml` file differs from that chart version located in the `charts/` folder, the command succeeds.
These commands succeed regardless of whether the `Chart.lock` file exists or not.
At the same time, the `helm dependency list` command marks that dependency chart with `wrong version`.
Looking at Helm's code, there is the [`CheckDependencies`](https://github.com/helm/helm/blob/e81f6140ddb22bc99a08f7409522a8dbe5338ee3/pkg/action/install.go#L701) function that checks that the dependency charts exists in the `charts/` folder. This function only compares by package name and doesn't compare the version.

Questions:
1. I was wondering why does it behave this way. Maybe it is related to the ability to manually manage the dependency charts?
2. Regardless of the above, do you think that it could be an improvement to enforce the version match when given a new flag? something like `--enforce-dependency-version`?

Thanks,
Raz

**Comment by z4ce** [comment]
What's the use case for wanting to enforce the versioning?

**Comment by ramir-savvy** [comment]
@z4ce, appreciate your attention to this, and your question is spot on! 😊

I've been working on an enhancement for argo-cd, and in the process, I encountered an interesting scenario.

The background in a nutshell: during its reconciliation cycle, argo-cd updates its git repo, cleans up leftover uncommitted code (usually from the `charts/` folder), and leverages `helm template` to regenerate manifests. If `helm template` fails, it checks the failure output for "missing dependencies". If found, it runs `helm dependency build` and retries `helm template`.
With multiple argo-cd applications having helm chart dependencies, each reconciliation cycle (which happens every few minutes) becomes quite time-consuming. The improvement I proposed in https://github.com/argoproj/argo-cd/pull/16750 tweaks the clean behavior by excluding the `charts/` folder (with a new flag), reducing the need for helm dependency build.

Here is the hiccup: I assumed `helm template` would fail if the dependency chart version in `Chart.yaml` changed in the git repo. It didn't, as described in this issue. To address this, I added a call to `helm dependency list` to catch the "wrong version" scenario, triggering `helm dependency build` if needed.

As a general use case, Helm's behavior in this context seems error-prone, especially if users manually bring in, by mistake, the wrong dependency chart versions into the `charts/` folder, and `helm template/install` remains silent about it.

I get that altering Helm's behavior has implications, which is why I'm suggesting the change only when a new flag is provided.

Thanks again for your attention!

**Comment by z4ce** [comment]
Hey @ramir-savvy if possible join the next developer call and bring this up. I've actually had this happen before myself (changing the version, neglecting to upgrade, and inadvertently using old chart versions).  I'd be in favor of this, but I actually wish it would just be the default. Developer call info is here: https://tockify.com/cncf.public.events/detail/158/1667493000000

**Comment by ramir-savvy** [comment]
Hi @z4ce, I will be happy t join if you think this is the way to promote this.
Can you tell what is the procedure to brung this up? Should I prepare anything?

**Comment by mattfarina** [comment]
I can provide some context here.

The source of truth for subcharts is the `charts/` subdirectory within a chart. You can put both chart archives in there and directories as charts. The charts don't need to be listed in the `Chart.yaml`. If there are "unmanaged" charts in the `charts/` directory than them will handle them gracefully when you deal with managed charts alongside them.

Checking for dependencies looked at the named availability of dependences and stopped there. This checking is a bit primitive, was lasted updated 5 years ago, and mostly has the original form to it.

What I would suggest is that for Helm v3, where we don't make braking changes, is that Helm check the dependencies listed in the `charts/` directory against the list in the dependencies within `Chart.yaml`. 

After considering this situation and looking at the backwards compatibility direction, I would suggest that for those that are listed in the `Chart.yaml` and the version does not match the constraint or the version listed in the lockfile (if present), a message is placed in the UI and Helm exit in error.

**Comment by ramir-savvy** [comment]
Thank you @mattfarina 

> What I would suggest is that for Helm v3, where we don't make braking changes, is that Helm check the dependencies listed in the charts/ directory against the list in the dependencies within Chart.yaml.
> 
> After considering this situation and looking at the backwards compatibility direction, I would suggest that for those that are listed in the Chart.yaml and the version does not match the constraint or the version listed in the lockfile (if present), a message is placed in the UI and Helm exit in error.

Can you please clarify if you suggest doing that change in Helm v3 or the next version?

**Comment by z4ce** [comment]
I think the general census was that `helm install` and `helm upgrade` should provide a warning message when `helm dependency list` indicates `wrong version`. And that would be applicable today. In Helm v4, we would want the the behavior to be exit with error. Is that right @mattfarina ?

**Comment by ramir-savvy** [comment]
Please also add `helm template` to the commands list
