### ISSUE TITLE
Disallowing '-' in key names causes problems

### ISSUE THREAD

**Issue by wgnathanael** [helm/helm#12865]
We're building a chart to deploy a number of sub-charts together. Essentially opensearch and opensearch-dashboards. We've run into an issue. 

To do this our values.yaml contains the keys `opensearch` and `opensearch-dashboards` to be able to provide values to the sub charts. This all works fine. 

*However*, in our own chart that has these as subcharts, we have templates and we'd like to reference values provided to subcharts so we don't have to define values in multiple places. This fails because in our templates when we do `{{ .Values.opensearch-dashboards.key }}` it dies because it found a - in a key name. 

I'm not sure why there's a restriction on key names not having - in them, its valid in yaml. However, if that remains then chart names should also disallow the '-' character. Or the restriction should be removed it seems.

**Comment by z4ce** [comment]
Here is a thread on this subject and a bit of explanation from ChatGPT :) 

https://github.com/helm/helm/issues/2192

In Helm, when you define values in a values.yaml file or through the command line, you might encounter issues accessing values that have keys with dashes (hyphens) in them. This is because Helm templates use Go's text/template package for templating, and the syntax for accessing map values directly in Go templates does not support keys with dashes without using a specific access pattern.

Here's a detailed explanation:

Dot Notation Limitation
In Go templates (and consequently in Helm), when you access a value using the dot notation, you're essentially navigating through the data structure. For example, {{ .Values.myValue }} accesses myValue under Values. However, if the key contains a dash (e.g., my-value), the template engine interprets the dash as a minus operator, leading to a syntax error or unexpected behavior.

Access Pattern for Dashed Keys
To access values with keys that contain dashes, you need to use the index method, which involves specifying the map (or object) and the key as a string. For example, if you have a value defined as:

```yaml
Copy code
my-values:
  key-with-dash: "example"
```

You can access it in a Helm template with:
```
```yaml
{{ index .Values "my-values" "key-with-dash" }}
```

This approach tells the template engine to look up the key "key-with-dash" within the map .Values["my-values"], effectively bypassing the limitation with the dot notation.

Best Practices
While you can use the index method to access keys with dashes, it's often recommended to avoid such keys when possible. Using camelCase, snake_case, or other naming conventions without special characters can make your templates cleaner and more straightforward to work with.

This explanation should help you understand the limitations regarding accessing values with dashes in Helm and how to work around them using the index method.

**Comment by wgnathanael** [comment]
Hello,

  Thanks for the thorough explanation. This does help clear up the issue. Though it does make it a bit tricky when the '-' is allowed in chart names. I would think that it would be good but probably too late to disallow the - in chart names.

  That being said, for anyone else running into the issue where you require a sub chart with a '-' in the name. We were able to work around the issue by aliasing the sub-chart to a name without a subchart. Thus allowing us to provide values to the subchart directly *and* use those values in our own templates without resorting to using index to access them which although it works isn't how you tend to see chart templates and could throw someone off on what is happening and why.
