### ISSUE TITLE
wrong kubeversion detected

### ISSUE THREAD

**Issue by Freundschaft** [helm/helm#13094]
I receive the following while trying to install a chart.

`Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.19 which is incompatible with Kubernetes v1.23.17-2+40cc20cc310518`

am I looking at this the wrong way, or isnt 1.23 >= 1.19 somehow?

Thanks!

**Comment by yxxhero** [comment]
@Freundschaft  I will confirm that.

**Comment by yxxhero** [comment]
@Freundschaft confirmed. because of `-2+40cc20cc310518`

**Comment by Freundschaft** [comment]
Yes i read somewhere that this happens because of semver my version is considered a pre release version, so is this behavior intended or a bug?

Thank you!

**Comment by mattfarina** [comment]
Two quick things before I get into the longer explanation.

1. This is intended behavior
2. There is a quick work around

This is all based around [SemVer](https://semver.org) and Kuberentes (see it's own [versioning guide](https://github.com/kubernetes/sig-release/blob/master/release-engineering/versioning.md)). From the specification:

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version.

Because of this, semver tooling usually requires opting into including pre-release versions. This isn't unique to Go. The JavaScript tooling, which might be the most widely used, does this.

`v1.23.17-2+40cc20cc310518` is a pre-release version because it has `-2`. The `+40cc20cc310518` is build metadata and is not to be used in sorting or comparisons. This is per the spec.

The work around for Helm charts is to set the `kubeVersion` to `>=1.19-0`. Adding the `-0` will tell Helm and the tooling to include pre-release versions since the range includes a pre-release. SemVer is based around ascii characters (according to the spec) and `0` is the lowest ascii character within the allowed rancher of characters. So, this will include all pre-releases for 1.19 and newer.

**Comment by yxxhero** [comment]
Cool. Got it.

**Comment by Freundschaft** [comment]
perfect thank you, ill close the issue

**Comment by azat** [comment]
Maybe it should strip at least `-gke` and similar prefixes, cause now it fails in GKE, i.e.:

```
Error: chart requires kubeVersion: >=1.30 which is incompatible with Kubernetes v1.30.2-gke.1587003
```
