### ISSUE TITLE
Directory structure not setup unless you `update`

### ISSUE THREAD

**Issue by slack** [helm/helm#216]
```
~ $ helm repo add slack git@github.com:slack/charts.git
[ERROR] Could not load /Users/jhansen/.helm/config.yaml: open /Users/jhansen/.helm/config.yaml: no such file or directory
~ $ helm update
---> Creating /Users/jhansen/.helm/config.yaml
---> Updating charts
---> Done
```

Do we consider this a bug? Or is `helm up` a required step.

**Comment by bacongobbler** [comment]
Are you upgrading from an earlier version? I think `helm update` should be the first thing you do after you grab the binary.

**Comment by rimusz** [comment]
@bacongobbler if we need to do the `helm update` after each new binary release we should some kind of note in the install docs

**Comment by slack** [comment]
Nope, this was a fresh compile, nuked `~/.helm` and then `helm repo ...`.

**Comment by technosophos** [comment]
I have been treating `helm update` as a required step. I don't want to have installation logic spread across every command, and I sorta feel like we should ensure that at least the base repo is installed. But I can probably be convinced otherwise for this particular case.

I see two questions for this case:

1. Should `helm repo add` perform installation logic?
2. If yes, should `helm repo add` also add the base repo (`deis/charts`), or just the one the user requested?

**Comment by technosophos** [comment]
This functionality is now provided by `helm doctor`. Yay @sgoings !
