### ISSUE TITLE
Why does Chart.yaml start with a capital 'C'

### ISSUE THREAD

**Issue by ethanculler** [helm/helm#2815]
I'm trying to understand the naming convention for files in Helm, but I am currently struggling. Files like "Chart.yaml" are always capitalized and "values.yaml" is always downcased.

Is there some pattern that I'm missing? Is there a purpose for the capitalization that I'm not aware of?

I'm sorry if this is a bit of a silly question, but it has been nagging me and i couldn't find any answers elswhere.

**Comment by bacongobbler** [comment]
Helm expects a capitalized `Chart.yaml`. As far as the actual reason behind that, I'm not sure.

relevant doc/source code links:

- https://docs.helm.sh/helm/#helm-package
- https://github.com/kubernetes/helm/blob/8e5a733b88c9af7e4057c918ad099c25c3b91233/pkg/chartutil/create.go#L30

This was also brought up in https://github.com/kubernetes/helm/issues/520, which was a ticket created before a Helm v2.0 MVP was even available.

**Comment by WillemMali** [comment]
Would it hurt to make it case-insensitive? (Right now it hurts my pinky.)

It would result in a degree of fragmentation (3rd party charts can now choose to break compatibility with old versions of Helm) but I'm not sure if that'd be a huge problem if the `stable` charts keep the Capital C for another year or two. Not really my area of expertise so perhaps someone more experienced in compat/versioning could chime in.

**Comment by bacongobbler** [comment]
slating as a discussion point for Helm 3.

**Comment by technosophos** [comment]
The story is long, rather uninteresting, and basically boils down to a claim made in the distant past that "metadata files should always begin with a capital letter because of the way old Linux sorts files by ASCII numeric value".

`values.yaml`, not being a metadata file, did not get an initial cap.

**Comment by bacongobbler** [comment]
After thinking this one through, while it seems like an easy choice for Helm itself to accept chart.yaml/Chart.yaml/chart.yml/Chart.yml, this makes it significantly harder on third-party projects to support marshalling/unmarshalling chart packages (as plugins, products etc). If we choose to accept multiple different file names for the package spec, then every other product has to support those choices.

My line of thinking here is this: by loosening the naming convention on files within the chart package specification, there's a much bigger cost than the net benefit. Because of this, I don't think that we should go ahead and support this.

I'm going to go ahead and close this as intended by design of the spec, but please feel free to leave a comment if you have an alternative use case where accepting differing names may be valuable.

Thanks for bringing this up!
