### ISSUE TITLE
Add plugin suggestions to helm core

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#2823]
For first time users to Helm, they may have heard about certain features that exist out of Helm core like `helm last`, `helm nuke` and `helm yeah`.

When users type out these commands but do not have them installed, perhaps Helm could make a suggestion for plugins blessed by the Helm community. e.g.

```
$ helm last
Error: unknown command "last" for "helm"
Please run `helm plugin install https://github.com/adamreese/helm-last` to install the `last` plugin.
```

**Comment by jascott1** [comment]
I like this idea. Some projects resist developing plugins and prefer core contributions since a plugin adds more installation steps (among other reasons). This would ease that a bit by providing the user with more info when they miss the 'install plugin' step.  This also leads to a registry of plugins that user can search and install from :)
```
helm plugin search
```
:sailboat:

**Comment by bacongobbler** [comment]
closing as inactive.
