### ISSUE TITLE
Not able to use the local icon image for packaging

### ISSUE THREAD

**Issue by willise** [helm/helm#2943]
I read the docs and find that the `icon` key in Chart.yaml just can use URL to fetch a icon image from internet.

But how should I display the chart "catalog" with icons if helm is installed in a private cluster without
internet access?

In OpenStack Murano, the local icon image can be packed with the package. And it would be a better experience.

**Comment by mattfarina** [comment]
@willise There are some differences between helm and Murano that are important. For example, helm packages are turned into `.tgz` files containing everything about a chart and put on a server that way. This is the the unit that is transferred around. Helm doesn't download a package until it needs it. So, when you pull up a listing the packages are not all available locally. How would helm or another tool get to the image this way?

Helm, Monocular, and any other tool that uses the `index.yaml` file needs a place to access the file remotely from just the `index.yaml` file and the availability of the remote endpoint.

This is why it's a URL. Even if the remote package is available it's a `.tgz` file and it's not easy to remotely access, over http, one of the files in its contents.

This setup for sharing information is based on debian. It's what we have today.

I just wanted to take a moment and explain for anyone who hasn't peeked at the setup.

This is the kind of change that could be possible in Helm 3 where some other changes are coming. Though, I'm not sure it will work to read inside local package files because you really don't want to have to download all of them to the client to view an image inside them.

**Comment by ktarplee** [comment]
Would [data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) work to inline the icon image in the Charts.yml file.  Kind of ugly but it might work.  I'm not sure if monocular supports data URLs.

**Comment by RoSk0** [comment]
I don't completely understand the problem of including an image in the chart itself. @mattfarina talks about other tools and having index.yaml but that file should be build somehow in the first place. If so, I believe this is reasonable to say that the tool that builds that file could extract the icon and cache it next to index.yaml.

**Comment by VladoPortos** [comment]
Was this solved somehow ? We also have airgap clusters, would be nice to include and reference the icon from the tgz

**Comment by dpapagiannis** [comment]
> Would [data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) work to inline the icon image in the Charts.yml file. Kind of ugly but it might work. I'm not sure if monocular supports data URLs.

This actually works! 

```bash
base64 your_img.png > pic.txt
```
Prepend the resulting base64 string with `data:image/png;base64,` and put it as a value to the `icon`, e.g.,

```yaml
icon: |
  data:image/png;base64,iVBORw0KGgo...
```
