### ISSUE TITLE
helm upgrade doesn't throw error when run in different namespace

### ISSUE THREAD

**Issue by mcwienczek** [helm/helm#3037]
`helm upgrade` doesn't throw the error when run with `--namespace` parameter that does not match release namespace. 

This looks like a breaking change and can probably be tackled in version 3 of helm.

**Comment by macropin** [comment]
Related #2814?

**Comment by bacongobbler** [comment]
Nope, separate issue.

**Comment by michelleN** [comment]
From the helm help text, it looks like the `--namespace` flag should only be used in conjunction with `--install` flag. See text copied below:
```
  --namespace string     namespace to install the release into (only used if --install is set). Defaults to the current kube config namespace
```

Helm should probably throw an error if a user is trying to use the `--namespace` flag without the `--install` flag. Were you using both flags? @mcwienczek

**Comment by mcwienczek** [comment]
Repro steps:
1. Install helm package using `helm install stable/mysql `
output:
```
NAME:   wandering-parrot
LAST DEPLOYED: Tue Oct 17 00:46:03 2017
NAMESPACE: default
STATUS: DEPLOYED
...
```
2. `helm delete wandering-parrot`
3. `kubectl create namespace different`
4. `helm upgrade --install --namespace different stable/mysql`

Output:
```
Release "wandering-parrot" has been upgraded. Happy Helming!
LAST DEPLOYED: Tue Oct 17 00:47:36 2017
NAMESPACE: default
STATUS: DEPLOYED
```

Is this the expected behaviour?

**Comment by michelleN** [comment]
Ah that's interesting. So, that's happening because there is still an underlying configmap associated with the release name still around. Because there is already a release with that name (in the deleted state), helm is skipping the install step and going straight to the upgrade in [which it uses the namespace in the last release ](https://github.com/kubernetes/helm/blob/master/pkg/tiller/release_update.go#L91).

The short term solution to this issue is in step 2, do a `helm delete wandering-parrot --purge`.

I'm not sure what expected behavior should be. Namespaces are a little tricky. Will have to get more eyes on this.

**Comment by vitorbaptista** [comment]
Just to confirm, this means that the releases must have unique names across namespaces, right? Something like this doesn't work by design:

```
helm upgrade --install --namespace staging myapp .
helm upgrade --install --namespace production myapp .
```

Instead, I should do:

```
helm upgrade --install --namespace staging myapp-staging .
helm upgrade --install --namespace production myapp-production .
```

Is that correct? If so, it's a bit surprising, as in Kubernetes AFAIK namespaces isolate everything, so I expected Helm to be the same.

Luckily, it's easy to just use different release names.

**Comment by mcwienczek** [comment]
That's correct

**Comment by bacongobbler** [comment]
It should be noted that we're changing that in Helm 3.

**Comment by bacongobbler** [comment]
Implemented in Helm 3. Changing the namespace context refers to a different instance altogether.

```
><> ./bin/helm version
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"5eb48f4471ac3aa9a3c87a07ee6f9e5bbc60a0e1", GitTreeState:"clean"}
><> ./bin/helm list --all-namespaces
NAME	        REVISION	UPDATED                                	STATUS  	CHART            	NAMESPACE
chartmuseum  	1       	2019-02-08 08:56:29.566393188 -0800 PST	deployed	chartmuseum-1.9.0	default  
chartmuseum  	1       	2019-02-08 09:14:01.978866327 -0800 PST	deployed	chartmuseum-1.9.0	foo
```

**Comment by zhangpengchen** [comment]
> Just to confirm, this means that the releases must have unique names across namespaces, right? Something like this doesn't work by design:
> 
> ```
> helm upgrade --install --namespace staging myapp .
> helm upgrade --install --namespace production myapp .
> ```
> 
> Instead, I should do:
> 
> ```
> helm upgrade --install --namespace staging myapp-staging .
> helm upgrade --install --namespace production myapp-production .
> ```
> 
> Is that correct? If so, it's a bit surprising, as in Kubernetes AFAIK namespaces isolate everything, so I expected Helm to be the same.
> 
> Luckily, it's easy to just use different release names.

Thanks @vitorbaptista,
The error message was misleading `Namespace "production" doesn't match with previous`. But actually the issue is same release name between different namespaces.
