### ISSUE TITLE
Using helm links to non-existent section on Tiller TLS configuration

### ISSUE THREAD

**Issue by danderson** [helm/helm#3229]
https://docs.helm.sh/using_helm/ says:

```
By default, when Tiller is installed,it does not have authentication enabled. To learn more about configuring strong TLS authentication for Tiller, consult the Tiller TLS guide.
```

The link points to https://docs.helm.sh/using_helm/#tiller_ssl , which does not exist.

**Comment by jascott1** [comment]
@danderson Thanks for catching this! I have confirmed this is a link to missing section.

**Comment by bacongobbler** [comment]
This doc exists, but it's not in helm-www. See https://github.com/helm/helm-www/pull/63 for an example on how to get this into docs.helm.sh.

**Comment by sslavic** [comment]
More sections in "Using Helm" have broken links, e.g. paragraph https://docs.helm.sh/using_helm/#tiller-namespaces-and-rbac has 3 links which all appear to be broken.

**Comment by jascott1** [comment]
Thanks @sslavic. I noticed that fragments are not working in some cases since (i think) the js router is writing urls to 'page/#fragment' instead of 'page#fragment' for some reason. Notice this link https://docs.helm.sh/using_helm#tiller-namespaces-and-rbac will take you to proper section but the URL will be rewritten to `https://docs.helm.sh/using_helm/#tiller-namespaces-and-rbac` with a new slash before the fragment. That URL does not navigate to the proper section.

I also ran [w3c link checker for https://docs.helm.sh](https://validator.w3.org/checklink?uri=https%3A%2F%2Fdocs.helm.sh&hide_type=all&recursive=on&depth=5&check=Check) and there are a lot of items to investigate (in addition to fragment problems).

**Comment by jody-frankowski** [comment]
The second RBAC link in [this section](https://docs.helm.sh/using_helm/#rbac) points to itself. It should point to `rbac.md` which should be [https://docs.helm.sh/using_helm/#role-based-access-control](https://docs.helm.sh/using_helm/#role-based-access-control) as far as i can tell.

**Comment by Nodraak** [comment]
Hi!

The page https://github.com/kubernetes/helm/blob/master/docs/tiller_ssl.md still does not appear on helm.sh

What is the status here ? Do you need any help ?

**Comment by bridgetkromhout** [comment]
Apologies for the delayed response here, and thank you all for your assistance.

The link originally mentioned - now found at https://v2.helm.sh/docs/using_helm/#installing-helm and pointing to https://v2.helm.sh/docs/using_helm/#using-ssl-between-helm-and-tiller - does now use the content from https://github.com/helm/helm/blob/dev-v2/docs/tiller_ssl.md.

The other links and redirections also work correctly now as well. Thanks!
