### ISSUE TITLE
Helm 3: Adopt common application metadata

### ISSUE THREAD

**Issue by bgrant0607** [helm/helm#3254]
The App Def Working Group is attempting to improve interoperability of tools. To that end, it would be useful if Helm participating in defining and adopting a common metadata CRD schema for much of the information currently in Chart.yaml.

#2431 covers use of JSON schema for parameter definition, which I also think would be useful, independent of the substitution syntax/mechanism.

**Comment by bacongobbler** [comment]
Thanks. Can you explain the use case more clearly so users who do not know what the app def working group is doing can better understand the end goal?

For what it's worth, I've attended several meetings and I'm *still* confused on the action items required to make apps like Helm inter-operable. I'm also missing the value-add here from the end user's perspective. I just haven't heard anyone from the community asking for this feature, from the end-user's POV *or* from maintainers of other Kubernetes tools that Helm is supposed to be inter-operable with.

It doesn't help either that half of the meeting is irrelevant to discussion around tool interop, but that's beside the point.

**Comment by bgrant0607** [comment]
Sorry for not responding earlier -- too many github notifications.

Intro to the App Def WG:
https://docs.google.com/presentation/d/1ZTsErNWwWCrGqIVRUHB-zjnZIgELNjqZe460Lvrd_60/edit#slide=id.p

Helm summit presentation:
https://docs.google.com/presentation/d/10dp4hKciccincnH6pAFf7t31s82iNvtt_mwhlUbeCDw/edit#slide=id.p

Application KEP (though yields pink unicorn consistently now):
https://github.com/kubernetes/community/pull/1629

The application metadata is now being worked on here:
https://github.com/kubernetes-sigs/apps_application

/remove-lifecycle stale

**Comment by bgrant0607** [comment]
@kow3ns

**Comment by bacongobbler** [comment]
Because the [Application CRD](https://github.com/kubernetes-sigs/application) is just another Kubernetes resource type, chart developers can utilize them with no further changes required to Helm or the template engine. If the Application CRD eventually becomes an interoperable standard for describing apps deployed to Kubernetes, we can propose a change to `helm create` to write one out for new charts, but it doesn't preclude Helm from supporting it in the first place, which was the original ask if I recall the conversation correctly.

I'm going to go ahead and close this as resolved, but please feel free to add any additional comments if there was something else you had in mind when creating this ticket. Thanks!

**Comment by mortent** [comment]
While I agree that it is technically possible to use the App CRD as any other Kubernetes resource in a Helm chart, it isn't very convenient. 

In many cases we probably want to make using the App CRD optional which means every resource in the chart needs a if statement around adding the App CRD labels. In order to make the list of resource types in the App CR correct, pretty complicated logic is needed to account for all configurations of the chart. Also, handling subcharts is complicated since it will require adding labels, but not create an independent App CR. And not to mention the work required to add App CRD support to all charts in the repo.. All of these things could be handled pretty easily if there were support for the App CRD in Helm.

Is there any way support for the App CRD could be done with a plugin for Helm 3? If there were a hook that allowed a plugin to inspect and potentially mutate the resources after the template engine step but before they were installed into the cluster, I think support for the App CRD could be done outside of the core Helm code.
