### ISSUE TITLE
Proposal: ability to save (export) and restore (import) releases

### ISSUE THREAD

**Issue by andreychernih** [helm/helm#3309]
We are using Helm as the only way to install and update software in the cluster (including system components for monitoring, logging and so on). It would be really good to be able to save the current state of all releases (name, chart, namespace, passed values) into a file (`helm export`). Later, this file can be used for disaster recovery or for creating new environment/cluster.

I know that Ark (https://github.com/heptio/ark) is a more specialized and sophisticated tool for such use cases but for our needs, Ark will be an overkill. We would also like to avoid using another tool.

I will be happy to implement it and submit PR if the community thinks this feature will be useful.

**Comment by bacongobbler** [comment]
#3089 might be related to this space. If we refactor tiller as a CRD controller for v3, it would open up the opportunity to save and restore releases. Right now, the common convention is to deploy an "immutable" chart to the cluster, but that might not best reflect the cluster's current state e.g. which versions were deployed, the dependency trees etc.

I know you think it might be overkill, but at the very least we would get Ark support for free by going that route because AFAIK it can handle the backup/restore of CRDs.

**Comment by technosophos** [comment]
I think it would be possible to implement something like this now. The release objects (usually the configmaps stored in the same namespace as `tiller`) contain all of the necessary information. So an export could simply bundle all of those. And an import could just replay them all.

So the workflow for `helm export` (or whatever it was named), would be:

- Fetch all ConfigMaps in Tiller's namespace where the label `STATUS=DEPLOYED` and `OWNER=TILLER`. (For legacy reasons, these are caps)
- Store the output in a file, probably gzipped

And the workflow for `helm import` would be:

- Read the archive
- For each configmap in the archive:
  - decode the release object
  - re-install with the chart and values in the release object using the `helm install` logic

This would be a great feature.

There are a few unknowns, though:

- Would we keep the revision history? We can dump all of the revisions by omitting STATUS=DEPLOYED, but we'd have to manually recreate the old revision ConfigMaps if we wanted
- Would we want to "replay" the upgrades? For example, if myApp is on version 5, do we do a `helm install` on version 5, or a `helm install` on version `, and then run a bunch of `helm upgrade` commands. Again, possible, but probably not desirable.

IMO, CRDs really have nothing to do with the feasibility of this. The release record that we currently store is more than sufficient. CRDs would just require us to use a slightly different query, but would otherwise work the same. So implementing this in the Helm 2 timeframe would actually streamline what we need to do in Helm 3 _if_ we use CRDs in Helm 3.

**Comment by bacongobbler** [comment]
I think this has been something that I haven't been too familiar with, which I need to do some research on... Does Tiller reconcile releases based on the ConfigMaps being deployed to Kubernetes, or is that a side-artifact *after* the deployment's already been done through tiller's deployment engine? If the former, then I agree, this would be completely feasible in Helm 2.

In other words, are the ConfigMaps just a "record" that tiller spits out, or could a user potentially `kubectl create -f` a configmap resource that will install a chart?

As for your unknowns:

> Would we keep the revision history? We can dump all of the revisions by omitting STATUS=DEPLOYED, but we'd have to manually recreate the old revision ConfigMaps if we wanted

I think retaining revision history would be a good idea, especially now that tiller can store a limited number of releases if the user chooses. That way users can export and import revision history and continue to perform rollbacks as they would have before.

> Would we want to "replay" the upgrades? For example, if myApp is on version 5, do we do a helm install on version 5, or a helm install on version , and then run a bunch ofhelm upgrade` commands. Again, possible, but probably not desirable.

This I think is undesirable. If chart hooks are involved, a user may be performing data migrations which could not be replayed back-to-front, but may be replayed front-to-back. Since this would be a back-to-front operation, it's probably better to just replay the latest deployment instead.

**Comment by andreychernih** [comment]
> In other words, are the ConfigMaps just a "record" that tiller spits out, or could a user potentially kubectl create -f a configmap resource that will install a chart? If it's the latter, then I agree, this would be completely feasible for Helm 2.

I was digging through code and I think that tiller first creates `release.Release` object and then installs it.

https://github.com/kubernetes/helm/blob/master/pkg/tiller/release_install.go#L36

```golang
// InstallRelease installs a release and stores the release record.
func (s *ReleaseServer) InstallRelease(c ctx.Context, req *services.InstallReleaseRequest) (*services.InstallReleaseResponse, error) {
	rel, err := s.prepareRelease(req)
        # ...

	res, err := s.performRelease(rel, req)
        # ...
}
```

Then ConfigMap is saved at the very end of this process. But it's just a base64 copy of `release.Release`.

https://github.com/kubernetes/helm/blob/master/pkg/tiller/release_install.go#L135

```golang

// performRelease runs a release.
func (s *ReleaseServer) performRelease(r *release.Release, req *services.InstallReleaseRequest) (*services.InstallReleaseResponse, error) {
        # ...
	s.recordRelease(r, true)

	return res, nil
}
```

This means that we can backup ConfigMaps and then simply send a request to tiller asking to re-install it.

**Comment by andreychernih** [comment]
Please let me know if it makes sense to implement this feature in Helm 2. I can come up with a formal proposal document.

**Comment by andreychernih** [comment]
I went ahead and created [proposal document](https://github.com/kubernetes/helm/pull/3343).

**Comment by vreon** [comment]
:wave: I'm also interested in the intersection of Helm, Ark, and disaster recovery -- and particularly how to deal with stateful apps.

Ark supports backup and restore of both API objects and PersistentVolumes (via cloud provider snapshots), and it also has a pretty sweet pre/post hooks system so you can flush writes, etc. However, as I understand it, an application restored by Ark wouldn't be managed as a Helm release without also backing up its Tiller ConfigMap. This proposal supports backup and restore of API objects (by reconstructing them from the release), but doesn't do anything special with respect to PersistentVolumes or hooks.

So this might be something I should bring up with the Ark maintainers instead, but I wanted to at least point out the areas where these two systems overlap / conflict / don't _quite_ meet my needs as a cluster admin.

**Comment by andreychernih** [comment]
Yeah, I think backing up volume contents is outside of the scope of this feature. I think it's even outside of the scope of Helm.

But I understand how it can be crucial for disaster recovery. My suggestion is to use external tools for that. My company does not have a similar problem at the moment because we prefer not to use Kubernetes for stateful services and databases. We've been having a really hard time trying to use volumes in Kubernetes and I honestly think Kubernetes is not quite there yet to support them reliably.

Our primary disaster recovery use case is when something happens with Kubernetes and it's easier to create a new cluster than trying to clean up the mess. Think Etcd crash / split brain.

**Comment by andreychernih** [comment]
@technosophos @bacongobbler just wanted to check in with you before I'll start working on this. Does my [proposal](https://github.com/kubernetes/helm/pull/3343/files) make sense?

**Comment by zamai** [comment]
I would also like to see this feature implemented.
The use case that brought me here is my CD pipeline:
When the build passes tests I want to update my values.yaml and then send that to tiller (doing sed in the file does not seem elegant solution). If the export would've been available the pipeline could be:
`docker build -t v2 ` >> `helm upgrade --set imageTag=v2` >> `helm export` >> `commit into git`

**Comment by bacongobbler** [comment]
If anyone wants to implement this as a [helm plugin](https://docs.helm.sh/using_helm/#the-helm-plugins-guide), that would be the best first steps to implementing this. That way you don't need sign-off from the core maintainers, and if it becomes a useful side project we can consider rolling it into core. `helm template` is one example that went through this process, for example.

**Comment by eversC** [comment]
@andreychernih (or anyone else) -- did you get round to having a go at this? 

I might have some time in a couple of weeks or so, but don't want to duplicate anyone's efforts..

**Comment by maorfr** [comment]
Hi,
Not quite the same as described here, but will get a similar result.
We wrote a tool wrapping Helm, which has an ability to assist in DR.

https://github.com/maorfr/orca#prepare-for-disaster-recovery

Hope this helps.

If this plugin is still not implemented by anyone, I would be happy to create it!
Let me know ;)

**Comment by maorfr** [comment]
A rather basic implementation. Would probably require additional modifications, but it works for some basic cases which I have tested:

https://github.com/maorfr/helm-backup

**Comment by maorfr** [comment]
@bacongobbler I think this issue can be closed :)
