### ISSUE TITLE
helm can delete resources not created by helm

### ISSUE THREAD

**Issue by svend** [helm/helm#3319]
**Issue**

A `helm install` can result in a FAILED deploy if resources it is trying to create already exist. Purging the failed deploy results in the existing resources getting deleted.

**What I expect**

Deleting a helm deployment does not delete resources that were created outside of helm.

**What happens**

Helm deletes resources that were created outside of helm.

Could helm use the heritage and release labels to determine which resources it owns?

**Steps to reproduce**

1. Manually create a kubernetes service resource named example using kubectl.
2. Install a helm chart that would also create a service named example. This will fail with error like `Error: release example failed: services "example" already exists`.
3. `helm delete --purge` the release. This will delete the example service.

**Version information**

```
$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment]
related comment: https://github.com/kubernetes/helm/issues/3313#issuecomment-355625103

**Comment by technosophos** [comment]
Since we don't _require_ the usage of those labels, we can't delete based on that. But I agree, this is a bug that we should fix.

Just to add some specificity for other readers:

If a chart is installed with the name `foo` and installs, says, a `deployment`, then the K8S API server _accepts the manifest_ (e.g. it is well formed), but then fails to _create_ the resources, we end up in a situation in which Helm believes the chart was installed, but k8s does not.

In a case where the install failed because a deployment exists with the same name, if you run a subsequence `helm delete`, Helm believes it owns the deployment that pre-dated the failed install. So it will delete it.

With Helm 3, we can _definitely_ solve this with labels. For Helm 2, we will need to figure out a more creative way to do this -- perhaps by checking that the creation time of the existing resources is equal to (or after) the release creation time.

**Comment by xchapter7x** [comment]
@technosophos 
mind if i take a crack at this one?

**Comment by bacongobbler** [comment]
sure!

**Comment by xchapter7x** [comment]
I had a little time to think on this and explore the code a bit. The discussion so far has been around preventing helm from deleting resources it didn't create, but perhaps we could just prevent it from wrongly claiming ownership in the first place.

currently in `func (s *ReleaseServer) prepareRelease` it performs operations like `uniqName` & `validateManifest`, would it make sense to add another validation step where we make a `Get` call using the KubeClient to check if the resource we are about to create already exists? 

It would mean an extra API call, but it would allow us to short circuit on existing resources, before tiller can claim ownership, which would prevent the issue described above.

Let me know if there are any gaps or things I am missing, or if this is a workable path forward for implementation of a fix.

Thanks in advance for your comments and suggestions.

-John

**Comment by xchapter7x** [comment]
hi @bacongobbler, @technosophos, @svend ,

I have a ready PR in to address this issue. Description and approach is in the PR.

Let me know your collective thoughts and feedback.
Thanks in advance.

pr: (https://github.com/kubernetes/helm/pull/3477)

-John

**Comment by xchapter7x** [comment]
hi @bacongobbler, @technosophos,

i just wanted to check in and see if you've had a chance to take a look at the PR for this issue?
Let me know your thoughts and how you'd like to proceed. Thanks :)
pr: (https://github.com/kubernetes/helm/pull/3477)
-John

**Comment by iomv** [comment]
We are in the same situation, with already existing services that creates aws' Load Balancers on creation. I don't want to delete the service to get it handled by Helm because it would mean re-creating the Load Balancer and losing all the references in my routing table.
Any chance we can get an update on this please?

**Comment by DanHoerst** [comment]
Any chance we could get an update on this?

**Comment by bacongobbler** [comment]
@DanHoerst feel free to give #3477 a try and see if that fixes the issue for you.

**Comment by bacongobbler** [comment]
fixed in Helm 3 via https://github.com/helm/helm/pull/6542
