### ISSUE TITLE
Expose chart's expected values to users

### ISSUE THREAD

**Issue by itaysk** [helm/helm#3431]
I think it will be beneficial for users to know the expected values files of a chart they are about to install, before they install it.

This is presumably solved by `helm inspect values` which is supposed to help the user understand what values are expected by the chart, but currently it just shows the contents of the `values.yaml` file. The problem with this implementation is that:
- the values file may not exist (it's optional according the our standard).
- the contents of values file are not required to cover all variables expected by the template.

I can think of several solutions:
- re-implementation of `helm inspect values` to crawl template files and extract values using regex.
- as part of the chart standard, define the `values.yaml` file as essential to charts, mandatory and complete.
- make all values required by default (in practice most charts in the wild think this way), and replace the `required` template function with another function to opt out.
- introduce a new construct as part of the chart metadata. related to: https://github.com/kubernetes/helm/issues/1098#issuecomment-359436138

Interested in your opinion. I am willing to implement the solution if we can agree on one.

**Comment by jascott1** [comment]
related: https://github.com/kubernetes/helm/issues/2744

**Comment by phemmer** [comment]
My own thoughts I figured I'd add here rather than creating a new issue:

I think it would be good to show the values of subcharts as well. Right now if you install a chart that has subcharts, you have to manually crawl the dependency tree to find all the required values (as mentioned, assuming they're documented in values.yaml).

----

Thoughts on the existing proposal

> re-implementation of helm inspect values to crawl template files and extract values using regex.

I don't think regex would be a good solution. This is akin to parsing xml with regex, [and we all know how that goes](https://stackoverflow.com/a/1732454/486035).

&nbsp;

> as part of the chart standard, define the values.yaml file as essential to charts, mandatory and complete.

There's nothing preventing someone from just creating an empty file. I think we need something that can be verified by a code.

&nbsp;

> make all values required by default (in practice most charts in the wild think this way), and replace the required template function with another function to opt out.

While I might agree with making vars required by default. I don't see how this relates to the exposed documentation of them.

&nbsp;

> introduce a new construct as part of the chart metadata.

I think something along these lines would work, but instead of just an opaque blob of text, actually have something machine parsable. I think this is going to be the only reasonable way to  handle the subchart issue since a chart might have the value `foo`, but once it becomes a subchart of the chart `bar`, the value (as exposed to the user) becomes `bar.foo`. Thus helm would have to recursively handle all the subcharts, and properly scope/prefix all the variable names.

If we want to maintain compatibility with the current value.yaml, we could do something like:
```
foo#description: This is foo
foo: bar
```
Or any way of adding an additional key to the yaml and deterministically relating it to the actual value name. And then something which isn't likely to collide with valid value names (hence my use of `#` in above example).

&nbsp;

> the contents of values file are not required to cover all variables expected by the template.

I think this one is a little hairy to enforce. The only possible way I can see to do it would be to use https://golang.org/pkg/text/template/parse/ to actually parse the template files, and look for `.Value.` references.

This might be a good start for a helm linter.

**Comment by bacongobbler** [comment]
closing as inactive.
