### ISSUE TITLE
Proposal: Add flag that automatically sets up roles in an RBAC enabled clusters

### ISSUE THREAD

**Issue by lilic** [helm/helm#3463]
When doing `helm init` in an RBAC enabled cluster, I would expect tiller to already have the necessary permissions setup. Currently the workflow is odd because most new clusters are RBAC enabled and RBAC is in stable now, so when you run `helm init` a user needs to setup `clusterrole`, `clusterrolebinding` as well as a `serviceaccount` to actually use Helm.

So the workflow I am imagining would be something like this:
```
helm init --service-account tiller --create-rbac
``` 

I had a look at some of the RBAC related issues but couldn't find anything related to this proposal, sorry if I missed any. :)

**Comment by bacongobbler** [comment]
Thanks @LiliC! I would love for this to come to fruition. The problem today with RBAC is that there is no "easy RBAC" solution out there. Off the top of my head, we have to handle a few use cases:

 - tiller in kube-system, acting as cluster admin (~90% of the userbase)
 - tiller in a namespace, able to create resources in that namespace
 - tiller in a namespace, able to create resources in a different namespace
 - tiller in a namespace, able to create resources in multiple namespaces

All of which have differing RBAC policies as provided in the [RBAC docs](https://docs.helm.sh/using_helm/#role-based-access-control). With that in mind, do you know of any solution we can implement to make that workflow easier to handle these different use cases (as well as potentially future use cases)?

**Comment by LiliC** [comment]
@bacongobbler Thanks for your quick answer! My suggestions would be the following:
- With the first case the above flag would work I think. So just run the following and the normal roles would be created. So the default would be `kube-system` namespace.
```
helm init --service-account tiller --create-rbac
```
- For the second case you would just have to pass in a namespace to override the default `kube-system` with the already existing flag `--tiller-namespace`. So same as above but with a namespace passed it would be:
```
helm init --service-account tiller  --tiller-namespace my-ns --create-rbac
```

As for the more complex namespace handling IMHO that is a small number of people and that can be done manually.

My suggestion would be also for this to be turned off by default and a warning given so that users are aware what kind of permissions they are giving to `tiller`.

**Comment by jascott1** [comment]
+1 for  a built-in solution to create the tiller RBAC stuff to allow new users to easily kick the tires. 
Thoughts:
1. Im not sure RBAC would change significantly but we would need to plan for what would happen if we implemented this and had to carry 1+n versions of RBAC for backwards compatibility. Even if its only 'support latest' we should spell it out imo.
2. Agree with @LiliC and we should have a warning and/or confirmation prompt when using this flag.

My very technical minded colleague stumbled on this today because he missed RBAC in the docs. I think this has been said but in the short term we might update https://docs.helm.sh/using_helm/#quickstart-guide to have RBAC instructions front and center since its the standard now.

**Comment by whereisaaron** [comment]
RBAC straightforwardly covers all those use cases @bacongobbler 

# User interface

`helm init --namespace=foo --service-account=tiller --create-rbac --deploy-namespaces=bar,baz,bif`
- `--namespace` defaults to `kube-system`
- `--deploy-namespaces` defaults to creating a single ClusterRoleBinding, or if one or more namespaces are listed, to one RoleBinding per namespace

You listed use cases:
1. `helm init --service-account=tiller --create-rbac`
2. `helm init --service-account=tiller --namespace=foo --create-rbac --deploy-namespaces=foo `
3. `helm init --service-account=tiller --namespace=foo --create-rbac --deploy-namespaces=bar`
4. `helm init --service-account=tiller --namespace=foo --create-rbac --deploy-namespaces=bar,baz,bif`

# Implementation

In all use cases `helm init` creates a Role for what tiller needs to run it its own namespace, and a ClusterRole for what it needs in deployment namespaces. Then in all use cases it creates one RoleBinding for the tiller Role in the tiller namespace (`kube-system` or `--service-account`).

Lastly, the only bit that differd by use case: 
- In the default use case it creates one ClusterRoleBinding for the ClusterRole
- In the `--deploy-namespaces` case, create one RoleBinding per listed namespace for the ClusterRole

**Comment by Jokero** [comment]
Also find this very inconvenient. A lot of people do the same actions for the same goal :)

**Comment by whereisaaron** [comment]
It's work noting that the plan is for tiller to go away in helm 3.x. Though that could be a way off.

**Comment by bacongobbler** [comment]
closing as inactive.
