### ISSUE TITLE
helm upgrade --reset-values not working

### ISSUE THREAD

**Issue by tadasv** [helm/helm#3685]
I'm running an upgrade command like this

```
helm upgrade --reset-values --set image.tag=$tag $service $chart_dir
```

If I manually modify some configuration in kube (via dashboard or kubectl) values are not reset when running the command above.

```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

**Comment by thomastaylor312** [comment]
Just double checking here, you are using `--set` which will still overwrite some values (I think...). Is it other values that aren't changing?

**Comment by tadasv** [comment]
@thomastaylor312 correct, as an example I am modifying CronJob schedule in the kube dashboard, and I have a variable in `values.yaml` for the schedule parameter that's different. I'm expecting the schedule parameter to be restored to chart default values. It also does not work if I additionally point to the values file with `-f`.

However it does work if I change the value in `values.yaml` to something else and run upgrade.

Example steps to reproduce:

1. initial values.yaml:
```
schedule: "*/10 * * * *"
```

Run helm install

2. Use kubectl or UI to modify resource
3. Run upgrade command from above

```
helm upgrade --reset-values --set image.tag=$tag $service $chart_dir
```

The value won't be restored to original.

**Comment by technosophos** [comment]
The reason things are not changing is because the diff to determine what changed is calculated between the last Helm release manifest and the re-rendered manifest generated by `helm upgrade`. In other words, your direct edits are being ignored by Tiller. Since nothing changed in your rendered templates, the patch set sent to Kubernetes is empty, and the existing objects (that you hand-edited) remain the same.

This is one of the reasons we recommend people not try to use Tiller and also manually edit objects directly. Use one or the other.

The design of this has to do with the way the `apply` logic works in Kubernetes. Kubernetes freely modifies your manifests. So Tiller needs to capture a "pure" version in order to generate a direct diff between what you intended on install and what you now intend upon upgrade. Apply happens client-side, not in Kubernetes itself (kubectl, for example, has all of the apply logic). That will change in the future, in which case Helm will redo the way we handle upgrades. At that point, this nuance will go away.

**Comment by tadasv** [comment]
@technosophos Your explanation makes things more clear. However, I'd consider such behavior a flaw in helm when using `--reset-values`, unless I'm completely misunderstanding the purpose of this flag.

Using only one of helm or kubectl/dashboard sounds nice in theory, however in practice I can see things being modified manually for any number of reasons, unless processes are very strongly enforced. My expectation for `--reset-values` is to have a similar behavior to terraform, puppet or any other config/resource management solutions where you ensure that resource state is always the same.

I'd like to update kube resources to default chart values even if there's no diff in Tiller config and when there are manual modifications in kube resources. It's almost like `helm del` + `helm install` without removing resources and with an option to pass in values with `--set` at the same time. Is there a way to achieve something like this with helm right now?

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by artem-kosenko** [comment]
> closing as inactive.

good solution, but the issue is still there :(

**Comment by bacongobbler** [comment]
The last time this ticket saw any activity was over two years ago. The answer @technosophos provided long ago discusses the internals of helm 2 and tiller, which was significantly refactored in helm 3.

If you are still experiencing issues, please open a new ticket and feel free to link back to this one.

**Comment by artem-kosenko** [comment]
I've updated to the latest helm version v3.2.1 but it has the same issue.

I resolved  the issue with a workaround:
- added additional environment variable with date of deployment in the helm-chart template.

helm recreate the pods each time it is updated, even the docker tag was not changed.
and as soon as image pull policy in "always" new pods start from the latest version.
