### ISSUE TITLE
Support release name reference in parent chart config

### ISSUE THREAD

**Issue by rmorrise** [helm/helm#3847]
I am trying as much as possible to use `helm create` scaffolding for my charts.

I have a parent chart with two child charts:
```
application:
db:
```

The `db` chart generates a name using the global fullname template from the scaffolding: `release-name`.

The `application` chart config needs to refer to the other chart's service name:
```
application:
  database:
    hostname: (db service name)
```
It looks as though it's impossible to do this, unless I override the db chart's name:

```
db:
  fullnameOverride: "myapp-db"
```

If I do this, this breaks the release-name convention in the scaffolding, meaning I can't have multiple side-by-side releases of the parent chart.

Please add support for this type of usage pattern (whether through templating in values.yaml or some other different mechanism).

Output of `helm version`:
```
$ helm version
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"g
o1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9
.1", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
$ minikube version
minikube version: v0.25.2
```

**Comment by englishm-llnw** [comment]
One way of accomplishing something roughly along these lines is to use `{{ .Release.Name }}-childchart-name` in your charts' templates, e.g.:
https://github.com/helm/helm/issues/3920#issuecomment-530443217

But if you're trying to establish this relationship _only_ by editing `values.yaml`, I can see the predicament **this** issue represents.

As for templating in `values.yaml`, I found some discussion of that possibility in https://github.com/helm/helm/issues/2492 with a [decision](https://github.com/helm/helm/issues/2492#issuecomment-413027879) that would not appear to support the scenario described here. Environment variable interpolation would not have access to `{{ .Release.Name }}`. I'm not sure if it could be done with a preprocessing plugin, but that seems like a less than ideal solution for this problem.

Perhaps scaffolding could be updated so that templates can more easily access sibling charts by accepting values which, if set, prepend `{{ .Release.Name }}` where they are used.

For example, maybe something like:
```
application:
  database:
    release_hostname_fragment: (db chart name)
```

...could be made to set `application.database.hostname` to `{{ .Release.Name}}-{{ template "application.database.release_hostname_fragment" }}`.

**Comment by bacongobbler** [comment]
closing as inactive.
