### ISSUE TITLE
<CHARTNAME> is not replaced in hidden files

### ISSUE THREAD

**Issue by s-spindler** [helm/helm#4058]
When using a custom starter via `--starter` the `<CHARTNAME>` placeholder is not replaced in hidden files like `.helmignore` or any custom dot-file.

Helm version: 2.9.0

**Comment by jgleonard** [comment]
Dotfiles are ignored on purpose, but I'm not sure why...

The rule added in the call to `AddDefaults` sourced in `pkg/ignore/rules.go` seems to be the root cause here.

I can create a PR with the change, but I'm not sure it's the RightThing to remove.

**Comment by SlickNik** [comment]
Hi @jgleonard, thanks for reporting this!

Taking a closer look it looks like this is likely by design -- the idea being to not interpret the dotfiles as YAML when loading templates since tools and OSes may create random dotfiles (more context at: https://github.com/kubernetes/helm/issues/1018 and the linked PR).

**Comment by jgleonard** [comment]
@SlickNik Thanks, based on the reasoning in there, I closed up #4064 but at least it got me familiar with the codebase.  I'll poke at another issue instead to start contributing.

**Comment by SlickNik** [comment]
@jgleonard No worries, thanks for taking a stab at it! You probably already knew this but good starter issues are tagged with `good first issue` -- just something to look at which might help with picking another issue. Thanks!

**Comment by bacongobbler** [comment]
closing as inactive.
