### ISSUE TITLE
plugin discoverability

### ISSUE THREAD

**Issue by michelleN** [helm/helm#4076]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment]
I'm working on re-writing the plugin system for Draft using GoFish as the underlying fetch/search mechanism. Would that be a fitting system to drop in for Helm 3? That would solve the plugin discoverability issue since users can then run `helm plugin search`, returning results from their local machine.

**Comment by bacongobbler** [comment]
for reference: https://github.com/Azure/draft/pull/764

**Comment by michelleN** [comment]
I wish I had put more context in this issue lol 😅 

This issue was intended to solve the plugin discoverability from the wild problem. For example, I want to be able to have a central place to see all the helm plugins that are available and what they do/what problem they solve and how much they are used, etc.

I was thinking it'd be nice to have a cncf landscape type of application where people can submit their plugins so that they can be discovered and used by others rather than a command on the command line. Picking plugins to use is a less common task so I think we should opt for the user interface option with a website and pretty frontend rather than a command. That's just my 2 cents. 

What do u think @bacongobbler ?

**Comment by bacongobbler** [comment]
closing as inactive.
