### ISSUE TITLE
Helm needs a complete template function reference

### ISSUE THREAD

**Issue by omkensey** [helm/helm#4077]
A very common issue users have writing charts is not knowing what chart functions are available, how to call them, and what their behavior is.  It would be good to have a nicely formatted complete reference:

* Functions by category with an alphabetical index
* Arguments they take and their types
* Expected output
* Examples of how they could be used in charts (example arguments, a template snippet, and the rendered output)

This will be somewhat duplicative of the upstream docs for gotpl and Sprig, but especially the last point I think would be useful for new chart authors.

**Comment by llamasoft** [comment]
I just wanted to chime in and say that the lack of function documentation has been a huge hinderance to my ability to adopt Helm.  There are so many useful functions (e.g. `AsConfig`/`AsSecrets`) simply mentioned _in passing_ in the documentation examples but they're never fully elaborated upon.  It makes me wonder how many useful tools I have at my disposal that I simply don't know exist because they're not documented.

I don't need anything fancy.  Just a list of functions, their parameters, and a brief description of what they do.

**Comment by bacongobbler** [comment]
PRs welcome: https://helm.sh/docs/chart_template_guide/functions_and_pipelines/

**Comment by howardjones** [comment]
The people looking for the documentation are not the people with the knowledge to write a PR for it, by definition.

**Comment by bacongobbler** [comment]
The ticket’s been open for 2 years. I’m closing it due to inactivity.

**Comment by GolubevV** [comment]
For me, it does not make sense closing the issue without anything actually been done.

Current documentation on functions sounds just ridiculous:

> Helm has over 60 available functions. Some of them are defined by the Go template language itself. Most of the others are part of the Sprig template library. We'll see many of them as we progress through the examples.

and then gives example of 3 of them

**Comment by hottomato4** [comment]
Some seem to have been added by this PR https://github.com/helm/helm-www/pull/700

**Comment by SDedik** [comment]
I believe this issue is still valid just as before and must be reopened.
Although there is this "functions list" https://helm.sh/docs/chart_template_guide/function_list/ it is far from being complete.
Just today I was working on a chart using I dare to say pretty basic functions like "join", "split" and "index". None of them is listed in that function list. Which is frankly embarrassing.
