### ISSUE TITLE
Duplicate keys in values.yaml are silently ignored

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/helm#4107]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

Duplicate keys in values.yaml are silently ignored: only the last value is used, no warning or error is raised.

Scenario:
```
$ helm create duplicatekey

$ cd duplicatekey

# edit values.yaml: duplicate and edit `image` subtree
$ cat values.yaml
# Default values for duplicatekey.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
image:
  repository: nginx
  tag: stable
  pullPolicy: Always
...

$ helm install . -f my-values.yaml --debug --dry-run 
[debug] Created tunnel using local port: '46691'

[debug] SERVER: "127.0.0.1:46691"

[debug] Original chart version: ""
[debug] CHART PATH: /home/thomas/work/2018-03-19-helm-deepo-chart/duplicate_key_yaml/duplicatekey

NAME:   honest-racoon
REVISION: 1
RELEASED: Tue May 22 17:26:36 2018
CHART: duplicatekey-0.1.0
USER-SUPPLIED VALUES:
bla: 2

COMPUTED VALUES:
affinity: {}
bla: 2
image:
  pullPolicy: Always
  repository: nginx
  tag: stable
...
```

Expected behavior: raise an error on duplicate key, or at least a warning.
Actual behavior: silent override `image` with latest value.

Silently overwriting the first key value can hide errors (for example a subtree copy/past with typo: forgot to edit the key on the pasted subtree).

I understand that silent values overriding is a main feature of helm **when the duplication is across multiple values sources**, but I don't see any use-case for same-source values.

**Comment by bacongobbler** [comment]
Labelling as an enhancement to `helm lint`.

**Comment by thomas-riccardi** [comment]
@bacongobbler it is not just a `helm lint` feature: I believe it would ideally be useful to raise an error on `helm install` too.
It would be a breaking change, so maybe just for helm 3? But at least a warning on `helm install` would help too.

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by torrescd** [comment]
Dramatization:
![image](https://user-images.githubusercontent.com/38782349/161972075-9f809edf-a31a-4b00-8be9-b62811704249.png)

![image](https://user-images.githubusercontent.com/38782349/161972275-e5428e0b-a768-470e-8f87-ee183cc51770.png)


A lot of sample values.yaml are populated with {} objects to comment optional values.

Usual error.

**Comment by KirkEasterson** [comment]
I recently faced an issue related to the lack of checking for duplicate keys. There were 2 devs on my team who simultaneously merged separate PRs introducing `environmentVariables` to `values.yaml`. But they each did this in separate parts of file which did not lead to a merge conflict. The staging deployment resulted in a crash loop due a missing environment variable. We should have caught this during review of the PRs. But given that it happened, it would have been preferable to catch this case with a CI linting error instead of our alerts.

~There exists [a test checking for duplicate keys](https://github.com/helm/helm/blob/59b57c5c31a009d069f9318c9d3ba8b784f1fe97/internal/chart/v3/loader/load_test.go#L475-L493), but previous comments in this issue imply that this is undesirable behavior.~ Is there still interest in fixing this issue? I can work on this issue. First I will focus on returning an error during `helm lint`. Then I can work on `helm install`. Does this sound reasonable?

EDIT: I misread the test. Ignore that sentence.
