### ISSUE TITLE
Extend the template lookup path when rendering

### ISSUE THREAD

**Issue by octplane** [helm/helm#4117]
Hello,

this is a feature request and I want to know the community advice before moving to a PR and/or help me figure out if my use of Helm is reasonable:

- We use Helm to `template` 10+ Charts for our infrastructure and in each of these Charts, we reuse some common parts with some slight configuration in each case: labels are normalised and applied to all objects, some specific CRDs are shared among most of the Charts, and we also share parts of the configmap.
- to achieve an efficient re-use, we `include` to grab these small templates and we use symlinking (this is the ugly part) to share the same templates across several Charts

It work pretty well, but rather cumbersome and not very nice to maintain.

So I wanted to know if his would be interesting to provide a way to extend the `templates` load path so that we could `include` files which are actually outside the Chart base path. I was thinking of an additional flag that would extend the Template load path:

```
# Render the chart but also provide access to templates stored in k8s/templates
$ helm template \
   --name=myapp \
   --namespace=default
    -f k8s/common.yaml
    -f datacenter-config/datacenter1/helm/common.yaml
    -f datacenter-config/datacenter1/helm/myapp/values.yaml
    -i k8s/templates
    k8s/myapp
```

Let me know what you think of this.

**Comment by michelleN** [comment]
Oh that's so interesting! If I'm understanding this correctly, templates in `k8s/templates` passed in via the `-i` flag contains libraries of common template libraries you use across charts which makes lots of sense. I'll let @prydonius and @technosophos weigh in here because they did quite a bit of work a while back around patterns from common templates used across charts.

I think this feature could be really useful. Generally speaking, the only issue I see here has to do with creating a complete chart artifact that can be shared and reused. How do you deal with these common templates in charts that are shared and passed around? 

If you're passing in these common templates from the command line, then your actual chart may be incomplete and un-installable on its own. Would that be a correct assumption here in your case? Even if that's true though, I don't know if we'd want to block this kind of functionality/ability for an end users in the `helm template` command.

Would it make more sense to have these common templates (`k8s/templates`) in the chart as a subchart? I believe that's the direction @prydonius and @technosophos were headed in a while back.

**Comment by octplane** [comment]
Thanks for your quick feedback @michelleN !

Building a complete chart artifact it this case seems more complicated, indeed and using subchart could maybe be a nice in between solution.

I have been able to reproduce the intended behaviour using a mostly empty subchart and a requirements which has the form:

```yaml
dependencies:
- name: commons
  version: 0.1.0
  repository: "file://../commons"
```

So far, this seems to do the trick for locally shared includes. Of course, if you want to push that in a Repository, you'll have to use the correct URL and version for these common includes.

If @prydonius and @technosophos think the subchart solutions is the recommended one, this could maybe be added to the official doc as a nice way to share templates across Charts.

**Comment by bacongobbler** [comment]
closing as inactive.
