### ISSUE TITLE
Allow returning specific exit code for helm plugins

### ISSUE THREAD

**Issue by royjs** [helm/helm#4170]
We are looking into returning different exit codes in the helm-diff to simplify some CI scenarios (See databus23/helm-diff#54)

The issue is that Helm considers any non zero exit codes from the plugin to be an error and will always exit with `1`. We need to be able to return a specific exit code to the caller.

E.g. we want the `helm diff upgrade` command to return with exit code `2` if no error occurred but some changes were found.

Any thoughts on how this could/should be implemented?

**Comment by mumoshu** [comment]
Anyone is working on this? If not, I'm going to pick this up!

My motivation to implement this inside helm went up due to that I can't just run the underlying `helm-diff` binary alone. That's because `helm-diff` depends on connectivity to tiller, that is `helm`'s functionality to start port-forwarding to tiller and populate the address:port to it in the TILLER_HOST envvar.

**Comment by mumoshu** [comment]
Submitted #4367 for this.
