### ISSUE TITLE
toYaml removes all quotes and yaml types breaks

### ISSUE THREAD

**Issue by shal** [helm/helm#4262]
Output of `helm version`:
```go
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```go
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.10-gke.0", GitCommit:"16ebd0de8e0ab2d1ef86d5b16ab1899b624a77cd", GitTreeState:"clean", BuildDate:"2018-03-20T20:21:01Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  **GKE**

I got following problem:

File: `values.yml`
```yaml
info:
  address: "0x1ddf249430c343f72f8b12848aa3f932538e3336"
```

File: `configmap.yml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  file.yml: |-
{{ toYaml .Values.info | indent 4 }}
```

After `toYaml` address will be not a string.

**Comment by bacongobbler** [comment]
@ashanaakh can you provide the output of `helm template` with this sample?

**Comment by ashanaakh** [comment]
@bacongobbler Sorry, I can't provide all output, because it is confidential information.

I see, that function changed type of `0x1ddf249430c343f72f8b19868ea4f932500e0000`.

In values.yml it was in quotes, like

```yaml
address: "0x1ddf249430c343f72f8b19868ea4f932500e0000"
```

After `toYaml`, I see

```
address: 0x1ddf249430c343f72f8b19868ea4f932500e0000
```

**Comment by bacongobbler** [comment]
oh I see what you mean. However, both are considered strings though according to the YAML spec though, right? That should still work as a string as the YAML spec says that single, double and unquoted values are accepted as strings.

**Comment by ashanaakh** [comment]
@bacongobbler Unfortunately, `0x1ddf249430c343f72f8b19868ea4f932500e0000` is hexadecimal literal in `yaml`.
Please, take a look on yalm specification [here](http://yaml.org/spec/1.2/spec.html).

Thanks!

**Comment by ashanaakh** [comment]
@bacongobbler

Here I see, that `toYaml` function just use dependency for marshaling.

https://github.com/kubernetes/helm/blob/aa98e7e3dd2356bce72e8e367e8c87e8085c692b/pkg/strvals/parser.go#L33-L40

I reproduced this bug using helm dependency `github.com/ghodss/yaml`.

```go
package main

import (
	"fmt"
	"github.com/ghodss/yaml"
)

func main() {
	p := map[string]string{"key": "0x1ddf249430c343f72f8b19868ea4f932500e0000"}
	d, _ := yaml.Marshal(p)
	fmt.Print(string(d))
}
```

Output will be:

```
key: 0x1ddf249430c343f72f8b19868ea4f932500e0000
```

Actually this dependency had one more dependency, which is `github.com/go-yaml/yaml`, where this bug occurs.

**Comment by hmcmanus** [comment]
It might be a bit late now but I had the same problem but was able to get around it by copying what these guys did here:

https://github.com/kubernetes/charts/blob/master/incubator/elasticsearch-curator/values.yaml

**Comment by amir-hadi** [comment]
@shal You closed this issue, did the problem disappear for you? I see a similar behavior with `toYaml` which is caused problems for me right now.

**Comment by shal** [comment]
Hey @amir-hadi, I temporary resolved this issue by just copying all YAML files as config maps into the helm chart 😄

**Comment by jocko-wowza** [comment]
So I'm trying to us toYaml to dynamically inject custom Environment variables along side required environment variables in my container: definition in my Helm chart.

The problem is that regardless of whether the value is a numer or string, the requirement is that the environment value needs to be quoted.   Because toYaml is unquoting it my helm chart is failing.

Anyone know how I can prevent this?

**Comment by jocko-wowza** [comment]
I solved it by not using toYaml ... That's a seemingly direct way to get data from a values file to append to my `env:` key, but this solution allows me to make sure all of the values are quoted:

```
{{- range some_value.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
{{- end }}
```

**Comment by rdxmb** [comment]
In my opinion this is a bug and not an question/support like it is actually labeled.

**Comment by rdxmb** [comment]
Can this issue be opened again?

**Comment by bacongobbler** [comment]
If someone wants to take a crack at this, here's where `toYaml` resides in the source code. Pull requests with unit tests welcome.

https://github.com/helm/helm/blob/bb33b9264fd657103d160adae5a091a2e3afdcc4/pkg/engine/funcs.go#L79-L90

**Comment by AdheipSingh** [comment]
i use this 
``` {{ tpl $value $ | quote }}```

**Comment by dfurtado** [comment]
Hi guys, I would like to leave my contribution to this issue, I have investigated a little bit, and I don't think this is actually a bug.

It seems like the package `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2` internally. The `gopkg.in/yaml.v2` try to figure it out which type of data it is going to parsed and written to the YAML output. This is done in the `marshal` function in `encode.go`, in case of a `map` it will iterate through the keys and values and call `marshal` function recursively for each key and value

The scenario described by this issue, you have a `string` value `0x1ddf249430c343f72f8b19868ea4f932500e0000`, so the `marshal` function will call a function called `stringv` which will decide how to output the value, for instance, if it should be quoted or unquoted and so on. 

Inside `stringv`, the function `resolve` is called and it will try to parse using `strconv.ParseInt` and `strconv.ParseUInt`, however, the value `0x1ddf249430c343f72f8b19868ea4f932500e0000` cannot be parsed correctly and the resolver assume that the value can be written as plain text returning a `tag:yaml.org,2002:str` and the value returned is unquoted.

If we use the same example to reproduce the problem with a valid value, it works:

```go
package main

import (
	"fmt"
	"gopkg.in/yaml.v2"
)

func main() {
	p := map[string]string{"key": "0x1c8"}
	d, _ := yaml.Marshal(p)
	fmt.Print(string(d))
}
```
Output: key: "0x1c8"

**Comment by franck102** [comment]
Just encountered this, it makes toYaml pretty useless for us. With this in values.yaml:

```
foo:
  bar: ":tricky-{}[]!#|>foobar%@"
```
this template

```
foo:
{{  .Values.foo | toYaml | indent 2 }}
```

loses the quotes:

```
foo:
  bar: :tricky-{}[]!#|>foobar%@
```

**Comment by bacongobbler** [comment]
see https://github.com/helm/helm/pull/8890.

**Comment by rdxmb** [comment]
/ no stale please

**Comment by javipolo** [comment]
This bug bit me in the ass today :(

Part of the map to that is passed through toYam are regexps that need to be in single quotes
Since the toYaml removes the quotes, the regexps are either different or directly invalid yaml

Is anyone looking at this 3 year old bug?

**Comment by AntonioCayulao** [comment]
I was able to fix the problem making this:
values.yaml:
```yaml
configmap:
  PROJECT_ID: ""
  ENDPOINT: ""
  PORT: ""
  PROTOCOL: ""
```
And in my configmap I wrote this:
```yaml
{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
{{- range $key, $val := $.Values.configmap }}
  {{ $key | quote }}: {{ $val | quote }}
{{- end }}
{{- end }}
```

**Comment by WassimBenzarti** [comment]
> This bug bit me in the ass today :(
> 
> Part of the map to that is passed through toYam are regexps that need to be in single quotes
> Since the toYaml removes the quotes, the regexps are either different or directly invalid yaml
> 
> Is anyone looking at this 3 year old bug?

Same issue just happened to me too, part of the yaml was a regex expression

**Comment by rdxmb** [comment]
closed? :confused: 

/reopen

**Comment by javipolo** [comment]
Yes, reopen please. This is a big issue

**Comment by mr-remington** [comment]
I havent seen this mentioned but toYaml is referenced in the library documentation here [](https://helm.sh/docs/topics/library_charts/). 

Dropping quotes or not respecting things like `{{ required "required: .Values.foo" .Values.foo | quote }}` from values will quickly become a blocker for anyone looking to adopt this was of doing things

**Comment by FelipeEmerim** [comment]
We are highly affected by this issue because we use library charts. All our templates call `toYaml`. We want to render consul service tags using helm, but helm removes the quotes and insert line breaks on whitespaces after calling `toYaml` on the merged templates, which breaks consul.

```yaml
consul.hashicorp.com/service-tags: "\
          traefik.enable=true,\
          traefik.http.routers.{{ .Values.app.fullName }}.entrypoints=websecure,\
          traefik.http.routers.{{ .Values.app.fullName }}.rule=Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.path }}`),\
          traefik.http.middlewares.{{ .Values.app.fullName }}-stripprefix.stripprefix.prefixes={{ .Values.ingress.path }},\
          traefik.http.routers.{{ .Values.app.fullName }}.middlewares={{ .Values.app.fullName }}-stripprefix"
```

Helm template outputs this instead:

```yaml
consul.hashicorp.com/service-tags: traefik.enable=true,traefik.http.routers.default-super-service.entrypoints=websecure,traefik.http.routers.default-super-service.rule=Host(`super-host-prd.com`)
          && PathPrefix(`/super-service`),traefik.http.middlewares.default-super-service-stripprefix.stripprefix.prefixes=/super-service,traefik.http.routers.default-super-service.middlewares=default-super-service-stripprefix
```

As a workaround we perform a replace after the toYaml call to keep the original format

**Comment by bacongobbler** [comment]
Sigh... I'll re-open this issue, but this ticket has been open for over three years, and I have not seen anyone attempt to fix this issue. [Contributions to help fix the issue](https://github.com/helm/helm/blob/main/CONTRIBUTING.md) are most welcome.

I pointed out where the code exists [a year ago](https://github.com/helm/helm/issues/4262#issuecomment-674193064). I even [provided a hint](https://github.com/helm/helm/issues/4262#issuecomment-678321251) as to how someone could test its expected behavior in certain situations.

Meanwhile, someone [looked into `toYaml`'s behavior](https://github.com/helm/helm/issues/4262#issuecomment-683432536) and concluded it was NOT a bug in the code itself, but how people are consuming the output of `toYaml`. In other words perhaps some documentation around how to use `toYaml` in a chart would be more sufficient.

But in any case... I have no idea how to proceed here. We also have to keep in mind that any changes to the template engine MUST remain backwards compatible. In other words, changing the behavior of `toYaml` may NOT be desirable, and it may be more preferable to document its behavior so that we don't accidentally break charts that have worked around this behavior.

If someone else can find the time to look into this and provide suggestions, we'd appreciate the help.

**Comment by rdxmb** [comment]
@bacongobbler thanks.

I am not a developer, so I cannot help here with coding. If there is something to test, I could help ...

> but this ticket has been open for over three years

That's why I am wondering about. Also I am wondering about why this issue was closed without any statement. If this is the way it goes, this should explicitly be closed with marked as a `won't fix`. 

For me as a system engineer `toYaml` just seems to be quite buggy. If this works as expected, the limitation should be documented in the docs.

As we see above in the comments, this is quite confusing. I've started using the workarounds listed above.

> In other words perhaps some documentation around how to use toYaml in a chart would be more sufficient.

At least this should be done. The docs should also have the alternatives documented. If  `{{ tpl $value $ | quote }` is the way to go in such cases, there should be a notice with examples or a link to [tpl](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function)

Do we need `toYaml` or can we always use the other solutions? If there is a way to use the other functions in **any** case, we do not need `toYaml`, do we?

**Comment by bacongobbler** [comment]
> At least this should be done.

Please feel free to do so. The documentation can be found [here](https://github.com/helm/helm-www/).

**Comment by rdxmb** [comment]
Hm, I guess I do not know if I've understooden the necessary thinks to do that. 
To be honest, I did not get the "way to do" it in this case.

Let's try:

```
$ cat values.yaml 
file: 
  address: "0x1ddf249430c343f72f8b12848aa3f932538e3336"
$ cat templates/dummy.yaml 
---
data:
  toYaml.yml: |
{{ toYaml .Values.file | indent 4 }}
$ helm template .
---
# Source: helm-stuff/templates/dummy.yaml
data:
  toYaml.yml: |
    address: 0x1ddf249430c343f72f8b12848aa3f932538e3336
```

```
$ cat values.yaml 
file: |
  address: "0x1ddf249430c343f72f8b12848aa3f932538e3336"
$ cat templates/dummy.yaml 
---
data:
  toYaml.yml: |
{{ tpl .Values.file $ | indent 4 }}
$ helm template .
---
# Source: helm-stuff/templates/dummy.yaml
data:
  toYaml.yml: |
    address: "0x1ddf249430c343f72f8b12848aa3f932538e3336"
```

Ok. This also works with

```
$ cat values.yaml 
env: |
  - name: address
    value: "0x1ddf249430c343f72f8b12848aa3f932538e3336"
$ cat templates/dummy.yaml 
---
env:
{{ tpl .Values.env $ }}
$ helm template .
---
# Source: helm-stuff/templates/dummy.yaml
env:
- name: address
  value: "0x1ddf249430c343f72f8b12848aa3f932538e3336"
```

Can we see `tpl` combining with `|` in the values as a solution for most of the use cases?

For this does not work:

```
$ cat values.yaml 
env: 
  - name: address
    value: "0x1ddf249430c343f72f8b12848aa3f932538e3336"
```
$ cat templates/dummy.yaml 
---
env:
{{ tpl .Values.env $ }}
```
$ helm template .
Error: template: helm-stuff/templates/dummy.yaml:3:14: executing "helm-stuff/templates/dummy.yaml" at <.Values.env>: wrong type for value; expected string; got []interface {}

Use --debug flag to render out invalid YAML
```

So I am kind of confused what the recommended way is to do things like that.

**Comment by FelipeEmerim** [comment]
Is there a solution to the library charts use case? Pretty much every template uses toYaml because of the merge function bellow:

```go
{- define "library.util.merge" -}}
{{- $top := first . -}}
{{- $overrides := fromYaml (include (index . 1) $top) | default (dict ) -}}
{{- $tpl := fromYaml (include (index . 2) $top) | default (dict ) -}}
{{- toYaml (merge $overrides $tpl) -}}
{{- end -}}
```

**Comment by SupornoChaudhury** [comment]
Can I also take a look at it? I went through the older comments and all. I can collaborate with you rdxmb.

**Comment by almson** [comment]
I'm not sure if this should go under this issue, although it's definitely in the same genre.

YAML types (eg `property: !MyClass {}`) get stripped out, and actually replaced by empty objects. Very broken.

**Comment by djmnnit10** [comment]
I used single quotes around the double quotes to get double quotes in toYaml outpu.
SERVER_USE-FORWARD-HEADERS: '"true"'

**Comment by artemmikhalitsin** [comment]
Looks like the issue reported by OP happens because the number is too big to fit into uint64, so is treated as a string and hence rendered without quotes. I submitted a possible fix in go-yaml/yaml, but I'm not sure whether this will fix all the related.

**Comment by theAkito** [comment]
> In other words perhaps some documentation around how to use `toYaml` in a chart would be more sufficient.

I've actually searched for hours to find clear and unambiguous documentation about `toYaml` and I simply could not find it anywhere. Many people talk about using it in general and using it a certain way, but I could not find a single, actual and official definition of that feature. It seems like this is some kind of hack or hidden feature, nobody should be using.

A feature without documentation is almost like a feature that does not exist, because if nobody can be sure to use it precisely according to spec -- as there is no spec -- then the feature becomes useless, and unusable in scenarios, where you want to be absolutely sure, it does exactly what is expected.

This issue here, which has been open for such an enormously long time, pretty much wouldn't exist, if documentation would be proper.

I constantly break my teeth out when trying to find documentation on any of the Kubernetes tools, which are popular. Kubernetes has documentation, but considering how complicated that software is, it would need 100 times more documentation, than it has now. Traefik has terrible documentation. You can't know anything when reading their documentation.
With Helm it's actually the funniest. When browsing the documentation, it seems like there is a lot of information there, but if you really want to look something up and get to know a Helm feature, you can't get to know anything, as only a few features are touched and even then, it's not really explained, but only mentioned in a sentence, as if it were the most obvious thing in the world.

Basically, software without documentation becomes useless for most users. Too few people have the time or ability to browse through thousand lines of Go source code, just to get the general gist of what is supposed to happen, regarding a certain functionality.

That said, I understand if it's not possible for the core maintainers to address every single issue in a timely manner. On the other hand, I think it's unfair to demand, that users, especially the ones who don't even know anything about how this works, are supposed to do work for this, like in this case, document this feature.

I would even document it, if I would get the point of it. However, I cannot get the point of it, as there is no information on it, beside the source code itself, offering that "feature".

A tiny step making this whole thing slightly less worse, is at least the following comment.

https://github.com/helm/helm/issues/4262#issuecomment-674193064

At least, this gives a little insight into what is happening. Still, one would need to read the whole YAML implementation of this specific library for the Go language, to be really sure, what the spec of this feature is or at least, to know what *should* and *should not* happen.



> In other words, changing the behavior of `toYaml` may NOT be desirable, and it may be more preferable to document its behavior so that we don't accidentally break charts that have worked around this behavior.

I also do not agree with this. First of all, where is the spec? If there is no spec, there is no definitive behaviour. I.e. it's already broken. Nobody can be sure, it does exactly what it is expected to do, as proven by this issue. As I said, this issue wouldn't exist, if proper documentation would be available.

To my knowledge, the current state of `toYaml` is, that it's behaviour is `undefined`. So, there is no breaking it, as it is already broken.

**Comment by bacongobbler** [comment]
> First of all, where is the spec?

https://yaml.org/spec/ is the canonical specification for YAML. If the yaml parser library does not conform to that specification, it is a bug. `toYaml` should be pretty self-explanatory.

As mentioned before, the entirety of `toYaml`'s code can be found [here](https://github.com/helm/helm/issues/4262#issuecomment-674193064). Helm passes the value to the YAML parser, and returns the output. It's very self-explanatory... Take a value and convert it to YAML. Any issues related to how those values are parsed and passed back to the template engine would be a bug in the YAML parser itself, which is why I suggested people try reproducing the bug in isolation using the YAML parser library.

Sounds like this is an upstream issue based on https://github.com/helm/helm/issues/4262#issuecomment-1025042645. Thank you @artemmikhalitsin for contributing a fix upstream. If/when that fix is merged, we can update our dependencies to receive a fix.

Doesn't sound like there's any further action to take here on our end. Please follow up with the go-yaml/yaml folks. Thanks.

**Comment by aarontavio** [comment]
> I used single quotes around the double quotes to get double quotes in toYaml output. SERVER_USE-FORWARD-HEADERS: '"true"'

This comment helped me achieve my goal. Thaaanks @djmnnit10!.
Maybe this helps somebody else with a similar problem like me that ends up here.

**Comment by ba32107** [comment]
> I used single quotes around the double quotes to get double quotes in toYaml output. SERVER_USE-FORWARD-HEADERS: '"true"'

This doesn't work for me. The single quotes are just carried over to the final output :(

None of the proposed solutions work if you don't control the chart you are using. In my case it's:
https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/extra-manifests.yaml

This allows adding any extra K8s object to the chart, but without quotes it's proving to be very challenging :/

**Comment by mindw** [comment]
Not being able to keep the type of the original yaml is a very surprising behavior. One expects the string `"1"` to stay a string and not turn into a yaml integer `1`: 
The issue seems to be in "sigs.k8s.io/yaml" package in the `Unmarshal` function as the following program will demonstrate:
```
package main

import (
	"fmt"

	"sigs.k8s.io/yaml"
)

var data = `
a: Easy!
b:
  c: 2
  d: [3, 4]
  e: "5"
`

func main() {

	// Unmarshal the YAML back into a Person struct.
	m := map[string]interface{}{}

	err = yaml.Unmarshal([]byte(data), &m)
	if err != nil {
		fmt.Printf("err: %v\n", err)
		return
	}
	fmt.Println(m)
}
```
The reference go-yaml v2 & v3 program (with the `"e"` addition) keeps the quotes just fine.

**Comment by andykcfung** [comment]
After trying for an hour to stop toYaml from removing the quotes that I wanted to keep, I found a solution for my specific usage:

To begin, I have this entry in my values.yaml (block 1)
<pre>
global:
  properties:
     mad:
       person: 'My id: 1234'
</pre>
where "1234" should actually come from another entry in my values.yaml (note that I hard coded the id "1234" above but this will be addressed by the solution later). The following entry is also in my values.yaml:
<pre>
person:
  id: 1234
</pre>

Now I needed to create a file named "mad.yaml" with the following content using toYaml (note the single code around the value) (target i):
<pre>
mad:
  person: 'My id: 1234'
</pre>

The code that I will use to create the file "mad.yaml" is like this (code A):
<pre>
mad.yaml: |-
{{ tpl (toYaml .Values.global.properties) . | indent 4}}
</pre>

The solution: I modified my original entry (i.e., block 1) to this:
<pre>
global:
  properties:
     mad:
       person: '{{ printf "%s %d" "My id:" (.Values.person.id | int) }}'
</pre>
and my code (code A) was able to produce what I wanted (i.e., target i).

Hope this helps. It took me much longer to write this up than to find the solution I needed.

**Comment by joejulian** [comment]
If your string has to have the single quotes, you could also use the squote filter

With a value of:

```
mystring: My id: 1234
```

this template:
```
{{ .Values.mystring | squote }}
```

produces:
```
'My id: 1234'
```

**Comment by RiccardoManzan** [comment]
I needed to put a yaml defined in a values file as a string with yaml format, and in order to do that i used `toYaml`.
Unfortunately in that yaml portion i had a string which contained some special characters like `: ` and `}`
I solved by using the backslash `\` before special characters.

In this way i was able to keep my escapes.

**Comment by almson** [comment]
> Not being able to keep the type of the original yaml is a very surprising behavior. One expects the string `"1"` to stay a string and not turn into a yaml integer `1`: The issue seems to be in "sigs.k8s.io/yaml" package in the `Unmarshal` function as the following program demonstrates:
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 
> 	"sigs.k8s.io/yaml"
> )
> 
> var data = `
> a: Easy!
> b:
>   c: 2
>   d: [3, 4]
>   e: "5"
> `
> 
> func main() {
> 
> 	// Unmarshal the YAML back into a Person struct.
> 	m := map[string]interface{}{}
> 
> 	err = yaml.Unmarshal([]byte(data), &m)
> 	if err != nil {
> 		fmt.Printf("err: %v\n", err)
> 		return
> 	}
> 	fmt.Println(m)
> }
> 
> /*
> age: 30
> name: John
> 
> map[a:Easy! b:map[c:2 d:[3 4] e:5]]
> */
> ```
> 
> The reference go-yaml v2 & v3 program (with the `"e"` addition) keeps the quotes just fine.

That's pretty garbage. Could also explain why people keep needing quotes even though the yaml spec doesn't require them. Eg. why does CronJob schedule need to be quoted? If Kubernetes won't fix its problems, then Helm should not insist "we're confirming to YAML, don't look at us!" Otherwise that's garbage behavior from both Helm and Kubernetes. What a crappy ecosystem.

The fix is pretty "simple." Stop using these parsers, and write (fork) your own that tracks the quote status of strings on Unmarshal and reproduces them on Marshal. Or is that too difficult for you?

**Comment by baracudda** [comment]
Having just run into this bug nearly 7 years after it was reported, disappointed is an understatement.  However, I found a simple workaround for those who find this thread after me.  Using the original definition as an example, just place the variable on the next line after a pipe, then toYaml() keeps the quotes.
```
info:
  address: |
    "0x1ddf249430c343f72f8b12848aa3f932538e3336"
```
which results in 
```
...
data:
  file.yml: |-
    info:
      address: |
        "0x1ddf249430c343f72f8b12848aa3f932538e3336"
```
do _NOT_ use `|-` or else you will end up with a single _and_ double quoted string as a result instead:
```
data:
  file.yml: |-
    info:
      address: '"0x1ddf249430c343f72f8b12848aa3f932538e3336"'
```

**Comment by grassehh** [comment]
> Having just run into this bug nearly 7 years after it was reported, disappointed is an understatement. However, I found a simple workaround for those who find this thread after me. Using the original definition as an example, just place the variable on the next line after a pipe-dash and without quotes, then toYaml() keeps the var as a string.
> 
> ```
> info:
>   address: |-
>     0x1ddf249430c343f72f8b12848aa3f932538e3336
> ```
> 
> which results in
> 
> ```
> ...
> data:
>   file.yml: |-
>     info:
>       address: |-
>         0x1ddf249430c343f72f8b12848aa3f932538e3336
> ```
> 
> If you use a pipe-dash and double quote the string, the quotes will be a part of the resulting variable value.

When I use double quote, the resulting variable has additionnal surrounding simple quotes. Exemple
```yaml
property: |-
    "value"
```
produces
```yaml
property: '"value"'
```

And if I try with simple quote, it ends with 3 quotes:
```yaml
property: |-
    'value'
```
produces
```yaml
property: '''value'''
```

**Comment by grassehh** [comment]
Hello, why is this issue closed ? The problem still remains

**Comment by dlerps** [comment]
This is a bug which is unresolved and should not be closed!

**Comment by almson** [comment]
helm and the Go/Kubernetes ecosystem sucks. for f's sake just ask Claude to write a better yaml library, if you can't be bothered to do it yourselves. it can use Java Jackson as a reference, since in Java people do things correctly.

**Comment by cwegener** [comment]
> helm and the Go/Kubernetes ecosystem sucks. for f's sake just ask Claude to write a better yaml library, if you can't be bothered to do it yourselves. it can use Java Jackson as a reference, since in Java people do things correctly.

seriously? https://matrix.yaml.info/valid.html

**Comment by almson** [comment]
> > helm and the Go/Kubernetes ecosystem sucks. for f's sake just ask Claude to write a better yaml library, if you can't be bothered to do it yourselves. it can use Java Jackson as a reference, since in Java people do things correctly.
> 
> seriously? https://matrix.yaml.info/valid.html

If it's so great, why can't it be used to preserve type information?

P.S. go-yaml has 49 errors in that table, but that's not the issue at the root of this bug
