### ISSUE TITLE
helm install is not a transaction action

### ISSUE THREAD

**Issue by chenzhiwei** [helm/helm#4328]
Output of `helm version`: v2.7.2

Output of `kubectl version`: v1.10.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Custom environment

helm install may success partially due to etcd connection timeout or something else.

when I want to retry the helm install I need to delete the release and then install.

So I want to ask is there a command line argument that allows helm remove the partially created resources?

Such as `helm install --clean-fail`, the `--clean-fail` means if a release is not created successfully then clean up the partial resources.

**Comment by michelleN** [comment]
@chenzhiwei - Did you get to a point where you had a ` release` object in `helm list --all`? 
If you did, you can run a `helm delete` and then re-install via `helm install`.

Helm stores information about the resources created during install in a`configmap` in the `kube-system` namespace. If there was partial success, we have no way of guaranteeing that a `configmap` was created and if it wasn't, there is no way to know which objects to clean up.

**Comment by michelleN** [comment]
@sczachariah if you or @chenzhiwei can provide more information on the problem, I'd be happy to assist.

**Comment by chenzhiwei** [comment]
@michelleN The requirement is when I run `helm install --clean-fail` failed, all things created by helm can be removed. But currently the resources are partially created which makes next `helm install` fail.

**Comment by bacongobbler** [comment]
Perhaps https://github.com/helm/helm/pull/4871 may be relevant here. Have you taken a look at that PR yet?

**Comment by sczachariah** [comment]
@michelleN The issue I am facing is :

Let's say I already have a namespace(or any resource for that matter) called "sample" in k8s, which was created using "kubectl create ns".

Now I have a helm chart which has got yaml file for creating a namespace, the idea is that any new installation of my chart should create separate ns for my application to run. I am using variable "namespace" in values.yaml.

apiVersion: v1
kind: Namespace
metadata:
name: {{ .Values.namespace }}

If I execute command :
helm install --name blue my-chart/ --set namespace=sample, 
It fails as expected since namespace already exists.
Error: release blue failed: namespaces "sample" already exists

helm ls blue

NAME REVISION UPDATED STATUS CHART NAMESPACE
blue 1 Fri Jul 20 08:22:45 2018 FAILED my-chart-0.1.0 default

Next if I execute:
helm delete --purge blue
release "blue" deleted

What I should expect from above helm delete command is that helm should not ideally delete any resources because helm did not create any.

Now the issue, the above helm delete command deleted ns "sample" from k8s. helm deleted ns "sample" even though it was not created by helm.

**Comment by bacongobbler** [comment]
Closing as implemented via `--atomic`. Thanks

**Comment by satyamsah** [comment]
hi, so what is the resolution here as a consumer. Do we need to add any flag while creating a helm chart to avoid this behavior?
