### ISSUE TITLE
Feature Request: Notify when a new version of Helm comes out

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#4329]
There are many versions of Helm being used and regularly downloaded (possibly via CI). We should notify users that a newer version is available.

Proposed method...
1. Regularly (not on every run but on first run) check if there is an update (a flag can disable this)
1. Check a URL on helm.sh with a JSON file of version details (including hashes)
1. Compare semver internal version to list. If a newer version exists print a message

Some open questions:
- Not all CI environments can make calls out to the Internet. Is a flag to disable the check enough or should we detect when inside CI and act differently?
- Helm versions tend to be most compatible with different versions of Kubernetes. Should any information on compatibility be part of the notification? Or, should we only notify on best compatible versions?

If we do this it should be added to both Helm v2 and v3.

**Comment by bacongobbler** [comment]
I think this is great. Minikube has had this for a while and it’s a nice feature to nudge people when a new release is out.
 
I wonder if third party projects around Helm are parsing Helm’s output. That might complicate things unless we display it on stderr possibly? Don’t know what the right course of action may be for that scenario, but in the general case this sounds like a good idea. 👍

**Comment by itowlson** [comment]
"I wonder if third party projects around Helm are parsing Helm’s output."  I don't know if the VS Code extension for Kubernetes counts as third party, but it parses Helm's output for sure!  Of course we can modify the extension to add the proposed 'skip check' flag but that causes an error on older versions of Helm so it all gets a bit messy.

It would also be useful to be able to invoke the update check directly in order to display a message in the VS Code environment.  I guess that could be done via a dummy call to `helm version` and parsing the output for an update message...

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by bacongobbler** [comment]
Also: 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/1360539/81990042-3959cf00-95f3-11ea-99e1-49c0652ed097.png">
