### ISSUE TITLE
Feature request: allow `helm template` to fetch

### ISSUE THREAD

**Issue by krancour** [helm/helm#4401]
`helm template` doesn't appear to support a `--version` flag for specifying a discreet release of a chart in the manner that `helm install` does.

Would this be a reasonable thing to add?

**Comment by bacongobbler** [comment]
If I recall, the `--version` flag in `helm install` specifies the version of the chart to fetch from the chart repository. Because `helm template` only interacts with on-disk charts, there is no need for the `--version` field. That is, unless someone contributes support for fetching charts on-the-fly to `helm template`... wink wink ;)

I hope that makes sense! Let me know if there's something else that the `--version` flag would address that I'm missing. Thanks!

**Comment by technosophos** [comment]
Use `helm fetch` then `helm template`

**Comment by bacongobbler** [comment]
fixed in Helm 3. `helm install` and `helm template` now share the same codebase and are identical in behaviour, so `helm template` will now fetch remote charts before templating. For example:

```
><> ./bin/helm template wordpress stable/wordpress | head -n 10
---
# Source: wordpress/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mariadb
  labels:
    app: "mariadb"
    chart: mariadb-5.2.5
    release: "wordpress"
```
