### ISSUE TITLE
Is there any way to tell helm to run in background ?

### ISSUE THREAD

**Issue by shettyh** [helm/helm#4488]
Hi all,

I created a helm chart with multiple dependencies. One of the dependencies have `post-install` hook, what is happening is images takes long to pull and post install hook fails before that.

Though the chart that has `post-install` hook images are small, image pull is not happening in dependency order.

This is why when i install i always get `release failed waiting for a condition` and the release will be marked as failure. Is there any way to tell the helm that run the post-install hook asynchronously instead of waiting for images to be pulled (Some images are in GB's, so it is taking long)  ?. 

I tried using `--wait` with helm install but it also fails after `activeDeadlineSeconds` that is mentioned in hook.

Output of `helm version`:
NA

Output of `kubectl version`:
NA

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
NA

**Comment by jascott1** [comment]
Hi @shettyh 

As far as I know, there is no built in way to "run in background" but you could try having your hook job execute kubectl to create a pod or job that needs that image. The hook will complete quickly since its just sending the object to k8s and helm is not aware of it. Obviously this is not ideal and perhaps someone else has a better idea.
