### ISSUE TITLE
Make Helm a Native LMMS Instrument

### ISSUE THREAD

**Issue by Reaper10** [helm/helm#455]
I think would be grate for helm  team to work with the LMMS team to make Helm a Native LMMS Instrument like this->  
![mdk008](https://cloud.githubusercontent.com/assets/8137561/14938254/5c9cab4a-0ee3-11e6-83c0-8aca6367824a.png)
![hqdefault](https://cloud.githubusercontent.com/assets/8137561/14938266/84396ecc-0ee3-11e6-8642-45f3e905af5e.jpg)
Make Helm a Native  LMMS Instrument

https://github.com/LMMS

**Comment by bacongobbler** [comment]
Helm is a package manager for kubernetes. How would that work? Press a key; deploy a package? ;)

**Comment by Reaper10** [comment]
contact LMMS devs for needed info

**Comment by bacongobbler** [comment]
I'm going to close this as the two projects are completely unrelated to each other. If one of the @LMMS devs wants to reach out and provide more info on how helm can produce music, then I'll be happy to entertain the idea.

**Comment by Umcaruje** [comment]
@bacongobbler Hi, I'm a member of the LMMS dev team. We're sorry about this, as the OP was banned from our tracker for some time, because he was abusing it. He probably misinterpreted your repo as the repo of mtytel's Helm, a popular softsynth. And even as this proposal was submitted to the correct repo, it'd be rejected, as we want to incorporate LV2 support, and not port each synth.

As you said, the two projects are completely unrelated to each other, and I'm not sure how any combination would work.

**Comment by mboersma** [comment]
@Umcaruje no worries! This was confusing, but mostly amusing. :violin:
