### ISSUE TITLE
Dependency update deletes subcharts not present in requirements.yaml

### ISSUE THREAD

**Issue by FX-HAO** [helm/helm#4667]
**Proposal:** Maybe we could provide a flag to `helm dependency update`, which deletes the subcharts not present in `requirements.yaml`.

Alternatively, we can add a flag to `install` and `upgrade`, which ignores the subcharts not present in `requirements.yaml`.

**Comment by tmahncke-lhind** [comment]
Is there a workaround for this "problem"? In our project we have a dependency that is no longer needed and might even be not present in the future. Due to the requirements.lock file in the helm chart repository the denpendency is treated as required.

Deleting the requirements.lock file manually after the helm package does not seem like a good solution and would need manual intervention as we are using a CI/CD pipeline.

**Comment by bacongobbler** [comment]
closing as inactive.
