### ISSUE TITLE
crd-install hook is not working on upgrade #4259

### ISSUE THREAD

**Issue by maver1ck** [helm/helm#4697]
This is follow up for:  #4259 

Upgrade of cert-manager chart from version 0.4.1 to 0.5.0 added crd-install hook to CRD resources
https://github.com/helm/charts/commit/e0505bbd09c4f8bf81fe583841c926e02cc82a8e

Unfortunately running helm upgrade on this chart actually removes all crd and not upgrading them.

Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kops

**Comment by mmerrill3** [comment]
I too had this issue, referenced here https://github.com/helm/helm/issues/4704.  I didn't see this until now.

**Comment by desaintmartin** [comment]
Same with Helm v2.11.0

Deleting and reinstall the chart works (beware of existing CRDs, you may have to use `--replace`).

**Comment by mortent** [comment]
So I think there are multiple issues here.

First, the crd-install hook only runs on install and it does a create op without checking if the crd already exists. This is the same behavior as for other hooks. But this will cause the create operation to fail if the crd already exist. It might be possible to work around this by using the before-hook-creation deletion policy, but that doesn't sound like a good approach since it would delete all resources based on the crd.

This also means that crds are not created (or updated) as part of updating a release, so changing an existing chart to use the crd-install hook will probably not work as expected.

Both of these issues seems to be pretty well covered in the PR that introduced the crd-install hook #3982

Also, transitioning a chart that is already installing crds in the normal way (without hooks) to use the crd-install hook has some pitfalls. If crds are created in the normal way, they will be managed by helm as part of the release, but with the crd-install hook that is no longer the case. So as part of an upgrade where the chart switches to create crds with the crd-install hook, the existing crds in the release will be deleted by helm. And since it is an upgrade, helm will not execute the crd-install hook (an even if it did, this would happen before the delete step).

For any use case where helm does not create custom resources as part of the chart, the best option is probably to install crds with regular templates instead of using the crd-install hook. The hook would only be required where the chart need tthe crd to be installed before validation and creation of other resources.

**Comment by sdake** [comment]
Istio also impacted by this issue - and it is critical/blocking Istio 1.1 and 1.0.4.  See https://github.com/istio/istio/issues/9604#issuecomment-437291974.

**Comment by Stono** [comment]
Hey,
I think it's important that whatever solution is found for this problem that the upmost is done to ensure an upgrade path for people who have either applied crd's manually, or used the install hook.

They can't go deleting these CRDs to get helm to track them because then they'll loose the implementations too.

The only approach I could see would be to have helm do a "create if missing, track if exists" style operation, that way it wouldn't require the pre-delete of the manifest.

**Comment by shikhasriva** [comment]
Is the fix for this issue underway? Any targets. ..thanks

**Comment by kfox1111** [comment]
@jascott1

**Comment by abhishekjiitr** [comment]
Any updates on this?

**Comment by woodcockjosh** [comment]
yo! still broken? so broken :-(

**Comment by monotek** [comment]
Try helm 2.14.3. They had some crd fixes...

**Comment by woodcockjosh** [comment]
Yeah just saw it. All the chart owners still have to re-add the CRD's to main helm charts. Epic fail. https://github.com/helm/helm/releases/tag/v2.14.3

**Comment by benbuzbee** [comment]
It seems @mortent has a very good grasp on the issues here, but the upshot seems to be it is impossible to add a CRD to a chart along with a CR that consumes it without breaking the upgrade path.

What is the recommendation? How can users upgrade a chart that has added a CRD/CR? Do they have no choice but to delete and re-install? That path breaks sane rolling-updates.

**Comment by woodcockjosh** [comment]
Upgrades should obviously ignore CRD's

**Comment by woodcockjosh** [comment]
@benbuzbee what I mean is that CRDs that already exist should just be ignored on updates. Helm should be able to determine whether or not a CRD exists. Any new CRDs should obviously be added.

**Comment by benbuzbee** [comment]
I interpreted what @mortent said as "crd-install is required for charts that also install the custom-resource that requires the crd"

And also "crd-install is ignored on upgrades"
Seems to be true, crd-install is run here, before pre-install hooks
https://github.com/helm/helm/blob/2b7221b5b721035b91691a90be3910a11e6df022/pkg/tiller/release_install.go#L168

But not here, during upgrade
https://github.com/helm/helm/blob/9b1d8f9c86c1307d3d1d084e02d3bc5c692a06dc/pkg/tiller/release_update.go#L276

The combination of those two facts leaves me puzzled as to how to upgrade a chart that has added a CRD + a custom resource that requires the CRD.

**Comment by mortent** [comment]
It's been a while since I was looking at this, but I think the best suggestion is to avoid mixing CRDs and CRs in the same chart. This allows CRDs to be installed without using the crd-install hook which should make it easier to update the CRD. Note that updating CRDs must be done very carefully as there are many ways to break existing CRs/controllers when updating a CRD. This is not specific to Helm. Also, a CRD is a global resource in the K8s cluster, so any changes will affect everyone in the cluster and should probably be a cluster-admin type of change.

What is the use case for including both CRs and CRDs in the same chart? Operators are a commonly used patterns for CRDs and for these I think it makes the most sense to split the CRD and the CR.

**Comment by moduspwnens** [comment]
We're currently building an application that makes use of [Metacontroller](https://metacontroller.app). To configure it with a new "controller" to send events to, you create an instance of a resource defined by their CRDs (e.g. DecoratorController, CompositeController), and our application has many instances of those resources. We're wanting to distribute our app as a single chart to end users without them having to know or care what Metacontroller is.

I don't know how common such a use case is, but we're conceptually just wanting to use another chart-based application (which defines CRDs) as a component of our own chart-based application. I expect that use case to become more common over time.

We are working around this currently by just not creating any resources of CRDs in our chart directly via Helm, but using a Helm-created Kubernetes Job that essentially just uses `kubectl` to create/update them, or delete ones that the job would have created in previous versions, but don't exist any more. The upside is that we still get creates / updates / deletes as part of the Helm chart, but we're effectively managing our own process for it that Helm is triggering.

**Comment by benbuzbee** [comment]
Our use case is similar - we are using helm mostly as an internal product release manager, and we need to create a custom operator that we then use. Adding multiple charts just for this case would be a bit round-about.  

Doing some looking, it seems even the canonical operator example, [prometheus](https://github.com/helm/charts/tree/master/stable/prometheus-operator), does this.  The chart can be configured with
```
prometheusOperator.enabled: true
prometheusOperator.createCustomResource: true
prometheus.enabled: true
```

Which will try to create a crd
https://github.com/helm/charts/blob/7adf7372236b1327daf9483ba76397f2e0b23018/stable/prometheus-operator/templates/prometheus-operator/crd-prometheusrules.yaml#L4

and also consume it
https://github.com/helm/charts/blob/7adf7372236b1327daf9483ba76397f2e0b23018/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L3

They are using the crd-install hook so it probably works, but if they had added this in an upgrade it would have failed.

It seem strange to me to have a case that users could achieve manually relatively easily, but that requires such workarounds in helm.

**Comment by bacongobbler** [comment]
related: #5871

**Comment by bacongobbler** [comment]
closing as inactive.
