### ISSUE TITLE
How to configure third-party Helm charts from an application Helm chart

### ISSUE THREAD

**Issue by ryall** [helm/helm#4711]
I can't seem to find any clear information on this anywhere, but is it possible in a Helm chart to require a third party, such as `stable/jenkins`, and specify configuration values? 

All the examples I see are for running the `helm install` command directly but I would like to be able to configure it as part of my application.

**Comment by ryall** [comment]
In answer, @desaintmartin referred me to these documents in Slack:

- https://github.com/helm/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md
- https://github.com/helm/helm/blob/master/docs/chart_best_practices/requirements.md
- https://github.com/helm/helm/blob/master/docs/helm/helm_dependency.md

This led me to find the [specific part I was looking for](https://github.com/helm/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md#overriding-values-from-a-parent-chart), where the parent chart can override child charts by specifying the chart name as a key in the parent `values.yaml`.

**Comment by wolasss** [comment]
All of the links are not worknig anymore and I am strugging with the same issue. The documantation is not clear about this.

**Comment by hickeyma** [comment]
@wolasss The links no longer work because the docs have been moved in the repo. It is the web rendered version of the doc source which should be used instead. I have updated the links in this comment with Helm v3 version of the docs. You can get the Helm v2 docs in https://v2.helm.sh/docs/. Just search for the relevant sections.

- https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
- https://helm.sh/docs/topics/chart_best_practices/dependencies/
- https://helm.sh/docs/helm/helm_dependency/

This led me to find the [specific part I was looking for](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart), where the parent chart can override child charts by specifying the chart name as a key in the parent `values.yaml`.
