### ISSUE TITLE
Helm 2.11.0 status output differs for deployments

### ISSUE THREAD

**Issue by ganeshvasudevan** [helm/helm#4712]
In helm version 2.11.0 the helm status output differs for the deployment.

In previous version (2.10.0) it showed
```
==> v1beta2/Deployment
NAME            DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
metrics-server  1        1        1           1          1d
```

In version 2.11.0 is shows
```
==> v1beta2/Deployment
NAME                           AGE
unhinged-hydra-metrics-server  20s
```

```
kubectl get deployments
NAME                            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
unhinged-hydra-metrics-server   1         1         1            1           3m
```

So there is some information that list lost in the status output in version 2.11.0.
Is this expected behaviour?

Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"e8c8ac53ee97f1968922718551a275c0abd15c3c", GitTreeState:"clean"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-09-07T15:46:48Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-09-07T15:45:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  N/A

**Comment by bacongobbler** [comment]
@adamreese do you think this might be due to the switch from `cmdutil.PrinterForOptions` to [NewHumanPrintFlags](https://github.com/helm/helm/blob/597c4fb421306f9673f43a27b0927af3884da84b/pkg/kube/client.go#L202-L207)?

IIRC this was because Kubernetes broke client-go package compatibility by removing `cmdutil.PrinterForOptions` (from `k8s.io/client-go/tools/clientcmd`) in favour of `NewHumanPrintFlags()` (from an entirely new package under `k8s.io/kubernetes/pkg/kubectl/cmd/get`), but the API changed entirely.

We'll have to take a look at how `kubectl` now prints objects and see what we can do to add those fields back.

Also cc @mattfarina since I know he was interested in hearing cases where client-go broke backwards compatibility.
