### ISSUE TITLE
Chocolatey helm package is out of date

### ISSUE THREAD

**Issue by Vhab** [helm/helm#4721]
Hi,

The documentation suggests using Chocolatey as the go to method of installing Helm on Windows.
However, the chocolatey package doesn't seem to have been updated to the latest release.
It's still on 2.10.0 at the time of creating this ticket.

**Comment by bacongobbler** [comment]
cc @synax

**Comment by synax** [comment]
Hi all, I just had a quick look at the pipeline which should be triggered via the feed of the release page. It seems the trigger actually worked, but there is something wrong with the pipeline itself (something related to the auto update script from chocolatey). I need to look in to this. Will try ti fix it asap.

**Comment by synax** [comment]
Hey, the latest version is now available. Cheers

**Comment by andresiraola** [comment]
2.14.1 hasn't been yet push to chocolatey

**Comment by bacongobbler** [comment]
@synax is there a way for the community to help contribute PRs when a new release of Helm is out, similar to how the community manages the homebrew package?

**Comment by synax** [comment]
Hey, Sorry for this happening again. The current setup is fully automated. This is how the setup is today: Github Releases RSS Feed > Zapier > AppVeyor > Chocolatey. I trigger a Zap using the Releases RSS feed on Github, which in turn triggers appveyor. When v2.14.1 got released, the pipeline failed because my script got confused with the helm v3.0.0-alpha-1 release :)  https://ci.appveyor.com/project/synax/chocolatey-packages/builds/25073530. PRs are very welcome and can be created for this repo, https://github.com/synax-io/chocolatey-packages. The best way to improve these build failures would be to make the package update script more resilient, the script is located here: https://github.com/synax-io/chocolatey-packages/blob/master/automatic/kubernetes-helm/update.ps1. I use the chocolatey auto-updater module which is PowerShell based.

For the current issue, I've triggered the pipeline again and it worked now. The package should now be available in the feed and fully approved until tomorrow.

**Comment by alexjamesbrown** [comment]
@synax did 2.14.1 make it to Chocolatey?
When I try to install this specific version with 

`choco install kubernetes-helm --version=2.14.1`

I get

Failures
 - kubernetes-helm - kubernetes-helm not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '2.14.1'. It is possible that version
 does not exist for 'kubernetes-helm' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

**Comment by synax** [comment]
Hi, yes its there. I've quickly tested it on my Win 10 VM and it worked.

https://chocolatey.org/packages/kubernetes-helm/2.14.1

choco install kubernetes-helm --version=2.14.1

are you sure your choco install is fine?

**Comment by alexjamesbrown** [comment]
yes, well, in so far as `choco install kubernetes-helm` installed the latest version
trying to specify the version resulted in the above.

`choco sources` results in

Chocolatey v0.10.15
chocolatey - https://chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.

**Comment by synax** [comment]
can you try this and see if there is anything of intrest in the debug log? 

'choco install kubernetes-helm --version=2.14.1 -d'

**Comment by alexjamesbrown** [comment]
very strange;
ran it with -d and it simply worked....

not sure why that'd have any effect

**Comment by templafymek** [comment]
Version 3.2.1 is not published.

**Comment by wiruzman** [comment]
Version 3.2.1 is not published.

**Comment by stefanhenseler** [comment]
@wiruzman Thanks for letting me know. For some reason, the zap has not been triggered this time. I've triggered the pipeline manually. The package is now available. takes about 30 to 60 mins until the auto-approval is done. https://chocolatey.org/packages/kubernetes-helm/3.2.1
