### ISSUE TITLE
Get https://kubernetes-charts.storage.googleapis.com/index.yaml: proxyconnect tcp: EOF

### ISSUE THREAD

**Issue by jisheng** [helm/helm#4732]
I'm running helm v2.11.0, and I still see a similar error to #4251 if I init with refresh or update repo.

I've tried older versions such as v2.9.1 and v2.10.0. Same behavior.

wget works fine.

+++++++++++++++++++
helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
Get https://kubernetes-charts.storage.googleapis.com/index.yaml: proxyconnect tcp: EOF
Update Complete. \u2388 Happy Helming!\u2388

+++++++++++++++++++
Output of `helm version`:

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

private

**Comment by lzcmoody** [comment]
aha, I have meet this issue : Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: proxyconnect tcp: EOF

and fixed follow https://github.com/helm/helm/issues/4271

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by neil-n-brown** [comment]
I using the latest Helm Windows 10 installed by Choclately and I am encountering the same problem for all repos that I try to add

helm repo add stable http://mirror.azure.cn/kubernetes/charts/

"Error: looks like "http://mirror.azure.cn/kubernetes/charts/" is not a valid chart repository or cannot be reached: Get http://mirror.azure.cn/kubernetes/charts/index.yaml: dial tcp XXX.XXX.XXX.XX:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

Same error for: helm repo add stable https://kubernetes-charts.storage.googleapis.com

I have set proxy but same result.

Does anyone have any thoughts on this from a Windows perspective?
