### ISSUE TITLE
Docs do not explain LICENSE file

### ISSUE THREAD

**Issue by timthelion** [helm/helm#4754]
The section of the docs that describes the LICENSE file does not actually explain it's purpose https://github.com/helm/helm/blob/71ba25a5a94fc9adaedc8adb1a454e15ba6aae23/docs/charts.md#chart-license-readme-and-notes
.

The existence of a LICENSE file is ambiguous. Does it refer to the chart or the application installed by the chart? If the later case is true, should it contain all licenses relating to the application installed by the chart? What characters should be used to delimit the licenses.

Note: This is not a question, it is a bug.

**Comment by bacongobbler** [comment]
labelling as a docs issue.

**Comment by hickeyma** [comment]
Is it OK if I take this?

**Comment by hickeyma** [comment]
IMO the license is related to the chart and not the application because charts can (and do) point to images/apps that are outside of its control.

Taking a step back from this, I wonder does it make sense to have a license file then? Charts are more like "config" than "code". What then are chart owners trying to protect? 

I appreciate suggestions.

**Comment by mattfarina** [comment]
The license is for the chart rather than the application itself.

The chart and application it installs can have two (at least) different licenses. And, it can be more complicated than that. For example, take mongodb. You can have a chart with one license and the application could have different ones (plural intended) depending if you are using the community or commercial version.

Then of course there is the case of an application using multiple images of different software with different licenses. Mongodb is a fairly simple case given the complexity we can get into.

It turns out listing the application license when the image can change and the varying software licenses is a hard problem.

Since a chart has programming logic in the templates it is different from something that is pure configuration (config legally is treated differently from code) it needs to be licensed. The license is for the chart.

If someone wants to clarify that in the docs that could be good.

Note, I am not a lawyer and this is not legal advice.

**Comment by hickeyma** [comment]
@mattfarina Thanks for elaborating further. This makes sense.

PR #4977 opened and ready for review.
