### ISSUE TITLE
global values not passed from parent to subchart (unless forced with --values)

### ISSUE THREAD

**Issue by czka** [helm/helm#4767]
Helm 2.11.0.

Looks like subcharts don't inherit their parent's `global` values set in `values.yml`, unless explicitly pointed at the file with a `--values` option.

A simplistic example setup (also attached to this ticket):

```
$ tree parent/
parent/
├── charts
│   └── child
│       ├── Chart.yaml
│       └── templates
│           └── configmap.yaml
├── Chart.yaml
└── values.yaml

3 directories, 4 files
```
```
$ cat parent/values.yaml 
global:
  test: "I'm your father."
```
```
$ cat parent/charts/child/templates/configmap.yaml 
apiVersion: v1
kind: ConfigMap
data:
  quote: {{ .Values.global.test }}
```

Installing the subchart fails as follows:

```
$ helm install --dry-run ./parent/charts/child/
Error: render error in "child/templates/configmap.yaml": template: child/templates/configmap.yaml:4:19: executing "child/templates/configmap.yaml" at <.Values.global.test>: can't evaluate field test in type interface {}
```

If I point it at its parent's `values.yml` it passes OK and produces a YAML with the global value set proper: 

```
$ helm install --dry-run --debug --values ./parent/values.yaml ./parent/charts/child/
[debug] Created tunnel using local port: '34971'

[debug] SERVER: "127.0.0.1:34971"

[debug] Original chart version: ""
[debug] Host="", Key="<redacted>", Cert="<redacted>", CA="<redacted>"

[debug] CHART PATH: /home/msieczka/helm/parent/charts/child

NAME:   handy-marsupial
REVISION: 1
RELEASED: Fri Oct 12 15:21:16 2018
CHART: child-0.1.0
USER-SUPPLIED VALUES:
global:
  test: I'm your father.

COMPUTED VALUES:
global:
  test: I'm your father.

HOOKS:
MANIFEST:

---
# Source: child/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
data:
  quote: I'm your father.
```

CCing @hickeyma who I discussed this with yesterday on #helm-users Slack.

**Comment by czka** [comment]
[parent.zip](https://github.com/helm/helm/files/2473285/parent.zip)

**Comment by hickeyma** [comment]
Investigating on Slack with @czka

**Comment by hickeyma** [comment]
Good discussion @czka.

There are two use cases here:
1) Install the umbrella chart (parent) which will install all its sub-charts (children)
2) Install individual or group of sub-charts

Use case 1 will work as it is the umbrella chart and has visibility of all the values. Use case 2 needs the parent values file passed explicitly as the global values are defined here. IMO, this works as expected.

@czka would like the ability to install the sub-charts with having to pass the values. The business model is as follows:

"we have this k8s app with aroung 60 "modules" being mainly pod deployments

some of those 60 modules are functionally related and need to deployed/redelpoyed as a "group" sometimes

and sometimes we deploy all the 60 guys altogether
(using a custom Bash/Python templating solution; trying to migrate to Helm)

~~~
ll
 group1
   module1
   module2
 group2
   module3
   module4
   module5
 group3
   module6
   module7
   module8
...
 groupX
   moduleY
   moduleZ
~~~
all groups would inherit some values from `all`
groups would set values common for their modules, but unique for the given group
"

Some suggestions  provided:
- Use dependencies instead of sub-charts with the dependecies in separate repositories
- Use helmfile (https://github.com/roboll/helmfile)
- Explicitly pass the values when install sub-charts

@bacongobbler any further suggestions here?

**Comment by czka** [comment]
> Use dependencies instead of sub-charts with the dependecies in separate repositories
Splitting our current Git repo into 60 ones, each for a single "module" is too much pain.

> Use helmfile (https://github.com/roboll/helmfile)
Might be an option, but we'd rather avoid introducing yet another tool.

> Explicitly pass the values when install sub-charts.
For now this is what I've been thinking too. But maybe there's a better way.

**Comment by darkstarmv** [comment]
we tried to use parent chart , but ran into multiple issues, so we developed a tool to manage helm chart releases to multiple clusters https://github.com/target/impeller.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
