### ISSUE TITLE
Proposal: Install release without tests `helm install --no-tests`

### ISSUE THREAD

**Issue by carlosjgp** [helm/helm#4790]
My business case is that we are developing lots of apps and but we are not packing tests within Helm, which will simplify our deployment pipeline, because some of those tests are quite aggressive with the databases, create users in other systems/apps or are performance tests which might impact the overall performance.

This is ok for test environments where the databases are ephemeral or there are actual clients using the systems, but we don't want to have the risk of accidentally running the tests in our production environment

**Comment by bacongobbler** [comment]
What would you propose what should change in helm to accomodate this?

**Comment by carlosjgp** [comment]
My proposal is to use a flag (eg. `--no-tests`) to stop installing and remove tests, if they are already installed

I'll try to raise a PR myself in the next few days, but my golang skills are quite limited... I'll do my best!

**Comment by bacongobbler** [comment]
closing as inactive.

**Comment by tspearconquest** [comment]
There appears to be no way to modify or remove pods created by a subchart if the pod template in the subchart has the `helm.sh/hook: test-success` annotation because hooks are not passed to post-renderers.

I have an admission controller in my cluster which blocks images from public repos; because we can't modify or remove the pods with this annotation that are created by the subchart, it's impossible to use a public helm chart which includes these type of test pods because gatekeeper blocks them due to the disallowed image repo.
