### ISSUE TITLE
helm history Error: grpc: trying to send message larger than max (21239406 vs. 20971520)

### ISSUE THREAD

**Issue by 27Bslash6** [helm/helm#4865]
Where number of revisions are above a certain threshold, we're seeing repeated errors with the `helm history` command:
```
$ helm history blahblahblah
Error: grpc: trying to send message larger than max (21239406 vs. 20971520)
```
Where a limited subset returns successfully
```
$ helm history blahblahblah --max=10
REVISION	UPDATED                 	STATUS    	CHART          	DESCRIPTION
177     	Wed Oct 24 20:08:30 2018	SUPERSEDED	wordpress-0.3.0	Upgrade complete
178     	Thu Oct 25 08:35:56 2018	SUPERSEDED	wordpress-0.3.0	Upgrade complete
179     	Fri Oct 26 08:36:48 2018	SUPERSEDED	wordpress-0.3.0	Upgrade complete
180     	Sat Oct 27 08:35:45 2018	SUPERSEDED	wordpress-0.3.0	Upgrade complete
181     	Sun Oct 28 08:33:33 2018	SUPERSEDED	wordpress-0.3.0	Upgrade complete
182     	Mon Oct 29 08:33:57 2018	SUPERSEDED	wordpress-0.3.0	Upgrade complete
183     	Mon Oct 29 19:32:37 2018	SUPERSEDED	wordpress-0.3.0	Upgrade complete
184     	Tue Oct 30 23:03:00 2018	SUPERSEDED	wordpress-0.3.0	Upgrade complete
185     	Wed Oct 31 08:37:16 2018	DEPLOYED  	wordpress-0.3.0	Upgrade complete
186     	Thu Nov  1 08:33:59 2018	FAILED    	wordpress-0.3.0	Upgrade "blahblahblah" failed: timed out waiting for the ...
```
Possibly related to #3322 - has the grpc buffer for helm history not received the same fixes as 'helm list' ?

Do the fixes in #4620 mean helm supports unlimited `list` results or is there still an upper bound?

---

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-22T05:40:33Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.6", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-16T21:33:47Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE 1.9.7-gke.6

**Comment by mortent** [comment]
So this just happens when the number of revisions for a release is high enough that the number of bytes in the response exceeds the threshold of 20MB. Not sure if this truly is a bug since returning a response of unbounded size is a bad idea.

One option would be to rewrite the history command to use a streaming grpc endpoint, similar to what is used for getting a list of releases. But that would involve changing the existing grpc endpoints (which I don't think is possible since it breaks backward compatibility), or add a new grpc service. Given that all the grpc endpoints are going away with Helm 3, I'm not sure if it worth changing.

@mattfarina Do you think a fix for this would be accepted?

**Comment by audip** [comment]
Having a similar issue when trying to list the history of istio releases: 
```
helm history istio                                         
Error: grpc: trying to send message larger than max (44504586 vs. 20971520)
```

**Comment by bacongobbler** [comment]
Personally I'd rather start thinking about contributing a fix to the history API in Helm 3 rather than maintaining two separate API endpoints for Helm 2. It's possible to get in a fix for Helm 2, but it'd end up as a new grpc endpoint as you suggest, @mortent.

We'd probably accept a fix should someone decide to work on this, but IMO this *really* should be done in Helm 3 and (optionally) back-ported.

**Comment by audip** [comment]
@bacongobbler Is there a certain label or milestone for helm version 3 that this issue can be added to?

**Comment by bacongobbler** [comment]
gRPC has been removed in Helm 3.

**Comment by Aisuko** [comment]
So, We should be waiting for Helm3 was released 😅

**Comment by lukesiler** [comment]
workaround for helm 2: use --max to limit results to most recent deployments

**Comment by whyh** [comment]
Some unfortunate folks will be stuck with helm2 for a while, and this bug renders the history command utterly useless

I have 800 releases, so max does not work for me. Will post an update here if I find a workaround
