### ISSUE TITLE
[Question] Schedule to publish release to support k8s 1.12?

### ISSUE THREAD

**Issue by hiscal2015** [helm/helm#4866]
Hi, 

Is there any schedule to release next version to support k8s 1.12? Thanks.

**Comment by mattfarina** [comment]
We do not have firm schedules for support for a new minor release of Kubernetes. It is typically about a month after a release but can be a little shorter or longer.

Kubernetes minor releases often make enough changes it takes many awhile to support them. For example, many public clouds (e.g., GKE and AKS) don't support 1.12 because it takes awhile.

In Helm's case, we use client-go and the changes in there need to be accounted for. The changes there can take a long time to account for.

We are working on it but do not have a time table yet.

**Comment by bacongobbler** [comment]
see https://github.com/helm/helm/milestone/56; kubernetes 1.12 support was merged into master a few weeks ago so it'll be available in Helm 2.12.0.
