### ISSUE TITLE
Error: release dapper-woodpecker failed: no objects visited

### ISSUE THREAD

**Issue by manojchandrabss** [helm/helm#4945]
Hi team,

I've used multi environment values in helm. when i try to do helm install with --debug i'm get below error

 **helm install . --set tags.qa-values=true --tiller-namespace eait-sovereign-poc --debug
[debug] Created tunnel using local port: '36084'

[debug] SERVER: "127.0.0.1:36084"

[debug] Original chart version: ""
[debug] CHART PATH: /home/manoj/sovereign-cloud-helm-prime/charts/sovereign-prime-qa

Error: release dapper-woodpecker failed: no objects visited**

and my directory structure is. Please help me to understand the issue

**.
├── charts
│   ├── sovereign-prime-int
│   │   ├── Chart.yaml
│   │   └── values.yaml
│   └── sovereign-prime-qa
│       ├── Chart.yaml
│       └── values.yaml
├── Chart.yaml
├── Chart.yaml_imp_bck
├── requirements.yaml
├── templates
│   ├── deployment.yaml
│   ├── _helpers.tpl
│   └── service.yaml
├── values.yaml
└── values.yaml_imp_bck**

Output of `helm version`:Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`: kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3+coreos.0", GitCommit:"f588569ed1bd4a6c986205dd0d7b04da4ab1a3b6", GitTreeState:"clean", BuildDate:"2018-02-10T01:42:55Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): kubernetes

**Comment by maorfr** [comment]
it seems like there are several issues here:
1. under the `charts` directory, each required chart should be in its own directory.
2. I see no `templates` in the required chart.

Does this help?

**Comment by manojchandrabss** [comment]
@maorfr thanks for very quick response, I've charts in each directory and template directory is also in place. could you please elaborate, I'm new to helm. If i use --dry-run, it is working. without dryrun it is failing with error no objects visited

**├── charts
│   ├── sovereign-prime-int
│   │   ├── Chart.yaml
│   │   └── values.yaml
│   └── sovereign-prime-qa
│   ├── Chart.yaml
│   └── values.yaml**

templates:
**├── templates
│   ├── deployment.yaml
│   ├── _helpers.tpl
│   └── service.yaml**

**Comment by maorfr** [comment]
notice that there aren't any `templates` directories under the charts/* directory, which means there aren't any resources to deploy...
I would expect something along the lines of:

├── charts
│ ├── sovereign-prime-int
│ │ ├── templates/ (and more files here)
│ │ ├── Chart.yaml
│ │ └── values.yaml
│ └── sovereign-prime-qa
│ │ ├── templates/ (and more files here)
│ |  ├── Chart.yaml
│  | └── values.yaml

* notice that there are 2 directories now, `sovereign-prime-int` and `sovereign-prime-qa`, and no files outside of them.

In addition, if both `sovereign-prime-*`  are the same chart as the name indicates, you should provide different values using the default values.yaml instead of treating them as two different charts.

**Comment by manojchandrabss** [comment]
perfect, now it is working.  i didnt create template in environment directories. Thank you very much for ur help.
