### ISSUE TITLE
Feature: [Plugins - support plugins in Lua using Helm built in Lua engine

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#5084]
This features is defined in [the v3 proposal](https://github.com/helm/community/blob/master/helm-v3/005-plugins.md#lua-plugins)

The gist is the plugins can be cross platform and written in lua.

**Comment by mattfarina** [comment]
Note, this is blocked until the Lua hooks for charts work is complete and the Lua library API is still being developed and is changing.

**Comment by bacongobbler** [comment]
Thought I should update the community on this work.

Many users have been asking for an accelerated timeline for Helm 3.0. However, we don't want to corner ourselves in a wall where we disregard the use cases the proposals intend to solve. So, we're compromising.

Right now, we're trying to take the approach of a 3.0 minimum viable product: instead of implementing all of the features the v3 proposals lay out, we're refactoring the codebase to allow these proposals to be implemented in a future release.

What does this mean for Lua?

The current plan is to ensure we lay the groundwork in the Go SDK, allowing the Lua hooks and Lua library APIs to be added post-3.0. As long as we can lay out the groundwork to add this functionality post-3.0 without any compatibility breakers, then that seems like something we can work with.

Note that in its current state, consumers of the Go SDK can instantiate a new rendering engine with `e := Engine{}` and call `e.Render(...)`. Either that, or just call the `engine` package's [`Render`](https://github.com/helm/helm/blob/2a3b7b5395bb7d71919ed3592c8c63c425353851/pkg/engine/engine.go#L64-L68) function which will create an default `Engine` and call its own `Render` function all in one go. That seems like a good minimal API to add upon in the future.

It's also worth pointing out that #5826 seems very relevant to this discussion. Any custom overlays with the rendering engine will likely overlap with the overlays the Lua runtime would implement, so perhaps the design work can be shared between these two efforts.

**Comment by bridgetkromhout** [comment]
@mattfarina Given that Helm v3 shipped without Lua and there is no Lua on the horizon, do you still want to keep this issue open? Thanks.

**Comment by mattfarina** [comment]
We should close this as Lua support is not coming anytime soon and we have other (arguably better) ideas on handling this (like WASM). This was in the plan but isn't any longer.

**Comment by errordeveloper** [comment]
> we have other (arguably better) ideas on handling this (like WASM)

That is quite intriguing, is there an active discussion, like design document or a brainstorming document of some sort?
