### ISSUE TITLE
Proposal: Configurable default deployment namespace for tiller instance

### ISSUE THREAD

**Issue by nrmitchi** [helm/helm#5111]
Note that I understand that Helm 3 is planning to deprecate Tiller, so I'm not sure how much traction this will get.

I'd like to propose adding the ability to set the default deployment target namespace on a tiller instance.

Currently, no matter what the `tiller-namespace` is specified as, the default namespace for a chart installation is the `default` namespace. When using multiple tiller installations across difference namespaces (typically scoped to the single namespace), all tiller's attempting to deploy into `default` by default is inconvenient, even though RBAC typically prevents it.

I would propose that we add a `--default-namespace` that can be set when installing tiller (via `helm init`).

For example, after `helm init --tiller-namespace tiller --default-namespace tiller-deployments`, then `helm install --tiller-namespace tiller stable/postgresql` should install `postgres` into the `tiller-deployments` namespace, rather than `default`.

**Comment by michelleN** [comment]
hey @nrmitchi - The core maintainers are currently working on maintaining helm 2.x and only doing features for helm 3. That said this is a great idea. Hidden behind a flag, this would also be backwards compatible with the rest of helm 2.x. If you or someone else would like to contribute, I don't see any major issues here. I'll let some of the other core maintainers weigh in as well. 
I do have a few clarifying questions:
1. Would the `--default-namespace` flag configure the default installation namespace client side or server side? Meaning, would this be an override just for the helm user or would this configuration also apply if someone else on a different machine using a different helm client did a `helm install`?
2. If the configuration is set server side, how can we ensure that another user understands the expected behavior?

**Comment by nrmitchi** [comment]
Thanks for the feedback, I'll try to take a stab at it this weekend.

Regarding your questions, I was thinking the following:

1. `--default-namespace` would configure the namespace server side. The main issue that I have encountered without this feature has been with tiller installations that only have RBAC permissions to a single namespace. In order to have this function "as expected", the default should apply regardless of the client.
2. I don't have a good answer to this. In my thoughts, this is something that would be configured by the Helm "administrator", vs the Helm user, and the user would expect the defaults to be "correct". Do you have any other thoughts about this?

**Comment by maorfr** [comment]
Already created it in the meanwhile, took about 10 minutes ;)

https://github.com/maorfr/helm-tiller-info

**Comment by michelleN** [comment]
@maorfr great! feel free to add it to[ this doc](https://github.com/helm/helm/blob/master/docs/related.md) that lists helm plugins and related projects.

**Comment by michelleN** [comment]
@nrmitchi thanks for answering the questions. I agree with your approach and the way you're thinking about it.

**Comment by maorfr** [comment]
for sure @michelleN :)

**Comment by bridgetkromhout** [comment]
Hi, @nrmitchi - thanks for your contribution of this plugin! We do have it listed on https://v2.helm.sh/docs/related/. As Helm 3 no longer has tiller, and we're only doing bugfixes for Helm 2, we won't be incorporating such a change into Helm itself at this time (but we appreciate you providing it as a plugin). I'll close this issue now; you can read more about the changes to Helm 3 in https://helm.sh/docs/faq/.
