### ISSUE TITLE
Proposal: sort fixes/new features in release notes

### ISSUE THREAD

**Issue by przemolb** [helm/helm#5119]
While reading https://github.com/helm/helm/releases I have noticed kind of mess: bugs fixes are mixed up with new features etc.
Can you please make a release notes sorted so there are sections like:
- new features
- bug fixes
- documentation changes
- etc
?

**Comment by michelleN** [comment]
yeah I think that's a good idea. I will bring this up at the next developer call and see if I can get consensus from the other core maintainers. Thanks

**Comment by thomastaylor312** [comment]
After discussing this in the dev call, we are going to add this to our release checklist. Thanks for the suggestion to do this @przemolb!

**Comment by bacongobbler** [comment]
So after going through with this during the 2.13 release, I do not think this is a workable solution to convey changes that occurred during a release. It's an intentional mess because commit messages are hard to determine what's a feature and what's a doc change, and by extension it makes it significantly more difficult for the core maintainer(s) cutting the release.

For example, here are a few commits that were in the last release:

- Added extra padding to resources template (#4981) 03718ee93d3dd290471554d6f4703c2e1539e1a3 (įoнииγ įoнииγ)
- Charts docs clean-up 73e985286f567bc5aa34399ca0e215840bee6c5e (Florent Monbillard)
- formatting b846560f4829ef725a425c43955e2c321755063a (jgleonard)
- gofmt -s 7b66bc7775086cac8fc7ee66ef5af8927e91facf (jgleonard)
- make docs 66e79227b2ff666ba66f48db992fc1f9c1ff464c (jgleonard)

All of that information is probably important to the contributors, but it doesn't convey much information to the user reading the changelog.

Instead, what we typically do is write up a short summary on all the changes that occurred that release. That way, the information that users really want to see (new features, bug fixes, doc changes, etc.) are all available as part of the release notes. The changelog is there just to give contributors an idea on whether their commit made it into the release or not. Users should not try to sift through there to find out what changed.

I'm gonna go ahead and revert this change after I'm finished with the 2.13 release.
