### ISSUE TITLE
Proposal: Display chart source repository in helm ls

### ISSUE THREAD

**Issue by maorfr** [helm/helm#5158]
Hey,

As public chart repositories are growing in numbers now that helm hub is in play, I thought that an addition of a `REPOSITORY` column would be a nice touch for `helm ls`.
This column may display the name of the repository from which (if at all) the chart was installed.

Another command may display the name and URL of the source repository.

Example output:
```
$ helm ls
NAME                ...        CHART                 REPOSITORY        ...
my-grafana          ...        grafana-1.23.0        stable            ...
```

In case the chart was not installed from a repository, but rather from source control, this field can remain empty.

Thanks a lot!
Looking forward for Helm v3!

**Comment by rimusz** [comment]
+1 for this one

**Comment by bacongobbler** [comment]
The reason we avoided this in the past is because each user can have a different name for the same repository. It's just an alias. We could use the full URL, though that could also leak internal infrastructure if the cluster was compromised and someone found out the (internal) URL where the chart is hosted.

How would we handle charts that are installed from disk?

Perhaps this is a good use case for the --description flag?

**Comment by maorfr** [comment]
Thanks for your reply.

I believe that although the repo name is an alias, it is consistent within the same organization. This is why it can bring additional value. We always call the different repos by the same names, even across different teams.

I agree about the URL not being exposed.

Regarding charts that are installed from disk - this field should remain empty in my opinion.

Regarding description - it can be used, but there is already use for this field, and I, as a user, wouldn't want to override it.

**Comment by bacongobbler** [comment]
closing as inactive.
