### ISSUE TITLE
import multiple templates from multiple directories

### ISSUE THREAD

**Issue by dorsanyvision** [helm/helm#5164]
I'm trying to achieve a way to install **one** chart with helm and this chart will point to several applications that located in a **common** Directory (contains many applications directories - only the k8s resources and nor charts), something that very similar to the ```requirements.yaml``` but only to import the some other k8s resources from a common dir .

**why?**
because I have several apps that are using the same pods (same docker images) with some extra different pods.

structure example:
```
├── charts
│   ├── app1
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   └── api-> /opt/kubernetes/common/api
│   │   │   └── api-gw -> /opt/kubernetes/common/api-gw
│   │   │   └── nginx -> /opt/kubernetes/common/nginx
│   │   └── values.yaml
│   ├── app2
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   └── mongo-> /opt/kubernetes/common/mongo
│   │   │   └── backend -> /opt/kubernetes/common/backend
│   │   │   └── nginx -> /opt/kubernetes/common/nginx
│   │   └── values.yaml
├── common
│   ├── api
│   │   ├── api-deployment.yaml
│   │   ├── api-env.yaml
│   │   └── api-service.yaml
│   ├── mongo
│   │   ├── mongo-deployment.yaml
│   │   ├── mongo-env.yaml
│   │   └── mongo-service.yaml
│   ├── nginx
│   │   ├── nginx-deployment.yaml
│   │   ├── nginx-env.yaml
│   │   └── nginx-service.yaml
.
.
.
```

**remark**: each app directory in the common directory contains only k8s resources (it is not chart)

some ways that I didn't like to solve it:
1) I already tried to use the subcharts but for this I needed to create my applications (api, api gw and etc...) as a charts, then running 2 commands ``` helm dep up ``` and ``` helm install ```, which makes it more complex, create duplicates (the dep dup create tar.gz and copy the charts into my app dir/charts) and with this I will get many charts instead of one chart.

2) I have also succeeded to implement this by using soft links, but this solution is not generic and needed some pre commands.

3) script that copy the relevant app dirs from the common dir to my chart templates dir, but with this way I will have to maintained my script.

any idea of how to implement this using helm only?
Due I need to make my all apps in the common dir as a charts and then there will be a nice solution?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```
Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
on premise
```

**Comment by mattfarina** [comment]
I wonder if it would be useful to touch on where Helm sits related to other tools and concepts. The scope and intent of a project can be useful.

Helm is a package manager rather than a configuration manager. I compare  it to things like apt, homebrew, yum, and so forth. It's targeted at package management.

Other tools tend to be used for config management. Typical examples of those are ansible, chef, and puppet.

I wrote a blog post awhile ago attempting to illustrate this at https://codeengineered.com/blog/2018/kubernetes-helm-related-tools/

The way Helm is being used here to deploy multiple applications together sounds a little outside the typical Helm case and more like what the config management tools have been doing. For example, my mind drifted to Helmfile when I thought about solving this problem.

Others may have other ideas and insights but this is what came to mind for me.

**Comment by hickeyma** [comment]
@dorsanyvision Any progress/feedback following @mattfarina suggestion?

**Comment by dorsanyvision** [comment]
it's all about the definition of helm. if helm is compared to app repos like apt, yum and etc.. so I can't expect from helm to solve my scenario. 
but if helm defined as kubernetes resources deployer, so I can expect that it will handle my issue.

FYI - I solved it just by using soft links with pre-script, in this case I can manage my common templates in one place and create some different charts that sometimes share the same template.

I will close this issue, But It will be amazing if helm will consider to solve my use case in native solution.

**Comment by hickeyma** [comment]
Thanks for the feedback @dorsanyvision.

**Comment by bacongobbler** [comment]
I agree with @mattfarina on this one. This definitely looks like a configuration management problem rather than a package management problem. Tools like [Terraform](https://www.terraform.io/) and [Pulumi](https://www.pulumi.com/) are designed to handle use cases like a "common library" and how the source code is structured in a manner that makes it more portable, whereas with Helm we're less concerned about how the source code looks and more concerned about how the code is packaged and shipped to the end user.

Helm was really designed in mind for the user that wants to package their application and provide a nice `helm install myapp` experience for their customers. The use cases described here seem more concerned about how the infrastructure is managed as source code and how it gets applied to the cluster, so those tools are probably going to be a better choice for your particular use case than Helm.

Hope this helps.
