### ISSUE TITLE
If Helm test fails before deployment, helm chart is deployed anyway

### ISSUE THREAD

**Issue by achmudas** [helm/helm#5385]
**Helm version**: v2.12.3
**Kubernetes version**: client - v1.11.1, server - v1.13.3

**Cloud Provider/Platform**: Minikube v0.34.1

I have a helm chart which creates 3 deployments and 3 services. One of the deployment needs to have an access to MongoDB. I created a test, which will run on *pre-install* hook:

    apiVersion: v1
    kind: Pod
    metadata:
      name: "{{ .Release.Name }}-database-connection-test"
      annotations:
        "helm.sh/hook": pre-install,test-success
        "helm.sh/hook-delete-policy": before-hook-creation
    spec:
      containers:
      - name: {{ .Release.Name }}-database-connection-test
        image: {{ template "mongo.image" . }}
        imagePullPolicy: Always
        env:
          - name: HOST
            value: {{ .Values.mongo.host }}
          - name: PORT
            value: {{ .Values.mongo.port | quote }}
          - name: DATABASE_NAME
            value: {{ .Values.mongo.databasename }}
          - name: USERNAME
            value: {{ .Values.mongo.username }}
          - name: PASSWORD
            value: {{ .Values.mongo.password }}
        command: ["sh", "-c", "mongo --username $USERNAME --password $PASSWORD --authenticationDatabase $DATABASE_NAME --host $HOST --port $PORT"]

No MongoDB runs on my cluster and test fails:

    NAME                                 READY     STATUS    RESTARTS   AGE
    helm-test-database-connection-test   0/1       Error     0          4h15m

I imagine, that if test fails, helm chart shouldn't be deployed, but it gets deployed:

    NAME            REVISION	UPDATED                 	STATUS  	CHART                  	APP VERSION	NAMESPACE
    helm-test	1       	Fri Mar  1 16:33:20 2019	DEPLOYED	helm-test-0.1.0	        1.0        	default 

Any thoughts would be appreciated.

**Comment by jlegrone** [comment]
Hi @achmudas, this is expected behavior. Helm test annotations are typically not used alongside other helm hooks, and are invoked outside of the release lifecycle with `helm test`.

If you would like to wait for some process to complete as part of a pre-install hook, this is possible if you use a `Job` resource instead of a `Pod`.

> What does it mean to wait until a hook is ready? This depends on the resource declared in the hook. If the resources is a `Job` kind, Tiller will wait until the job successfully runs to completion. And if the job fails, the release will fail. This is a _blocking operation_, so the Helm client will pause while the Job is run.

Reference: https://github.com/helm/helm/blob/33589472cf02d8d10e96e06085d95791c0611a75/docs/charts_hooks.md#hooks-and-the-release-lifecycle

**Comment by jlegrone** [comment]
Hi @achmudas! This is expected behavior. Helm test annotations are typically not used alongside other helm hooks, and are invoked outside of the release lifecycle with `helm test`.

If you would like to wait for some process to complete as part of a pre-install hook, this is possible if you use a `Job` resource instead of a `Pod`.

> What does it mean to wait until a hook is ready? This depends on the resource declared in the hook. If the resources is a `Job` kind, Tiller will wait until the job successfully runs to completion. And if the job fails, the release will fail. This is a _blocking operation_, so the Helm client will pause while the Job is run.

Reference: https://github.com/helm/helm/blob/33589472cf02d8d10e96e06085d95791c0611a75/docs/charts_hooks.md#hooks-and-the-release-lifecycle

**Comment by achmudas** [comment]
Hi @jlegrone! Hm... Not the best approach, because need to add timeout for a job, otherwise it will run until will succeed. Anyway, thank you for the answer.

**Comment by Ruby0510** [comment]
> Hi @jlegrone! Hm... Not the best approach, because need to add timeout for a job, otherwise it will run until will succeed. Anyway, thank you for the answer.

Hi achmudas, I have smiliar request to have a pre-install job which is ecpected to block the installation if it fails. do you find any other way to reach this? Thansk you!

**Comment by jlegrone** [comment]
@achmudas I'm not sure if I follow what the issue is with jobs as hooks. You can set a timeout using `.spec.activeDeadlineSeconds`:

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#job-termination-and-cleanup

**Comment by achmudas** [comment]
@jlegrone yes, timeout is fine in this case. Just the idea itself is not so appealing for me, that a test needs to have a timeout. But let's not dig deeper here. Thanks for the help.
