### ISSUE TITLE
Support Helm login for V3

### ISSUE THREAD

**Issue by sajayantony** [helm/helm#5461]
Currently you can push a helm chart to an OCI registry in V3. 
We need to support a unified way of storing credentials so that the user name and passwords can be used during push to an OCI registry. 

Output of `helm version`:
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"a32f8ebb377da054d21510671d63729fe6a00f3a", GitTreeState:"clean"}

/cc @jdolitsky @shizhMSFT

**Comment by shizhMSFT** [comment]
Precisely, we need `helm login` like `docker login`.

@jdolitsky  @sajayantony  Should we reuse docker credentials in `~/.docker/config.json` and `docker-credential-*` helpers? If we do,  helm can automatically reuse the credentials stored by `docker login`, `az acr login`, and many others.

Alternatively, we can have a credential file at `$HELM_HOME/chart_auth.json` so that we can read credentials from that file first, and then fall back to docker credentials if not exists.

**Comment by jdolitsky** [comment]
@sajayantony @shizhMSFT I the fallback idea. I think that oras lib should be modified to support a generic "login" method, which takes a array of paths to check. This way it is not specific to Docker or Helm.

**Comment by bacongobbler** [comment]
closed via #5597
