### ISSUE TITLE
Feature: 'helm test' extra resources

### ISSUE THREAD

**Issue by atheiman** [helm/helm#5474]
Im using [`helm test`](https://github.com/helm/helm/blob/master/docs/chart_tests.md) to test my chart and it works well. Unfortunately I need more than just a pod for my chart to be accurately tested - I need to spin up a new namespace and a service and pods in that namespace.

What I'm doing to make this work right now is I have a Boolean value that determines if the extra test resources will be spun up when the chart is installed (`helm install ... --set create_test_resources=true`), then I run `helm test`, then I manually cleanup the extra resources after with `kubectl delete ...`.

Apparently `helm test` knows how to filter resources that should only be spun up during testing, but currently that functionality is limited to the test Pods. I'd like to be able to spin up other test resources during `helm test` and to clean them up after with `helm test --cleanup`.

I think the way to denote a test resource could be either
- all manifest yamls in the `templates/tests` directory
  - this would be a breaking change
- use an annotation such as `helm.sh/test-resource`
  - I don't know if _all_ kubernetes resources support annotations

**Comment by hickeyma** [comment]
@atheiman thanks for raising this.

@michelleN I wonder should this be put on the [test proposal plan](https://github.com/helm/community/pull/40) for v3?

**Comment by jlegrone** [comment]
I definitely agree that it would be useful to allow creating arbitrary resources as part of `helm test`. 

The [hook delete policy](https://github.com/helm/helm/blob/master/docs/charts_hooks.md#hook-resources-are-not-managed-with-corresponding-releases) annotations seem like they would be a great potential replacement for the `--cleanup` flag as well.

**Comment by michelleN** [comment]
this is an excellent idea @atheiman and I'd love to see if we could work this into helm 3! 

Background/Context: Some of the work I am currently doing includes removing the coupling of tests and hooks. Tests would then become a first class abstraction with their own annotation instead of a hook annotation. 

- I really like the idea of mandating that all test manifest be in a `templates/tests` directory. In the current proposal, we have proposed that there should be `templates/tests/success/` and a `templates/tests/failure`. After further evaluation, that seems like it would just overcomplicate things unnecessarily. I would like to get more feedback from the community around mandating tests be stored in `templates/tests`. Implementation wise, we wouldn't need to render the test templates until the the `helm test` command has been invoked which could help with efficiency.

- I'm wondering what the best way to create setup resources for tests are. Perhaps a `pre-test` hook annotation can denote which resources should be created as setup. The problem we'd run into here is if we need to wait for these resources to be created before running test. Right now, hooks are fired off but there is not wait policy on a hook as far as I know that denotes for example that a pod (created from a hook) has not only been created but is also running (@thomastaylor312 - do you have any thoughts on this?). A nice thing about using hooks for test setup is that there is already a concept of `hook-weight` which can help with determining execution order.

- We're planning on adding a `helm test cleanup` command in v3 to delete test resources. We can throw an annotation on the setup resources to figure out which ones to cleanup on `helm test cleanup`. I don't think that should be complicated.

**Comment by atheiman** [comment]
bullet 1: yea that seems overly complicated. Maybe there is value in test directories for different test cases (`test/test-one/my-test-resources.yaml`, `test/test-two/different-test-resources.yaml`). In this case all of `test/test-one/` templates would be deployed and cleaned up before `test/test-two/` templates would be deployed.
bullet 2: I havent ever needed anything like that. If my pod depends on another test service coming up, I'd use an initContainer to verify the service is available before moving on to my main container of the pod which executes my test.
bullet 3: `helm test cleanup` would be helpful in a ci pipeline where you want to "always run" that command at the end.

**Comment by michelleN** [comment]
That's very helpful feedback. Thanks @atheiman. While I'm working this refactor, I'll go ahead and make it a requirement that tests be defined in a directory called `tests/`.

**Comment by bacongobbler** [comment]
Has there been any movement on your end to pursue this proposal further, @atheiman? `helm test` now supports both Jobs and Pods, but I do not believe we support arbitrary resources at this point. @jlegrone may know more about the internals to give a better answer.

I'm curious if this still needs to be addressed. It's been a year with no movement on this proposal.

**Comment by dingobar** [comment]
Hi! I'm trying to mount a script into a container to run the test, to do so I would like `helm test` to deploy a `ConfigMap` containing my script. However, looks like non-pod resources won't get picked up. Does anyone know of a workaround for this problem? If possible I would like to avoid baking the tests into the image.

**Comment by dingobar** [comment]
That works nicely, and it is pretty straightforward for users too. I may just leave the script `ConfigMap` hanging in the production versions too, because that allows the pattern of applying an upgrade, testing that it runs as expected, and rolling back if the tests fail for minimal downtime for users.
