### ISSUE TITLE
Helm 3: `helm list --date` and `helm list --reverse` aren't working

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#5499]
See https://github.com/helm/helm/pull/5489 for more information.

**Comment by jan25** [comment]
Is anyone working on this? If not, I can look into this

**Comment by bacongobbler** [comment]
Nobody's currently working on this. If you feel up to it, go ahead! Do keep in mind that this is for Helm 3 (the dev-v3 branch) rather than Helm 2 (master). If you're comfortable with that then go nuts.

**Comment by jan25** [comment]
@bacongobbler 👍 thanks! Will checkout that branch

**Comment by jan25** [comment]
Hey @bacongobbler, what would be expected behavior if both `-d` and `-r` options are used?
I’m thinking of having both sortBy and sortOrder, this way reverse would work for both date and release name. What do you think?
Precisely:
  `helm list` (Default case - sort by name Asc)
  `helm list -r` sorts by name Desc
 `helm list -d`  sorts by date Desc (latest release first)
  `helm list -d -r` sorts date Asc (oldest release first)

**Comment by bacongobbler** [comment]
fixed in #5539
