### ISSUE TITLE
Helm lint does not warn or error on duplicate keys at the same level of config

### ISSUE THREAD

**Issue by bigjonroberts** [helm/helm#5524]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): in-house kubernetes

**Comment by bacongobbler** [comment]
Do you feel like writing a PR to fix this?

**Comment by bigjonroberts** [comment]
@bacongobbler I don't really feel like it, but I'm willing to give it a try.
I installed go, cloned the repo, installed glide, ran `glide i` in the repo dir.  Then I ran `make build` and got the following:
```
jon@DESKTOP-02BTALV:/c/work/go/src/k8s.io/helm$ make build
GOBIN=/c/work/go/src/k8s.io/helm/bin go install  -tags '' -ldflags '-w -s -X k8s.io/helm/pkg/version.GitCommit=53d432fa58748412ff3dc10bc27cbf996d96c3ed -X k8s.io/helm/pkg/version.GitTreeState=clean' k8s.io/helm/cmd/...
# k8s.io/helm/pkg/kube
pkg/kube/client.go:80:30: cannot use getter (type "k8s.io/helm/vendor/k8s.io/cli-runtime/pkg/genericclioptions".RESTClientGetter) as type "k8s.io/helm/vendor/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions".RESTClientGetter in argument to "k8s.io/helm/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util".NewFactory:
        "k8s.io/helm/vendor/k8s.io/cli-runtime/pkg/genericclioptions".RESTClientGetter does not implement "k8s.io/helm/vendor/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions".RESTClientGetter (wrong type for ToDiscoveryClient method)
                have ToDiscoveryClient() ("k8s.io/helm/vendor/k8s.io/client-go/discovery".CachedDiscoveryInterface, error)
                want ToDiscoveryClient() ("k8s.io/helm/vendor/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery".CachedDiscoveryInterface, error)
```
I found the code for linting and I think this will be a simple fix.  Do you have any advice on my environment or what's going on there?

**Comment by bigjonroberts** [comment]
@bacongobbler I also posted this question about my environment to the `#helm-dev` channel on the kubernetes slack.

**Comment by hickeyma** [comment]
@bigjonroberts Can you try running `make bootstrap build`?

**Comment by bacongobbler** [comment]
yeah, I'd recommend using `make bootstrap` instead of `glide install`. The `--strip-vendor` flag is important if I recall.

**Comment by vaizki** [comment]
I ran into this today, running 3.0.0rc3.

I had a `{{- range ... }}` loop generating multiple objects and only the last object was created on the cluster although the output of --debug looked just fine. Well after (too much) head scratching I realized the end of the range loop was missing a `---` document separator. So each successive object was just overriding the values from the previous one.

Then it was down the rabbit hole into Helm, kube go client and YAML specs.
1) YAML specifications say that map keys must be unique. So invalid YAML is being generated.
2) Helm runs each template file through the go template library Execute but does not check if the output is valid YAML (or YAML at all)
3) Helm aggregates all generated manifests by sorting them and concatenating, adding a `---` between manifest file outputs but does not verify that the aggregate is valid YAML
4) The kubectl validator is used to validate the aggregate manifest but there the data is handled as JSON where duplicate keys are acceptable (although in a bit of an undefined way). The only duplicate keys validated are that there are no dups in metadata or annotations.
5) The whole chart manifest, now validated, is sent to the cluster via go client and only one of the objects ends up being created.

I actually consider this a kubernetes go client bug for not erroring out on duplicate keys in YAML (see 1 above) in the validator and cluster ops. This is due to use of `gopkg.in/yaml.v2` which validates duplicate keys in strict mode (which cannot be used due to dynamic nature of kubernetes objects). the very freshly minted yaml.v3 apparently does enforce the "no duplicate keys in map" part of the YAML spec but waiting for kubernetes project to bump up to v3 might take a bit of time.

Would it be a bad idea to try unmarshalling each manifest with yaml.v3 right after it emerges from template Execute?

**Comment by technosophos** [comment]
I am marking this as "won't fix", as it appears that this is largely a feature of all of the YAML processors I have tested. The spec actually doesn't give any meaningful guidance on parsing in this situation -- only that a YAML serializer should not emit duplicate keys. The template engine in Helm is not a YAML serializer, per se. It is a text template engine. And the parser/serializer in Helm does indeed seem to follow the specification.

If someone wanted to fix this, it appears that they would have to write a custom YAML stream parser and emit errors. We have talked in the past about writing a custom YAML parser for Helm and decided conclusively that we will not do that. It's simply not a code weight that it makes sense for Helm to include.

**Comment by dirkmueller** [comment]
So technically there are yaml parsers that do reject and flag this, so I wonder if helm can decide whether it treats yaml as 'strict yaml' or as 'json compatible yaml'. 

based on that, helm lint should be enforcing that. 

as a seemingly arbitrary example, https://onlineyamltools.com/validate-yaml is rejecting duplicate keys, and I'm pretty sure there are yaml parsers that do as well.
