### ISSUE TITLE
Helm API is out of sync

### ISSUE THREAD

**Issue by hickeyma** [helm/helm#5658]
The protobuf generator (`make protoc`) generates Go code with errors.  
The files that are generated contains structs with a few new fields named such as "XXX_NoUnKeyedLiteral, XXX_unregognized and XXX_sizecache". Test code fails as a consequence.

Thanks to @mortent for raising this issue: https://kubernetes.slack.com/archives/C51E88VDG/p1556499269085500

Output of `helm version`:
From master

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by mattfarina** [comment]
Paging @technosophos @bacongobbler @adamreese 

The exact comment in slack reads:

> Does anyone know the current state of the files generated from protobuf? Running make protoc with a clean checkout leads to lots of changes to the generated files and some test failures. The files that are generated contains structs with a few new fields named XXX_NoUnKeyedLiteral, XXX_unregognized and XXX_sizecache. This cause tests that rely on DeepEqual to fail. I am using protoc 3.2 and the go generator in Helm as described in the documentation. Seems like the go generator has been updated, but the files has not yet been generated with the new version?

I was able to verify the issue following the docs at https://github.com/helm/helm/blob/master/docs/developers.md#grpc-and-protobuf including the use of any documented versions.

**Comment by technosophos** [comment]
Hmmm... it appears that I am using a newer protoc version:

```console
$ protoc --version
libprotoc 3.4.0
```

**Comment by mortent** [comment]
I'm seeing the same result with newer versions of protoc. I've tried both 3.4.0 and 3.7.1 in addition to the 3.2 version mentioned in the docs. 
I believe this is related to the protobuf compiler plugin for golang, not protoc. There is a discussion around the addition of the XXX_ fields here: https://github.com/golang/protobuf/issues/594. I think regenerating the go files and making sure Helm always compare the generated types with using only the fields that define equality (rather than something like DeepEqual) should resolve this. I'm happy to do the work on this if we think this is the right approach.

**Comment by technosophos** [comment]
Yeah, that sounds sensible.
