### ISSUE TITLE
What are Reviewers in the OWNERS file?

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#5685]
In the OWNERS file there is a reviewers section. What is the meaning of this?

The `reviewers` key has a special meaning when using the Kubernetes tools so it means something when Helm was part of Kubernetes. But, this code is no longer using the Kubernetes tools.

There may be some distinction outside of those tools. Just looking for a pointer (docs?).

cc @technosophos

**Comment by bacongobbler** [comment]
I found this tidbit while grokking old issues/PRs: https://github.com/helm/helm/issues/1906

> The trend in Kubernetes files is to have an OWNERS file at the project root that has two broad categories: reviewers and approvers. We should probably add one of these in Helm.

So your assumption about it being from the Kubernetes org seems correct.

Interestingly enough, @fibonacci1729 is noted as a reviewer but not as a maintainer. I presume that was an accidental typo.

Given that we've moved away from the Kubernetes org, it makes sense to remove this section. As far as I know there's no distinction between "reviewers" and "maintainers" in the development process - we're all either core maintainers or emeritus maintainers.

Would love if someone prior to my time could chime in to make sure that information is correct :)

**Comment by technosophos** [comment]
@bacongobbler is correct. I created that file back when we were under the Kubernetes org. At that time, @fibonacci1729 was working on another project, so I put him down as a reviewer so we could use his expertise when we were doing Proto/gRPC stuff. But he has actually been a core maintainer since the early days of 2.0. So his name can be bumped up, and the reviewers section can be removed.
