### ISSUE TITLE
Proposal: Rollout of v3 release

### ISSUE THREAD

**Issue by adamreese** [helm/helm#5695]
This proposal defines three alpha releases.  This will allow for testing three of the bigger new features in isolation: the removal of Tiller, initial support for Lua hooks, and using CRDs as the storage layer for release metadata.

## alpha.1

- Simplified client only architecture
- Initial support for OCI repositories (`helm chart push`)
- Schematized Values Files - Support validating chart values with [JSONSchema](https://json-schema.org/)
- Remove global namespace -  Releases are stored within the same namespace as the Kubernetes objects
- Vanity import path change
   - `k8s.io/helm` => `helm.sh/helm`
- Consolidate requirements.yaml into Chart.yaml
- Command renames:
   - inspect => show
   - fetch   => pull
   - delete  => uninstall
- Name (or `--generate-name`) is now required on `helm install`
- `helm serve` has been removed
- Library chart support

## alpha.2

- Initial support for chart hooks in Lua
- Helm tests as first class abstraction
- Remove `helm init` and support XDG Base Directory
- OCI support for `helm install|template|upgrade|dep|pull` commands

## alpha.3

- Support using CRDs as release storage
- Three-way diff (apply)
- Lua CLI plugins

**Comment by mattfarina** [comment]
> Support using CRDs as release storage

I'm not sure this is a good idea for 2 reasons:

1. We won't have a controller looking for changes to these. The typical model of coupling a CRD with a controller won't be in use
2. To install a CRD into a cluster is an admin operation because it's cluster wide. Many people who work with clusters won't have that level of permission. Today we have people who can't install Tiller globally because they don't have access. A work around is to use tiller in a namespace. With CRDs the namespaced option won't be there

I would be curious as to what others thing. I'm trying to think of the end users who have to use helm for the first time in a locked down environment.

**Comment by bacongobbler** [comment]
Thanks for your thoughts @mattfarina. I expressed some of the same concerns RE: requiring admin privileges to register a CRD. I don't think we ever resolved that conversation.

@adamreese when you have time, would you mind sharing your thoughts on that point? As I recall from the conversation, the decision was to stay with secrets for the storage layer because CRDs were still in beta and are expected to change over time (along with the admin privileges required to register CRDs). The only benefit was to allow fine-grained permission controls over who can `helm install` (create the CRD) vs who can `helm upgrade` (patch existing resources), and I don't think we've been hearing users ask for that functionality at this time.

**Comment by adamreese** [comment]
As discussed on the public call, we will go with the plan outlined.  I will create the missing milestones for tracking.

**Comment by bacongobbler** [comment]
closing as the milestones have been created for tracking these milestones. Please follow the [beta.1](https://github.com/helm/helm/milestone/65) and the [3.0.0](https://github.com/helm/helm/milestone/69) milestones. Thanks!
