### ISSUE TITLE
Deploy multiple Helm Charts in a desired order

### ISSUE THREAD

**Issue by ameymehta** [helm/helm#5723]
I am deploying multiple helm sub-charts in Kubernetes Cluster through Helm and tiller. How can I make sure that a particular chart completely installs its containers before starting to install other charts and their containers?

I looked into requirements.yaml and hooks, none of them look like can be the solution I am looking for.

I have multiple sub-charts, and want to make sure containers of App1 are up and ready before helm installs other charts.

**Comment by hickeyma** [comment]
There is a good explanation [here](https://stackoverflow.com/questions/50492389/helm-subchart-order-of-execution-in-an-umbrella-chart)

**Comment by hickeyma** [comment]
Some context on ordering also  in https://github.com/helm/helm/issues/1780

**Comment by hickeyma** [comment]
Ping @ameymehta.

**Comment by pamiel** [comment]
This plugin is giving you all you want: ordering of sub-charts execution, plus a very interesting visibility of the deployment at sub-chart level instead of at the upper level.
https://github.com/gemalto/helm-spray

**Comment by hickeyma** [comment]
Closing as questions answered and no feedback after few months. We can re-open if need be.

**Comment by kycrow32** [comment]
+1
We have a few subcharts that we will ship to customers.  We would prefer not to ask them to install a third-party helm plugin (but thank you @pamiel).
Subchart1 installs an OAuth2 service. We do not control the docker image for this service, so we call a post-install job that calls the service to create some initial state (an OAuth2 clientId + secret).
Subchart2 installs a pod. That pod's application calls the service from subchart1, asking for that initial state (a client grant using that clientId + secret).

This setup will fail. The post-install job will never run, because subchart2 is waiting for the job to install that initial state.

**Comment by backnotprop** [comment]
I believe this warrants a re-open. "Deployments" may not be encompassed in a single chart... there's a lot that can go into a distributed app, esp through testing. We need reproducibility & testing across apps that are built from multiple charts.

**Comment by nitishm** [comment]
Might not be the best forum for this but take a look at https://github.com/Azure/orkestra which is built exactly for that use case
