### ISSUE TITLE
Unable to install custom resources (CRDs) with Helm v2.14.0

### ISSUE THREAD

**Issue by andresmgot** [helm/helm#5756]
After upgrading from Helm v2.13.1 to v2.14.0 we  have found an issue installing a chart with CRD and custom resources. The chart is [Kubeapps](https://github.com/bitnami/charts/tree/master/bitnami/kubeapps):

```
▶ helm --debug install bitnami/kubeapps --namespace kubeapps --name kubeapps                                              
[debug] Created tunnel using local port: '44385'

[debug] SERVER: "127.0.0.1:44385"

[debug] Original chart version: ""
[debug] Fetched bitnami/kubeapps to /home/andres/.helm/cache/archive/kubeapps-1.6.2.tgz

[debug] CHART PATH: /home/andres/.helm/cache/archive/kubeapps-1.6.2.tgz

Error: error validating "": error validating data: ValidationError(CustomResourceDefinition.spec): missing required field "scope" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec
```

Apparently, now the `scope` key is needed but when I add `scope: Namespaced` to the CRD spec I get a different error:

```
▶ helm --debug install ./chart/kubeapps --namespace kubeapps --name kubeapps                            
[debug] Created tunnel using local port: '45445'

[debug] SERVER: "127.0.0.1:45445"

[debug] Original chart version: ""
[debug] CHART PATH: /home/andres/projects/src/github.com/kubeapps/kubeapps/chart/kubeapps

Error: unable to get CRD: an empty namespace may not be set when a resource name is provided
```

The interesting thing is that it's able to create one `apprepository` but not the rest:

```
▶ kubectl get apprepositories -n kubeapps                                   
NAME      AGE
bitnami   77s
```

These are the logs of Tiller:

```
[tiller] 2019/05/17 20:15:47 preparing install for kubeapps
[storage] 2019/05/17 20:15:47 getting release history for "kubeapps"
[tiller] 2019/05/17 20:15:47 rendering kubeapps chart using values
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/svc-primary-rs.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/statefulset-primary-rs.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/initialization-configmap.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/templates/ingress.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/statefulset-secondary-rs.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/poddisruptionbudget-arbiter-rs.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/statefulset-arbiter-rs.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/pvc-standalone.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/templates/tls-secrets.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/templates/apprepositories-secret.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/secrets.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/prometheus-alerting-rule.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/poddisruptionbudget-secondary-rs.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/prometheus-service-monitor.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/headless-svc-rs.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/configmap.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/charts/mongodb/templates/poddisruptionbudget-primary-rs.yaml" is empty. Skipping.
2019/05/17 20:15:47 info: manifest "kubeapps/templates/apprepository-crd.yaml" is empty. Skipping.
[tiller] 2019/05/17 20:15:47 performing install for kubeapps
[tiller] 2019/05/17 20:15:47 executing 16 crd-install hooks for kubeapps
[kube] 2019/05/17 20:15:47 building resources from manifest
[kube] 2019/05/17 20:15:47 creating 1 resource(s)
[tiller] 2019/05/17 20:15:47 warning: Release kubeapps crd-install kubeapps/templates/apprepositories.yaml could not complete: unable to get CRD: an empty namespace may not be set when a resource name is provided
[tiller] 2019/05/17 20:15:47 failed install perform step: unable to get CRD: an empty namespace may not be set when a resource name is provided
```

I guess the issue is related to the fact that we are using a `range` to generate an array of custom resources:

https://github.com/bitnami/charts/blob/master/bitnami/kubeapps/templates/apprepositories.yaml#L1

I have unsuccessfully tried to force the namespace in the template but that ends up with the same result. Am I missing something?

------

Output of `helm version`:

Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by karuppiah7890** [comment]
@andresmgot I tried debugging this based on all details you provided. After trying different things, and checking the helm 2.14.0 code, helm 2.13.1 code, and the chart, I believe you have to make changes in the chart to fix the issue. Let me explain the issue first.

The line https://github.com/bitnami/charts/blob/master/bitnami/kubeapps/templates/apprepositories.yaml#L9 is the issue. 

I don't know much, but on checking some code here and there based on the error message, I noticed that in Helm v2.13.1 , nothing much was done for the hook `crd-install`. But in Helm v2.14.0 now, there's a waiting for "CRD to be Established" over here : https://github.com/helm/helm/blob/62edd09800f8459cee13b1a671355ec2e4faf3b1/pkg/tiller/release_server.go#L417 and it basically leads to this method https://github.com/helm/helm/blob/0d81d92a01c20a908d045c8067d04e3bb10be443/pkg/kube/client.go#L503 and on tracing over here: https://github.com/helm/helm/blob/0d81d92a01c20a908d045c8067d04e3bb10be443/pkg/kube/client.go#L518 which is where the error you showed occurs. It basically tries to get the CRD and check it's status and makes sure it's `Established` . 

Now coming back to your chart, I noticed that there are two template yamls with the hooks `crd-install`, one is a CRD `AppRepository`, the other is a list of instances of `AppRepository`. Now, the CRD template is all fine. But when the CRD objects template are processed, the presence of `crd-install` hook makes helm consider that it's a CRD resource, and tries to look it up and process it. And I think when it tries to look it up, since `AppRepository` is namesapced, when trying to lookup it says the error that you have to give the namespace to lookup the resource, so I added in metadata `namespace:   namespace: {{ $.Release.Namespace }}` in `apprepositories.yaml` and tried installing again, this time it said that it could not convert to CRD type. Basically helm thinks it's a CRD type due to the `crd-install` hook, but in reality it's a CRD instance and hence the whole issue. To confirm this whole thing, I even made a little change in the error messages and got these logs 

[helm-client.log](https://github.com/helm/helm/files/3193751/helm-client.log)

[tiller.log](https://github.com/helm/helm/files/3193752/tiller.log)

May be a better error message would have helped debug the issue better. And may be we could talk to the maintainers about checking the `kind` for `crd-install` hooks and make sure it's `CustomResourceDefinition` so that we can give a better error saying that only CRDs can be installed with `crd-install` hooks

And I noticed that you have put the hook on the CRD objects only because there was an issue https://github.com/kubeapps/kubeapps/pull/955#pullrequestreview-200764260 where the CRD objects were trying to be created even before the CRD was processed. Looks like that's what's been solved with the v2.14.0 code that I just referred above. I am not completely sure though, since this is the first time I am checking out CRD issues and respective code in helm. But if that's the case, you can remove the annotations for `tiller version >= v2.14` (using `Capabilities.TillerVersion` in the chart) and I think it will work without the glitches you experienced earlier regarding CRD objects getting created before the CRD getting processed

**Comment by andresmgot** [comment]
Thanks a lot @karuppiah7890 for the detailed debugging! Indeed replacing the hook from `crd-install` to `pre-install` did the trick:

https://github.com/kubeapps/kubeapps/pull/1037

We can close this issue now

**Comment by karuppiah7890** [comment]
Cool ! 😄 🎉
