### ISSUE TITLE
Clarification - post-upgrade with deployment, when does it run?

### ISSUE THREAD

**Issue by kierenj** [helm/helm#5793]
Is it when the new deployment resources is in place on the server? When all of the pods are created? Or when they are all ready?

I'm looking to achieve a new version's pods being created, them not have traffic routed yes by having a "ready check" that looks at DB state, then having a job run to update the DB state.

Do I want a `post-upgrade` hook, or regular job to be deployed to run once per upgrade alongside the pods being deployed?

**Comment by bacongobbler** [comment]
Looking at Helm 3:

https://github.com/helm/helm/blob/357d265de0e72f02c493701cdbee9ecc6eb0a016/pkg/action/upgrade.go#L260-L272

So the post-upgrade hooks are invoked after all the pods are ready if `--wait` is invoked, otherwise it is invoked as soon as the deployment object is created/updated.

Hope this helps.
