### ISSUE TITLE
Helm 3 Proposal: chart values schema in yaml

### ISSUE THREAD

**Issue by astorath** [helm/helm#5812]
Hi!

With the latest helm 3 alpha.1 values can be validated with json schema. I think it would be a good option to make json schema be available in yaml format, like any other artifact in helm / kubectl. Working with yaml is much easier.

**Comment by bacongobbler** [comment]
cc @ian-howell, what do you think about this?

**Comment by bacongobbler** [comment]
For background context, originally the JSON schema was originally designed as a YAML construct (values.schema.yaml), but then after some design review it was discussed as odd for a JSON schema to be defined in YAML, which then we switched to values.schema.json. It is called a **JSON** schema after all.

**Comment by astorath** [comment]
> originally the JSON schema was originally designed as a YAML construct

@bacongobbler Yeah, I've seen those commits. But:
- you're validating a **YAML** file(s) with **JSON** Schema ;)
- one could insert any JSON in YAML file with no issues

Just my 2 cents...

**Comment by ian-howell** [comment]
I agree with @bacongobbler. Using YAML for a JSON schema would make Helm the odd one out. Any other tool which might want to consume the schema would potentially need to do a conversion beforehand.

**Comment by bacongobbler** [comment]
Good point RE third parties consuming the schema. I think that's the important bit to take away here: most third party tooling relies on the JSON schema being written in... JSON.

Given that, I don't think we should put any effort into supporting this. Thank you for bringing up the question!

**Comment by johanfleury** [comment]
I really find it odd to have a json file lying there in the middle of all the yaml files of Helm and Kubernetes. I feel for this file, it will be so lonely. 

On a more serious note, I just wanted to let you know that when I first started working with Helm, I saw this proposal and decided to create `values.schema.yaml` for my personal and work charts (even if Helm is still not validating those schemas). I made two Python scripts: one that merges and validates multiple `values.yaml` files (the default one and the "release" ones) and one that extracts values from the schema and generates a "reference" a markdown table.

**Comment by zurvan2** [comment]
Kubernetes now has a standard yaml representation of an openApiV3Schema: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

Can the same syntax be used?

**Comment by glb** [comment]
GCP Marketplace also requires a parameter schema in YAML:

https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/create-app-package#custom-parameters

@bacongobbler could this proposal be reconsidered as an option?

**Comment by bacongobbler** [comment]
Already implemented as JSONSchema. See https://helm.sh/docs/topics/charts/#schema-files for more details.

**Comment by johanfleury** [comment]
BTW, the statement about confusing the user or third parties doesn’t hold as we have an example of JSON schema written in YAML with OpenAPI specifications.

Also, the difference between YAML and JSON should be minimal:

```
values = load_yaml(value_file)

if schema_file == "values.schema.yaml":
    schema = load_yaml(schema_file)
else if schema_file ==  "values.schema.json":
    schema = load_json(schema_file)

validate(values, schema)
```

**Comment by bacongobbler** [comment]
YAML can be used to instantiate specific types or classes when it is loaded, while JSON has no syntax to do so. An obvious difference is that YAML can specify an ordered map with `!!omap` or an unordered set with `!!set`, neither of which can be done in JSON.

Again, JSONSchema was specifically designed around JSON as the format for defining schemas. If you have concerns with the spec, please raise it with the JSON Schema maintainers, and we can look into supporting alternatives if the specification allows it.

**Comment by ferm10n** [comment]
The reasoning here doesn't sit right with me.

- Developer experience can be improved by this simple feature request. I'm taking the time to write this comment because working on my chart's `values.schema.json` is one of my biggest sources of friction, and I really wish I could comment stuff out as I try different things. I could do this with a YAML Schema.
- While it's true that YAML can do things that JSON can't, like the `!!omap` and `!!set`, at the end of the day it should always be able to be converted back to JSON. Especially true if the YAML in question follows the spec of a "JSONSchema"
- Third party tools that consume the schema could be adapted to support `values.schema.yaml`. If a chart developer chooses to put their schema in yaml, then they also choose to miss out on the third party tools that don't support it. Why limit the choices just because the entire landscape of possible tooling might not support it? `values.schema.json` is optional anyways.
  - counterpoint, I think this could cause problems with subcharts that use a yaml schema
- If the idea of putting a "JSON Schema" in a yaml file is undesirable because it has "JSON" in the name, then perhaps the REAL proposal should be adding support for "YAML Schema"

**Comment by Zeratoxx** [comment]
I have an eye on this issue for quite a while now.. so I want to share my thoughts on this.

First off, I think that values.yaml should be somehow replaced by schema.yaml in Helm Chart, making schema.yaml mandatory for distributed Helm Charts.

Here is why:  
Helm Chart is a package format for distributing a Kubernetes configuration while also allowing that configuration to be customized.  
When a Helm Chart is publicly distributed, validation of the values is required to maintain expected behavior during updates. This is particularly important for productivity systems.  
In my opinion, Schema.json is a superset of values.yaml for distributed Helm Charts. You can set default values in Schema.json and there is a “description” identifier for comments, while Schema.json allows validation for values. So you don't need a values.yaml file for distributed Helm Charts.  
The main disadvantage of schema.json in the Helm Charts environment is that it is in JSON format, which makes working with it more strenuous and is out of line with all the other YAML files around it.

I also know that Helm charts containing dependencies require a simple values.yaml. That's why I wrote: "[...] should _**somehow**_ be replaced by [...]". I don't know how this could be implemented cleanly 🤷.

**Comment by sirewix** [comment]
It would be nice to have this feature. Additionally to everything that was said here:
- yaml is much more diff-friendly
- yaml is more human readable (and writable) 
- every other file in helm chart and in k8s in general uses yaml format, this feels more like an exception
- I think storing jsonschema in yaml is pretty common practice in general, many tools support it

**Comment by tmmorin** [comment]
Just throwing my 2 cents, in favor of having Helm evolve to accept both `values.schema.json` and `values.schema.yaml`.

One argument in the above that I don't find convincing is the idea that it would be exotic to write a JSONSchema in Yaml: it's in fact widespread already in the Kubernetes ecosystem (OpenAPI is using JSONSchema, and the OpenAPI found in CRD definitions is typically stored in YAML manifest files).

Another mentioned argument is the idea that it would be "odd" to define a JSONSchema in something else than a JSON file, but I think that as soon as we have in mind that what matters  in a JSONSchema is the datastructure that it defines, what the JSONSchema validation will use is the schema datastructure, independently of the language used to build this datastructure.  Again, in the Kubernetes ecosystem, it's extremely frequent to define the OpenAPI/JSONSchema part of a CRD definiton, from Golang code -- this is what all projects building controllers with kubebuilder do.

And of course YAML being a direct superset of JSON makes it, to me, even less exotic.  

But ultimately, what matters more is certainly the benefits of allowing `values.schema.yaml` (reminded above).  Having a nicer tool to write a schema will increase the adoption of schema-based values validation and this will be beneficial to the Helm world.
