### ISSUE TITLE
Feature request: helm 3 custom rendering engine

### ISSUE THREAD

**Issue by joelanford** [helm/helm#5826]
I'm a maintainer of the helm-operator that is built into the Operator SDK, and I've been experimenting with the Helm 3 alpha libraries.

Using Helm 2 libraries, we are able to provide a custom implementation of tiller's `environment.Engine` interface to our tiller instance so that we can inject owner references into the release manifest. 

https://github.com/helm/helm/blob/500f46bd62ab25b48032caffa17d6dfdec86b2be/pkg/tiller/environment/environment.go#L95-L101

In Helm 3, it appears this interface is removed and there is not currently a way to customize the engine that is used to render the manifest. For example, the install action calls the global `Render` function in the `engine` package, which uses the default go templating engine.

https://github.com/helm/helm/blob/2a3b7b5395bb7d71919ed3592c8c63c425353851/pkg/action/install.go#L323

https://github.com/helm/helm/blob/2a3b7b5395bb7d71919ed3592c8c63c425353851/pkg/engine/engine.go#L66-L68

I know there are plans to support a Lua templating engine, so I'm wondering if there are also plans to add an `Engine` interface back into Helm 3 and update the actions to be able to use it?

If so, I'd be willing to work on a PR for this.

**Comment by bacongobbler** [comment]
IIRC this was an intentional design decision from a code sanity point of view. As I recall the discussion with @adamreese, there were architectural design issues with exposing and allowing other packages the ability to customize the engine prior to the rendering stage, so for the time being it was decided to make the template functions private, making the `.Render()` function the only publicly accessible endpoint.

I think it's worth discussing the possibility of exposing the engine for customization, and I do believe that there was design work ongoing for laying out an event-based rendering pipeline so this seems like something we were considering. https://github.com/helm/helm/commit/849f27d11f733592f1fa384e35e3b65696fe017a hints at this a bit.

@adamreese when you have a moment, would you mind providing some background context here?

**Comment by joelanford** [comment]
As far as I'm concerned, this feature was delivered with the PostRenderer work done in #7259. Closing.
