### ISSUE TITLE
helm upgrade problem

### ISSUE THREAD

**Issue by z00314736** [helm/helm#5876]
I installed a release with helm , after that, my chart changed, for example , added a deployment template or service template,  Then I want to use `helm upgrade` to upgrade the installed release, But it cannot work .  it says that the added  resource does not exists.   Is there any solution to solve my problem?

Output of `helm version`:
`Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

self-created cluster

**Comment by z00314736** [comment]
How to resolve this problem?

**Comment by hickeyma** [comment]
@z00314736 Can you show the error message returned by the `helm upgrade`?

**Comment by z00314736** [comment]
> @z00314736 Can you show the error message returned by the `helm upgrade`?

embarrassing...

The old versions of helm has this problem.  I just downloaded helm v2.14.1,  It can work normaly with this situation.  sorry for the carelessness , I close this issue.

**Comment by rafagonc** [comment]
I recommend reopening this issue because it is still happening even with the prettier error message on 2.14.1

I have a chart  with 5 subcharts. Added a secret to my master chart, the first helm upgrade runs fine, but the second time it fails and keeps failing on the next tries.

root@master:~#` helm upgrade processei processei-1.1.tgz 
Release "processei" has been upgraded.
LAST DEPLOYED: Fri Jun 14 22:15:26 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                                DATA  AGE
processei-nginx-ingress-controller  5     137d

==> v1/Deployment
NAME                 READY  UP-TO-DATE  AVAILABLE  AGE
processei-pgbouncer  1/1    1           1          3s

==> v1/PersistentVolume
NAME        CAPACITY  ACCESS MODES  RECLAIM POLICY  STATUS     CLAIM                         STORAGECLASS  REASON  AGE
postgresql  25Gi      RWO           Retain          Bound      default/processei-postgresql  postgresql    137d
rabbitmq    8Gi       RWO           Retain          Available  rabbitmq                      137d

==> v1/PersistentVolumeClaim
NAME                  STATUS  VOLUME      CAPACITY  ACCESS MODES  STORAGECLASS  AGE
processei-postgresql  Bound   postgresql  25Gi      RWO           postgresql    137d

==> v1/Pod(related)
NAME                                                      READY  STATUS   RESTARTS  AGE
processei-captcha-85754bbc88-qswj7                        1/1    Running  6         7d20h
processei-cronos-65f555f99-8dp9r                          1/1    Running  0         3h44m
processei-nginx-ingress-controller-775bc6d4b7-kmmkq       1/1    Running  0         7d19h
processei-nginx-ingress-default-backend-7fb678dbdc-hsjgk  1/1    Running  3         29d
processei-notifications-notifications-f7fbd7b68-lxbr4     1/1    Running  0         3h44m
processei-pgbouncer-689d6cb76d-fpxtz                      2/2    Running  0         2s
processei-postgresql-b449c7f5-dscm7                       2/2    Running  0         3h44m
processei-processei-68bbf8544b-shgzr                      1/1    Running  0         31m
processei-worker-api-8997986d6-5sgf9                      1/1    Running  0         3h44m
processei-worker-api-8997986d6-ln9cd                      1/1    Running  0         3h43m
processei-worker-api-8997986d6-m64jv                      1/1    Running  0         3h44m
rabbitmq-0                                                1/1    Running  7         137d

==> v1/Secret
NAME                  TYPE    DATA  AGE
bounceruri            Opaque  4     3s
processei-postgresql  Opaque  1     137d

==> v1/Service
NAME                                     TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)                                      AGE
db-postgresql                            NodePort   10.97.151.52   <none>       5432:5432/TCP                                137d
pgbouncer-service                        ClusterIP  10.111.112.50  <none>       5432/TCP,9127/TCP                            3s
processei-nginx-ingress-controller       NodePort   10.103.242.63  <none>       80:80/TCP,443:443/TCP                        137d
processei-nginx-ingress-default-backend  NodePort   10.105.27.158  <none>       80:28100/TCP                                 137d
rabbitmq                                 NodePort   10.106.97.9    <none>       5672:5672/TCP,4369:6170/TCP,25672:24324/TCP  137d
rabbitmq-management                      NodePort   10.110.115.81  <none>       15672:31059/TCP                              137d
service-captcha                          NodePort   10.106.40.26   <none>       80:25218/TCP                                 137d
service-cronos                           NodePort   10.110.40.77   <none>       80:28721/TCP                                 137d
service-processei                        NodePort   10.110.77.41   <none>       80:9135/TCP                                  137d

==> v1/ServiceAccount
NAME                     SECRETS  AGE
processei-nginx-ingress  1        137d

==> v1beta1/ClusterRole
NAME                     AGE
processei-nginx-ingress  137d

==> v1beta1/ClusterRoleBinding
NAME                     AGE
processei-nginx-ingress  137d

==> v1beta1/Deployment
NAME                                     READY  UP-TO-DATE  AVAILABLE  AGE
processei-captcha                        1/1    1           1          137d
processei-cronos                         1/1    1           1          137d
processei-nginx-ingress-controller       1/1    1           1          137d
processei-nginx-ingress-default-backend  1/1    1           1          137d
processei-notifications-notifications    1/1    1           1          137d
processei-postgresql                     1/1    1           1          137d
processei-processei                      1/1    1           1          137d
processei-worker-api                     3/3    3           3          137d

==> v1beta1/PodDisruptionBudget
NAME                                     MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
processei-nginx-ingress-controller       1              N/A              0                    137d
processei-nginx-ingress-default-backend  1              N/A              0                    137d

==> v1beta1/Role
NAME                     AGE
processei-nginx-ingress  137d

==> v1beta1/RoleBinding
NAME                     AGE
processei-nginx-ingress  137d

==> v1beta1/StatefulSet
NAME      READY  AGE
rabbitmq  1/1    137d


root@master:~# helm upgrade processei processei-1.1.tgz 
UPGRADE FAILED
Error: kind Secret with the name "bounceruri" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
Error: UPGRADE FAILED: kind Secret with the name "bounceruri" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart

**Comment by JennyLi90** [comment]
> I recommend reopening this issue because it is still happening even with the prettier error message on 2.14.1
> 
> I have a chart with 5 subcharts. Added a secret to my master chart, the first helm upgrade runs fine, but the second time it fails and keeps failing on the next tries.
> 
> root@master:~#` helm upgrade processei processei-1.1.tgz
> Release "processei" has been upgraded.
> LAST DEPLOYED: Fri Jun 14 22:15:26 2019
> NAMESPACE: default
> STATUS: DEPLOYED
> 
> RESOURCES:
> ==> v1/ConfigMap
> NAME DATA AGE
> processei-nginx-ingress-controller 5 137d
> 
> ==> v1/Deployment
> NAME READY UP-TO-DATE AVAILABLE AGE
> processei-pgbouncer 1/1 1 1 3s
> 
> ==> v1/PersistentVolume
> NAME CAPACITY ACCESS MODES RECLAIM POLICY STATUS CLAIM STORAGECLASS REASON AGE
> postgresql 25Gi RWO Retain Bound default/processei-postgresql postgresql 137d
> rabbitmq 8Gi RWO Retain Available rabbitmq 137d
> 
> ==> v1/PersistentVolumeClaim
> NAME STATUS VOLUME CAPACITY ACCESS MODES STORAGECLASS AGE
> processei-postgresql Bound postgresql 25Gi RWO postgresql 137d
> 
> ==> v1/Pod(related)
> NAME READY STATUS RESTARTS AGE
> processei-captcha-85754bbc88-qswj7 1/1 Running 6 7d20h
> processei-cronos-65f555f99-8dp9r 1/1 Running 0 3h44m
> processei-nginx-ingress-controller-775bc6d4b7-kmmkq 1/1 Running 0 7d19h
> processei-nginx-ingress-default-backend-7fb678dbdc-hsjgk 1/1 Running 3 29d
> processei-notifications-notifications-f7fbd7b68-lxbr4 1/1 Running 0 3h44m
> processei-pgbouncer-689d6cb76d-fpxtz 2/2 Running 0 2s
> processei-postgresql-b449c7f5-dscm7 2/2 Running 0 3h44m
> processei-processei-68bbf8544b-shgzr 1/1 Running 0 31m
> processei-worker-api-8997986d6-5sgf9 1/1 Running 0 3h44m
> processei-worker-api-8997986d6-ln9cd 1/1 Running 0 3h43m
> processei-worker-api-8997986d6-m64jv 1/1 Running 0 3h44m
> rabbitmq-0 1/1 Running 7 137d
> 
> ==> v1/Secret
> NAME TYPE DATA AGE
> bounceruri Opaque 4 3s
> processei-postgresql Opaque 1 137d
> 
> ==> v1/Service
> NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
> db-postgresql NodePort 10.97.151.52 5432:5432/TCP 137d
> pgbouncer-service ClusterIP 10.111.112.50 5432/TCP,9127/TCP 3s
> processei-nginx-ingress-controller NodePort 10.103.242.63 80:80/TCP,443:443/TCP 137d
> processei-nginx-ingress-default-backend NodePort 10.105.27.158 80:28100/TCP 137d
> rabbitmq NodePort 10.106.97.9 5672:5672/TCP,4369:6170/TCP,25672:24324/TCP 137d
> rabbitmq-management NodePort 10.110.115.81 15672:31059/TCP 137d
> service-captcha NodePort 10.106.40.26 80:25218/TCP 137d
> service-cronos NodePort 10.110.40.77 80:28721/TCP 137d
> service-processei NodePort 10.110.77.41 80:9135/TCP 137d
> 
> ==> v1/ServiceAccount
> NAME SECRETS AGE
> processei-nginx-ingress 1 137d
> 
> ==> v1beta1/ClusterRole
> NAME AGE
> processei-nginx-ingress 137d
> 
> ==> v1beta1/ClusterRoleBinding
> NAME AGE
> processei-nginx-ingress 137d
> 
> ==> v1beta1/Deployment
> NAME READY UP-TO-DATE AVAILABLE AGE
> processei-captcha 1/1 1 1 137d
> processei-cronos 1/1 1 1 137d
> processei-nginx-ingress-controller 1/1 1 1 137d
> processei-nginx-ingress-default-backend 1/1 1 1 137d
> processei-notifications-notifications 1/1 1 1 137d
> processei-postgresql 1/1 1 1 137d
> processei-processei 1/1 1 1 137d
> processei-worker-api 3/3 3 3 137d
> 
> ==> v1beta1/PodDisruptionBudget
> NAME MIN AVAILABLE MAX UNAVAILABLE ALLOWED DISRUPTIONS AGE
> processei-nginx-ingress-controller 1 N/A 0 137d
> processei-nginx-ingress-default-backend 1 N/A 0 137d
> 
> ==> v1beta1/Role
> NAME AGE
> processei-nginx-ingress 137d
> 
> ==> v1beta1/RoleBinding
> NAME AGE
> processei-nginx-ingress 137d
> 
> ==> v1beta1/StatefulSet
> NAME READY AGE
> rabbitmq 1/1 137d
> 
> root@master:~# helm upgrade processei processei-1.1.tgz
> UPGRADE FAILED
> Error: kind Secret with the name "bounceruri" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart
> Error: UPGRADE FAILED: kind Secret with the name "bounceruri" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart

I have meet the same issue, is there any clues?

**Comment by zffocussss** [comment]
same here
