### ISSUE TITLE
Support verification of PGP trust signing

### ISSUE THREAD

**Issue by sburton84** [helm/helm#5913]
The [page on provenance signing](https://github.com/helm/helm/blob/master/docs/provenance.md) mentions that part of the reason that OpenPGP was chosen was for its decentralised model, yet the decentralised trust model of PGP does not seem to actually be used when verifying signatures. As long as the corresponding public key is in the given keyring then the signature verifies successfully, regardless of whether that key is actually trusted or not.

The recommendations given for managing which keys are trusted both involve pulling down a list of trusted public keys from a centralised repository, which seems entirely counter to the decentralised model for which OpenPGP was chosen.

I propose that there is an option, which might not necessarily be the default, but which allows the `helm verify` command to verify the trust of the corresponding public key when verifying a signature, and which will cause the verification to fail if the public key is not actually trusted.

This will, by extension, also allow use of a web-of-trust or hierarchical trust pattern, whereby the public key used for signing does not have to be explicitly trusted itself, but instead it can be trust-signed by another key which is itself trusted. This could then also allow keys to be pulled automatically from a keyserver, either as part of `helm verify` or in a prior step, while still ensuring that only those keys which are actually trusted will verify correctly.

**Comment by mattfarina** [comment]
@sburton84 thank you for bringing this up.

Looking this over there are two parts to signing.

1. Did the content come from who it claims to have. If someone signs it and you verify it than you can trust it came from them
2. Do you trust the signer?

The first one is what Helm does and is the more common feature used in PGP. The second, where you have to decide how much you trust the signer, is a part of PGP that I would suggest many do not do. PGP is hard and part of that is because it is not well documented or understood. For a long time I did not know about this level of trust element.

If Helm is going to start using that I would suggest that a) we have some people wanting to use it and b) great docs explaining it. I also wonder, are any other projects using the web of trust features?

In the docs (linked above) it says:

> The key used to sign the file is not in your keyring. This indicate that the entity who signed the chart is not someone you've already signaled that you trust.

Just having a key in your keyring does not signify trust. It means you have the capability to validate something from them. You can validate something is from someone without trusting them.

I would suggest we reword that. PRs welcome.

**Comment by sburton84** [comment]
> I also wonder, are any other projects using the web of trust features?

It looks like, for Docker container signing, OpenShift uses a separate [JSON config file](https://github.com/containers/image/blob/master/docs/containers-policy.json.5.md) to specify which keys are trusted. So they don't use PGP's web-of-trust features but they do have an alternative method for explicitly trusting specific keys.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
