### ISSUE TITLE
Helm not updating Kubernetes objects properly

### ISSUE THREAD

**Issue by thomastaylor312** [helm/helm#5915]
Many users are still reporting issues with manifests being updated with a new value, but then those changes do not get applied to the actual Kubernetes objects. A common theme seems to be when you change a value from A to B and then B to A, things do not update correctly. However, there seem to be varied circumstances for when this happens and it has been hard to duplicate consistently for the core maintainers

This issue is meant to consolidate is #1844 and #3933.

**Comment by thomastaylor312** [comment]
As a note, I have taken this on and am trying to debug it based on all the examples provided in other issues

**Comment by thomastaylor312** [comment]
If anyone has a chart they can share that reliably has this issue, please do

**Comment by erismaster** [comment]
https://github.com/mattermost/mattermost-helm/tree/master/charts/mattermost-team-edition

Making a change to the configJSON section of values.yaml (Which generates a configmap), does not apply new values without deleting the configmap prior to running `helm upgrade`

**Comment by thomastaylor312** [comment]
Awesome. Thank you @erismaster I'll give it a whirl

**Comment by thomastaylor312** [comment]
@erismaster I can't seem to reproduce with that chart. I have tried modifying both the chart `values.yaml` and passed an extra values file. I also have used those files to switch back and forth between values. Each time, it updates the `Secret` object without a problem. In my case, I was changing the email settings with 

```yaml
configJSON:
  EmailSettings:
    FeedbackEmail: foo@bar.com
    FeedbackName: Foobar
    FeedbackOrganization: Foobar
```

Is there something else I should be modifying to make it work?

**Comment by erismaster** [comment]
@thomastaylor312 I tried to reproduce myself again and am not able to repro anymore. Perhaps the bug was in the helm chart itself and not with helm. 
The chart was at [this tag ](https://github.com/mattermost/mattermost-helm/blob/mattermost-team-edition-3.3.0/charts/mattermost-team-edition/values.yaml) when I was experiencing the issue last.

**Comment by thomastaylor312** [comment]
@erismaster Hmmm...doing the same thing as before and it is still working ok. Can you still reproduce the issue with that chart version? Also, what version of Helm and k8s are you using?

**Comment by erismaster** [comment]
@thomastaylor312 When I reported the bug in the previous issue it was against v1.14.1 (this cluster is on prem deployed with kubespray). Helm at that time was 

`helm version Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"} Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", `GitTreeState:"clean"}``

Todays test was minikube v1.14.2, Helm 

`Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}`

**Comment by erismaster** [comment]
@thomastaylor312 I can confirm that on the existing cluster the issue is no longer present. I was able to modified a value and have it successfully update the secret.
Helm has been upgraded from v2.13.1 -> v2.14.0
From what I can deduce it would seem the Helm update from v2.13 to 2.14 (either server or client), has resolved this issue.

**Comment by thomastaylor312** [comment]
@erismaster Thanks for digging into it! Glad it is working for you, I'll keep trying to dig around to see if I can duplicate it

**Comment by peay** [comment]
@thomastaylor312 not quite sure if this is related, but I couldn't find clear documentation on the topic/expected behavior:

- I have used `kubectl edit` to change a volume mount and add a node selector to a `Deployment` deployed with Helm.
- I have then run `helm upgrade` with my original chart. I was expecting my manual changes to be reverted, but they did not. I have `timestamp: "{{ date "20060102150405" .Release.Time }}"` in my annotations, and I can see the annotation has been updated at least.

Could this be related to what you are discussing here?

**Comment by hickeyma** [comment]
@thomastaylor312 Some feedback that might be relevant:
- When Helm does an upgrade, it uses the Kubernetes [Patch API](https://github.com/kubernetes/cli-runtime/blob/master/pkg/resource/helper.go#L141). However, not all Kubernetes objects are handled by patch, and in such a scenario it will think that no change has occurred and will not apply the update. This is the reason why updates seem to occur in a non consistent fashion. Refer to https://github.com/helm/helm/issues/5473#issuecomment-480276011 for an example of a pod issue.
- Helm does not support 3-way merge and therefore if changes are made directly to the cluster, they will not be picked up on an upgrade.  Issue #3805 open for 3-way merge.  Some discussion thread on this in https://github.com/helm/helm/issues/5430

**Comment by thomastaylor312** [comment]
@peay Yep, that comment is correct. We are working on a new merge strategy for Helm 3 stuff

@hickeyma re: the patch API, my thinking is something along those lines as well. Most people were reporting problems with `Deployment` and `ConfigMap` objects though, which are patch-able. Let me take a look at that example and give it a whirl

**Comment by hickeyma** [comment]
@thomastaylor312 Sure, just wanted to add about cases which are not patchable. This adds to the mis-understanding.

Issue #1811 might also be worth a look. If applicable, maybe add details to this and close out that issue?

**Comment by pakhomov-passteam** [comment]
+1 same issue with my chart's configmap

**Comment by thomastaylor312** [comment]
@pakhomov-passteam do you have a chart I can use to duplicate? I've been trying for weeks and cannot duplicate the issue

**Comment by haywoood** [comment]
Just to add, I'm currently running into this issue where one of my SecretClaims (and subsequent container environment variables) is not reflected in the deployed yaml. `--debug` and `helm template` show the correct output, but the env var is left off. I can't delete this deployment, unfortunately.

The SecretClaim does exist in `k get secret -n my-ns`

**Comment by thomastaylor312** [comment]
@haywoood What are your Helm and Kubernetes versions?

**Comment by haywoood** [comment]
@thomastaylor312 

```yaml
Helm: 2.8.2
Kubernetes:
  client: 1.14.2
  server: 1.11.10-gke.5
```

The secret in question lives in a list of secret definitions in `values.yaml`, which are then iterated over and placed in the manifest. I tried hardcoding this secret into my template, but no dice. It's hard to pin down what exactly is different about this secret, as it's apart of a larger list of secrets that exist no problem.

**Comment by thomastaylor312** [comment]
@haywoood Hmmm...that is an older version of Helm and Kubernetes. It seems like most people aren't seeing the issue with the latest version of Helm and k8s. Makes it kinda hard to see what caused it

**Comment by MWilkin12** [comment]
I am seeing the same issue - kubernetes (v1.11.7), helm (v2.12.2)

We have found that when we are doing an **upgrade** on a **failed release** if environment variables exist with the same value  as the **successfully deployed release** then they are not being passed into the container. For example: This a test example

Revision 1: **Helm get values** (successfully deployed release)
      ENVIRONMENT: *****
      LIST: *****
      BUCKET: *****
      NAME: *****
      URL: *****
      ENV: *****

Revision 2: **Helm get values** 
 no config variables (causes the deployment to fail) **as expected**

Revision 3 **Helm get values** (failed release)
      ENVIRONMENT: *****
      LIST: *****
      BUCKET: *****
      NAME: *****
      URL: *****
      ENV: *****

Revision 3 **Kubernetes Deployment**
      - env:
        - name: LIST
          value: *****
        - name: BUCKET
          value: *****
        - name: NAME
          value: *****
        - name: URL
          value: *****
        - name: ENV
          value: *****
as you can see, **ENVIRONMENT** not being passed in to kubernetes deployment which causes it to fail

**Comment by MWilkin12** [comment]
I have replicated the above on kubernetes kubernetes (v1.11.7), helm (v2.14.2)

**Comment by hickeyma** [comment]
@MWilkin12 Helm currently uses Kubernetes 1.15. Would you be able to upgrade to version near to this?

**Comment by MWilkin12** [comment]
Unfortunately not, we are using KOPS and the latest version we can go to v1.12.x

**Comment by diegosoek** [comment]
Same error here:

`Error: configmaps "app.job-config.beta-app" already exists`

Helm version: v2.14.1
Kube version:
Client: v1.14.0
Server: v1.13.7-gke.8

My ConfigMap:
```'
apiVersion: v1
kind: ConfigMap
metadata:
  name: app.job-config.beta-app
  labels:
    app: app
    chart: app-0.1.1
    release: beta
    heritage: Tiller
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "hook-succeeded"
data:
```

**Comment by thomastaylor312** [comment]
@diegosoek I am not sure if that is the same issue. The behavior we've seen is that the release "updates" but the values in an object are not actually updated

**Comment by tecnobrat** [comment]
I can confirm we saw this with:

```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

We changed the docker image from for example:
`service:a`
then:
`service:b`
and then back to:
`service:a`

It never went back to `service:a` and stayed at `service:b`, even tho if I do a `helm get release-name` I get a chart that has `service:a` in it.  the deployment is still showing `service:b`

**Comment by tecnobrat** [comment]
We also cannot go to 1.14 yet since we're on AWS EKS which doesn't yet support 1.14.

**Comment by tecnobrat** [comment]
I followed up with the k8s slack and was told that we can run helm 2.14.x on our 1.13 cluster.  I upgraded helm and I was able to repro it.

I went from `a => b => a` and the image never changed from b => a, even tho `helm get` says b.

**Comment by thomastaylor312** [comment]
It very well could be a k8s issue as well @tecnobrat. Thanks for the repro steps and I'll give it a try

**Comment by gnalsa** [comment]
I am hitting this issue as well with one of our complex internal charts. I am unable to reproduce the issue with a simple chart. I will keep trying to reproduce the issue, but I guess it is caused by some specific combination of resources.

running v1.11.5 k8s and v3.0.0-alpha.2 helm
`
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}
`

**Comment by thomastaylor312** [comment]
@gnalsa Please let me know if you do find something! The new three way merge should definitely prevent this kind of stuff from happening

**Comment by tuantranf** [comment]
@thomastaylor312 I'm not quite sure if it may help for someone
I have the same issue on 
```
(env) ➜ git:(develop) ✗ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
(env) ➜  git:(develop) ✗ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-2e569f", GitCommit:"2e569fd887357952e506846ed47fc30cc385409a", GitTreeState:"clean", BuildDate:"2019-07-25T23:13:33Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
Running `helm upgrade` did not update my configmap so i tried a work around with adding a label with timestamp
```
  labels:
    timestamp: "{{ .Release.Time.Seconds }}"
```
 and it works for me.

**Comment by winromulus** [comment]
The timestamp workaround did not work for me.
Unless I delete the configmap and apply it again, helm upgrade does nothing.

`helm version`
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sfitts** [comment]
For us the key seems to be editing the config map (outside of helm).  I understand that helm won't do a 3 way merge (yet), but I would expect it to overwrite any manual changes with the config map it generates and that's not what we see.

**Comment by winromulus** [comment]
I don't understand how this is a 3-way merge for us (it does not seem to be the same issue). We created a config map via helm, we update it via helm but the update fails. There are no processes or devs that touch that config map. And I agree with @sfitts, the expectation is that helm will not do merges but ensure that what we pass in as the newest value gets applied.

**Comment by bacongobbler** [comment]
FYI Helm performs a 3-way merge as of Helm 3.0.0-beta.1, @sfitts.

**Comment by lucwillems** [comment]
i have similar issues with changes in configmaps which are not propagated.
in my case, i use a configMap to inject a configuration + setup script  into a pre-upgrade hook , to be run before the upgrade.
while working on the script i noticed that any change i do in the script (embedded in configMap) was not updated on the k8s cluster 
this is the way i run it :
+ helm -n cornerstone upgrade -f ../global.yaml --debug cornerstone .
upgrade.go:79: [debug] preparing upgrade for cornerstone
upgrade.go:87: [debug] performing update for cornerstone
upgrade.go:225: [debug] creating upgraded release for cornerstone
client.go:222: [debug] Starting delete for "job-setup-cornerstone" Job
client.go:89: [debug] creating 1 resource(s)
client.go:422: [debug] Watching for changes to Job job-setup-cornerstone with timeout of 5m0s
client.go:450: [debug] Add/Modify event for job-setup-cornerstone: ADDED
client.go:489: [debug] job-setup-cornerstone: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:450: [debug] Add/Modify event for job-setup-cornerstone: MODIFIED
client.go:489: [debug] job-setup-cornerstone: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:450: [debug] Add/Modify event for job-setup-cornerstone: MODIFIED
upgrade.go:280: [debug] warning: Upgrade "cornerstone" failed: pre-upgrade hooks failed: job failed: BackoffLimitExceeded

the script current ends with error (exit 1) by design so we can check/validate its working before 
going forward with upgrading the pods.

i used random annotations & labels on the configMap / Hook job  but no result .
work around : uninstall / install which is not a option in production environment.

**Comment by thomastaylor312** [comment]
@lucwillems is the ConfigMap also annotated as a hook? If so is it weighted such that it gets updated first? It could also be that you don't have the `"helm.sh/hook-delete-policy": before-hook-creation` policy set if it is a pre-create/pre-upgrade

**Comment by tendant** [comment]
Had similar issue. 

Helm version: version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-aae39f", GitCommit:"aae39f4697508697bf16c0de4a5687d464f4da81", GitTreeState:"clean", BuildDate:"2019-12-23T08:19:12Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Added below annotation in the deployment of a helm chart. After helm upgrade, release version increases by 1, however the pod stays the same as old one without new annotations.

`+  annotations:
+    prometheus.io/scrape: "true"
+    prometheus.io/path: /metrics
+    prometheus.io/port: "8080"
`

**Comment by tendant** [comment]
> Had similar issue.
> 
> Helm version: version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
> 
> Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-aae39f", GitCommit:"aae39f4697508697bf16c0de4a5687d464f4da81", GitTreeState:"clean", BuildDate:"2019-12-23T08:19:12Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
> 
> Added below annotation in the deployment of a helm chart. After helm upgrade, release version increases by 1, however the pod stays the same as old one without new annotations.
> 
> ```
> +  annotations:
> +    prometheus.io/scrape: "true"
> +    prometheus.io/path: /metrics
> +    prometheus.io/port: "8080"
> ```

False report. Looks like annotations are added in deployment instead of pod, however I was checking it in pod. The deployment was actually correct. 

I will still keep it here, in case someone else might make similar mistake.

**Comment by anchal-chaudhary** [comment]
We're still facing this issue though, intermittently.
Version details: helm v2.15.2 and K8s 1.15.

Only solution right now seems to be uninstalling the chart and reinstalling it

**Comment by austinorth** [comment]
Having an issue where a deployment shows as being updated correctly with a `helm upgrade`, but the pods are not updated because the ReplicaSet is not updated correctly by the deployment. _Then_ the deployment refreshes and has its _old values_ in place. Super weird, and I'm still digging around to determine what's causing this, but figured I'd mention here as this was the most relevant issue I could find on the topic.

**Comment by Woile** [comment]
I'm having a similar issue, I have a normal chart, I update `appVersion` and the `tag` and the pod is not recreated. I'm using `pullPolicy: Always`. The deployment is up-to-date.

**Comment by nimishajn** [comment]
I see behaviour where my configmap gets deleted everytime when I run helm upgrade command and then gets created again. Is this expected behaviour? This way, my upgrade completely depends upon configmap creation as the new pods would refer it and if configmap creation step fails, my pods would never start. 

This is the hooks I have attached to my configmap:

`annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation`

This is my chart structure : 
`mychart/
├── charts
|        ├── subcharts....
├── Chart.yaml
├── templates
│   ├── configmap.yaml
│   └── pod.yaml
└── values.yaml
`

**Comment by bacongobbler** [comment]
> "helm.sh/hook-delete-policy": before-hook-creation

Yes. That hook deletes and re-creates the object if it exists.

**Comment by nimishajn** [comment]
Even if I don't apply `"helm.sh/hook-delete-policy": before-hook-creation` label to my configmap resource, the helm upgrade command still deletes the existing map and recreates it. Is there a way, I can avoid deleting the existing configmap and only update it?

**Comment by kymtwyf** [comment]
? is this issue fixed ?

**Comment by rajha-korithrien** [comment]
While I don't think this is a solution for everyone experiencing this problem. For me, the symptoms described in this issue were caused by user error. Specifically a poorly maintained `.helmignore` file.

I use `vim` which creates files that end in `~` as a backup of what the editor is working on. Helm will quite happily render these files, which creates a duplicate of whatever the original file renders, but at the previous state of the file.

For my chart I am working on notice the listing of files rendered:
```
[rajha@voyager charts]$ helm template -f asterisk-answers.yaml asterisk/ | grep Source
# Source: asterisk/templates/serviceaccount.yaml
# Source: asterisk/templates/tls-secret.yaml
# Source: asterisk/templates/configmap.yaml
# Source: asterisk/templates/configmap.yaml~
# Source: asterisk/templates/service-sip.yaml
# Source: asterisk/templates/service-web.yaml
# Source: asterisk/templates/services-rtp.yaml
# Source: asterisk/templates/deployment.yaml
# Source: asterisk/templates/ingress.yaml
# Source: asterisk/templates/tests/test-connection.yaml
```
What ends up in Kubernetes is the contents of `configmap.yaml~` even though what I just edited and *want* is `configmap.yaml`.

Placing the proper pattern in the `.helmignore` file for my chart causes helm to ignore these backup files and this makes the issue disappear.

**Comment by pmbeaumier** [comment]
Could we reopen this issue ? This still appears to be a problem in 3.6.

**Comment by emi662002** [comment]
Still happens in 3.6 indeed:
Upgrade the deployment manually (or make helm adopt an existing resource created with kubectl), with and env variable.
run helm upgrade with a deployment.yaml without the given env variable.
expected: variable to be removed
actually: variable is still there

**Comment by caleb15** [comment]
I consistently ran into this issue with helm 3.6.3 and helmfile sync v0.139.9. We had a configmap that wasn't updating no matter what I tried. We were finally able to work around the issue by getting rid of the pre-install annotation on our configmap - turns out it wasn't needed anyways because helm applies configmaps early on in the deployment process (see [link](https://github.com/helm/helm/blob/ac925eb7279f4a6955df663a0128044a8a6b7593/pkg/releaseutil/kind_sorter.go#L27)). Or at least I think that's what fixed it - we made a few other changes too.

@adamreese can this be reopened please? I could also make a new issue if you'd like.

**Comment by prein** [comment]
Confirmed with helm 3.7.1

**Comment by gooddalton** [comment]
This is still an issue, please can we re-open?

**Comment by mikegpl** [comment]
This is still an issue with helm v3.7.2

**Comment by Phil0ctetes** [comment]
Hi I am facing this issue as well with helm v3.7.2 
For me it happens when changing values in an umbrella helm chart.  Do we need to create a new issue for that?

**Comment by tabramczyk** [comment]
1. We've added podAnnotation to helm chart: `security.alpha.kubernetes.io/unsafe-sysctls`.
2. We've rotated all pods to see annotation. It worked.
3. We've deleted it and rotated all pods again.
4. New pods still have annotation.

**Comment by prein** [comment]
It seems to me that for most commenters, the issue seems to be apparent mostly, if not only, with configmaps. This is my case as well.

**Comment by alexnoz** [comment]
@mattfarina @bacongobbler guys, sorry to `@` you, but can we please reopen the issue? After 3 years ConfigMaps still don't get updated.

**Comment by orefalo** [comment]
same issue with replicaset - adjusting the count of replicas in values doesn't redeploy the chart. Feels like it doesn't detect the change. It works fine on first deployment.

**Comment by notque** [comment]
Configmaps still don't get updated. I'm not sure how this hasn't been solved yet, but I'd appreciate if it was reopened.

**Comment by tarbaig** [comment]
Seeing this error on helm 3.9.0
also related to configmaps

Helm version 
``` version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}```

k8s verseion
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.14", GitCommit:"57a3aa3f13699cf3db9c52d228c18db94fa81876", GitTreeState:"clean", BuildDate:"2021-12-15T14:47:10Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carlosjgp** [comment]
Hey @thomastaylor312 any chance you can reopen this issue?

Still happening on Helm 3.9.0
https://github.com/fluxcd/helm-controller/blob/a2147639031eb1362360b52c6f596c066270ecc4/go.sum#L1232

**Comment by quintonthompson** [comment]
Well issue is still happening when updating configmaps. Surprised this hasn't been solved or at least reopened yet....

Helm version: 3.9.4
k8s version:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by darkprisco** [comment]
Sorry I didn't get what is the update of such issue, any news? It is still happening.

Just for my understanding:
In case some values are manually added in the configmap (new values) via `kubectl edit cm `
Could happen that `helm upgrade` verifies the configmap without replacing that since it matches the previous values ones with the new  ones present in the configmap itself _excluding the ones added manually_?

**Comment by InbarRose** [comment]
this is still happening.
is there any update or new ticket to track this?

**Comment by palmobar** [comment]
Hi, if this issue is still with us then why is this ticket closed (maybe I missed an update)?

**Comment by grecosoft** [comment]
This appears to still be an issue.  Config Maps are not updated.  Kind of defeats the purpose of helm....

**Comment by alfredopalhares** [comment]
We are currently seeing this issue on helm for a configmap  should this ticket be reopened ?

**Comment by ShantanuKumar** [comment]
Struggling with same issue

**Comment by hieulw** [comment]
I encouter this problem not for configmap but volumes.
helm template --debug show expected values but it is not when use `helm upgrade --install`

**Comment by douglascamata** [comment]
Well, this issue seems to install happen in 3.16.4, over 3 years from the initial report.

**Comment by douglascamata** [comment]
For those that land here looking for a solution: use the `--force` flag. It will force a total replacement instead of relying on the 3-way-merge that can't handle all scenarios of ConfigMap update.

**Comment by orefalo** [comment]
Maybe --force should be made the default.

it can be confusing to see a deployment agent not properly landing on the end-state.

I lost trust in the project after submitting my comment in 2022. I manage large deployments, some created by other vendors. I am not familiar with all the details of their deployments and couldn't afford to perform manual quality checks.
