### ISSUE TITLE
Applying a manifest before installing sub chart

### ISSUE THREAD

**Issue by vitobotta** [helm/helm#5957]
Hi, I am experimenting with umbrella charts/sub charts, and am trying to create a chart that installs cert-manager and then creates issuers etc. so I can install the thing with one helm command instead of several manual commands. However before installing the cert-manager chart, a yaml manifest needs to be applied to create the required CRDs (see https://github.com/helm/charts/tree/master/stable/cert-manager). So the question is, how can I have my chart process things in this order:

- apply the CRDs manifest
- install the cert-manager sub chart
- create the issuers and secrets with my chart

Is it possible? Thanks in advance

**Comment by bacongobbler** [comment]
The only way to do this would be to merge the two charts as a single chart rather than a child/parent dependency tree. That way, resources are created in the expected order before the issuers and secrets are created.

The umbrella pattern only works if the child dependencies don't rely on each other to be installed in a particular order.

Hope this helps!

**Comment by vitobotta** [comment]
Hi @bacongobbler , sorry for the delay but I've been buried by emails/notifications. I solved for now by using a hook that ensures the CRDs are installed first. Downside is that when I update cert-manager I will have to update the CRDs file with the hooks.  Thanks :)
