### ISSUE TITLE
Hello, I have problem to update a deployment

### ISSUE THREAD

**Issue by henres** [helm/helm#6002]
I have a problem with helm deployment.
When I add a new environment variable to the deploymemt. When I do a helm update, I have this error.
Maybe it's not a bug, but I don't understand what is the problem.

```
Error: The order in patch list:
[
    map[name:APP_ENV value:prod]
    map[name:MAILER_URL value:...] 
    map[name:APP_VERSION value:v0-0-3] 
    map[name:APP_COMMIT_SHA value:...]
]
 doesn't match $setElementOrder list:
[
    map[name:APP_ENV] 
    map[name:COMPOSER_HOME] 
    map[name:PHP_XDEBUG_ENABLED] 
    map[name:DATABASE_DRIVER] 
    map[name:DATABASE_HOST] 
    map[name:DATABASE_NAME] 
    map[name:DATABASE_USER] 
    map[name:SECRET] 
    map[name:INDEX_HOSTS]
    map[name:MAILER_FROM_ADDRESS] 
    map[name:MAILER_FROM_NAME] 
    map[name:UPLOAD_DIR] 
    map[name:ARCHIVE_DIR] 
    map[name:CATALOG_STORAGE_DIR] 
    map[name:ASSET_STORAGE_DIR] 
    map[name:TMP_STORAGE_DIR] 
    map[name:UPLOAD_TMP_DIR] 
    map[name:APP_VERSION] 
    map[name:APP_COMMIT_SHA] 
    map[name:APP_CRON] 
    map[name:DATABASE_PASSWORD] 
    map[name:MAILER_URL]
]
 && The order in patch list:
[
    map[name:APP_ENV value:prod] 
    map[name:MAILER_URL value:...] 
    map[name:MAILER_URL value:...] 
    map[value:v0-0-3 name:APP_VERSION] 
    map[name:APP_COMMIT_SHA value:...]
]
 doesn't match $setElementOrder list:
[
    map[name:APP_ENV] 
    map[name:COMPOSER_HOME] 
    map[name:PHP_XDEBUG_ENABLED] 
    map[name:DATABASE_DRIVER] 
    map[name:DATABASE_HOST] 
    map[name:DATABASE_NAME] 
    map[name:DATABASE_USER] 
    map[name:SECRET] 
    map[name:INDEX_HOSTS] 
    map[name:MAILER_URL] 
    map[name:MAILER_FROM_ADDRESS] 
    map[name:MAILER_FROM_NAME] 
    map[name:UPLOAD_DIR] 
    map[name:ARCHIVE_DIR] 
    map[name:CATALOG_STORAGE_DIR] 
    map[name:ASSET_STORAGE_DIR] 
    map[name:TMP_STORAGE_DIR] 
    map[name:UPLOAD_TMP_DIR] 
    map[name:APP_VERSION] 
    map[name:APP_COMMIT_SHA] 
    map[name:NEW_RELIC_ENABLED] 
    map[name:NEW_RELIC_KEY] 
    map[name:NEW_RELIC_FRAMEWORK] 
    map[name:NEW_RELIC_APP_NAME] 
    map[name:APP_CRON] 
    map[name:DATABASE_PASSWORD] 
    map[name:MAILER_URL]
]
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by hickeyma** [comment]
@henres What error is returned by the `helm update` command? What output do you get from `helm update --debug --dry-run`?

**Comment by henres** [comment]
I have no error in my dry-run

**Comment by bacongobbler** [comment]
This is not an error I'm familiar with. Is this possibly an error being raised by the chart itself?

**Comment by mwconceicao** [comment]
Maybe related to #3805?

**Comment by VincentDehaye** [comment]
Had the same problem with the following output
```
UPGRADE FAILED
Error: The order in patch list:
[map[name:AWS_ACCESS_KEY_ID value: valueFrom:<nil>] map[name:AWS_ACCESS_KEY_ID value:<nil> valueFrom:map[secretKeyRef:map[key:aws-key name:awscred]]] map[name:AWS_SECRET_ACCESS_KEY value: valueFrom:<nil>] map[name:AWS_SECRET_ACCESS_KEY value:<nil> valueFrom:map[secretKeyRef:map[key:aws-secret-key name:awscred]]] map[name:S3_REGION value:eu-north-1] map[name:S3_REGION value:] map[$patch:delete name:DASK_DISTRIBUTED__WORKER__MEMORY__PAUSE] map[$patch:delete name:DASK_DISTRIBUTED__WORKER__MEMORY__SPILL] map[$patch:delete name:DASK_DISTRIBUTED__WORKER__MEMORY__TARGET]]
 doesn't match $setElementOrder list:
[map[name:AWS_ACCESS_KEY_ID] map[name:AWS_SECRET_ACCESS_KEY] map[name:GOOGLE_APPLICATION_CREDENTIALS] map[name:GOOGLE_CLOUD_PROJECT] map[name:EFS_HOSTNAME] map[name:S3_BUCKET] map[name:S3_REGION] map[name:S3_MAX_CACHE_SIZE] map[name:MY_POD_NAME] map[name:MY_POD_NAMESPACE] map[name:EXTRA_PIP_PACKAGES] map[name:AWS_SECRET_ACCESS_KEY] map[name:AWS_ACCESS_KEY_ID] map[name:S3_BUCKET] map[name:S3_REGION]]

Error: UPGRADE FAILED: The order in patch list:
[map[name:AWS_ACCESS_KEY_ID value: valueFrom:<nil>] map[name:AWS_ACCESS_KEY_ID value:<nil> valueFrom:map[secretKeyRef:map[key:aws-key name:awscred]]] map[name:AWS_SECRET_ACCESS_KEY value: valueFrom:<nil>] map[name:AWS_SECRET_ACCESS_KEY value:<nil> valueFrom:map[secretKeyRef:map[key:aws-secret-key name:awscred]]] map[name:S3_REGION value:eu-north-1] map[name:S3_REGION value:] map[$patch:delete name:DASK_DISTRIBUTED__WORKER__MEMORY__PAUSE] map[$patch:delete name:DASK_DISTRIBUTED__WORKER__MEMORY__SPILL] map[$patch:delete name:DASK_DISTRIBUTED__WORKER__MEMORY__TARGET]]
 doesn't match $setElementOrder list:
[map[name:AWS_ACCESS_KEY_ID] map[name:AWS_SECRET_ACCESS_KEY] map[name:GOOGLE_APPLICATION_CREDENTIALS] map[name:GOOGLE_CLOUD_PROJECT] map[name:EFS_HOSTNAME] map[name:S3_BUCKET] map[name:S3_REGION] map[name:S3_MAX_CACHE_SIZE] map[name:MY_POD_NAME] map[name:MY_POD_NAMESPACE] map[name:EXTRA_PIP_PACKAGES] map[name:AWS_SECRET_ACCESS_KEY] map[name:AWS_ACCESS_KEY_ID] map[name:S3_BUCKET] map[name:S3_REGION]]
```

Some names in the $setElementOrder list were duplicated. Instead of having my elements order following the order of last apparition, reordering them to the first apparition order fixed the problem.

@henres it might work if you put your MAILER_URL element after your APP_COMMIT_SHA

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by habutre** [comment]
This issue is closed but I believe my comment might help a bit.
I would like to use multiple `values.yaml` to override some values based on running environment. 
When I pass both `values.yaml` and `testing-values.yaml` to `helm upgrade` I got that error.

The default `values.ymal` file has many env vars and the `environment-values.yaml` just a small number of them with some overriding ones.

 ```
UPGRADE FAILED
Error: The order in patch list:
[map[name:SALES_BONUS_API_URL value:override-by-target-environment-files] map[name:SALES_BONUS_API_URL value:https://sales-api.dev.acme.com/v1/bonuses] map[name:SALES_EXPORTS_API_URL value:overri
de-by-target-environment-files] map[name:SALES_EXPORTS_API_URL value:https://sales-api.dev.acme.com/v1/exports] map[name:PLANNINGS_API_URL value:override-by-target-environment-files] map[name:PLANNINGS_API_URL value:https://plannings-api.dev.acme.com/api] map[name:ID_MANAGER_CLIENT_ID value:sales-legacy] map[name:ID_MANAGER_ACCESS_TOKEN_URI value:https://auth.acme.com/auth/realms/acme/protocol/openid-connect/token] map[name:ID_MANAGER_SCOPE value:openid] map[name:ID_MANAGER_GRANT_TYPE value:client_credentials]]
 doesn't match $setElementOrder list:                                                                  
[map[name:SALES_BONUS_API_URL] map[name:SALES_EXPORTS_API_URL] map[name:PLANNINGS_API_URL] map[name:ID_MANAGER_CLIENT_ID] map[name:ID_MANAGER_ACCESS_TOKEN_URI] map[name:ID_MANAGER_SCOPE] map[name:ID_MANAGER_GRANT_TYPE] map[name:SALES_BONUS_API_URL] map[name:SALES_EXPORTS_API_URL] map[name:PLANNINGS_API_URL] map[name:PLANNINGS_DB_URL] map[name:FLOWING_DB_URL] map[name:FLOWING_DB_USER] map[name:FLOWING_DB_PASSWORD] map[name:ID_MANAGER_CLIENT_SECRET]]
```

The upgrade command used was:

`helm upgrade "sales" sales-0.0.2.tgz --install --namespace acme-sales --values values.yaml --values minikube-values.yaml`

I am not a helm expert but I figured out I couldn't  override env vars in a way I thought could be done.

**Comment by laurawadden** [comment]
I am still having this issue and it matches exactly the description above. 

`helm version 3.0.1`

Whenever I add a new environment variable in `values.yml` and run `helm upgrade`, the patch fails with:

`Error: UPGRADE FAILED: release <release-name> failed, and has been rolled back due to atomic being set: failed to create patch: The order in patch list:
[env list here]
doesn't match $setElementOrder list: 
[env list here]`

I would expect helm to be able to add a new element to the list without complaining. 

Any thoughts? This is a complete show-stopper for us, as we aren't able to add any new environment variables without helm breaking our deployment pipeline. For the last month we have been fixing this by hand by destroying the release and re-installing. Thank you :)

**Comment by tredmon** [comment]
I've just encountered this same thing upon adding env variables via the chart's default `values.yaml`. The strange thing about my case is that I get the error when passing the chart's default `values.yaml` (since I do this before passing any other values it should essentially be a no-op), but I don't get the error when I don't pass the chart's default.

An example of the failing command: `helm upgrade --install --wait my-chart ./helm/charts/my-chart --namespace my-namespace -f ./helm/charts/my-chart/values.yaml -f ./ci/dev/values.yaml --set env.SOME_VAR=example-value`

An example of the succeeding command: `helm upgrade --install --wait my-chart ./helm/charts/my-chart --namespace my-namespace -f ./ci/dev/values.yaml --set env.SOME_VAR=example-value`

Just posting this in case it will help some other poor soul.

**Comment by Wouter0100** [comment]
This seems to related when you define multiple Envs with the same name. Removing the duplicates it, fixed it for me.

**Comment by mprokopov** [comment]
In my case it was the issue with one of the containers in deployment that was completely commented out. Once removed commented section, everything worked like a charm

**Comment by alegmal** [comment]
> This seems to related when you define multiple Envs with the same name. Removing the duplicates it, fixed it for me.

@Wouter0100 do you remember by chance if you meant that you had duplicated envs only in your custom values?

I had the "doesn't match $setElementOrder list" issue and removing envs from my custom values.yaml that had the same key and value as those in chart helped solve the issue.

This is still not a desired outcome - I would expect helm to handle this OR give a clear explanation of the problem.

**Comment by rmtolmach** [comment]
Same situation as @alegmal: custom value was a dupe of the value defined in the main chart. It wasn't being overwritten as it should have because our custom value was nested at a level that the default chart wasn't expecting. So it showed up as a duplicate even though we just had one instance of the value in _our_ code.
