### ISSUE TITLE
go get k8s.io/helm/pkg/kube  is failing because of missing packages

### ISSUE THREAD

**Issue by Saurabh-16** [helm/helm#6029]
I am importing a package k8s.io/helm/pkg/kube  in my go file.
When I am doing go get k8s.io/helm/pkg/kube in my local , it is complaining about two missing packages.

../../../k8s.io/cli-runtime/pkg/kustomize/k8sdeps/factory.go:24:2: cannot find package "sigs.k8s.io/kustomize/pkg/factory" in any of:

../../../k8s.io/cli-runtime/pkg/kustomize/k8sdeps/factory.go:24:2: cannot find package "sigs.k8s.io/kustomize/pkg/factory" in any of:

Could you please tell me the resolution for this.

**Comment by bacongobbler** [comment]
Currently, Helm's master branch is built against kubernetes 1.14. By using `go get`, you are fetching a newer version of Kubernetes. Kubernetes does not make backwards compatibility guarantees with their SDK.

I suggest using a proper package manager like [dep](https://github.com/golang/dep) instead of `go get`. That way you can fetch the proper version. Thanks.
