### ISSUE TITLE
Proposal: Helm v2 support plan once v3 is released

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#6144]
In the Helm developer call we discussed the Helm v2 support plan once v3 is released. Given the time table we are looking at there are migration issues for uses due to the holiday shopping season and tax season. We want to try to take that into account.

With that in mind here is the proposal once Helm v3.0.0 is released:

* Helm v2 is supported for bugs for the next 6 months. All new features will be in Helm v3.0.0
* Helm v2 is supported for security fixes only for the 6 months after that
* After the year support for Helm v2 will formally end. The Google Cloud buckets for the charts repositories, Helm client download, and tiller may go away. I would suggest this is likely. They are managed by Google (created prior to the CNCF). We will make tiller available in an alternative location (it can be used with the `--tiller-image` flag on `init`). Helm v2 downloads are already available at https://get.helm.sh as an alternative.

Note, if there was a method to transfer Google Cloud buckets from one project to another we would consider that but it is not possible. From our statistics we know that there have been numerous people using older Helm versions so we are sensitive to not everyone using the latest releases.

If you have questions, feedback, or thoughts on this please fee free to share.

**Comment by karuppiah7890** [comment]
Some questions I have is
1. There are so many issues being reported for v2, and many old issues still remain, will they be completely closed after an year? 

2. What's the plan to communicate this with the community ? Since this is big. Many people use helm v2, some very very old minor versions of v2. They need to know it won't be supported after one year, meaning no bug fixes including security issues. And the big message about helm chart repos being shutdown. 

Some thoughts I have is - 
1. V2 support plan could be communicated as a big flashy message in the docs, and communicated in twitter, slack and any other platforms too

2. We could start communicating more about helm v3 in all the platforms and work towards better stability so that everyone is confident to onboard to it and try to address any onboarding issues

**Comment by bacongobbler** [comment]
> will they be completely closed after an year?

If they're relevant for Helm 2 (i.e. gRPC proto errors), then probably yes. If they're relevant for Helm 3 then they should stay open. Others may have opinions here but I believe that once support has been dropped for Helm 2, we should prune the issue queue.

We will be sharing more communication about Helm 3 in the coming weeks, though any major communications about dropping support for Helm 2 should be done when we make the final call. Traditionally we've communicated these topics over the usual comms:

- public dev calls
- the release notes
- blog posts on https://helm.sh/blog
- mailing list announcements on helm-users
- on the helmpack twitter account
- in the documentation

If there are other places we should consider, I'd love to hear about it.

Right now the current plan is to implement the features we intend to ship for Helm 3 and cut a beta. Once we've shaken out the beta and have a better idea what Helm 3 is going to look like, we can start work on the messaging.

The FAQ has been a good starting point to make sure we have all of the major topics covered, so if there are things we need to communicate out, that's a good place to start looking at right now, adding more information that may be missing.

cc @bridgetkromhout

**Comment by mattfarina** [comment]
@michelleN Here is the issue for Helm v2 for the support cycle once v3 is out.

**Comment by bacongobbler** [comment]
punting this work item to the 3.0.0 milestone since we're not particularly waiting on a PR to be merged before releasing 3.0.0-beta.5.

**Comment by bacongobbler** [comment]
fixed in #6695.
