### ISSUE TITLE
Tiller docker image v2.14.3 has vulnerability CVE-2019-14697

### ISSUE THREAD

**Issue by guysports** [helm/helm#6178]
The rootfs/Dockerfile is based from `alpine:3.10` and has currently built image `gcr.io/kubernetes-helm/tiller:v2.14.3`

We have detected the following vulnerability in the image

CVE-2019-14697

musl libc through 1.1.23 has an x87 floating-point stack adjustment imbalance, related to the math/i386/ directory. In some cases, use of this library could introduce out-of-bounds writes that are not present in an application's source code.

    musl libc through 1.1.23 has an x87 floating-point stack adjustment imbalance, related to the math/i386/ directory. In some cases, use of this library could introduce out-of-bounds writes that are not present in an application's source code. 

To fix, the latest version of musl is required `1.1.22-r3`, I would suggest you alter your Dockerfile to do an `apk --no-cache upgrade` to pull in latest packages at build time.

eg
```
RUN apk --no-cache upgrade && apk add --no-cache ca-certificates socat
```

**Comment by mattfarina** [comment]
@guysports Thank you for your concern. In the future could you please contact the [security list](https://github.com/helm/community/blob/master/SECURITY.md) with things like this.

Tiller does not use libc. The image is created with a [make target](https://github.com/helm/helm/blob/v2.14.3/Makefile#L84). If you follow that you will see that cgo is disabled. Tiller is started from the entrypoint rather than a cmd. So, libc isn't in the loop. From the looks of it, Tiller could be run in a scratch container.

I'm not entirely sure why alpine is being used or the history around it. If you can make a case for why this particular CVE is impacting tiller can you share the details on the security mailing list.

**Comment by bacongobbler** [comment]
As far as I can remember, the reason scratch never caught on in the past was due to production debugging utilities. Back then there wasn't a whole lot of tooling available to debug networking issues in a container, so you needed to `exec` into the container and install networking utilities using `apk` to debug the container.

+1 to making a case for why this may have an impact on the security mailing list. For now let's close this, and if there are security disclosures let's use the normal communication channels (read: not in public) for security disclosures. Thanks.
