### ISSUE TITLE
Proposal:  Pluggable templating engines for Helm

### ISSUE THREAD

**Issue by nimakaviani** [helm/helm#6184]
**Author(s):** 
Nima Kaviani @nimakaviani (IBM) , Dmitriy Kalinin @cppforlife (Pivotal)

**Helm Version:** 3.0+

**Motivation**

We have recently open sourced ytt (https://get-ytt.io) - the YAML templating tool - which we believe improves on current ways to template YAML. Helm currently uses Go's text templating (text/template package) for templating configuration. Given the rising popularity of different templating languages, we would like to propose an optional mechanism for Helm to offload its templating functionality. Such mechanism would allow Helm users to use ytt, jsonnet, and jinja (to name a few) instead of default templating engine without having to abandon other Helm features.

In this proposal we have also accounted for thoughts and conversations made in the earlier discussions on making the HELM templating engine customizable:

- https://github.com/helm/helm/issues/5826
- https://github.com/helm/helm/issues/5084
- https://github.com/helm/helm/issues/4718
- https://github.com/k14s/ytt/issues/40

**Requirements / Assumptions**

- each chart can use a different engine (including subcharts)
- engine provides a script that allows for running the engine
- engine can be independently versioned from helm itself
- engine is trusted to keep template content secure
- engine should be kept external to the core of HELM

**User Experience**

_* Installing an Engine_

You should be able to install an engine exactly as a plugin with the same structural format, with the same top level directory and the `plugin.yaml` file

`helm plugin install https://github.com/k14s/ytt-helm-engine`

The engine is however slightly different than a regular plugin in that the `plugin.yml` file provides the additional field `type`:

```
name: "ytt"
version: "0.1.0"
usage: "Integrate ytt templating engine with Helm"
description: |-
  This plugin provides ytt templating engine to Helm.
ignoreFlags: false
useTunnel: false
type: engine
command: "$HELM_PLUGIN_DIR/ytt.sh"
```

For a templating engine, the `type` field needs to be strictly set to `engine`, informing HELM that the plugin should be used as a templating engine. 

The rest of the fields are the same as in HELM Plugins.

Having the engine listed as a subcommand under helm allows for the engine to offer additional functionality (e.g. debugging) of the charts templates in the target engine’s templating language. As a result, something like the following should be doable:

`helm ytt -f templates/ -f values.yml --debug`

_* Creating a HELM Chart with a Templating Engine_

Users should be able to choose an engine when creating their Helm chart. This can be done by passing in a `--engine` flag when creating the chart:

`helm create [chart-name] --engine [engine-name]`

The created Chart.yaml file will have an extra field with a reference to the engine.

```
apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: chart
version: 0.1.0
engine:
  name: [engine-name]
  version: [engine-version]
```

The create command is expected to provide the necessary scaffolding for the HELM chart in the given templating language.

The `engine.version` in `Chart.yaml` should match the version of installed engine from doing the earlier: `helm plugin install`.

Attempting a dry run of the generated chart should result in valid YAML configuration deployable to kubernetes:

`helm install [chart-name] [chart-path] --dry-run`

A mismatch between the version of the installed engine and the engine-version listed under `Chart.yaml` should result in an error when installing / updating the chart.

_* Runtime Contract Between Helm and the Templating Engine_

v1 input to engine would look like this:

```json
{
  "version": "v1",
  "chart": {
    "templates": [
	{
		"name": "template/something.yml",
		"path": "abs-path/template/something.yml"
	},
        {
		"name": "template/something2.yml",
		"path": "abs-path/template/something2.yml"
	}
    ]
  },
  "values": {
    "Release": {
      ...
    },
    ...
  }
}
```

- `version` is currently set to `v1` and may change with future versions
- `templates` is a list of all template files in a chart (i.e. `chart.Templates`). Note that file paths are resolved to their absolute paths to avoid any mistakes on engine's part.
- `values` is based on contents of `chartutil.Values`.

for `v1` input, the engine should produce the following output:

```json
{
  "results": [
	{
		"name": "template/something.yml",
		"content": "<output>"
	},
        {
		"name": "template/something2.yml",
		"content": "<output>"
	}
  ],
}
```

It's important that all of the output is not saved anywhere to disk (kept in memory) as it most likely will contain sensitive values.

**Comment by bacongobbler** [comment]
Hi @nimakaviani, thanks for writing this up. Do you have a reference implementation of this available somewhere?

I'm a little concerned about the user needing to install a plugin for `helm install` to work. This seems detrimental to the end-user: If I as a user want to install a chart, I now need to

1. determine what engine is being used, and at what version
1. determine how to retrieve that engine
1. install the engine using `helm plugin install`
1. install as usual

This is a big disconnect from the existing use case where the user does not need to understand the working internals of a chart in order to install it. How do you imagine we could resolve that?

**Comment by nimakaviani** [comment]
very good question @bacongobbler ... 

For the purpose of this proposal, we meant to limit the scope and have the user go through the steps you described above in order to download and install an engine. Helm can help with providing information on where to find the plugin and how to download it if it realizes an engine is missing.

If we want to extend it further and make it more seamless to the users, then our idea has been to follow a model similar to [terraform providers](https://www.terraform.io/docs/configuration/providers.html#initialization) and how they are installed. 

We can have Helm offer a list of blessed engines which it knows how to install. Upon a `helm install` it would fetch the appropriate version of the engine and make it available to the user. For third party engines it will ask users to do a manual installation at their own risk. 

Quoting below what terraform does for its providers: 

> Provider initialization is one of the actions of terraform init. Running this command will download and initialize any providers that are not already initialized. 
>
> Providers downloaded by terraform init are only installed for the current working directory; other working directories can have their own installed provider versions.
>
> Note that terraform init cannot automatically download providers that are not distributed by HashiCorp. See Third-party Plugins below for installation instructions.

**Comment by technosophos** [comment]
This looks to me like it would just lead to fragmentation of which helm charts can be installed by what tools. This is why the Helm 3 proposal called for the TPL engine to be embedded in the chart using Lua. And that feature is delayed until after Helm 3.0 is released.

**Comment by mattfarina** [comment]
@nimakaviani and @cppforlife thanks for the proposal.

There are a few things going here.

1. There is a potential for dependency problems here. Imagine you have chart A depend on chart B depend on chart C and depend on chart D (i.e., A -> B -> C -> D). Now, imagine that each of the charts uses a different engine. Now Helm would need to warn people about all the missing plugins and a user has to install each of those. Does this sound like a good user experience?
2. In Helm v2 there is the ability to add engines to Helm. Yet, no one used it or added any engines new engines. Note, funny easter egg... the internal type for a list of the engines is called `EngineYard`. This code was written why folks worked at Deis which was a division of EngineYard. How much call is there for this functionality? When we polled for it in the past it was minimal. We do prioritize [application operators and application distributors](https://github.com/helm/community/blob/master/user-profiles.md) over other rolls. How much do they want this?
3. For Helm v3 we are nearing a feature freeze to focus on getting bugs fixed and Helm v3 released. I'm not sure there is enough time to get something like this written in time for that. The way new engines are handled in Helm v3 may have to wait for a feature release due to timing.
4. Our original thought was that other engines could be embedded in charts or library charts. The idea was to use Lua but that appears to not be ready for 3.0. I wonder if Lua or WASM embedded in a chart or subchart that handles the engine would be a better way to go. What do y'all think. Then the engine doesn't require a plugin to run.

**Comment by nimakaviani** [comment]
Thanks for the comments @technosophos and @mattfarina 

@mattfarina,

On your first point, sure chart dependency can become complicated. that's why in my [next comment](https://github.com/helm/helm/issues/6184#issuecomment-519661204) I suggested the idea of trusted engines for which helm acts automatically, potentially pulling the engines before templating the charts. The idea with the proposal was to minimize user facing changes particularly for the operators and distributors (hence piggy backing on plugins)

On your second point, correct me if I am wrong but I think in v2 `EngineYard` isn't really pluggable. An engine needs to implement the interface and for a wider adoption it has to be compiled with the rest of the Helm code. Despite that, it appears that some people managed to build their custom engines like in https://github.com/helm/helm/issues/5826 but didnt go as far as sharing it with others. For other operators and users, the ytt community is pretty new but we already see some demands for it. like questions on our slack channel or issues like https://github.com/k14s/ytt/issues/40

As for points 3 and 4, fair enough. We don't intend to rush a half baked feature into Helm but it would be good to allow some way of  even experimentally supporting other templating engines at some point in v3. It doesn't have to be through this proposal but may potentially adhere to these requirements that we have identified:

> - each chart can use a different engine (including subcharts)
> - engine can be independently versioned from helm itself
> - engine is trusted to keep template content secure
> - engine should be kept external to the core of HELM

@technosophos to your point, 

> This looks to me like it would just lead to fragmentation of which helm charts can be installed by what tools.

I wonder if this is really a concern if the tool used to install the chart is kept hidden from the users? This can be either through some Lua extension point or some other abstraction that Helm provides. I am assuming you dont mean Lua to implement the entire templating engine but rather have a way to run the templating engine in a sandbox in which case how we run the engine (which seems to be through bash scripts in current implementation of plugins) is orthogonal to the pluggability idea.

**Comment by mattfarina** [comment]
@nimakaviani I have some more questions...

> I suggested the idea of trusted engines for which helm acts automatically, potentially pulling the engines before templating the charts. The idea with the proposal was to minimize user facing changes particularly for the operators and distributors (hence piggy backing on plugins)

There are two situations I'm aware of people encountering and I'm curious how a system like this would work with them. The situations are:

1. Environments cut off from the public Internet. The chart, images, and helm are on on the network and work.
2. Security conscious environments where management doesn't want things pulled down from the Internet that are non-obvious. Some of the changes to Helm v3 enable it to run without privileged access to the cluster (no need for an admin to install something like a CRD or Tiller).

How would these situations work? For example, in charts you can specify an alternative image location.

This also opens up the question, what is trusted and how does Helm verify trust? For example, an engine could become trusted and then loose it if new maintainers do something bad. On npm some modules were handed over to maintainers who then injected malicious code into the packages. They lost trust. What kind of trust system would the Helm project need to run in order to handle this?

> On your second point, correct me if I am wrong but I think in v2 EngineYard isn't really pluggable. An engine needs to implement the interface and for a wider adoption it has to be compiled with the rest of the Helm code. Despite that, it appears that some people managed to build their custom engines like in #5826 but didnt go as far as sharing it with others.

You are right about it being compiled in. I wasn't aware of #5826. Thanks for pointing it out.

I appreciate the desire to have pluggable systems here. I've proposed a couple different ways to achieve this in the past. The idea of using something like Lua or WASM was interesting because everything could be packaged as part of a chart or a common library chart. This proposal would work for 3 of your 4 bullets.

The one bullet that concerns me is:

> * engine is trusted to keep template content secure

What do you mean by this? If an engine is a binary it could make network calls and send content over the network to someone else. How do we make sure it is secure? Do we need to review each engine at each release version to make sure it's secure? How is this security verified and by whom?

If we expect enterprises to trust statements on keeping content secure they should be able to audit what we are doing and agree with it, right?

Lua interested us in this way because a script would need to list the libraries it used (e.g., networking) and the end user would need to opt-in to using it. This could allow network access to be discovered and looked at.

> I wonder if this is really a concern if the tool used to install the chart is kept hidden from the users? 

Will users want it hidden? What kind of bad things might someone do if it was too hidden? Wouldn't it be better to be automatic and in the logs rather than hidden?

> I am assuming you dont mean Lua to implement the entire templating engine but rather have a way to run the templating engine in a sandbox in which case how we run the engine (which seems to be through bash scripts in current implementation of plugins) is orthogonal to the pluggability idea.

You could implement an entire engine in Lua (or WASM) or you could call out to something on the file system. The person doing the implementation is free to take either route.

A complexity to this that shows up with bash scripts is Windows users who are not using windows subsystem for linux. Bash scripts don't work there and A LOT of developers are on Windows. If we want them as a market we need a better way to do plugins and engines.

Even take YTT as an example. It is written in Go. So, if a user is on Mac or Linux how does the system know how to handle the right binary for that environment?

**Comment by nimakaviani** [comment]
good questions @mattfarina 


>   -  Environments cut off from the public Internet. The chart, images, and helm are on on the network and work.
 >  -  Security conscious environments where management doesn't want things pulled down from the Internet that are non-obvious. Some of the changes to Helm v3 enable it to run without privileged access to the cluster (no need for an admin to install something like a CRD or Tiller).
> 
> How would these situations work? For example, in charts you can specify an alternative image location.

I think this is similar to the situation where they want to use some stable charts internally. or to use some plugins internally. The probably end up cloning them and storing them in a repo local to their networks. They should be able to do the same for the engine too. It certainly won't be as smooth but it won't be impossible.

> This also opens up the question, what is trusted and how does Helm verify trust? For example, an engine could become trusted and then loose it if new maintainers do something bad. On npm some modules were handed over to maintainers who then injected malicious code into the packages. They lost trust. What kind of trust system would the Helm project need to run in order to handle this?

yeah trust is a difficult thing to achieve. But I suppose these questions apply to Helm itself at a higher level as well. People still trust Helm with their secrets and believe it doesn't do evil (they probably achieve it through detailed auditing or just by assuming good virtue). Similarly, if Helm chooses to bless some engines (e.g. even if it is only gotpl) it is believed to have been reviewed and approved by the Helm maintainers. From there on whoever trusts Helm will trust the templating engine too (whichever way the reach this level of trust). Like I said, I believe this is already happening.

> The one bullet that concerns me is:
>
> >       engine is trusted to keep template content secure
>
> What do you mean by this? If an engine is a binary it could make network calls and send content over the network to someone else. How do we make sure it is secure? Do we need to review each engine at each release version to make sure it's secure? How is this security verified and by whom?

Right. If Helm chooses to trust an engine then it needs to be reviewed and approved. Like any other library or tool that gets pulled in. Organizations independently will have to do their auditing too.

> You could implement an entire engine in Lua (or WASM) or you could call out to something on the file system. The person doing the implementation is free to take either route.

I haven't played with Lua enough to know all the quirks of it, but I assume the richness of libraries in other languages and developer's familiarity with a certain language are enough motivations for a subset of engine authors to want to try other languages.

> Will users want it hidden? What kind of bad things might someone do if it was too hidden? Wouldn't it be better to be automatic and in the logs rather than hidden?

Right, so by hidden I meant transparent. In the sense that the platform takes care of it for them but obviously it should leave the audit trail behind.

> Even take YTT as an example. It is written in Go. So, if a user is on Mac or Linux how does the system know how to handle the right binary for that environment?

Right, so ytt is already released for all platforms. This is not in the initial proposal but I can see in a manual install of the engine, devs would choose the target distro they want to install. As you mentioned, this is already an issue with plugins too. So if Helm chooses to solve it at a higher level, the engine would benefit from the same solution too.

**Comment by mattfarina** [comment]
@nimakaviani to continue this...

> yeah trust is a difficult thing to achieve. But I suppose these questions apply to Helm itself at a higher level as well. People still trust Helm with their secrets and believe it doesn't do evil (they probably achieve it through detailed auditing or just by assuming good virtue).

As I think about this I'm finding several things come to my mind...

* Who does the work of certifying engines and keeping up on this? As in, which people. Open source is about contributions and people need to do this leg work. If it were merged into core, the way a new addition to the `EngineYard` would be, it would follow along with the way gotpl is
* Part of the trust for Helm comes from the parent organization. The CNCF which is really a sub-foundation of the linux foundation. For CNCF project graduation projects now get security audits (Helm's is coming soon). This is an example of things in place to do verification on the old saying, "trust but verify". Trust is earned as well. How does this work for engines that are not part of the CNCF? Enterprises are pretty strong on trust. Look at the models used by the Linux distributions.
* _assuming good virtue_, as you put it, is something we can't do. There are simply too many bad actors. So, who writes the auditing code and maintains that? Where do the people and time for that come from?

> If Helm chooses to trust an engine then it needs to be reviewed and approved.

I don't think Helm can trust an engine in general. There are two parts to this.

1. An engine at a version would need to be trusted. What if maintainer-ship is changed and a new maintainer does something bad? This has recently happened with some high profile dependencies in some ecosystems.
2. If an engine can be moved between locations, such as to a private network, how do we verify the engine? Would it need to be signed or otherwise checked (hash?)? How does that system work?

I raise these kinds of questions to illustrate the complexity and behind executing on a system like this. Not to shoot it down.

In a chat with @technosophos on this topic he wondered what it would like to wrap engines in containers. Then you would just need a runtime. This isn't even a half baked idea just yet but it has promise. Calling to the engine could use CRI so many could be used. It could default to docker and work with docker for mac, etc. Container images already have signing tools (e.g., Notary and TUF which are part of the CNCF). The container trust model is something organizations already know.

After the release of v3 this is something I would like to take a look at because it might solve some of the problems from previous attempts to make engines pluggable. What do you think?

**Comment by nimakaviani** [comment]
@mattfarina, very valid points.

> I raise these kinds of questions to illustrate the complexity and behind executing on a system like this. Not to shoot it down.

totally understood.

Complexities of dealing with trust was one of the reasons we went down the path of the already existing plugins model. The idea was that Helm leaves it to the users to decide whether or not they want to trust an engine. similar to how plugins are treated currently.
 
>In a chat with @technosophos on this topic he wondered what it would like to wrap engines in containers. Then you would just need a runtime. This isn't even a half baked idea just yet but it has promise. Calling to the engine could use CRI so many could be used. It could default to docker and work with docker for mac, etc. Container images already have signing tools (e.g., Notary and TUF which are part of the CNCF). The container trust model is something organizations already know.

Running templating engines / plugins in a container I would say solves half of the problem, ensuring that the engine or the plugin will not do evil on the host machine where they run. In fact ytt already maintains strong sandbox boundaries between the templating language and the external environment.

On the other hand however, even if an engine runs inside a container it can still push secrets out to a remote server (unless you are thinking of modifying iptable rules or blocking outbound connections?). Even then, the engine can still inject containers into a deployment, mount secrets, and then send them away upon deployment to a cluster. Who is responsible to verify that won't happen? the operators or the Helm community?

Every way we look at it, unless some serious auditing process is in place, it would be hard to assume a fully trusted solution from a technology standpoint.

I suggest we take a step back and see what happens in the absence of Helm assuming responsibility for engines or having to offer a trusted set of engines. 

The problems we discussed are the followings:

- the user needs to trust the plugin (based on their own discretion)
- the user needs to manually install the plugin
- In case of some chained dependencies among a number of charts, the user needs to deal with resolving engine constrains manually.

Anything else you can think of?

As for the above problems, the biggest one is probably the last one, in which case I believe it is up to the chart authors to ensure smooth installation of their charts given the subchart dependencies. Maybe less of a concern for Helm itself? Basically Helm just fails if an engine of the right version is not found. This may even encourage users who want to use charts with custom engines to look into what engine they are installing and why.

As for the other two problems, I wonder if users who choose to use engines other than what helm is shipped with by default are willing to live with those constraints?

**Comment by bridgetkromhout** [comment]
Hi, @nimakaviani - Thank you for your ideas to improve Helm. We now have a defined process so that if you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make these ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
