### ISSUE TITLE
Feature Request: Machine Readable Output

### ISSUE THREAD

**Issue by endzyme** [helm/helm#6239]
I think it would be beneficial to have a global flag that could render all output as machine readable. 

Initially it would be a nice start if `template` supported it, mostly for my purposes of reading `COMPUTED VALUES` and `USER-SUPPLIED VALUES` as json.

Happy to help here where I can, but not sure if this should first be implemented in helm 2 or just looked at for helm 3. There are lots of differences on where and how things are printed so implementations would likely vary widely. 

Potentially Related Issues: 
- https://github.com/helm/helm/issues/6184 (suggested via slack: #helm-dev)
- https://github.com/helm/helm/issues/6238

**Comment by thomastaylor312** [comment]
This is actually partially implemented with #6504. It introduces an interface that can be implemented for anything that wants to print, which should make this easier to do

**Comment by bridgetkromhout** [comment]
Hi, @endzyme - As mentioned above, this is partially implemented with https://github.com/helm/helm/pull/6504. I'm closing this issue because we now have a recommended path forward for proposals: if you'd like to formally propose this idea, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community so as to move your idea forward. Thanks!
