### ISSUE TITLE
Helm 3.0 helm config file location

### ISSUE THREAD

**Issue by dhineshbabuelango** [helm/helm#6249]
Hi All,
We are using helm in aws EKS. The current helm version is 2.14.3 which is using tiller pod which has some security concerns because of the privilege we are giving to tiller. We saw this has been fixed in helm 3.0, we tried using 3.0 but we have some queries and need help.

1. We are not able to mention the name for all helm commands as it is saying --name is invaidoption.

2. In the older version, while installing helm it will create a .helm directory and some config files but now I don't see any config file or .helm directory, how does it finds the kubernetes API.

3. Apart from pulling images, will this setup require internet

4. Is there any tentative date the prod version will be released

**Comment by mattfarina** [comment]
A `.helm` directory is created but it now follows [XDG for the base directory](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html). #6244 has been opened to provide a command that will show the locations.

This setup will require Internet to connect to the Kubernetes cluster. The Kubernetes cluster will need internet access to pull any images. Helm currently does not pull images itself.

Helm v3 beta is coming any day now. Once that happens we will be focused on bug fixes in order to get the the 3.0.0 release out. We are in the final stretch to release.

What command did you expect to run with the `--name` flag?

**Comment by bacongobbler** [comment]
Ping, any further comments before we close this one out?

**Comment by dhineshbabuelango** [comment]
Thanks for the responses, we will wait until the helm3 production version releases
