### ISSUE TITLE
Chart Test Question

### ISSUE THREAD

**Issue by kevensen** [helm/helm#6262]
Is it possible to have Helm test charts in sequential order via `helm test ...`?

**Comment by mattfarina** [comment]
By default Helm v2 is supposed to run them in serial. There is a `--parallel` if you want to run them in parallel. What problem are you having?

**Comment by kevensen** [comment]
Hi @mattfarina Thanks for the answer.  I am not having any problems :-).  I am just trying to understand the behavior.  What determines the order?

**Comment by mattfarina** [comment]
If I understand it right, and I might not because this is nested deep in Helm, when a release is created a set of YAML manifests is created and sent to Kubernetes. The tests are run in the order in which the manifests appear in the generated output. The generated manifests are sorted. For example, they are sorted by kind using a custom sorter (code [here](https://github.com/helm/helm/blob/df5ca23a418199c1b2af3abfc420f8339d0b9b8e/pkg/tiller/kind_sorter.go#L116)).

It's complicated.

**Comment by kevensen** [comment]
Fair enough.  Thanks for the insight.
