### ISSUE TITLE
Remove global value does not take effect in dependency chart

### ISSUE THREAD

**Issue by bianpengyuan** [helm/helm#6277]
This happens when running `template` command, not sure if it happens to other commands. When removing a value from global using `null`, it does not remove that value from subchart if it is declared as dependency. Using `docs/examples/alpine` as an example to reproduce:
```
diff --git a/docs/examples/alpine/charts/subchart/Chart.yaml b/docs/examples/alpine/charts/subchart/Chart.yaml
new file mode 100644
index 00000000..a9dbafe4
--- /dev/null
+++ b/docs/examples/alpine/charts/subchart/Chart.yaml
@@ -0,0 +1,5 @@
+apiVersion: v1
+appVersion: "1.0"
+description: A Helm chart for Kubernetes
+name: subchart
+version: 0.1.0
diff --git a/docs/examples/alpine/requirements.yaml b/docs/examples/alpine/requirements.yaml
new file mode 100644
index 00000000..75a09661
--- /dev/null
+++ b/docs/examples/alpine/requirements.yaml
@@ -0,0 +1,3 @@
+dependencies:
+  - name: subchart
+    version: 0.1.0
\ No newline at end of file
diff --git a/docs/examples/alpine/values.yaml b/docs/examples/alpine/values.yaml
index 225e0472..beb98559 100644
--- a/docs/examples/alpine/values.yaml
+++ b/docs/examples/alpine/values.yaml
@@ -4,3 +4,6 @@ image:
   pullPolicy: IfNotPresent
 
 restartPolicy: Never
+
+global:
+  key: val
```

Run `helm template --set global.key=null --debug alpine`, output is:
```
REVISION: 1
RELEASED: Fri Aug 23 11:31:51 2019
CHART: alpine-0.1.0
USER-SUPPLIED VALUES:
global:
  key: null

COMPUTED VALUES:
global: {}
image:
  pullPolicy: IfNotPresent
  repository: alpine
  tag: latest
restartPolicy: Never
subchart:
  global:
    key: val

HOOKS:
MANIFEST:
```

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

**Comment by bianpengyuan** [comment]
Also note this only happens when subchart is declared as dependency. Removing `requirements.yaml` makes helm work as expected.

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by vfoehn** [comment]
This issue seems to still exist in Helm 3. As @bianpengyuan said, the issue only occurs when the subchart is declared as a dependency.  However, sometimes there is no way around declaring a subchart as a dependency as I understand it.

I created a sample project (https://github.com/vfoehn/Helm-Remove-Global) to demonstrate the issue.

Subchart declared as dependency:
```
USER-SUPPLIED VALUES:
global:
  key: null

COMPUTED VALUES:
global: {}
subchart:
  global:
    key: val
```

Subchart not declared as dependency:
```
USER-SUPPLIED VALUES:
global:
  key: null

COMPUTED VALUES:
global: {}
subchart:
  global: {}
```

In my actual project I am able to circumvent the issue by overriding `key` with `""` instead of `null`. But of course, this is not a perfect fix.

Output of `helm version`:
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
