### ISSUE TITLE
Garbage collect hook resources after release deletion

### ISSUE THREAD

**Issue by jlegrone** [helm/helm#6364]
This addresses the same use case brought up in #3128, deleting hook resources when the corresponding release is deleted.

In the helm community project a [similar behavior is described](https://github.com/helm/community/blob/5da0c4f0b3123b32f16958fa32075499ba3fa398/helm-v3/004-hooks.md):

> In Helm 2, resources with hook annotations were unmanaged. In Helm 3, the owner reference is set on those, and they will be removed when the chart is deleted. There will be a way to override the management policy by setting an annotation for `helm.sh/hook-policy: unmanaged`

I think the existing `helm.sh/resource-policy: keep` annotation should work for opting out of this behavior.

CRDs should probably be an exception.

**Comment by bridgetkromhout** [comment]
Hi, @jlegrone - Thank you for your ideas to improve Helm. I see that some related PRs have been merged. We now have a defined process so that if you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make the remaining ideas here a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!

**Comment by fschmied** [comment]
@bridgetkromhout @jlegrone Has there been any follow up on this feature request? The [docs](https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases) say it might be implemented some time in the future:

> Garbage collection of hook resources when the corresponding release is deleted may be added to Helm 3 in the future, [...]

Is there some work item that I can watch to see the plans about it? (I've looked through the HIPs, but there doesn't seem to be a matching one.)
