### ISSUE TITLE
Not able to pass multiple values for a key in helm .

### ISSUE THREAD

**Issue by dhineshbabuelango** [helm/helm#6403]
Hi All, We are using AWS EKS. I am trying to deploy a helm chart for creating service role in istio. 
My helm chart looks like below

![image](https://user-images.githubusercontent.com/51995628/64606032-eb535280-d3f7-11e9-94d4-232d54a294a0.png)
and below is the values file.

![image](https://user-images.githubusercontent.com/51995628/64606495-f65ab280-d3f8-11e9-878d-3081d06e9082.png)

but when I try running helm install, I am getting the below error 

Error: failed to parse istio-routes/values.yaml: error converting YAML to JSON: yaml: line 54: did not find expected alphabetic or numeric character

expected output should have methods and paths like below

![image](https://user-images.githubusercontent.com/51995628/64606280-7c2a2e00-d3f8-11e9-921b-fda9e17f5497.png)

I am able to achieve that only if i hardcode the values like below.

![image](https://user-images.githubusercontent.com/51995628/64606323-93691b80-d3f8-11e9-8bbf-5b21439d3670.png)

**Comment by karuppiah7890** [comment]
@dhineshbabuelango could you also give the output of `helm version` ?

**Comment by karuppiah7890** [comment]
@dhineshbabuelango I have found the issue. The problem is that the values.yaml is not a valid one. I just tried this yaml and linted it in http://www.yamllint.com/
```
key: *
```
and got the error : `(<unknown>): did not find expected alphabetic or numeric character while scanning an alias at line 1 column 6` . I think it's related to the anchors feature that you can read here : https://learnxinyminutes.com/docs/yaml/ and try the below yaml in http://www.yamllint.com/
```
something: &abc ok
key: *abc
```

So to fix your issue, you can put the below and try it out. If it works, you can close the issue 😄 

```
    path: "*"
```

**Comment by dhineshbabuelango** [comment]
Thanks Karuppiah.
