### ISSUE TITLE
helm 3 seems to double base64 release data. 

### ISSUE THREAD

**Issue by paulczar** [helm/helm#6409]
Helm version v3.0.0-beta.2

after some experimenting I need to double base64 decode before I can gunzip the release data.  There might be a valid reason for the double encoding, but it's not obvious to me so I'm going to suggest its a bug to be doing it.

```
$ kubectl get secrets my-app.v1 -o json | jq .data.release -r | base64 --decode | base64 --decode | gunzip -
```

**Comment by bacongobbler** [comment]
This is because there are more storage layers than the secrets backend. ConfigMaps, Postgresql (only in Helm 2 at the moment), in-memory, etc. It's difficult to pass gzipped binary data to a secret so we have to base64-encode the data before storing it, which then the secrets API will base64-encode the data a second time.

It seems awkward, but it's definitely intentional from what I understand.

**Comment by paulczar** [comment]
ahhhhha!  I knew there would be a reason.
