### ISSUE TITLE
[Feature Request]: running a single test & ability to pass values specific to the test

### ISSUE THREAD

**Issue by Leekao** [helm/helm#6410]
I'd like the ability to run something like "helm test [deployment name] [test name]" and helm will run the test with the corresponding name, also, I'd like the ability to override the values that were initially defined in the test with new values, something like "helm test [deployment name] --set key=value" would be awesome.

**Comment by chriswells0** [comment]
In addition to being able to run a single test, it would be useful for an an application operator/distributor to be able to specify one or more tests to be skipped when executing the test hook. This is helpful when performing QA on a chart that has a large number of tests with one or more failing due to a defect in the test. It allows QA to proceed without being blocked in order to create a complete list of failing tests.
