### ISSUE TITLE
Helm install via Ansible tower 

### ISSUE THREAD

**Issue by rmaheshvarma** [helm/helm#6445]
We are trying to do the Kubernetes operations using Ansible tower. Using kubernetes method is working fine, same operation when we are trying do using helm, We are facing connection refused .

**Comment by bacongobbler** [comment]
The crux of the issue is here:

> Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 127.0.0.1:8080: connect: connection refused

Essentially, your client is trying to establish a connection to a Kubernetes cluster on 127.0.0.1:8080, which is the default settings. 9 times out of 10 this means you don't have the machine running Helm properly configured to talk to your Kubernetes cluster.

Helm uses your Kube config (~/.kube/config) to connect to your cluster. If it isn't present, that may be the reason why Helm cannot find your cluster.

Can you try running basic `helm` commands like `helm version` from the machine you're trying to run Helm from?

**Comment by rmaheshvarma** [comment]
Okay. Thank you for response. I understand. May I know do you have any idea how to pass that kubeconfig for Azure AKS using helm with Ansible tower.

**Comment by hickeyma** [comment]
@bacongobbler ^^

**Comment by bacongobbler** [comment]
`az aks get-credentials` will generate the kube config file. I haven't worked with Ansible Tower to know if there's some other setup involved. If Tower runs locally on your machine, then that should be the only setup required to work.

Let us know how you get along.

**Comment by bridgetkromhout** [comment]
Hi, @rmaheshvarma - thanks for reaching out. As stated above, you will want to generate the correct kube config file for your environment. We have no further information about Ansible Tower specifically, but please give that a try. We'll resolve this issue now.
