### ISSUE TITLE
Shortcuts for --namespace and --tiller-namespace

### ISSUE THREAD

**Issue by kapodes** [helm/helm#6446]
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Please make shortcuts for namespace/tiller-namespace filters.
typing them all the time is totally unnecessary.

```    
--namespace string                show releases within a specific namespace
--tiller-namespace string         namespace of Tiller (default "kube-system")
```

I think `-n` and `-tn` would be easy to use and match other shortcuts

`helm ls --tiller-namespace staging`
vs 
`helm ls -tn staging`

**Comment by bacongobbler** [comment]
-n is reserved for the --name flag for `helm install`, which is why we haven't been able to provide --namespace with that shortflag in Helm 2. Right now, all of the core maintainers are working on Helm 3 so I don't perceive this being a feature we can implement any time soon. Right now we're focusing on bug fixes and security releases.

In Helm 3, --namespace has now been given the -n shortflag, and --tiller-namespace no longer exists as an option now that tiller has been removed.

Will that work for you?

**Comment by kapodes** [comment]
Yes, that looks like a solution :)
