### ISSUE TITLE
error api vesion

### ISSUE THREAD

**Issue by 13567436138** [helm/helm#6451]
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

[root@dev3 kubernetes]# helm template istio --namespace istio-system ./helm/istio > ~/istio-1.2.2.yaml
Error: apiVersion "config.istio.io/v1alpha2" in istio/charts/mixer/templates/config.yaml is not available

**Comment by hickeyma** [comment]
@13567436138 Can you show the the `istio/charts/mixer/templates/config.yaml` template to better understand the issue? Also, what Helm and k8s versions are you using?

**Comment by 13567436138** [comment]
the problem of helm,downgrade from 3.0.0.beta3 to 2.14.0 solve the problem

**Comment by mhofstetter** [comment]
i guess, that this issue is related to https://github.com/helm/helm/issues/5654.

it's necessary to add the parameter `--validate` to the templating command. then the available api-versions will be checked against the remote-cluster. without the `--validate` parameter, the validation is executed against the default k8s api-types. 

IMO opinion there are two optimizations which may be discussed in this context.
* the naming parameter `--validate` is quite irritating - because a validation happens always, it just tell helm to perform a remote-validation --> call the parameter `--remote-validation`
* a complete "offline-templating" isn't available in helm v3. it would be nice to have the offline-templating without validation back

PS: i opened the issue https://github.com/helm/helm/issues/6452 where i've found another issue in combination with this validation, when the client-go cache isn't up-to-date.

**Comment by bacongobbler** [comment]
The istio chart is known to not work with Helm 3. It uses the crd-install hook which was dropped in Helm 3. https://github.com/istio/istio/issues/17167
