### ISSUE TITLE
proposal: automatically download dependencies if they are missing

### ISSUE THREAD

**Issue by woodcockjosh** [helm/helm#6454]
As an extension of https://github.com/helm/helm/issues/6005. I think we should automatically download missing dependencies for the following commands in case they are missing: 

- `helm install .`
- `helm package`
- `helm dependency update`

If this is approved. I will work on a PR.

**Comment by woodcockjosh** [comment]
relates to #6258

**Comment by bridgetkromhout** [comment]
Hi, @woodcockjosh - I see that this relates to #6258, which has been merged. We now have a defined process so that if you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make the rest of this idea a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
