### ISSUE TITLE
[Helm2] helm install and template produce different output

### ISSUE THREAD

**Issue by yfei1** [helm/helm#6548]
It seems like `helm template my-chart` install the helm tests but `helm install my-chart` excludes them. Is it the expected behavior? If so, should we document this behavior somewhere in the website?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.9-gke.3", GitCommit:"cf98c87ae263ea1b75e03d11251acdb958286c9d", GitTreeState:"clean", BuildDate:"2019-08-12T23:00:17Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`GKE`

**Comment by jlegrone** [comment]
Helm tests are [hooks](https://helm.sh/docs/developing_charts/#hooks), which are only applied to the cluster during specific phases of helm install/upgrade/delete/test subcommands.

The difference in output between `helm template` and `helm install` is expected behavior. Template is often used for debugging purposes and by default renders all chart resources, including hooks. There is a `--no-hooks` flag to skip rendering hooks which should give you the same output as `helm install`, however.

Here are the docs for template:

https://helm.sh/docs/helm/#helm-template

**Comment by yfei1** [comment]
@jlegrone `helm template` does not inherit the `--no-hooks` flag though. I use `helm template` to generate the static yaml resources with different customization options so that customers are able to `kubectl apply -f app.yaml` with one line. If template is solely used for debugging purposes, what would you recommend using helm for such a use case?

**Comment by bacongobbler** [comment]
You are correct. In Helm 3, `helm install` and `helm template` share the same code base so `helm template --no-hooks` is present and works as expected. This flag is not present in Helm 2's `helm template` command, however.

**Comment by yfei1** [comment]
Ah, thanks for the update. Can’t wait to use helm3!
