### ISSUE TITLE
Proposal: Bazel Build Tool

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6557]
Currently we are using `go test`. It works well and does caching too. In my team we recently tried [bazel](https://bazel.build) and noticed it's so fast and does caching and supports golang along with few other languages. The tests literally run in few seconds - by processing only files that have changed and their related files and using the cache for everything else. I would love to show a proof of concept for the same. We used https://github.com/bazelbuild/bazel-gazelle to generate necessary files and then that's it! It wasn't very tough after the setup. Let me know what you folks feel about it!

**Comment by hickeyma** [comment]
@karuppiah7890 Can you do a proposal outlining the details in this issue?

**Comment by karuppiah7890** [comment]
Sure @hickeyma . I'll incorporate Bazel into helm with minimal effort and show the details. I haven't tried Bazel a lot. But I have seen it in action and it's pretty fast. Want to highlight that with facts :)

**Comment by mattfarina** [comment]
To add some more context... Go 1.13 can cache test results as well. It will only run what has changed. In CI, we recently removed caching (which is needed to know the test results for things that have not changed). The reason the caching was removed is that the CircleCI caching system needs to store and restore the cache. The time to cache/restore was approximately equal to the time to run everything from scratch.

I am likely overthinking this but... If I understand it right, the modules pulled in would be coming from Google Cloud (where the default Go Proxy is at) and circle looks to be hosted out of AWS so the module ingress to CircleCI would be free while caching would cost them. I could be wrong as this is my rough look at it and would be open to correction.

I just ran `go test ./...` locally for a case with no changes. It took 2 seconds because all the results were cached. The machine I ran the tests on it working fairly hard at the moment, too.

How would bazel provide an improvement?

**Comment by karuppiah7890** [comment]
@mattfarina Hmm, makes sense. I'll still do the spike and see the results.

Circle ci storing and restoring cache thing - I hear bazel can take care of it's cache, given a storage service (like AWS S3, GCS). But yeah, for that we need to think about paying for the service.

Is it okay to still go ahead and demo Bazel? Will surely compare it with `go test` 😄 

And yes, I tried running unit tests in my local too just now, after the first two, three runs, it was very fast, like 2-3 seconds.

**Comment by bacongobbler** [comment]
I'm averse to introducing new tooling for the sake of using new tooling. If there's a clear benefit to using Bazel for local development over what Go provides, then we could consider it.

Feel free to experiment with Bazel, but unless there's some clear benefit for every developer over the existing tooling, then I don't see it becoming part of Helm's standard dev tooling.

Similar arguments were made when it was asked if we could "docker-ize" the dev build in #4172. We saw a significant increase in build times so we had to drop it from Helm 3 as more developers were frustrated with the slow build times compared to the portability gains.

**Comment by jlegrone** [comment]
I use bazel quite a bit but I think it raises a significant barrier to entry for new contributors as well as nontrivial cost of ownership for maintainers. For a project like helm that is a single binary written in a single language, the benefits are also typically minimal (as mentioned above go tooling already does a pretty good job with caching and change detection).

The main benefit of using bazel to build helm might be that external workspaces could import helm's go_binary target rather than writing their own main package and using helm3 as a library. I'm currently using the library approach in a separate bazel project without issue.

**Comment by karuppiah7890** [comment]
Thanks for the inputs. I agree to all of it. Like @bacongobbler mentioned, I'll experiment it, along with my friends and see if there are any clear benefits. 

But yeah, it's a bit of a barrier for new contributors - especially if they have to do a lot. I hope it'll only be installing Bazel and generating Bazel build files and running tests and build only. Let's see

**Comment by karuppiah7890** [comment]
Considering we felt it will increase the barrier for new folks, I'm going to close this issues 👍 Just me trying to reduce the number of issues by removing some stale issues 😛  with enough inputs to say the feature is not needed
