### ISSUE TITLE
Ability to add last-applied-configuration Annotation to kubernetes services

### ISSUE THREAD

**Issue by vshalchian** [helm/helm#6610]
Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Centos 7

I install my K8S resources using helm and would like to add last-applied-configuration to my services (Specifically because Velero backup tool needs that annotation to preserve the NodePort). I know that if I use kubectl apply I can add last-applied-configuration annotation but is the same possible somehow in Helm installation though any option/configuration or is this a potential new feature for Helm ?

Thank you

**Comment by bridgetkromhout** [comment]
Hi, @vshalchian - Thank you for your idea for adding a `last-applied-configuration` to Helm. I'm closing this issue because we now have a recommended path forward for proposals: if you'd like to formally propose this idea, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community. Thanks!
