### ISSUE TITLE
docs: demonstrate a template that can determine if this chart is being rendered by Helm 2 or Helm 3

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#6686]
In some cases, Helm 3 has intentionally broke compatibility because there are similar systems in place. For example, `{{ .Release.Time }}` was dropped in favour of the `now` function introduced in sprig.

However, there are cases where there are objects that exist only in Helm 3, and there is a parallel equivalent in Helm 2.

One use case is with the same object: `{{ .Release.Time }}`. `.Release.Time` was formatted as a date string using Unix epoch time formatting. `now` does not, so you have to pass it through `unixEpoch`, which is a new function introduced to Sprig and doesn't exist in older versions of Helm.

So, we need a way to document a pattern in the documentation where users can detect whether the chart is being rendered in Helm 2 or Helm 3, so the chart can be rendered in either version using the following pseudo syntax:

```
if helm 2:
    {{ .Release.Time }}
else:
    now | unixEpoch
```

**Comment by domhdp** [comment]
This is bugging me, since I am trying to get a chart working for both Helm 2 and Helm 3.

Previously I was using the `.Release.Time.Seconds` for Helm 2. I have added something like
```
## deployment.yaml
{{- $timeSeconds := "unknown" -}}
{{- if and (.Values.helmMajorVersion) (ge .Values.helmMajorVersion 3) }}
{{- $timeSeconds = now | unixEpoch -}}
{{- else }}
{{- $timeSeconds = .Release.Time.Seconds -}}
{{- end }}
```

This works for Helm 3 but fails in Helm 2 since attempting to locate the function `unixEpoch`.

Should I be using the `tpl` function? Something like
```
## values.yaml
timeSecondsTpl: "{{ .Release.Time.Seconds }}"

## deployment.yaml
{{- $timeSeconds := tpl .Values.timeSecondsTpl . -}}
```

Or is there a better way? I am a bit lost on how to get my chart working for bother versions, any tips are appreciated.
