### ISSUE TITLE
Adding CA certificate to .helm or another fixed location

### ISSUE THREAD

**Issue by webmutation** [helm/helm#6816]
Is there a location to place the CA certificates so that we do not have to pass the location of the file
helm push --ca-file=myfile.crt package remote-repo-location ?

**Comment by karuppiah7890** [comment]
@webmutation This looks like an option in the https://github.com/chartmuseum/helm-push plugin code. Could you raise an issue there / ask the question there? Also, this looks like a more OS specific question rather than a tool specific. Ideally, if your OS believes the CA, then you are all good. For example, in the case of MacOS this would be the `Keychain Access`, if your CA certificate is there and is trusted by all users, you don't have to pass it separately in any tool and it will be trusted, even in the browser it will be trusted. 😄 I hope that answers the question

**Comment by bacongobbler** [comment]
As per the help text, you can set the $HELM_REPO_CA_FILE environment variable for a constant lookup path. For further questions/feature suggestions, please open a ticket over at the [helm-push issue queue](https://github.com/chartmuseum/helm-push/issues). Thanks!

**Comment by webmutation** [comment]
Indeed it is also an issue when trying to helm repo refresh the external Helm Chart repositories in our PKS harbor, the certificate is signed by an internal CA... I will see if we can get the certificates to be added to the trust store in some way.

Thanks for your reply. I will look into a way to add CA files there are more than one that is why it's a bit anoying since per each helm repo we have a different key/tenant.

Thanks to both
