### ISSUE TITLE
`helm template` output of manifests does not follow order of filenames and manifests within each file (random results)

### ISSUE THREAD

**Issue by AndiDog** [helm/helm#6843]
Output of `helm version`:

(all of these versions are buggy as described)

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

version.BuildInfo{Version:"v3.0.0-beta.2", GitCommit:"26c7338408f8db593f93cd7c963ad56f67f662d4", GitTreeState:"clean", GoVersion:"go1.12.9"}

version.BuildInfo{Version:"v3.0.0-rc.1", GitCommit:"ee77ae3d40fd599445ebd99b8fc04e2c86ca366c", GitTreeState:"clean", GoVersion:"go1.13.3"}
```

`helm template` loops over file paths and manifests within a file via a `map[string]string`, which produces random results as Go does not guarantee any order. More details in the proposed fix #6842 (sorry, created the PR first).

Example from the PR, using a buggy helm version. Running the same command twice:

```
$ helm-3.0.0-rc.1 template ../helm/cmd/helm/testdata/testcharts/object-order/ | grep -E '^# \d'
# 1
# 2
# 3
# 7
# 8
# 5
...

$ helm-3.0.0-rc.1 template ../helm/cmd/helm/testdata/testcharts/object-order/ | grep -E '^# \d'
# 2
# 3
# 1
# 7
# 8
# 5
...
```

The example manifests here all have the same kind, and therefore should be sorted in a stable manner. Namely, the order from the template file should be kept. This helps the author match source with generated output, which is especially critical for CI/CD pipelines where `helm template` output gets committed to a Git repo and people would like to have readable diffs instead of manifests changing their position with every change.

**Comment by thomastaylor312** [comment]
This makes complete sense to have, but I think in this case we have never guaranteed that `helm template` output is deterministic (please let me know if I missed somewhere that we did!). So we are going to classify this as a feature and bring into 3.1

**Comment by vikstrous** [comment]
I think it's extremely important for `helm template` output to be deterministic. For my use case the order doesn't matter, but I need to be able to diff the output. Without being able to diff the output, how can I make sure that when I change a chart, I'm changing what I intend to change? I don't want to deploy a kubernetes cluster to validate that a trivial config change is made correctly or a refactor hasn't changed the output.

**Comment by diist** [comment]
Especially since `helm` 2 _is_ deterministic. I'm sure a lot of people rely on this.

**Comment by cristiklein** [comment]
I started working on this. Here is a [commit with a test](https://github.com/cristiklein/helm/commit/fc4d1f51b4d0c9e5e0ddda6ef7ca9d6283a424d9) that fails due to non-determinism.

**Comment by bacongobbler** [comment]
Might also want to check out #6842

**Comment by cristiklein** [comment]
Thanks @bacongobbler 

Assuming stable `helm template` output is a feature that will only exist in Helm 3.1, we have an opportunity to come up with a specification of the ordering of entries. What would the community prefer?
1. Sort entries by kind (as per InstallOrder / UninstallOrder), then by kind alphabetically, then by **filename**, then by **index** within the file (as in #6842).
2. Sort entries by **kind** (as per InstallOrder / UninstallOrder), then by kind alphabetically, then by **filename**, then by entry **name** (`.metadata.name`) (as in #7118).
3. Sort entries by kind (as per InstallOrder / UninstallOrder), then by kind alphabetically, then by entry **name** (`.metadata.name`).

I am starting to find the 3rd option more appealing for two reasons:
* It feels more **consistent**, since the ordering by kind is already ignoring the physical layout of the entries. For example, a Chart with a single Secret, Ingress, Service and Deployment currently renders the same, no matter how the entries are organized in files.
* The ordering would be **robust** to refactoring the Chart, e.g., if multiple entries are split from a single file to multiple files or if files are renamed. Indeed, `helm template` would only change if the Chart truly changed, a very desirable property for testing.

My 2 cents.

**Comment by AndiDog** [comment]
It should be clear that InstallOrder should be considered first, while remaining items should be sorted in a consistent way. I implemented 1) because it looks consistent to humans – if I write a template with entries A, B, C (no matter what their `.metadata.name` is), I expect them to come out as A, B, C. Especially in large outputs, reordering things as compared to the source code is surprising.

**Comment by ryan-dyer-sp** [comment]
Any update on this?  Though helm may have never declared that template output be ordered.  I never saw this issue with v2.  We routinely regenerate templates and commit to SCM and until v3 we never had random diffs occurring.

**Comment by thomastaylor312** [comment]
Looks like we just need a second review on the PR, which likely didn't happen because of the holidays. I'll do it tomorrow

**Comment by ryan-dyer-sp** [comment]
any update?

**Comment by AndiDog** [comment]
MR got merged. Only waiting for release, I believe. This issue can be closed afterwards.

**Comment by hickeyma** [comment]
Closing this as #6842 is merged. It is due in the 3.1.0 release.
