### ISSUE TITLE
Helm upgrade --reuse-values on clean chart doesn't apply

### ISSUE THREAD

**Issue by technicool** [helm/helm#6899]
Output of `helm version`: version.BuildInfo{Version:"v3.0.0-rc.3", `GitCommit:"2ed206799b451830c68bff30af2a52879b8b937a", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
DigitalOcean

## Premise
When creating a new chart, and then attempting to apply values using either `--set` or via a file (`-f values.yaml`), the new values will not apply if there have been no user supplied values.

## Detailed logs

These have been reproducable for the at least rc-2 and rc-3. Multiple times, and in both the default and other namespaces. For example, I am using the `stable/redis` chart; although, any chart appears to have this issue, including file-based charts.

```
$ helm install redis stable/redis
....

$ helm upgrade redis stable/redis --reuse-values --set a=a
Release "redis" has been upgraded. Happy Helming!
NAME: redis
LAST DEPLOYED: Wed Nov  6 21:54:07 2019
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
...

$ helm get values redis
USER-SUPPLIED VALUES:
null
```

Notice how there is nothing coming back, when we expected

```
USER-SUPPLIED VALUES:
a: a
```

Instead, it appears that we must first omit `--reuse-values` the first time we modify the chart.

```
$ helm upgrade redis stable/redis --set a=a

$ helm get values redis
USER-SUPPLIED VALUES:
a: a

$ helm upgrade redis stable/redis --reuse-values --set b=b
...

$ helm get values redis
USER-SUPPLIED VALUES:
a: a
b: b

$ helm upgrade redis stable/redis --reuse-values --set a=c
...

$ helm get values redis
USER-SUPPLIED VALUES:
a: c
b: b
```

**Comment by karuppiah7890** [comment]
Able to reproduce. Will check why this occurs

**Comment by karuppiah7890** [comment]
This is what I tried to debug:
```
$ helm upgrade test test --reuse-values --set "something=blah"
```

The error occurs at this line

https://github.com/helm/helm/blob/7f7e90b4078d412e2ff36d8220409ff8497c93a1/pkg/action/upgrade.go#L361

where `current.Config` refers to the current release's values, which is `nil` and the `newValues` is a `map[string]string` containing `"something":"blah"` key value pair, according to my example

And then here

https://github.com/helm/helm/blob/a758490f4d29f032927f06bf3b52c1f92c430b4d/pkg/chartutil/coalesce.go#L179-L185

`nil` is returned. Not sure what's the idea behind the `if` condition. I would expect `dst` to be returned if `dst` has a value and also since it has more precedence. Any thoughts on this @bacongobbler ?
