### ISSUE TITLE
Use kubectl context namespace

### ISSUE THREAD

**Issue by caalberts** [helm/helm#6928]
It looks like the feature to use default tiller namespace from kube context is broken. I have a kube context like this:
```
- context:
    cluster: gke_foo_us-central1-b_bar
    namespace: bar
    user: user
  name: gke_foo_us-central1-b_bar
```

When I run `helm version --tiller-namespace=bar`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

But when I just run `helm version`, it is returning the tiller version in `default` namespace:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.9", GitCommit:"6c1e92d07f5717440f751666d4aad6943015d3cb", GitTreeState:"clean", BuildDate:"2019-10-11T23:14:17Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by karuppiah7890** [comment]
@caalberts Helm actually expects you to set the tiller namespace explicitly. If you check help, you can see this

```
$ helm version --help
...
...
   --tiller-namespace string         Namespace of Tiller (default "kube-system")
```

In the above case, I think it gave the tiller version in the `kube-system` namespace, unless you have set a value for the environment variable `TILLER_NAMESPACE` , which you can see from the `$ helm --help` output

So, this is expected and not an issue. And if you want this to be a feature, it can't be accepted, as we aren't accepting any more new features for v2. And v3 has no concept of tiller, so no tiller namespace. Only namespace concept exists

**Comment by bacongobbler** [comment]
I believe long ago this was a supported feature, albeit not well used or documented.

@caalberts is there a version where this used to work? If you can provide:

- a version where this feature worked, and
- approximately when this feature stopped working for you

We can look into fixing this. PRs to fix regressions would also be accepted, should you be willing to work on this.

**Comment by caalberts** [comment]
@bacongobbler I have not seen this feature worked myself. I raised this issue because I came across https://github.com/helm/helm/issues/1396 and https://github.com/helm/helm/pull/2808 through https://github.com/helm/helm/issues/3911 

Looking at this the second time, it looks like I might have misinterpreted #2808, thinking that it implemented `--tiller-namespace`, but it actually implemented `--namespace`.

Considering #3911 is still open, I'm guessing that defaulting `--tiller-namespace` to kubectl namespace has not been implemented yet.

In this case, is #3911 still open for PR?

Sorry for the false bug report.

**Comment by TBBle** [comment]
I guess this is a duplicate of #3911, which needs a v2.x flag since in Helm v3, the equivalent of the Tiller namespace (where the release metadata is stored) is [the same as the release's target namespace](https://helm.sh/docs/faq/#release-names-are-now-scoped-to-the-namespace).

And v2.x is closed for features, per [Support Contract for Helm 2
](https://github.com/helm/helm/blob/master/CONTRIBUTING.md#support-contract-for-helm-2), feature dev is closed for Helm v2. That probably should be easier to find, it's not in the docs at all, unless you count the docs search box finding the Helm 2.15.0 release blog post.

**Comment by bacongobbler** [comment]
@TBBle #3911 is a slightly different issue than what @caalberts suggested. Helm 2 already has a feature flag for this: `--tiller-namespace`. @caalberts is just asking for a feature that once existed to work.

Is there someone from the community willing to fix this?

Keep in mind that our timeframe for fixing bugs for Helm 2 closes in a month. After that, Helm will only accept security issues, and this will be considered intentional behaviour.

If nobody is willing to put in the time to fix this, we should probably close this out.

**Comment by jeff-knurek** [comment]
I read through this issue with the plan to look into fixing it, but I don't see anything to indicate that this feature _(`tiller-namespace` defaulting to the kube context)_ ever existed.

The best I could find was that in Dec 2016, the feature to allow `tiller-namespace` was added: https://github.com/helm/helm/pull/1691 and since then it has defaulted to "kube-system" if not provided as an env var ( `TILLER_NAMESPACE`) or via the flag. Before that time the value was hardcoded to "kube-system". 

To me, this issue falls under a "feature" in v2.x, and should be therefor be closed.
