### ISSUE TITLE
`helm package` is stripping comments from `values.yaml`

### ISSUE THREAD

**Issue by technosophos** [helm/helm#6951]
In Helm 3.0.0 final, `helm package` appears to be stripping the comments out of the values file. This happens when the values file is parsed and then re-marshaled (since the Go YAML parser does not keep comments).

To reproduce:

```
$ helm create foo
$ helm package foo
$ helm inspect values ./foo
$ helm inspect values foo-0.1.0.tgz
```

**Comment by mattfarina** [comment]
This looks like it happened because you can now pass in `-f`, `--set`, `--set-string`, and `--set-file` on `helm package` so it needs to be able to merge values. This is a change from v2. To do the merge means stripping comments with the existing libraries.

I missed this feature change landing. This is a side effect of that.  #6142 is the PR that made the change.

**Comment by cdrage** [comment]
Ping @joelanford 

Any idea what set of code introduced this bug? I'm digging into helm code now (and slowly learning) so I could push a PR, but as of right now, I'm unsure where to start.

Thought I may ping you to see if you're already working on it or not! :+1:

**Comment by joelanford** [comment]
I could be wrong, but I don't _think_ anything in #6142 caused this change. The `-f`, `--set`, `--set-string`, and `--set-file` flags were already present on the `package` subcommand before #6142. That PR simply changed the SDK API such that the final merged values are passed in with the `Run` function rather than handled in an unexported field.

**Comment by cdrage** [comment]
Yeah, that's what I was getting confused at on the PR... I'll try to figure out what happened, but honestly, with Christmas coming up + my PTO, I wouldn't be able to work on it.

**Comment by bacongobbler** [comment]
In Helm 2, `helm package` didn't handle CLI flags like `-f`, `--set`, `--set-string` and `--set-file`. The values were loaded into memory twice (once as raw content, then as marshalled data), then saved as a tar/gzip archive using the raw file content:

https://github.com/helm/helm/blob/0ca95341c19fcaf9cecdf50caef1693568835a84/pkg/chartutil/save.go#L49-L55

In Helm 3, `SaveDir` reads `.Values` and writes it to the expected file type:

https://github.com/helm/helm/blob/e30cbbbaeeea08303e54a4e70d216e96647a4602/pkg/chartutil/save.go#L51-L58

This allows consumers of the SDK to modify values after the chart is loaded into memory. For example, in pseudo-code:

```
load chart as c
set c.Values["foo"] as "bar"
save chart as archive
```

Looking at the history, the `-f`, `--set`, `--set-string` and `--set-file` flags were introduced well before #5365. I'll try to dig in when we introduced those flags. If we can identify whether this was intentional or just a mistake, we can remove those flags in 3.1 as a bug and restore the old functionality by saving raw chart values.

**Comment by bacongobbler** [comment]
found the culprit... #3471. This PR sneaked its way into the Helm 3 branch after we forked from the Helm 2 development branch, and it was reverted as per https://github.com/helm/helm/pull/3471#issuecomment-381779783. I think it's safe to remove these flags as this was never intended to make its way into Helm 3.
