### ISSUE TITLE
[helm3] Outdated Releases Command

### ISSUE THREAD

**Issue by l0nax** [helm/helm#7014]
_This is a Feature Request on which I wanna work and I would maintain it also_

I'm the Maintainer of a Fork from a Plugin called `whatup`, the goal of this Plugin is to show the User which installed Charts are outdated and whats the newest Version.
With _hem v3_ Tiller has been removed, so this Plugin will not work anymore.

Since its a nice feature to have a list which shows which releases are outdated and what the newest Chart Version is it would be nice to have this Command _directly_ in Helm.

For example: `helm outdated` would print a List with all Outdated Releases.

Ref: fabmation-gmbh/helm-whatup#10
Ref: https://github.com/bacongobbler/helm-whatup/issues/23

There exists an active Pull-Request: #7021

**Comment by karuppiah7890** [comment]
Just my thoughts, irrespective of it being present in helm or not, this sounds really cool! Please go ahead and start working on the same helm plugin to add v3 support. It shouldn't be tough to integrate it later if needed

And I have seen many cool plugins. It always feels like - "this is so good and general, why not have it in helm? 🤔 ". In general, in software development, I think agreeing to add a feature comes with some cost (more maintenance, more venues for possible errors, possible increased complexity). I'm interested to know on what basis features are accepted in Helm 😄 I'm hoping to see what the core maintainers have to say about this

**Comment by bacongobbler** [comment]
A couple of things here:

- I am the original author of the plugin, and I am still actively maintaining it.
- This plugin will continue to work regardless of Tiller's presence or not. The code for release lookups relied on tiller, but it isn't required. The plugin path lookup code can be updated to work for Helm 3 as well.
- the plugin is licensed as MIT. You will require a sign-off from every author that has contributed to the plugin since its inception, as all Helm projects are apache 2 licensed.
- the proposal was originally raised at https://github.com/bacongobbler/helm-whatup/issues/21. The discussion is still ongoing.
- as the original author, the plugin and its design has serious design flaws, which is why I have advocated for it to NOT be a core project.

**Comment by bacongobbler** [comment]
> I'm interested to know on what basis features are accepted in Helm

A few cases for accepting plugins as core features has been:

- is it a command which is used in all cases, or is it a niche case?
- has the maintainer performed all of the legal due diligence required to contribute the code?
- is the codebase stable, or does it require a ton of maintenance to support?
- has the plugin demonstrated a high caliber of code quality, or is it a mishmash of bash scripts hacked together over a weekend?
- does it include tests?
- does it include documentation?

**Comment by bacongobbler** [comment]
As the original author, I can definitely say from that rubric:

1. definitely a niche case. Not everyone deploys from a remote chart repository.
1. see above
1. it will require many changes over time to support new cases from the community
1. it was written over a weekend. It does not include any tests.
1. no
1. a README with usage information doesn't count

**Comment by fcuello-fudo** [comment]
I'd also add a "7. is there an alternative way to do it?", and I couldn't find any.

Regarding 1., that can be addressed by making it more specify, for example, as a sub-command to `helm repo`

**Comment by karuppiah7890** [comment]
There is an alternative  @fcuello-fudo , it's the existing whatup plugin

**Comment by vdboor** [comment]
I'd love to see this in core helm! I was the one suggesting to @l0nax to persue this. I picked his fork because it seemed to have more maintenance.

A package manager needs to tell whether there are upgrades available. Imagine `apt` being unable to tell you that there is a security update? This is a first good step towards that.

Agreed that tests and docs are needed, but I still think this is a good first step to further get to a ready to merge state.

**Comment by micheelengronne** [comment]
I'd love to see it in core helm too. It is a first step to automate charts update with help when a new chart is pushed in a repository.

It would increase security as there is no manual operation needed anymore to keep a kube cluster up to date.

**Comment by karuppiah7890** [comment]
I agree to all the points. The feature is really good. I still don't see why it should be in core helm ? Why not be a plugin and still work ? Everything still works. All good. 

I do have some concerns about the discoverability of such good plugins, like the one mentioned here https://github.com/bacongobbler/helm-whatup/issues/21#issuecomment-550432715. Which can be solved differently - probably by providing a platform similar to Helm Hub but for Helm plugins

Also, I think we need more points and thoughts on the goals of Helm to take such decisions, along with the great points mentioned here https://github.com/helm/helm/issues/7014#issuecomment-555568414 and https://github.com/helm/helm/issues/7014#issuecomment-555572103 .

**Comment by bacongobbler** [comment]
> It would increase security as there is no manual operation needed anymore to keep a kube cluster up to date.

The plugin only informs you that there's an update available. It does not automatically update outdated charts. That's the role of `helm upgrade`. :)

**Comment by bacongobbler** [comment]
> Which can be solved differently - probably by providing a platform similar to Helm Hub but for Helm plugins

We have [discussed that topic before at Helm Summit NA](https://github.com/helm/helm-summit-notes/blob/master/helmplugins.md#curating-helm-plugins), though that was long ago and nobody followed up from there. It would require an overhaul of the existing plugin system, which we decided not to tackle for Helm 3 due to low demand.

**Comment by shibumi** [comment]
Is there any `outdated` command yet for helm? This is a key feature IMHO.

**Comment by l0nax** [comment]
You can currently use one of the two `outdated` plugins to have this feature until the proposal has been written:
* (bacongobbler) https://github.com/bacongobbler/helm-whatup
* (l0nax) https://github.com/fabmation-gmbh/helm-whatup

**Comment by shibumi** [comment]
@l0nax Ah, I see. The second one even works for me. I tried one of them 2 weeks ago and I got errors. Now the  installation worked! Thanks a lot.

**Comment by stevehipwell** [comment]
Is there an official reason why _Helm_ would not want a native `outdated` command? Being able to find upgrades is one of the, if not the most important, features of a [package manager](https://en.wikipedia.org/wiki/Package_manager#:~:text=A%20package%20manager%20or%20package,system%20in%20a%20consistent%20manner).

I'm aware of the various discussions over the years so I'm not asking why the [original](https://github.com/bacongobbler/helm-whatup) or [ current](https://github.com/fabmation-gmbh/helm-whatup) `whatup` command isn't part of core _Helm_. I'm asking if there is a technical or fundamental reason why this functionality, if implemented correctly, shouldn't be included?
