### ISSUE TITLE
internal/experimental should be moved to pkg/experimental

### ISSUE THREAD

**Issue by Sh4d1** [helm/helm#7079]
Hey! 

I think putting a package just because it's experimental in an internal package is a bit annoying. An `experimental` package name is quite enough to signal that it is indeed experimental. I think it will also just force the people that want to use it to either copy paste or fork Helm.

**Comment by mattfarina** [comment]
Some of this is about trade offs. [Helm follows semantic versioning](https://github.com/helm/helm/blob/master/CONTRIBUTING.md#semantic-versioning). That includes the `pkg` directory which is a library others can import.

The experimental work does not follow semantic versioning. The current experiment of OCI registries is taking a slow path to a stable API and design due to work happening within the OCI.

This leaves the Helm project with two routes:

1. Have the experimental package in the `pkg` directory where the API and design will break
2. Have the experimental package in the `internal` directory where others will need to copy it to use it

In both cases we will hear some complaints. Some would complain if we broke semver on the API. I've personally encountered complaints from people when changing the API at a major version change. This even follows semver but there are still complaints. The other side is situations like this where someone needs access to the code and wants it exposed.

In either case we will have some complaining or asking for it to be different.

Because Helm tends to take the conservative route (because we know people run it in production where they are conservative about change) and Helm follows semver we have chosen to have it in `internal` while it is still being formed.

I look forward to the day it is not longer an experiment and we can expose a stable API and feature set.

**Comment by Sh4d1** [comment]
Hmm okay fair enough :grin:  
Looking forward to this day as well then!
