### ISSUE TITLE
Helm3 does not do templating of CRDs

### ISSUE THREAD

**Issue by wpwoodjr** [helm/helm#7083]
As noted by @bacongobbler [here](https://kubernetes.slack.com/archives/C51E88VDG/p1571776404147600), CRDs are not templated in Helm3.  This is a breaking change from Helm2.  At Kubecon, I spoke to someone on the Helm team who acknowledged that this was intentional since often CRDs are implemented by an OPs team and not developers.  While I understand that rationale, it seems to me that CRD templating should be allowed in Helm3 as many charts rely on it.

**Comment by turkenh** [comment]
This is also a valid scenario for us, we want to add some labels to CRDs by templating or conditionally install/skip some of the CRDs based on values provided.

I personally think, templating is the most powerful feature of helm and I don't think introducing limitations for this is a good idea since everyone has different use cases.

**Comment by tamalsaha** [comment]
I would like to add that not allowing templatinf files inside crd folder makes it unusable for older version of Kubernetes. Since k8s 1.16 introduced structural schema, the CRD yaml file has fields like preservedUnknowfields etc that returns error in older version of k8s. Also, similar issue exists for K8s 1.11 (openshift 3.11) https://github.com/jetstack/cert-manager/issues/2200 .

**Comment by igorcezar** [comment]
Is there any work on this issue?
Would be great if CRDs were templated in Helm3. 

In [Velero chart](https://github.com/vmware-tanzu/helm-charts/) I would like to include an option to disable hooks on crds folder, but I can't because it's not templated so the condition (if/else) is not rendered.

**Comment by hickeyma** [comment]
I am unsure that this feature will be implemented. The reason for not using templating with CRDs is described in the [Helm CRD doc](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) as follows:

"
Another important point to consider in the discussion around CRD support is how the rendering of templates is handled. One of the distinct disadvantages of the `crd-install` method used in Helm 2 was the inability to properly validate charts due to changing API availability (a CRD is actually adding another available API to your Kubernetes cluster). If a chart installed a CRD, `helm` no longer had a valid set of API versions to work against. This is also the reason behind removing templating support from CRDs. With the new `crds` method of CRD installation, we now ensure that `helm` has completely valid information about the current state of the cluster.
"

**Comment by wpwoodjr** [comment]
I don't get this:
> This is also the reason behind removing templating support from CRDs. With the new crds method of CRD installation, we now ensure that helm has completely valid information about the current state of the cluster.

Why can't helm 3 do the templating initially when it deploys the files in the CRDs directory?  This is useful for metadata labels, for example.

**Comment by hickeyma** [comment]
@technosophos might be able to shed more insight on this.

**Comment by MartinGolding515** [comment]
I would also like to have templating support with the CRD folder. 
I want to deploy the CRD and CR within the same chart and I have go templates within the CRD to ensure consistent naming. Currently this is not possible:
1. Let helm do it. Templating does work within the CRD folder.
2. Put the CRD in a subchart. Helm gives an error that the CRD is not installed when it attempts to load the CR, even if post-install hook is set on the CR.
