### ISSUE TITLE
Windows support for Helm plugin installers

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#7117]
Helm's plugin install hook system relies on `/bin/sh`, regardless of the operating system present. Windows users can work around this by using Helm under WSL, but it would be great to have true Windows support out of the box.

Example use case as demonstrated in https://github.com/helm/helm-2to3/issues/55:

```
$ helm3 plugin install https://github.com/helm/helm-2to3 --debug
[debug] updating https://github.com/helm/helm-2to3
[debug] symlinking C:\Users\nlowe\AppData\Local\Temp\helm\plugins\https-github.com-helm-helm-2to3 to C:\Users\nlowe\AppData\Roaming\helm\plugins\helm-2to3
plugin_install.go:75: [debug] loading plugin from C:\Users\nlowe\AppData\Roaming\helm\plugins\helm-2to3
plugin.go:60: [debug] running install hook: &{sh [sh -c cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh] []  <nil> <nil> <nil> [] %!s(*syscall.SysProcAttr=<nil>) %!s(*os.Process=<nil>) <nil> <nil> %!s(*exec.Error=&{sh 0xc00008d5c0}) %!s(bool=false) [] [] [] [] %!s(chan error=<nil>) %!s(chan struct {}=<nil>)}
Error: exec: "sh": executable file not found in %PATH%
helm.go:81: [debug] exec: "sh": executable file not found in %PATH%
```

**Comment by bacongobbler** [comment]
ref: https://github.com/helm/helm/blob/22e00bebdf0cb247f4a4fe534026a352f228f450/cmd/helm/plugin.go#L56-L60

**Comment by thebjorn** [comment]
I'm almost completely new to helm, so this might be a stupid question..., but why is there a windows executable of helm (https://github.com/helm/helm/releases) if we can't use it?

I followed the steps listed at https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/ using cmd.com since that is my command line, and soon hit the error described above:
```
c:\srv\gitlab\datadog> helm3 2to3
Error: exec: "C:\\Users\\bjorn\\AppData\\Roaming\\helm\\plugins\\helm-2to3/bin/2to3": file does not exist
```
however, now, when trying to use wsl, I get:
```
bp@bjorn8:/mnt/c/srv/gitlab/datadog$ alias helm3=/mnt/c/bin/helm3.exe
bp@bjorn8:/mnt/c/srv/gitlab/datadog$ helm3 version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
bp@bjorn8:/mnt/c/srv/gitlab/datadog$ helm3 plugin install https://github.com/helm/helm-2to3
Error: plugin already exists
bp@bjorn8:/mnt/c/srv/gitlab/datadog$ helm3 plugin list
NAME    VERSION DESCRIPTION
2to3    0.2.2   migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
bp@bjorn8:/mnt/c/srv/gitlab/datadog$ helm3 2to3
Error: exec: "C:\\Users\\bjorn\\AppData\\Roaming\\helm\\plugins\\helm-2to3/bin/2to3": file does not exist
bp@bjorn8:/mnt/c/srv/gitlab/datadog$
```
Is this salvageable?  Could three be a note in the docs (at https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/) warning windows users to not try this procedure in any of the windows shells?

**Comment by marckhouzam** [comment]
@thebjorn I assume you installed the 2to3 plugin outside of WSL.  That's probably causing the errors due to the forward slashes in the path used in your example.

If you install the plugin from WSL it should work.  This issue has good info on your problem: https://github.com/helm/helm-2to3/issues/55

**Comment by thebjorn** [comment]
@marckhouzam Thanks for the info, I'm sure that will work (although I opted to just stay with helm 2 for now).  Your answer seems to indicate that I'll need a parallel helm installation in WSL and that it will not be interchangeable with the one installed from cmd.exe - have I understood that correctly?  If I have then I would urge you to update the docs!

**Comment by hickeyma** [comment]
@thebjorn I agree with you, thanks for raising. This need better clarification for users. I have opened the following issue for it: https://github.com/helm/helm-2to3/issues/114

**Comment by TBBle** [comment]
This seems hard to fix without requiring installation of some Bourne shell on Windows, e.g. bash from MSYS2 or Git For Windows.

Particularly because the plugins contain the shell script, so would each need extra work to support a CMD batch file or PowerShell script.

That said, if plugin authors are willing to maintain parallel install scripts for Bourne shell and PowerShell, then it should be relatively easy to fix on the Helm side.

**Comment by TBBle** [comment]
A [search on GitHub](https://github.com/search?q=%24HELM_PLUGIN_DIR+filename%3Aplugin.yaml+language%3AYAML&type=Code&ref=advsearch&l=&l=YAML) suggests we have over 300 Helm plugins that reference `$HELM_PLUGIN_DIR`. It's possible that somehow most of these are not using an install hook, but certainly a lot of them are, from a brief glance, I saw 3 out of the first 50 that used `platformCommand` instead of `command`, and did not have any hooks.

The only way I can see forward here would be to have `platformHooks` like `platformCommand`, and make that just `exec` everywhere, rather than implicitly `sh -c`; and deprecate the current `hooks`. That would also make the code more internally-consistent, e.g., we can share behaviour with `PrepareCommand`.

The cost is that plugins need to take an action to become compatible with this, and we also cannot use `hooks` as a platform-agnostic fallback as we can for `command`, because the implicit `sh -c` cannot be assumed to work on Windows.

**Comment by jkroepke** [comment]
`platformHooks` would be great!

**Comment by TBBle** [comment]
This remains a reasonable important feature to implement, but it looks like no one (including me) has had the time/priority to advance it.

**Comment by karuppiah7890** [comment]
I have seen quite some people talk about issues with true support for Windows and that needing bash / sh for installing helm plugins is a bit annoying

**Comment by TBBle** [comment]
This remains a reasonable important feature to implement, but it looks like no one (including me) has had the time/priority to advance it.

**Comment by jkroepke** [comment]
Looks like the helm maintainer are under powered in general. There are a lot of opened topic but the maintainers did not have the time for it.

**Comment by bacongobbler** [comment]
Generally speaking the maintainers have their hands full reviewing code. There are over 100 PRs in the queue. We really don’t have time to write new features ourselves.

**Comment by TBBle** [comment]
This remains a reasonable important feature to implement, but it looks like no one (including me) has had the time/priority to advance it.

**Comment by dimabru** [comment]
I'd like to tackle this issue and try to implement it. We need to be able to run our plugin on windows so might as well solve this for everyone :)

@marckhouzam What do you suggest a good solution would be?
 
As I see it, there are two ways of dealing with it. Either supporting powershell script for windows plugin installations with `platformHooks` or using hybrid script as suggested by @jkroepke

**Comment by dimabru** [comment]
update: I'm adding `platformHooks` support with very similar functionality to `platformCommand`. 
Any help with documentation will be much appreciated :)

**Comment by eyarz** [comment]
Any update on this issue? It looks like @dimabru submitted a PR (#10126) but I don't see it's getting any attention from the maintainers :/

**Comment by mindw** [comment]
> This remains a reasonable important feature to implement, but it looks like no one (including me) has had the time/priority to advance it.

**Comment by TBBle** [comment]
Nope, still a thing we need to do at some point.

**Comment by srilumpa** [comment]
Still a feature that would be useful to have

**Comment by mblaschke** [comment]
bump

**Comment by mindw** [comment]
A lot of people still use helm on windows 😉

**Comment by stevehipwell** [comment]
@TBBle could doing something like below work with less complexity than the other solutions and offload shell selection to the plugin developers and/or OS?

```yaml
platformHooks:
  install:
    - os: linux
      command: ["sh", "-c", "$HELM_PLUGIN_DIR/scripts/install.sh"]
    - os: windows
      command: ["pwsh", "-c", "$HELM_PLUGIN_DIR/scripts/install.ps1"]
```

The commands would then be run by `prog = exec.Command(hook.Command)`. For hook selection `arch` would be supported like `platformCommand`. If a script was being run and you wanted to use the default shell (more likely on Windows) you could just provide the script to the command. It would also be valid to not provide `os` to get the same behaviour as the legacy `hooks`. The legacy `hooks` would be deprecated and only run in the absence of `platformHooks`.

If this design (or something like it) looks good and there is enough bandwidth to review the PR I'd be happy to have a go at it as I don't think it adds much complexity.

**Comment by jkroepke** [comment]
> and there is enough bandwidth to review the PR

Take a look at https://github.com/helm/helm/pull/10126, it may answers your question.

**Comment by stevehipwell** [comment]
@jkroepke the PR author never replied to @TBBle so I'd categorise that as an abandoned PR and not a lack of maintainer input.

**Comment by TBBle** [comment]
@stevehipwell Yeah, that was my preferred solution.

It looks like both what I thought https://github.com/helm/helm/issues/7117#issuecomment-657342139 would look like:

> The only way I can see forward here would be to have `platformHooks` like `platformCommand`, and make that just `exec` everywhere, rather than implicitly `sh -c`; and deprecate the current `hooks`. That would also make the code more internally-consistent, e.g., we can share behaviour with `PrepareCommand`.

and what I was thinking in https://github.com/helm/helm/pull/10126#issuecomment-927295879:

> Basically, I was mirroring the behaviour of `platformCommand`, and that [does not prepend a shell in the command](https://github.com/helm/helm/blob/9fafb4ad6811afb017cc464b630be2ff8390ac63/cmd/helm/load_plugins.go#L124-L132). I think having `platformHooks` act differently to `platformCommand` in this regard would be a surprising mistake.

I'm in-general not a fan of implicit shell-calls in "exec" systems; this includes things like the `RUN` command in a Dockerfile and the use of the Python's `subprocess` module too; both provide a way to not invoke an implicit shell, and this seems like an opportunity for us to remove it from Helm while introducing a new API.

I also liked the idea (although I didn't actually try to implement this) of sharing more code with the `platformCommand` implementation.

But that of course is just my opinion, for as much or as little as it's worth.

**Comment by stevehipwell** [comment]
@TBBle does it matter that although closely aligned to `platformCommand` my proposal here uses an array instead of a string for `command`? I think this is a better API than a single string.

It's been a while but I think the YAML package used by Helm can support an array value mapped as a single string so potentially we could support both patterns?

**Comment by TBBle** [comment]
Oh, I missed that difference. I personally prefer it as an array. I recognise not everyone loves the ergonomics of that, i.e. people still write `RUN <string>` in Dockerfile when `RUN ['args'...]` is _right there_. ^_^

Obviously the most flexible is if we have have _both_ do both, as long as that's not maximising surprise for users, e.g., Dockerfile's `RUN <string>` implies a shell but ours doesn't; or making the code needlessly painful, e.g., the YAML package used in Helm can't distinguish the two forms.

This is used by plugin authors, rather than all Helm users, so some complexity to gain features is reasonable. On the other hand, just having the array format is also probably not unworkable for the target audience, no one's going to be writing dozens of these every week.

**Comment by stevehipwell** [comment]
I'm not sure if the abstraction on top of go-yaml in sigs.k8s.io/yaml limits the ability to use a custom marshalling solution to solve the multi-type issue. But IMHO this is more of a nice to have than an essential feature.

**Comment by bakito** [comment]
> `platformHooks` would be great!
> 
> I also look into hybrid script. Hybrid scripts are runnable inside cmd and bash. They could be use as bootstraper to call the right script on the right platform.
> 
> See: https://stackoverflow.com/questions/17510688/single-script-to-run-in-both-windows-batch-and-linux-bash

I got a working solution for my plugin by creating a hybrid hook script as mentioned in the stackoverflow link above which works fine for me.

```bash
:; if [ -z 0 ]; then
  @echo off
  goto :WINDOWS
fi

# ***********************************************************
# * This script is runnable on windows with cmd and linux with bash
# * cmd will ignore lines that start with :;
# * See https://stackoverflow.com/questions/17510688/single-script-to-run-in-both-windows-batch-and-linux-bash
# * and https://github.com/helm/helm/issues/7117
# *
# * The script must have LF line separator and must have extension *.cmd
# * git update-index --chmod=+x bin/install-tools-hook.sh.cmd
# ***********************************************************

# bash stuff
echo "Installing for Linux"
${HELM_PLUGIN_DIR}/bin/install-tools.sh
exit

:WINDOWS
:: windows stuff
echo Installing for Windows
%HELM_PLUGIN_DIR%\bin\install-tools.cmd

```

This script the executes the windows/linux specific install-tools.xxx script to install the required tools.

**Comment by mindw** [comment]
People still insist on using helm on windows.

**Comment by Hollerweger** [comment]
Here a manual way to get plugins working which are just copying a binary in the helm plugin folder.

Example for helm-images plugin:

1. Execute `helm plugin install https://github.com/nikhilsbhat/helm-images` which will fail
a. This step will only checkout the repo in your helm plugin directory which is still needed for the plugin.yaml (maybe just copying the plugin.yaml manually is also enough)
3. Then go to the Plugin Release page and download the required Windows binary. 
a. E.g.: https://github.com/nikhilsbhat/helm-images/releases
b. If the plugin is not released on github then maybe check the install scripts where it fetches the release from.
5. Create a bin folder in your helm-images plugin directory and extract the downloaded binary to it
a. For me it was under  _~\AppData\Roaming\helm\plugins\helm-images\bin_
6. Fix the plugin command configured in helm\plugins\helm-images\plugin.yaml
a. Ajust the command to: `command: "$HELM_PLUGIN_DIR\\bin\\helm-images.exe"`
7. Plugin should work now:
```
PS C:\LocalData\test> helm images
  images [command] [flags]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  get         Fetches all images those are part of specified chart/release
  help        Help about any command
  version     Command to fetch the version of helm-images installed
```

**Comment by mindw** [comment]
And yet, people still insist on using helm on windows.

**Comment by mindw** [comment]
/bot Windows is a supported platform by Helm still.

**Comment by stevehipwell** [comment]
Sorry, I need to add the docs PR to go with #12962.

**Comment by suehshtri** [comment]
I came here from https://github.com/databus23/helm-diff/issues/316

**Comment by stevehipwell** [comment]
I've added https://github.com/helm/helm-www/pull/1627 to update the docs.

FYI the plugins need to be reworked to use this new code as they will need to use the `platformHooks` field. As an example I [forked](https://github.com/stevehipwell/helm-diff) and [modified](https://github.com/databus23/helm-diff/commit/c1c67c13dc985528e6f7ee41e72407d768db0f64) the Helm Diff plugin to work with this pattern.

**Comment by yxxhero** [comment]
@stevehipwell did the 3.16.4 support this feature?

**Comment by stevehipwell** [comment]
@yxxhero it's currently only been merged to `main` which is tracking v4 changes. I need to open a PR to take the changes to the `dev-v3` branch to get it released before v4.

**Comment by stevehipwell** [comment]
REF: https://github.com/helm/helm/pull/13592
