### ISSUE TITLE
helm template command does not add a newline when used with range

### ISSUE THREAD

**Issue by PankajWorks** [helm/helm#7149]
Output of `helm version`: `Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}`

Output of `kubectl version`:` Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:43:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

consider the following piece of code
```yaml
---
{{- range $service := (list "frontend" "matching" "history" "worker") }}
{{- $serviceValues := index $.Values.server $service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadence.componentname" (list $ (printf "%s-headless" $service)) }}
  namespace: {{ $.Release.Namespace }}
  labels:
........
..........
---
{{- end}}
```
running helm template produces
```yaml
---apiVersion: v1
kind: Service
........
```
because of `---apiVersion: v1 ` the kubectl command fails

**Comment by bacongobbler** [comment]
This appears at first glance to be intentional. When you add a hyphen to the block quotes (i.e. `{{-` on line 2), text/template strips all preceding whitespace before that block quote. My suggestion would be to play around with the hyphens from the first few block quotes to prevent all whitespace from being removed:

```
---
{{- range $service := (list "frontend" "matching" "history" "worker") }}
{{- $serviceValues := index $.Values.server $service }}
apiVersion: v1
```

See https://golang.org/pkg/text/template/ for more information on how the block quote syntax works, and https://github.com/helm/charts/blob/e6f6df78eb86d8593f0567f75500326a7753cf98/stable/metricbeat/templates/secret.yaml#L15-L16 for an example.

**Comment by hickeyma** [comment]
@PankajWorks Did you get a chance to look at suggestion from @bacongobbler in https://github.com/helm/helm/issues/7149#issuecomment-562673835?

**Comment by Novitoll** [comment]
@PankajWorks , you can add `{{printf "\n" }}` since it;s GoLang:

```
---
{{- range $service := (list "frontend" "matching" "history" "worker") }}
{{- $serviceValues := index $.Values.server $service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadence.componentname" (list $ (printf "%s-headless" $service)) }}
  namespace: {{ $.Release.Namespace }}
  labels:
........
..........
{{ printf "\n" }}
---
{{- end}}
```

**Comment by mattfarina** [comment]
I can explain this one...

```
---
{{- range $service := (list "frontend" "matching" "history" "worker") }}
{{- $serviceValues := index $.Values.server $service -}}
apiVersion: v1
```

A `-` next to a `{{` or `}}` removes all whitespace outside between it and the next non-whitespace character. New lines are considered whitespace. So...

`{{-` next to range on line 2 removes all white spaces between it and the `---`. `{{-` next to `$serviceValues` on line 3 removes all white space up the `}}` on the previous line. Since the previous line block has no output the space is all stripped up to `---`.

The `-}}` on the line prior to `apiVersion: v1` strips all white space up to that. So much white space stripping leaves it at `---apiVersion: v1`.

This is working as expected.

**Comment by bacongobbler** [comment]
Thanks @mattfarina!

I haven't heard back from the OP after explaining the situation back in 2019, so I think this is safe to close.

**Comment by heedlesscomet** [comment]
@novitoll https://pythoner.space/questions/insert-content-to-the-center-of-a-document-according-to-a-specific-array
