### ISSUE TITLE
An image referencing convention

### ISSUE THREAD

**Issue by jhvhs** [helm/helm#7154]
We, as well as other members of the community, are facing the following issues: 
1. It is difficult or even impossible to automatically extract all the image references from a given helm chart. This is important for security, scanning and license checking purposes.
2. It is difficult for the end user to easily install an existing helm chart using images that have been re-located to a private registry. There is a large number of users who must run their workloads behind a firewall.
3. The problems above escalate with the use of sub-charts.

See below conversations within the community for more context:
- https://kubernetes.slack.com/archives/C0NH30761/p1559589151166400
- https://kubernetes.slack.com/archives/C0NH30761/p1571850216043700
- https://kubernetes.slack.com/archives/C0NH30761/p1571156640168300

## Short term solution
Since helm 3 has just gotten out, we shouldn't be pushing for a major structural change,
so our short-term proposal is to introduce a convention for referencing images via the `values.yaml`.
To simplify the problem with re-location, it would be nice if the helm charts adopted a convention for enabling the end user to set the registry and other default image settings in the `global` section. For example:
```
global:
  imageRegistry: my.registry.internal
  imageNamespace: project-xyz
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
```
where the image namespace is the part of the image path between the registry hostname and the image name, e.g. a docker user id on dockerhub.

In addition to that, the end user should be able to override the global setting on a chart or the image level by either setting the registry and namespace setting on a chart or even the image level. They should also be able to skip the defined overrides on both levels, which becomes tricky, as the templating engine is unable to restore the value was overwritten by the end user. In order to overcome the issue, we propose that the chart authors define the registry and the namespace using the `originalRegistry` and `originalNamespace` properties on the image itself, or the `originalImageRegistry` and `originalImageNamespace` properties on the chart itself.
The user will then be able to revert to the original values for certain images or even entire charts by setting the `useOriginalRegistry`/`useOriginalNamespace` boolean properties to `true` on the image or the whole chart.

This functionality can then be utilised when defining the images to be used in the chart. Unfortunately, the current template for `values.yaml` assumes that there is a one-to-one correspondence between the chart and an image, which is often not true (see https://hub.helm.sh/charts/choerodon/istio, https://hub.helm.sh/charts/aerospike/aerospike, https://hub.helm.sh/charts/bitnami/postgresql). It would be nicer if, instead of the `image` section, the `values.yaml` would have had an `images` section, that could be easily referred to in the templates, for example:
```
originalImageNamespace: bitnami
images:
  postgresql:
    name: "postgresql"
    tag: "11.3.0-debian-9-r38"
    digest: "sha256:0641cf60734a9cfa30e8b6debebd716bf69498aa68ed4efcfb7912e45c18766c"
  volumePermissions:
    name: "minideb"
    tag: "latest"
    pullPolicy: "Always"
  metrics:
    name: "postgres_exporter"
    tag: "v0.4.7"
    digest: "sha256:dd8051322ceb8995d3d7f116041a2116815e01e88232a90f635ebde8dcc4d3f4"
    pullPolicy: "IfNotPresent"
```
See the [design document](https://docs.google.com/document/d/1zsuq_iOWCrwA2tnB0Ka0E4ewyr5cZIoHXLD6W24O2gE/edit?usp=sharing) for more examples and data flows.

With this structure in place, it would be easy to reference the images in the templates using the following template helpers:
```
{{/*
Create a registry image reference for use in a spec.
Includes the 'image' and 'imagePullPolicy' keys.
*/}}
{{- define "<CHARTNAME>.registryImage" -}}
image: {{ include "<CHARTNAME>.imageReference" . }}
{{- $pullPolicy := include "<CHARTNAME>.imagePullPolicy" . -}}
{{- if $pullPolicy }}
{{ $pullPolicy }}
{{- end -}}
{{- end -}}

{{/*
The most complete image reference, including the
registry address, repository, tag and digest when available.
*/}}
{{- define "<CHARTNAME>.imageReference" -}}
{{ include "<CHARTNAME>.imagePath" . }}
{{- if .image.tag -}}
{{- printf ":%s" .image.tag -}}
{{- end -}}
{{- if .image.digest -}}
{{- printf "@%s" .image.digest -}}
{{- end -}}
{{- end -}}

{{- define "<CHARTNAME>.imagePath" -}}
{{- $registry := include "<CHARTNAME>.imageRegistry" . -}}
{{- $namespace := include "<CHARTNAME>.imageNamespace" . -}}
{{- printf "%s/%s/%s" $registry $namespace .image.name -}}
{{- end -}}

{{- define "<CHARTNAME>.imageRegistry" -}}
{{- if or (and .image.useOriginalRegistry (empty .image.registry)) (and .values.useOriginalRegistry (empty .values.imageRegistry)) -}}
{{- include "<CHARTNAME>.originalImageRegistry" . -}}
{{- else -}}
{{- include "<CHARTNAME>.customImageRegistry" . -}}
{{- end -}}
{{- end -}}

{{- define "<CHARTNAME>.originalImageRegistry" -}}
{{- printf (coalesce .image.originalRegistry .values.originalImageRegistry "docker.io") -}}
{{- end -}}

{{- define "<CHARTNAME>.customImageRegistry" -}}
{{- printf (coalesce .image.registry .values.imageRegistry .values.global.imageRegistry (include "<CHARTNAME>.originalImageRegistry" .)) -}}
{{- end -}}

{{- define "<CHARTNAME>.imageNamespace" -}}
{{- if or (and .image.useOriginalNamespace (empty .image.namespace)) (and .values.useOriginalNamespace (empty .values.imageNamespace)) -}}
{{- include "<CHARTNAME>.originalImageNamespace" . -}}
{{- else -}}
{{- include "<CHARTNAME>.customImageNamespace" . -}}
{{- end -}}
{{- end -}}

{{- define "<CHARTNAME>.originalImageNamespace" -}}
{{- printf (coalesce .image.originalNamespace .values.originalImageNamespace "library") -}}
{{- end -}}

{{- define "<CHARTNAME>.customImageNamespace" -}}
{{- printf (coalesce .image.namespace .values.imageNamespace .values.global.imageNamespace (include "<CHARTNAME>.originalImageNamespace" .)) -}}
{{- end -}}

{{/*
Specify the image pull policy
*/}}
{{- define "<CHARTNAME>.imagePullPolicy" -}}
{{- $policy := coalesce .image.pullPolicy .values.imagePullPolicy .values.global.imagePullPolicy -}}
{{- if $policy -}}
imagePullPolicy: "{{- $policy -}}"
{{- end -}}
{{- end -}}

{{/*
Use the image pull secrets. All of the specified secrets will be used
*/}}
{{- define "<CHARTNAME>.imagePullSecrets" -}}
{{- $secrets := .Values.global.imagePullSecrets -}}
{{- range $_, $chartSecret := .Values.imagePullSecrets -}}
{{- if $secrets -}}
{{- $secrets = append $secrets $chartSecret -}}
{{- else -}}
{{- $secrets = list $chartSecret -}}
{{- end -}}
{{- end -}}
{{- range $_, $image := .Values.images -}}
{{- range $_, $s := $image.pullSecrets -}}
{{- if $secrets -}}
{{- $secrets = append $secrets $s -}}
{{- else -}}
{{- $secrets = list $s -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- if $secrets }}
imagePullSecrets:
{{- range $secrets }}
- name: {{ . }}
{{- end }}
{{- end -}}
{{- end -}}
```

We propose to include the above changes into the default templates used by the chart generator and to publicise them in the [best practices](https://helm.sh/docs/topics/chart_best_practices/) section of the documentation.

An example of using the image references would look like the following:
```
...  
      {{- include "<CHARTNAME>.imagePullSecrets" . | indent 6 }}
      containers:
        - name: metrics
          {{- include "<CHARTNAME>.registryImage" (dict "image" .Values.images.metrics "values" .Values) | nindent 10 }}
        {{- if .Values.metrics.securityContext.enabled }}
...
```

## Long term solution
The long term solution would be to move the image defaults and the image list into the chart definition, `Chart.yaml`, and make an `.Images` accessor available in the templates that would remove the necessity in the template helpers referenced above.

**Comment by jhvhs** [comment]
The proposal has been updated with changes resulting from the collaboration with other helm chart authors.

**Comment by carrodher** [comment]
Hello everyone, I am Carlos from Bitnami.

We were added to the loop because the POC was done in the PostgreSQL chart that is maintained by Bitnami. See associated PR: https://github.com/helm/charts/pull/20241.

After several interactions and study the proposed solution, we agreed on this decision and we are happy to implement this convention in all the Bitnami charts. Although we are moving to a distributed model to create and host the charts, I think it is very important to maintain the same conventions and best practices shared with the whole community so before taking a step forward it would be nice to hear the opinion of the Helm maintainers.

What do you think about this proposal? @mattfarina @prydonius @unguiculus @scottrigby

**Comment by mattfarina** [comment]
If I understand this right there are two slightly different problems being described here.

1. The ability to reference images in different repositories
2. Being able to get all the images out of a chart to use in other things like security scanning

What follows are some stream of thought notes rather than an action or outcome.

First, Helm does not control the way people create and use `values.yaml` files. This has enabled a certain amount of creativity. For example, people are now putting application configuration and more business logic into charts that are passed on to the application. They creates a better experience for chart consumers.

This means that even if some or many people pickup a pattern of handling images not everyone will. That creates problems when extracting images from charts.

Another way to extract images is to render the chart (using something like `helm template`) and pulling the images from there because there is a structured known format. But, depending on the configuration of the chart the images installed may be different. Again, this creates a limiting situation.

This is a problem for general scanners but not a problem for scanners trying to scan charts at a version with a specific configuration as the images there can be figured out.

Again, this is stream of thought...

To look at the input problem... we already recommend things in the format..

```
image:
  repository: aerospike/aerospike-server
  tag: 4.5.0.5
  pullPolicy: IfNotPresent
```

This is similar to the above. Dealing with digests is the difference and it would be useful to start having a pattern that can incorporate those.

Digests do present a problem though. The digest for an image in one repository may be different from a digest for the exact same image in a different repository. Copy and image at a version from Docker Hub to Quay for an example. A digest is good for an image at a location and not everywhere the image resides. Yet, tags are mutable.

> The long term solution would be to move the image defaults and the image list into the chart definition, Chart.yaml, and make an .Images accessor available in the templates that would remove the necessity in the template helpers referenced above.

Helm enables backward compatible feature additions. This may be a route. I'm not sold on the idea but could be. Though, other maintainers would need to be sold as well. Might I suggest two things...

1. Write up a feature request just for this designed with backwards compatibility in mind and outline the use case
2. Once this is shared some to the Helm Developer Call and pitch it to the core maintainers

**Comment by jhvhs** [comment]
Thank you @mattfarina for taking the time to review the proposal

> If I understand this right there are two slightly different problems being described here.
> 1. The ability to reference images in different repositories
> 2. Being able to get all the images out of a chart to use in other things like security scanning

There's also a matter of including more than one image. Currently, about half of the charts in helm/charts use more than one image. About a third of those multi-image charts hard-code image references simply because it’s the easiest thing to do. And in half of those hard-coding cases, all but one image are hard-coded. It feels as if the single image key in the template is almost encouraging the authors to hard-code the rest of the images.

> This is a problem for general scanners but not a problem for scanners trying to scan charts at a version with a specific configuration as the images there can be figured out.

This is a problem for both software vendors and end-users:
- When distributing a helm chart, the distributor should be able to tell what is going inside, and scan all the relevant images and/or move them between different registries;
- The end users, on the other hand should be able to scan all the images, rather than a specific subset, in order to approve a chart for use within the organisation, as well as being able to push the images to a local registry.

> To look at the input problem... we already recommend things in the format..
> 
> ```
> image:
>   repository: aerospike/aerospike-server
>   tag: 4.5.0.5
>   pullPolicy: IfNotPresent
> ```
> 
> This is similar to the above. Dealing with digests is the difference and it would be useful to start having a pattern that can incorporate those.

This proposal creates a much more flexible structure via the template helpers, that would allow the end-user to selectively relocate images from the chart and its sub-chart to a different registry, or a different project within the same registry, with barely any toil on the part of the chart author. This requires breaking out `repository` into the following components: `registry`, `namespace` and `name`. Take a look at the [feature design document](https://docs.google.com/document/d/1zsuq_iOWCrwA2tnB0Ka0E4ewyr5cZIoHXLD6W24O2gE/edit?usp=sharing) to see how that could be used both by the authors and the end users.

> Digests do present a problem though. The digest for an image in one repository may be different from a digest for the exact same image in a different repository. Copy and image at a version from Docker Hub to Quay for an example. A digest is good for an image at a location and not everywhere the image resides. Yet, tags are mutable.

I completely agree, automatically pinning a docker image to a specific version across multiple registries is virtually impossible, which is why both the tag and the digest should be factored in as options, delegating the control to the end user, who can always either overwrite or reset the digest.

> > The long term solution would be to move the image defaults and the image list into the chart definition, Chart.yaml, and make an .Images accessor available in the templates that would remove the necessity in the template helpers referenced above.
> 
> Helm enables backward compatible feature additions. This may be a route. I'm not sold on the idea but could be. Though, other maintainers would need to be sold as well. Might I suggest two things...
> 
> 1. Write up a feature request just for this designed with backwards compatibility in mind and outline the use case
> 2. Once this is shared some to the Helm Developer Call and pitch it to the core maintainers

Thank you so much for the suggestion, I will definitely go ahead and do this. So far it looks like the end-user interface shouldn't change between the current implementation, and the one I'm planning to propose.

**Comment by thomas-melville** [comment]
Hi all,

If the details about the images are present in the values file will that cause issues when doing an upgrade with the --reuse-values flag.
I think the values from the original chart will be used instead of the values in the new chart, so the new versions of the images won't be applied to the Pods in the cluster.
When I get a chance I can do a test to verify

**Comment by jhvhs** [comment]
> If the details about the images are present in the values file will that cause issues when doing an upgrade with the --reuse-values flag.
@thomas-melville Isn't that the case for any image definitions right now (apart from the hard-coded ones)?

**Comment by thomas-melville** [comment]
@jhvhs,

Yes, I think it's the case.

**Comment by jhvhs** [comment]
See https://github.com/helm/helm/issues/7754 for a long-term proposal.

**Comment by bridgetkromhout** [comment]
As the more recent discussions are in https://github.com/helm/helm/issues/7754 and this is being marked inactive per our stale issues bot, I'll resolve this one in favor of https://github.com/helm/helm/issues/7754 and ongoing HIP work.
