### ISSUE TITLE
Update the labels used in Helm in order to organize the many issues submitted

### ISSUE THREAD

**Issue by cdrage** [helm/helm#7180]
Output of `helm version`: N/A
Output of `kubectl version`: N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

There are issues which are seldom used in this project  as well as a few which are either way too weighted (question/support) or no longer used due to no longer using the k8s bot / CI / etc.

### Statistics:

| Label | Number |    
| ----  | -----   |    
| question/support | 417 open issues and pull requests |    
| feature | 225 open issues and pull requests |    
| bug | 151 open issues and pull requests |    
| v3.x | 100 open issues and pull requests |    
| proposal | 70 open issues and pull requests |    
| docs | 40 open issues and pull requests |    
| help wanted | 22 open issues and pull requests |    
| size/XS | 18 open issues and pull requests |    
| size/S | 18 open issues and pull requests |    
| v2.x | 16 open issues and pull requests |    
| unconfirmed | 16 open issues and pull requests |    
| size/L | 15 open issues and pull requests |    
| good first issue | 15 open issues and pull requests |    
| refactor | 13 open issues and pull requests |    
| size/M | 11 open issues and pull requests |    
| area/helm-test | 8 open issues and pull requests |    
| awaiting review | 5 open issues and pull requests |    
| wip | 3 open issues and pull requests |    
| plugin | 2 open issues and pull requests |    
| size/XXL | 1 open issue or pull request |    
| size/XL | 1 open issue or pull request |    
| needs-rebase | 1 open issue or pull request |    
| blocked | 1 open issue or pull request |    
    
Unused labels:    
- ¯\_(ツ)_/¯    
- wont fix    
- v3 port complete    
- release note required    
- picked    
- Needs v3 fix    
- needs-pick    
- lgtm    
- keep open    
- in progress    
- cncf-cla: yes    
- cncf-cla: no    
- breaking    
- approved    

### My suggestion changes:

Implement a more [sane GitHub label structure](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63)

I suggest the following:

* Implement changes to how we set certain PR's / issue statuses:

![image](https://user-images.githubusercontent.com/6422176/70354329-3f29d800-183d-11ea-8302-ba706c8787a5.png)

* Add a handy label (and minimal) type label structure.

![image](https://user-images.githubusercontent.com/6422176/70354343-494bd680-183d-11ea-8668-c06f2fad51a4.png)

Including adding the following additional labels: `Type: Feature` and `Type: Support`

* Set priorities.

![image](https://user-images.githubusercontent.com/6422176/70354444-84e6a080-183d-11ea-87a0-44537f1aecf1.png)

### Removal of old labels / unused labels

Removal of any labels which are either part of the k8s CI / org (there's a few such as the CLA) or seldom used. Here are the following unused labels:

Unused labels:    
- ¯\_(ツ)_/¯    
- wont fix    
- v3 port complete    
- release note required    
- picked    
- Needs v3 fix    
- needs-pick    
- lgtm    
- keep open    
- in progress    
- cncf-cla: yes    
- cncf-cla: no    
- breaking    
- approved    

### Restructure of the question/support label

I suggest that the following be done to "restructure" the question/support label.

There are **over 400** issues (half of all issues submitted!) which are support only.

Direct users to use StackOverflow, Slack or https://helm.sh/docs

This is similar to how Kubernetes directs all support questions: https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/ISSUE_TEMPLATE/support.md

**Comment by bacongobbler** [comment]
Hi @cdrage. Thanks for providing your thoughts on this topic.

I had a few comments/questions about your proposal.

In general, what is the intended goal for these proposed changes? It would be helpful to clarify the intent behind this proposal so we can better understand its intent.

> as well as a few which are either way too weighted (question/support)

I don't necessarily perceive this to be an issue. Having a large chunk of the issue queue as support questions seems par for the course, and many of these support questions are eventually answered by the community over time as use cases evolve and users understand the tool. As long as we're consolidating duplicate questions and moderating the discussion, conversations are free to carry on until an answer or a solution is reached.

IMO the more important goal as maintainers is to keep the number of open bug reports to a minimum.

> Direct users to use StackOverflow, Slack or https://helm.sh/docs

Similar to the previous answer, I'm not sure how this will help keep the traffic down. We're just redirecting the user elsewhere, increasing traffic in those support channels. In many cases, support questions have transformed into actionable ticket items, and as a core maintainer, I'd rather avoid having to monitor another page just to track those discussions. https://github.com/helm/helm/issues/7082 is a recent example of a ticket where a support question evolved into a feature request. Keeping support questions and feature requests allows these conversations to evolve over time.

> Implement changes to how we set certain PR's / issue statuses:
> Set priorities.

Many of the proposed labels here involve an increased workload on the core maintainer's end as part of the PR review process. Why do we need to change this? What is the end benefit for the maintainers?

On priority labels: we haven't really found much utility with them in the past. Github milestones has worked quite well for tracking issues/PRs in progress, and provides the community a sense of what's being prioritized. The core maintainers have based the level of priority on certain tickets based on how involved the community is engaged with a particular topic, as well as the labels attached to it. For example, an issue with the `bug` label implies higher priority than an issue labeled `question/support`.

> Including adding the following additional labels: Type: Feature and Type: Support

The `feature` and `question/support` labels are used for those purposes. I'm not sure what would be the difference between a `Type: Enhancement` and a `Type: Feature` in this context.

Support issues can also be labeled as general questions, which is why they were consolidated in the first place.

> Unused labels:

Please ensure you're also checking closed issues as well as open issues in your search filters -- a lot of these labels are still actively used. Some labels like the `cncf-cla: yes`, `cncf-cla: no`, `lgtm`, `v3 port complete` and `approved` labels could be removed, but many of those labels are all used quite actively. For example:

- [PRs labeled with breaking](https://github.com/helm/helm/pulls?q=is%3Apr+label%3Abreaking+is%3Aclosed) was used recently to note breaking changes introduced during Helm 3's development cycle
- [PRs labeled with needs-pick](https://github.com/helm/helm/pulls?q=is%3Apr+is%3Aclosed+label%3Aneeds-pick) is used often when we need to track pull requests to be cherry-picked into the next patch release.

The `size/` labels are currently used to determine how many reviewers should approve the PR before it is merged, so those should stay as well. See [CONTRIBUTING.md](https://github.com/helm/helm/blob/master/CONTRIBUTING.md#pull-requests) for more details.

**Comment by bridgetkromhout** [comment]
Hi, @cdrage - as you likely saw, we replied with some detail around current labels. Because we are always interested in improving, we now have a defined process so that if you'd like, you can submit a Helm Improvement Proposal so as to work in the community to make new ideas a reality: https://github.com/helm/community/blob/master/hips/hip-0001.md - meanwhile, I will close this issue. Thanks!
