### ISSUE TITLE
helm delete is not honoring --timeout, it exists even before that

### ISSUE THREAD

**Issue by damodhar22** [helm/helm#7221]
Output of `helm version`:v3.0.0

Output of `kubectl version`:v15.0.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): eks

> @damodhar22 Can you add details on the issue in he description field?
Example:
Create pods with the below command

`helm install myrelease mychart --wait --timeout 10m0s`

`helm delete myrelease --timeout 10m0s`

the expectation is that delete command will exit after all the resources are deleted or after the timeout is up.

But the actual behavior is  delete command exits even before the timeout is up
and I can still query for the pods which are terminating state.

Why is delete command does not respect --timeout value?

**Comment by hickeyma** [comment]
@damodhar22 Can you add details on the issue in he decsripotion field?

**Comment by jpc4242** [comment]
I don't know if @damodhar22 was referring to this. I interpret this as allowing `helm delete` to accept a `--wait` option as `helm install` does, and in that case really wait (up to the limit established by `--timeout` for the resources (Pods, ....) to disappear

**Comment by damodhar22** [comment]
> I don't know if @damodhar22 was referring to this. I interpret this as allowing `helm delete` to accept a `--wait` option as `helm install` does, and in that case really wait (up to the limit established by `--timeout` for the resources (Pods, ....) to disappear

@jpc4242 Yes, you interpreted it correctly. This is exactly what I was referring.

**Comment by jpc4242** [comment]
The problem I see in order to implement this is that the pods that you are seeing in terminating state may not even _directly_ appear inside the helm chart. Probably your helm chart has e.g. a deployment or statefulset and this is what makes the Pods appear.
So for helm to "wait until all resources disappear" means that helm needs to know perfectly this list of resources, and IIRC as of today helmv3 doesn't do that and thats why you no longer receive in helm status the list of resources that you got in helmv2

For "correctly written" charts, you should expect the
`-l app.kubernetes.io/instance=<releasename>` selector to give you that list, or if not, at least the `-l release=<releasename>`. But this depends on the helm chart author doing things "correctly" so I am not sure if the helm command should rely on that.

**Comment by AirbornePorcine** [comment]
I'm confused - helm 3 already knows exactly what resources are involved in a deployment, as can be seen when using `--debug` (it lists exactly what it's terminating). So what's preventing helm from waiting until those resources which it knows about are fully deleted, not just terminating?

This causes us major headaches when working with PVCs, as if someone deletes their environment then rapidly recreates it, the PVC is not finished terminating, but helm seems to think that's fine and proceeds with the recreation, then gets confused when the PVC vanishes from under it (as the termination is now complete).

**Comment by yashbhutwala** [comment]
Ping!  Can we please add `--wait` flag to `helm uninstall`?

**Comment by bacongobbler** [comment]
Yes - see https://github.com/helm/helm/issues/2378#issuecomment-676530173.

**Comment by omerfsen** [comment]
#2378 became stale..
