### ISSUE TITLE
The Memory storage driver does not have consistent ordering

### ISSUE THREAD

**Issue by absoludity** [helm/helm#7263]
The memory driver, which is often (mostly?) used for unit tests, does not have a consistent ordering of results when calling `List`. This is because it is implemented as a simple map (https://github.com/helm/helm/blob/master/pkg/storage/driver/memory.go#L33), which is iterated over with a `range` statement in `List` (https://github.com/helm/helm/blob/master/pkg/storage/driver/memory.go#L75).

As a result, tests need to sort the result to have consistent ordering. It would be nicer if the memory driver used the sorted list of keys for the map instead.

**Comment by bridgetkromhout** [comment]
Hi, @absoludity - Thank you for your feedback! I'm closing this old issue because we now have a recommended path forward for proposals: if you'd like to formally propose this idea, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community. Thanks!
