### ISSUE TITLE
Error: unknown flag: --namespace

### ISSUE THREAD

**Issue by stodge** [helm/helm#7291]
Output of `helm version`:

Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2-k3s.1", GitCommit:"b8b17ba55f20e590df507fce333dfee13ab438c6", GitTreeState:"clean", BuildDate:"2019-10-16T05:17Z", GoVersion:"go1.13.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): k3s/k3d

I upgraded my installation of Helm from 2.14.x to 2.16.1 and now my commands are failing:

```
helm delete --purge --namespace=mike <name>
Error: unknown flag: --namespace
```

I'm really new to Helm/Kubernetes so am I doing something wrong or did something major change between these version of Helm?

Thanks

**Comment by marckhouzam** [comment]
Hi @stodge. Welcome to three helm community.

Helm 2, which you are using, only partially uses namespaces.  The `install` and `upgrade` commands allow you to specify in which namespace to install your objects using a `--namespace` flag, but helm itself stores it's own release information outside the namespace.

This implies that when doing a delete you only need to specify the release name, no need for a namespace. That's why the `delete` command doesn't support the `--namespace` flag.

Note that when you will upgrade to helm 3, this changes as helm 3 stores its release information within the namespace. So for helm 3 you need to specify the `--namespace` flag for a delete and many other commands.

**Comment by stodge** [comment]
Thanks for your help.
