### ISSUE TITLE
[Feature Request] helm package name should use --app-version

### ISSUE THREAD

**Issue by guice** [helm/helm#7299]
This is a continuation of the helm install --app-version thread #3555.  RE: _@iorlas in https://github.com/helm/helm/issues/3555#issuecomment-549582383_

To avoid all confusions, assuming:

* A helm package is meant to be the "rpm" of an k8s application
* Chart.version is meant to be the version of chart files (i.e. the yamls)
* Chart.appVersion is version of the application - locking "this" .tgz to _this_ application version (e.g. docker image tag)

In order to match the naming schemas of rpms and to avoid all confusions between `--version` and `--app-version`: the package name needs to reflect the _app_ version, not the chart version.

In an idea world: once you've build your helm yaml files, you'll almost never change them as you deploy additional versions of your application.

One issue with matching versions is this doesn't really work in the real world dev environment: 

> \# This is the chart version. This version number should be incremented each time you make changes to the chart and its templates, including the app version.

e.g. How do you build a package tagged by ref tags, e.g. git rev hash?

This, production releases, and the confusion over helm versions can all be resolved by just naming the package after the `--app-version`.

**Comment by TBBle** [comment]
If this was the case, you couldn't iterate on charts unless there's also upstream changes to bump the version. This would render https://github.com/helm/charts/ impossible to deliver.

*If* your Helm charts are part of the project they deliver, then the `version` and `appVersion` should be the same (except the latter's a string). This is the case for Agones, for example, as well as the Helm charts we develop at my workplace.

In the RPM world, the RPM version generally *contains* the `appVersion`, with preceding epoch, and trailing package version. However, RPMs do not expect SemVer the way Helm does. I'm more familiar with Debian, which had its own version-ordering system and depended on packagers to mangle upstream versions to suit that, if they didn't already have a consistent order. It couldn't do things like SemVer can in terms of the `~` or `^` operators, because the version was purely ordered, without semantics.

It's the same reason `version` is a SemVer, while `appVersion` can be a string.

So in-short, (IMO) the Chart version is closer to the *intent* of the RPM version, but due to stricter limitations, diverges further from the appVersion than happens in RPMs.

**Comment by guice** [comment]
Hmm. This is where things start coming at odds with each other when you start tying the `appVersion` to a Docker tag (a logical association). This is where we're having trouble, i.e. the dev scenario I mentioned above. Since `version` must be a SemVer, we simply cannot use Docker tags as a Chart `version`.

How do we create a visual version difference to the developers when `appVersion` isn't apparent on the charts? 

Because of how k8s works with it applications: in a dev world, there has be be some way to allow tag versions across the board.

> It couldn't do things like SemVer can in terms of the ~ or ^ operators, because the version was purely ordered, without semantics.

Why not? We do this all the time with php `composer`. We can use SemVer or we can use strings versions which are simply parsed or ignored in versioning schema, i.e. if `version` is not a SemVer number, don't include it in `~` and `^` pattern matching.

**Comment by bacongobbler** [comment]
Please keep the conversation going in #3555. That way the rest of the community interested in the discussion can follow along without having to follow multiple threads. Thanks.

**Comment by iorlas** [comment]
@bacongobbler I guess it is an attempt to split the discussion into multiple sub-topics. #3555 covers more than just a flag question.

This issue covers package naming issue, which is a side-question, although related to the whole versioning epic, could be covered aside.

Do you suggest to come up with whole picture of versioning first, in #3555, then providing a proposal covering all the pieces?

**Comment by bacongobbler** [comment]
yes.
