### ISSUE TITLE
Is there support for multiple "urls" in the index.yaml?

### ISSUE THREAD

**Issue by mikeshng** [helm/helm#7314]
Hi,

Looking at the example at https://helm.sh/docs/topics/chart_repository/#the-index-file
There seems to be an intention to support multiple URLs. For example:
```
      urls:
      - https://technosophos.github.io/tscharts/alpine-0.2.0.tgz
```
But when I look at the code https://github.com/helm/helm/blob/master/pkg/downloader/chart_downloader.go
There is a `TODO: Seems that picking first URL is not fully correct`
So it seems like only the first entry is actually being used? Or am I looking at the wrong place?

I ran some testing on my own using Helm 2 and it seems like only the first url is being used.

What is the actual intention of `urls`? Is it to support multiple parts for download? Or is it more like mirror urls, where all the urls are basically the same chart and if one is successfully downloaded then it's ok?

Thanks.

**Comment by bacongobbler** [comment]
The `urls` field was originally designed as a place for mirror URLs.

On the client side, there were open design questions over how Helm would handle package resolution for HTTP 300-599 requests. There were also open questions about how one would add mirror URLs to the index with `helm repo index`, so the client was originally designed to support one URL.

When the chart repository API was first designed, we wanted to leave the design open for opportunity to supporting many mirror URLs for a chart package. We figured it would be better to allow the API to support multiple URLs to support that use case in the future without breaking compatibility.

Over time, it turned out that nobody has since asked nor requested this feature, so that's where it currently stands today.

Hope this helps.

**Comment by mikeshng** [comment]
Thanks for the clarification.
