### ISSUE TITLE
Helm `default` shouldn't dive into non-existing objects

### ISSUE THREAD

**Issue by guice** [helm/helm#7331]
When using the following checks in the template, you get undefined interface when you really expect for a waterfall "exists" check:

```
  type: {{ default "NodePort" .Values.fpm.service.type }}
```

If you don't define `fpm.service` within your values file, Helm will fail with: 

```
 <.Values.fpm.service.type>: nil pointer evaluating interface {}.type
```

Expected behavior would be to stop at `.Values.fpm.service` check and default to "NodePort".

I do understand this may be more in the Go language behind it ... but, thought I'd post anyway in case `helm` can do something about this.

---

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

Output of `kubectl version`: N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  N/A

**Comment by thomastaylor312** [comment]
Thanks for letting us know about this! This would likely be a helpful enhancement. However, the `default` function comes from the [Sprig](https://github.com/Masterminds/sprig) library. Because this isn't a Helm specific issue, I'm going to close this. I would recommend opening the issue against Sprig and linking to this issue. If the change is accepted there, we'll bump the library version over here
