### ISSUE TITLE
Package signing does not work with GPG subkeys

### ISSUE THREAD

**Issue by antevens** [helm/helm#7340]
For security reasons we sign all our releases with a subkey of our master code signing key (which we store offline), unfortunately it seems that helm does not work with subkeys:

helm package my_chart --destination /tmp/my_charts --sign --key 1FDAEEDD
Error: openpgp: unsupported feature: S2K function

----------------------------------------

Output of `helm version`: v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"

---------------------------------------

$ gpg --list-keys
pub   4096R/BDA52FD9 2013-12-04
uid                  Security Compass (Code signing and encryption for Security Compass products) <sysadmin@securitycompass.com>
uid                  SDElements (Code signing and encryption for SDElements products) <sysadmin@sdelements.com>
sub   4096R/40F591E0 2013-12-04 [expires: 2023-12-02]
sub   4096R/4FB7A219 2013-12-04 [expires: 2023-12-02]
sub   4096R/1FDAEEDD 2019-07-09 [expires: 2029-07-06]

This seems to be a bug related to how GPG keys are handled in Go, perhaps the following will help:
https://github.com/keybase/keybase-issues/issues/1822
https://github.com/keybase/keybase-issues/issues/1887

**Comment by bacongobbler** [comment]
Hi @antevens. Can you please provide more information on this ticket? Thanks.

**Comment by antevens** [comment]
Hey @bacongobbler, sorry about that, hit enter by accident before I was done filling in the details, let me know if you need any more info or details or if there is any debugging I can do to help.

**Comment by bacongobbler** [comment]
Thank you! Yes, we have had issues before with Go's OpenPGP libraries in the past as well, so this doesn't entirely surprise me. For example, https://github.com/helm/helm/issues/2843 was due to a change in GnuPG switching to a newer keyring format, but Go's OpenGPG does not support that new format: https://github.com/golang/go/issues/29082

If you can figure out how Helm can support GPG subkeys, we'd highly appreciate a patch!

Alternatively, you can give the helm-gpg plugin a shot and see if it works for you. It calls `gpg` to perform the package signing and verification, which you can use with `helm gpg sign` and `helm gpg verify`.

https://github.com/technosophos/helm-gpg

Let us know what you think!

**Comment by antevens** [comment]
Hey @bacongobbler, thanks for the swift response and workaround, by making slight modifications to the bash script in the gpg plugin I was able to use it to sign using a sub-key.

I'm going to continue my testing, I might make an MR/PR to the GPG plugin or an MR/PR to helm itself depending on how much time I'm able to spend on this going forward.

As a side-note it would be great if plugins were signed and by default helm would reject un-signed plugins (could have a --insecure flag or similar, the current way of installing/running them seems a bit risky at best.

**Comment by bacongobbler** [comment]
Good suggestion. Would you mind opening a new ticket requesting that feature with more details? We'd really appreciate that!

**Comment by antevens** [comment]
Sure, done: https://github.com/helm/helm/issues/7342

**Comment by bacongobbler** [comment]
closing as stale.
