### ISSUE TITLE
Trying to install Helm on openshift PPC

### ISSUE THREAD

**Issue by joscorga** [helm/helm#7341]
Output of helm version:
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}

Output of kubectl version:
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-02T00:03:59Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/ppc64le"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-12-02T08:31:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/ppc64le"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
OpenShift v3.11.157

Trying to install helm on OpenShift v3.11 following the instructions listed here: https://blog.openshift.com/getting-started-helm-openshift/ after installing the server, the pod is created but it fails and the error in the logs is:
standard_init_linux.go:178: exec user process caused "exec format error"

This is the second issue I create, the first one is #7276 which is closed. I tried adding one more comment to that issue but I didn't receive any response and that's why I'm creating this other issue.

As I mentioned in that other issue, the goal I'm trying to achieve is to get DB2 installed on openshift using the instructions listed here: https://github.com/IBM/Db2/tree/develop/deployment

Hopefully you can help me out.

Thanks!

**Comment by bacongobbler** [comment]
Sorry about not catching your last comment. We were out for the holidays.

I cannot understand your last comment in #7276. However, as mentioned earlier in that ticket, `helm init` does not provide a ppc64le image for tiller. We don't have a tiller image which supports that chip architecture in Helm 2.

If you would like to look further into ppc64le support for Helm 2, please have a look at the tiller-multiarch project. Several community members use that project to build a version of Tiller that will support alternative architectures, such as 64-bit ARM architectures. Have you had a chance to look at that project yet?

https://github.com/jessestuart/tiller-multiarch

Also as mentioned in the previous ticket, Helm 3 is also a good option, since [Helm 3 removed Tiller](https://helm.sh/docs/faq/#removal-of-tiller), bypassing this issue. I would suggest following up with the db2 team at https://github.com/IBM/Db2/issues/10 and asking for more clarification on how to set up db2 with Helm 3.

Let us know if you have any further questions.

**Comment by joscorga** [comment]
I got a response in the issue @bacongobbler mentioned, I'll close this issue now.

Thanks!
