### ISSUE TITLE
install: reintroduce name long flag (--name) for v2 compatibility 

### ISSUE THREAD

**Issue by desimone** [helm/helm#7345]
## Summary 

To support backwards compatibility, helm should honor `name` passed in as both an argument or a long option.  

### What happened

I ran the following command:
```
helm install stable/kubernetes-dashboard \
  --name helm-dashboard \
  --set ingress.enabled="false" \
  --set enableSkipLogin="true
```

And I got the error 

`Error: unknown flag: --name`

### What I expected to happen

I expected helm to recognize that a name _has_ been provided. This command (`--name`) worked in Helm v2. 

I understand and agree with the change from v2 --> v3 such that helm name's should be explicitly set or generated but this feels like an unnecessary breaking change.

Helm is getting name explicitly passed to it.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```

I am willing to help contribute a fix to this issue.

**Comment by bacongobbler** [comment]
PRs welcome to accept the name argument as a flag. Cobra (the library used in Helm for assembling the CLI) doesn't support this out of the box, so I imagine the design may be tricky to nail it correctly. Give it a go and let us know if you run into trouble.

**Comment by desimone** [comment]
@bacongobbler Sounds good. 


v3
```
Usage:  helm install [NAME] [CHART] [flags]
```

The install argument must be a chart reference, a path to a packaged chart,
a path to an unpacked chart directory or a URL.
```

Cobra aside, what makes this a bit tricky is we have two positional arguments versus the one in v2. 

What do you think about assuming that  if the name flag is set, the the remaining argument is the chart name, and fail we get two arguments _and_ the chart name flag?

**Comment by marckhouzam** [comment]
In a similar issue of supporting the `-c` flag for `helm version` some maintainers expressed concern about supporting flags that could cause confusion. In the end that particular case was accepted because it provided other benefits than just backwards-compatibility.

I'm my humble opinion, having an argument NAME and also flag --name will seem counterintuitive.  With a major version increment (v2 going to v3) such backwards-compatibility "hacks" may not be desirable, especially since it will imply the --name flag would not be possible to remove (for the same compatibility reasons).

I believe users are expected to make certain changes when migrating to helm v3.

That being said, it's ok with me if @bacongobbler feels it is ok?

**Comment by mattfarina** [comment]
I had the same thought at Marc. I've added this to the agenda for the next Helm dev call so we can hash this out.

If we do use it I would like to add a deprecation message to users.

**Comment by bacongobbler** [comment]
closing as stale.
