### ISSUE TITLE
helm upgrade --install --wait does not wait for pods to be ready in statefulset when updateStrategy: OnDelete 

### ISSUE THREAD

**Issue by pomberer** [helm/helm#7424]
Helm --wait --install does not wait for Pods to be ready in a statefulset when setting updateStrategy: OnDelete

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

**Comment by bacongobbler** [comment]
Have you had a chance to look into how this could be achieved?

https://github.com/helm/helm/blob/0beb9f70407bed715e67dc28eaf6e6eb3c3263e1/pkg/kube/wait.go#L208-L215

**Comment by arianvp** [comment]
This seems to be a regression compared to Helm 2; where this did work.

https://github.com/helm/helm/blob/0beb9f70407bed715e67dc28eaf6e6eb3c3263e1/pkg/kube/wait.go#L289-L291

 is the offending line. Helm refuses to wait if the type is not `RollingUpdate`

In helm 2; it seems `--wait` would just count until  number of `pods  >= expected`

I do understand that this is a bit  problematic with `OnDelete` as old pods do not get reaped. So  the number of pods isn't a reliable number.

The old behaviour in helm 2 was to just get all the pods in the statefulset and wait for all of them to be ready; instead of using this `ReadyReplicas` number.

https://github.com/helm/helm/blob/release-2.16/pkg/kube/wait.go#L163-L168

We should either document the new behaviour (it isn't currently) or fix the behaviour

**Comment by bacongobbler** [comment]
closing as stale.

**Comment by carlosrmendes** [comment]
is there any way to achieve this already?
