### ISSUE TITLE
Helm 3.0.2 - generating an action.Configuration for in-cluster runtime

### ISSUE THREAD

**Issue by mmailhos** [helm/helm#7430]
It seems to me that Helm 3 does not provide a way to create an `action.Configuration` structure if the code is running from within the cluster.

Here is a code sample that I have tried, building my own generic flags:

```
config, err := rest.InClusterConfig()
if err != nil {
    panic(err)
}
insecure := false

genericConfigFlag := &genericclioptions.ConfigFlags{
    Timeout: stringptr("0"),
    Insecure: &insecure,
    APIServer: stringptr(config.Host),
    CAFile: stringptr(config.CAFile),
    BearerToken: stringptr(config.BearerToken),
    ImpersonateGroup: &[]string{},
    Namespace: stringptr(namespace),
}

actionConfig := &action.Configuration{
    RESTClientGetter: genericConfigFlag,
    KubeClient: kube.New(genericConfigFlag),
    Log: log.Infof,
}

```

Unfortunately, this result in a `SIGSEGV` error later when running `action.NewList(actionConfig).Run()`.

Is it the right way to define an action config for Helm 3 from within a Kubernetes cluster, without altering the current library of course?

**Comment by hickeyma** [comment]
@mmailhos Thanks for raising this. I am trying to understand your use case to get an understanding what you are trying to do. Do you mind providing more details about it?

I suppose you have already looked at examples of using the Helm Go library to get the `action.Configuration`, for example: https://github.com/helm/helm-2to3/blob/master/pkg/v3/connect.go

**Comment by mmailhos** [comment]
@hickeyma Thank your for your reply. I'm building a simple reporting tool to describe my charts and monitore them.

The problem with the `cli` package is that it integrates with the environment and the KubeConfig while I was looking for a more _native_ solution (maybe using the k8s api, not sure). Anyway that's better as I got rid of my segfault error and now getting `context deadline exceeded`. Still troubleshooting that integration.

**Comment by hickeyma** [comment]
@mmailhos This snippet of code might be useful then:

```code
kubeConfigPath := "/path/to/kubeconfig"
namespace := "<namespace>"
actionConfig := new(action.Configuration)
if err := actionConfig.Init(kube.GetConfig(kubeConfigPath, "", namespace), namespace, os.Getenv("HELM_DRIVER"), func(format string, v ...interface{}) {
		fmt.Sprintf(format, v)
}); err != nil {
		panic(err)
}
```

**Comment by hickeyma** [comment]
FYI, docs for v3 SDK: https://pkg.go.dev/helm.sh/helm/v3

**Comment by mmailhos** [comment]
> @mmailhos This snippet of code might be useful then:
> 
> ```
> kubeConfigPath := "/path/to/kubeconfig"
> namespace := "<namespace>"
> actionConfig := new(action.Configuration)
> if err := actionConfig.Init(kube.GetConfig(kubeConfigPath, "", namespace), namespace, os.Getenv("HELM_DRIVER"), func(format string, v ...interface{}) {
> 		fmt.Sprintf(format, v)
> }); err != nil {
> 		panic(err)
> }
> ```

Thanks! But I am actually trying to avoid loading a kube config file. I would like to run my service with a Service Account only and load whatever is needed to execute helm commands via the pod environment.

**Comment by LeeHampton** [comment]
Pinging this issue to see if anyone has additional insight here. I cannot for the life of me figure out a sane way to construct a `&genericclioptions.ConfigFlags` using an in-cluster configuration.

The use case for me is that I have a pod in my k8s cluster that serves as a "deployer" of sorts, kicking off dynamic helm releases on demand. In the interest of security (and not having to do some awkward meta-setup for my deployer pod), I do not want to have a kubeconfig file in my pod -- I would rather rely on the pod's internal permissions, as I can easily do for my programmatic kube-client. In-cluster config worked fine for me with Helm2, but that may have been because it had to establish a tunnel to the Tiller server which already had in-cluster permissions.

Is the best option here to just manually create the `&genericclioptions.ConfigFlags` struct. If so, any insight into avoiding the `SIGSEGV` error @mmailhos mentions?

**Comment by darshan-karia** [comment]
This is what I did, and works fine for me (using helm 3.2.0 level sdk code):
**imports**
```go
import (
	"log"

	"helm.sh/helm/v3/pkg/action"

	"k8s.io/cli-runtime/pkg/genericclioptions"
	"k8s.io/client-go/rest"
)
```
**ActionConfig**
```go
func getActionConfig(namespace string) (*action.Configuration, error) {
	actionConfig := new(action.Configuration)
	var kubeConfig *genericclioptions.ConfigFlags
	// Create the rest config instance with ServiceAccount values loaded in them
	config, err := rest.InClusterConfig()
	if err != nil {
		return nil, err
	}
	// Create the ConfigFlags struct instance with initialized values from ServiceAccount
	kubeConfig = genericclioptions.NewConfigFlags(false)
	kubeConfig.APIServer = &config.Host
	kubeConfig.BearerToken = &config.BearerToken
	kubeConfig.CAFile = &config.CAFile
	kubeConfig.Namespace = &namespace
	if err := actionConfig.Init(kubeConfig, namespace, os.Getenv("HELM_DRIVER"), log.Printf); err != nil {
		return nil, err
	}
	return actionConfig, nil
}
```
**Usage**
```go
actionConfig, kubeConfigFileFullPath, err := getActionConfig(namespace)
listAction := action.NewList(actionConfig)
releases, err := listAction.Run()
if err != nil {
	log.Println(err)
}
for _, release := range releases {
	log.Println("Release: " + release.Name + " Status: " + release.Info.Status.String())
}
```
It is not much different from what @mmailhos originally did, except the initialization of the actionConfig. It could also be that newer version fixed some issues. Let me know if this works for you guys.
@LeeHampton I am also doing something similar to what you're trying to do, due to lack of rest interface for helm3 :-)
