### ISSUE TITLE
Helm package without dependencies

### ISSUE THREAD

**Issue by vijay-v6** [helm/helm#7441]
Is there a way we could package a helm chart without dependencies?
We need our dependencies to be listed in the requirements.yaml. But the dependencies should not be packaged in the umbrella helm chart when we issue the helm package command.

Thanks!

**Comment by bacongobbler** [comment]
There is no `helm dependency cleanup` command. Perhaps this may be a convenient feature to introduce! Have you had a chance to look into this further?

**Comment by vijay-v6** [comment]
I haven't had a chance to look further into this. This came as a requirement before and it is parked for now. Might've to check this out. Would be good to have this option.

**Comment by mvukadinoff** [comment]
+1 

We would also like to see this feature. 
It doesn't make sense to package a copy of the referenced charts in the umbrella in case they're used from a repository. This way if one doesn't have a requirement for a strict version one need to build the umbrella chart everytime a sub-chart is updated. 

So in case we have:
{code}
- name: sub-chart-inrepo
  version: ^0.0.1
  repository: http://chartmuseum.somewhere.com/
  condition: sub-chart-inrepo.enabled
  alias: sub-chart-inrepo1
{code}

The desired behavior is to package directly and then satisfy requirements on install and not during package
{code}
helm package .
helm push xxx.tgx repo
#then dependecies to be satisfied during install
helm upgrade --install chart
{code}

Instead of the current scenario.
{code}
helm dependency update .
helm package .
helm push xxx.tgx repo
{code}

**Comment by phoenixwp** [comment]
That would be great feature!

@mvukadinoff,
I found, that `helm push ` does mentioned action, pushes chart package without including sub-chart's bodies into package archive, but it doesn't have an option --app-version, like `helm package`. So if you don't need to change appVersion field in Chart.yaml, you can use this way.

But it is not my case. I have to change appVersion and also use library chart as the dependancy, so I would like to get the latest dependancy charts with each deploy.

**Comment by odelucca** [comment]
+1

No updates on this? In my opinion, there is no sense of having a dependency manager if it is mandatory to install those dependencies before packing the chart.

**Comment by SleepyBrett** [comment]
Yeah I don't understand at all why `helm install/update` doesn't just fetch the dependency at deploy time.

**Comment by AiRrRock** [comment]
The issue is extremly important! Can we reopen it and do smthing about it?

**Comment by darint00** [comment]
Need this option as well.  Simple fix.  --nodep  Please add this.

**Comment by bacongobbler** [comment]
Contributions are provided by the community. Please feel free to work on something.

**Comment by AllieEvers** [comment]
@bacongobbler 
I'd like to request this feature request be reopened. This seems reasonable/useful.

We also have a situation where helmchart dependencies are only present in our runtime environment as a helm repo and not in our CI/CD pipeline. Being forced to have dependencies present in order to package a chart when helm readily supports dependency updates at install is awkward. It's forcing us to essentially perform a helm package via script by updating the values.yaml and tarring the helmchart rather than the helm cli.

I'd propose --dependency-update not being set to true causes helm package to not attempt to update dependencies. I think this could be accomplished, in action/Package.go, by having run() only call checkDependencies() if DependencyUpdate is true or have reqs be set to empty if DependencyUpdate is false. Alternatively, if you don't want to give --dependency-update new behavior, you could provide a new arg, like the suggested --nodeps, that does what I suggest here.

**Comment by juanjo-vlc** [comment]
Let's keep this alive, there is no sense of including charts where the repository is referenced by url. But including them when they are local, makes sense.

**Comment by GaMartinelli** [comment]
Having to include a third party chart that’s being referenced by an URL is perhaps the most counter-intuitive thing I’ve ever seem

**Comment by krishna-birla** [comment]
Anything on this?

**Comment by theMalapeno** [comment]
+1 for this feature.

Having the ability to pull in dependencies at install time as opposed to package time makes sense.

**Comment by imizimi95** [comment]
> +1 for this feature.
> 
> Having the ability to pull in dependencies at install time as opposed to package time makes sense.

@theMalapeno you can with `helm install --dependency-update ...`

**Comment by charlyinalbon** [comment]
I think this feature is of importance in conjunction with the GitOps workflow when using ArgoCD. There it is more efficient to package and push to the intermediary repo without including the dependencies statically.

**Comment by Djaytan** [comment]
I agree that this feature should be kept open.
If contributions are welcome, then simply tag it as "contributions welcome" or something like that instead of "stale".
