### ISSUE TITLE
 Proposal: Handle private repos with Authorization tokens

### ISSUE THREAD

**Issue by jakesyl** [helm/helm#7451]
So #3102 went stale in 2017, and @lionelvillard and I tried to `/reopen`, but that didn't work so here's the issue as written by @burdiyan 

> Right now a user can specify TLS credentials when doing helm repo add by using --ca-file, --cert-file and --key-file flags.
> 
> It would be great if user could also specify an authorisation token, so that Helm would pass it in every request to the repo.
> 
> This may simplify a lot dealing with private repos. A repo can be plain GCS or S3 bucket (non-public), which accept Bearer authorization tokens of allowed IAM users. This also allows to have complex access control use-cases which are already covered by object store provider.
> 
> Required changes:
> 
> Add --token flag to repo add command. This would store the token in repositories.yaml file.
> Update the code that interacts with the repo, to check if token is specified, and pass it as Authorization: Bearer <token> HTTP header for all requests to the repo.
> As far as I'm concerned, this shouldn't bring any compatibility issues, but I would like to have a comment from maintainers about it.

Note: I don't think the removal of Tiller really changes any of this. I'd like to add my impetus for reopening this issue is the [wacky stuff](https://github.com/helm/chart-releaser/issues/14#issuecomment-577045042) we've been doing to get chart-releaser working with private repos (see helm/chart-releaser#14). I think this warrants a relook as it solves #3092
and #2590

**Comment by hickeyma** [comment]
@jakesyl Thanks for raising this again. Would you be willing to work on this feature and push the PR?

**Comment by jakesyl** [comment]
Yeah, I should be able to - let me look into this a bit more. I'm definitely willing to take it on, but want to make sure the above approach is ideal. Just wanted to make sure there's not a hard reason we can't do it

**Comment by gboor** [comment]
Any news on this? This would be a very handy feature to have for my use-case (private charts).

I noticed there is a --kube-token param, but that seems to be unrelated to the repo access.

**Comment by bacongobbler** [comment]
`--kube-token` is for passing OAuth tokens to the Kubernetes API server, so different use case.

The problem in the past (and why #3102 was left inactive) was because there were no known chart repository reference implementations using auth tokens.

@jakesyl feel free to implement something. @gboor given that it's been 7 months since there's been any activity on this ticket, I would also encourage you to look into implementing this feature.

**Comment by jakesyl** [comment]
@bacongobbler we're using basic auth for now

**Comment by gboor** [comment]
@bacongobbler I won't have time to work on this any time soon, but may pick it up if it remains open. I have also found the [Helm GCS Plugin](https://github.com/hayorov/helm-gcs) to be a viable alternative, maybe it will be for someone else as well.

**Comment by ivanov-aleksander** [comment]
I am going to use github as private helm repo and need authorization: token for this.

**Comment by bacongobbler** [comment]
Cool - feel like taking a crack at a patch?

There may already be a PR in the ticket queue that implements this functionality. I’d search for existing PRs first before attempting to write something up.

**Comment by orecht** [comment]
Looks like PR #8447 addressed this issue.

**Comment by jakesyl** [comment]
I don't have permissions to do it, but if a maintainer wants to link this or to #8447 that'd be great, otherwise will keep this open until that gets merged.

**Comment by koalalorenzo** [comment]
Maybe re-open? :D 😅 I really really really dislike this automatic closing, I am now on the 5th issue that looks like is copy pasted, but nobody cares about it because it was closed automatically.

https://github.com/helm/helm/issues/3102
https://github.com/helm/chart-releaser/issues/14

Did anybody solve the issue? 😢

**Comment by shaunofneuron** [comment]
@koalalorenzo digging this up as https://github.com/helm/helm/pull/8447 was never merged but _also_ because I was looking for prior art to inform solving this problem for krew private indexes (https://github.com/kubernetes-sigs/krew/issues/817), trying to pull artifacts stored in private github releases.  Both systems are very similar, any input welcome to that discussion 😉
