### ISSUE TITLE
Helm3: lint --strict broken for "default" on maps

### ISSUE THREAD

**Issue by micw** [helm/helm#7483]
Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Given the following values:
```
myMap:
  key1: value1
```

And the following expressions:
```
{{ default "default1" .Values.myMap.key1 }}
{{ default "default2" .Values.myMap.key2 }}
```

Renders to
```
value1
default2
```

`helm lint` is fine with that expressions. Nevertheless, `helm lint --strict` fails with

```
[ERROR] templates/: template: [templatename].yaml:5:29: executing "[templatename].yaml" at <.Values.myMap.key2>: map has no entry for key "key2"
```

**Comment by technosophos** [comment]
Reproduced by creating a new chart with `helm create` then following instructions in the issue.

I am working on a fix now.

**Comment by technosophos** [comment]
This appears to be by design.

If `--strict` is set, then the template engine is put in `missingkey=error` mode, which will trigger an error any time a `.Values` lookup does _not succeed_. The purpose of this is apparently to make sure that the default values cover all possible cases.

This does not seem like correct behavior to me, though. Especially not for maps. The documentation for `--strict` does not state that it turns on extra errors -- only that it fails if any warnings are emitted.

I am going to open a PR to fix this, but I am not sure whether it will be accepted.
