### ISSUE TITLE
Helm ls --failed returns releases which are "deployed" now, but has a failure in the history .

### ISSUE THREAD

**Issue by adusumillipraveen** [helm/helm#7495]
```
helm ls --namespace=reform-scan
NAME                   	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                         	APP VERSION
reform-scan-blob-router	reform-scan	50      	2020-01-30 10:16:28.851853992 +0000 UTC	deployed	reform-scan-blob-router-0.0.22	1.0
```

```
helm ls --namespace=reform-scan  --failed
NAME                   	NAMESPACE  	REVISION	UPDATED                                	STATUS	CHART                         	APP VERSION
reform-scan-blob-router	reform-scan	44      	2020-01-29 14:19:37.643962942 +0000 UTC	failed	reform-scan-blob-router-0.0.20	1.0
```
I wouldn't expect --failed to return a helm release which is currently deployed. At least, that was how helm 2 was behaving. Is this a change or bug in helm 3?

Output of `helm version`: 
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

Output of `kubectl version`: 
`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-13T18:46:24Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

**Comment by Dean-Coakley** [comment]
I've started work on this. Hopefully will have a PR next week :)

**Comment by bacongobbler** [comment]
Hey @Dean-Coakley! Where are we at with the PR?

**Comment by Dean-Coakley** [comment]
@bacongobbler I think I have a pretty good understanding of the issue and wrote a unit test.

https://github.com/helm/helm/compare/master...Dean-Coakley:fix-deployed-fail-report

However I'm lacking ideas on how to fix the issue, especially with avoiding additional calls to the Kubernetes api.

I'm happy for someone else to pick this up if it's high priority. 
Or I can take one more look to see if I can come up with some solution.

It should be noted that I think this bug is not specific to the `DELETED` state. But applies to all cases where a filter is applied and the release may be currently successfully deployed.

**Comment by andrewmelis** [comment]
I was surprised by this behavior as well and put up a proposed fix at https://github.com/helm/helm/pull/8282.

Many thanks to @Dean-Coakley -- you did all the legwork in finding the issue in the code.
