### ISSUE TITLE
Helm 3.0.3 change to not delete templated CRDs breaks backward compatibility

### ISSUE THREAD

**Issue by moduspwnens** [helm/helm#7505]
I noticed after upgrading to Helm 3.0.3 that our CRDs (that were *not* in the *crds* directly) are no longer getting deleted when the installed helm release gets deleted. They still are if I use Helm 3.0.2, and that was our desired behavior.

We've avoided the *crds* directory (and the prior *crd-install* hook) because for our use case, we *do* want CRDs to just be treated like normal resources (that is, upgraded and deleted). I understand that puts us in an odd spot relative to the Helm project's plans (i.e. not deleting or upgrading CRDs), but I'd at least expect an upgrade with only a patch number revision (3.0.2 to 3.0.3) to not break backward compatibility in this way.

The commit that changes this behavior seems to be here:
https://github.com/helm/helm/commit/9711d1c6bfd9cd0cebe47b069a18cfc83ac3bfee

We'll plan to get our deployment model for our CRDs in-line with Helm's plans for the long-term future.

**Comment by mattfarina** [comment]
@moduspwnens I appreciate you bringing up your CRD needs. Could you please provide your use cases for us? In there, could you describe your needs around CRDs and CRs from those CRDs. I want to work on Helm CRDs in 2020 either in a plugin or in Helm itself. I expect the work to start in a plugin as it will initially be experimental.

For context... CRDs are difficult. The Kubernetes project has not provided clear guidance on using them either in docs or codified. This has left many people to use them for many different things and in different ways. Sometimes those ways work well for projects but go against what people on the Kubernetes project say you "should" do. This has made it hard for Helm to codify CRD handling for many use cases.

**Comment by moduspwnens** [comment]
Thanks @mattfarina. I've read some of the other discussion topics here about it and I understand it's tricky and (from my perspective) may not be universally solvable by Helm alone.

In our case, we're building what is (at this point) a Kubernetes-based appliance that performs various packet processing features on the appliance's underlying network (not the pod network). Instead of building our own declarative API, permissions, etc. for defining how to encrypt, decrypt, route, inspect, or otherwise handle that underlying network traffic, we've created CRDs so our app (or a savvy user) can declaratively configure our box to handle that traffic. Think like a *PacketHandlingPolicy* CRD, a *PacketEncryptionConfiguration* CRD, and similar.

Because it's only our application using them and (currently) we're only targeting an appliance-based model, we feel comfortable ensuring CRD changes apply cleanly as plain upgrades such that Helm can upgrade them the same way it would any other resource. We won't upgrade them in ways that aren't backward compatible.

For deletes, from our perspective, if the user wants to delete the chart, s/he wants to remove the application completely. And frequently as part of development and QA, we'll want to delete the chart so we can install a fresh version. With CRDs not being deleted, we're not in a clean state for a fresh install. So we'd want them to be uninstalled, too.

Now naturally using our own CRDs, CRs, and controllers, some CRs are created with finalizers that don't get removed when Helm deletes the controllers, so I did develop a delete hook that clears out those finalizers and deletes any resources our project creates that Helm wouldn't have known about. We just label those resources with a key and value indicating the Helm release name, so the hook loops through all resources in the apiserver and deletes / removes finalizers from resources with that label.

Not ideal, of course, but I haven't yet seen a great pattern for this. I expect virtually any operator-style Kubernetes project would have the same issue. It'll define some CRD, and if a user creates a CR instance of it that requires any kind of cleanup, the operator will need to add a finalizer for it (so that cleanup can be done before the instance is fully deleted). That CR is outside the scope of Helm, so if Helm comes through and deletes the operator and the CRD instance, it'll be stuck in "terminating" because the CR instance still has that finalizer and the operator that would remove it is gone.

I'm happy to see you're working on a plugin! Without it, I'm not sure of a strong path forward for us other than to remove all CRDs from the chart and install / upgrade them without Helm. This adds some complexity for us, since we were using the Helm chart as "the build artifact" to publish / share. For us to get back to a "single build artifact" to do an install / upgrade / delete, we'll likely need to look into CNAB or some other spec for packaging a build artifact that can both do the CRD install / upgrade step and the "helm install" step. And then it can handle deletes, too.

Sorry about the wall of text but it's tough to give the full context of our use case without the details. This is definitely a tough problem to solve and I appreciate your efforts.

**Comment by dmmsonos** [comment]
I also would like to see this reversed, I'm surprised and disappointed to find out this behavior has changed. For example, our opa/gatekeeper CRDs are in the /templates directory alongside gatekeeper service, deployment, etc. We have two custom resource charts (constraint templates and constraints) that are deployed shortly after the CRD becomes available and gatekeeper manager is running. This is all automated and we do not intend for (or allow) any manual management of custom resources. It's safe and preferred if the CRDs are deleted when we delete the gatekeeper chart so we can actually clean out all gatekeeper-related resources. When gatekeeper is deleted none of the CRDs or custom resources make any difference at all since there's nothing to enforce them, and all resources are in code and can be recreated.

**Comment by hypertext418** [comment]
I also would like to see this reversed, I'm surprised and disappointed to find out this behavior has changed. For example, our opa/gatekeeper CRDs are in the /templates directory alongside gatekeeper service, deployment, etc. We have two custom resource charts (constraint templates and constraints) that are deployed shortly after the CRD becomes available and gatekeeper manager is running. This is all automated and we do not intend for (or allow) any manual management of custom resources. It's safe and preferred if the CRDs are deleted when we delete the gatekeeper chart so we can actually clean out all gatekeeper-related resources. When gatekeeper is deleted none of the CRDs or custom resources make any difference at all since there's nothing to enforce them, and all resources are in code and can be recreated.

**Comment by dsharp-pivotal** [comment]
We were also surprised by this change. We publish an operator that is deployed by a helm chart. We expected that deleting the helm chart would also delete all of the CR objects managed by the operator/controller, since the controller would no longer be available to manage them. Letting helm delete the CRD would cause the CRs to get deleted as well.

We found that we were not able to re-apply our helm chart after deleting it. That makes the helm chart harder to work with, since it would require manual intervention to re-install the helm chart.

Refusing to touch existing CRDs means we cannot extend our CRD, even in a backwards-compatible manner, without bumping the apiVersion, or forcing our customers to take manual intervention.

Helm should allow chart authors to decide how they want their CRDs to be managed. Updates to existing CRDs should be possible. Deleting CRDs should be possible. If the helm chart author wants to explicitly prevent this, then it should be possible as well.

CC: @jvigil-pivotal

**Comment by bacongobbler** [comment]
Given the amount of pushback, we should probably revert to the original behaviour. 

pinging @PhilGrayson for visibility

**Comment by moduspwnens** [comment]
I support reverting the change.

As it is now, the CRD behavior still isn't consistent because the commit only covers deletion of CRDs in the _templates_ directory. But CRDs in the _templates_ directory are also treated differently than ones in the _crds_ directory in that:
 * They are templated
 * They are upgraded by Helm if a newer chart contains a revised version

If I'm understanding this correctly, that makes this only a partial step toward actual consistency. Perhaps the easiest compromise would be to back out this change at least until a more complete change is available.

Alternatively, project maintainers might consider backing out the change and just making CRDs outside the _crds_ directory be treated like normal resources (preserving backward compatibility) as a first-class documented feature. The new functionality is still there with the _crds_ directory, and it'll be incumbent upon **Helm chart maintainers** that include CRDs outside the _crds_ directory (**not Helm itself**) to ensure those CRDs can / should be upgraded / deleted like any other resource. That draws a hard line on user expectations of Helm's behavior.

That'd bring about two ways of including CRDs in a chart:
 * Include them in the _crds_ directory. They will then be installed during `helm install`, not upgraded, and not deleted. 
 * Include them in the _templates_ directory. They will be given no special treatment and handled like any other resource.

**Comment by PhilGrayson** [comment]
I support reverting to give time to iron out a better approach. 

My main motivation was to provide a safe Chart upgrade path that moved the CRDs from templates/ to crds/. Then I could install a new Release of the Chart into the same Kubernetes cluster without Helm erroring because the CRDs were already defined.

My use-case could have been solved with a flag on `helm upgade` to skip CRD deletion. Or some way to force a release to forget that it's managing a resource. 

Also, the documentation could be clearer on the options a Chart author has on managing CRDs. When I was migrating from helm 2 to helm 3 I got the impression that the crds/ method was the recommend way ["CRD YAML files should be placed in the crds/ directory inside of a chart"](https://helm.sh/docs/topics/charts/#custom-resource-definitions-crds).

**Comment by hickeyma** [comment]
Closing as change reverted in #7571.

@PhilGrayson It might be beneficial to open a new issue to handle a new approach with deletion of CRDs.

**Comment by kfox1111** [comment]
Oh my gosh.... depending on which helm version you have, they all treat crd's differently. Can we please just give up and recommend to users officially to never put a crd inside a helm chart? As a user, it is impossible to know what helm version will work/wont work with any given crd. Not  trying to troll here. Just trying to be pragmatic. Do we still think it is possible for crd's to ever be reliable with helm?

**Comment by bacongobbler** [comment]
#5871

**Comment by kfox1111** [comment]
@bacongobbler are you saying I should comment there?

**Comment by alice-sawatzky** [comment]
is it really breaking backwards compatibility if the behavior being relied upon is undocumented? The behavior this brings back contradicts the docs ("CRDs are never deleted", with no clarification that it's only referring to CRDs from the `crds` directory), as well as historical helm community discussions on leaving CRD life-cycle after initial deploy up to the user.

By default, Helm should behave according to the documentation, and if exceptions are needed, this could be provided in the form of a CLI flag or an annotation on the resource.

This looks like a clear case of "fixing this bug breaks my workflow", where the solution cannot be to simply reintroduce the bug!

**Comment by kfox1111** [comment]
crds getting mangled/destroyed can cause some real damage to production systems.... whether its documented or not. Consistency is probably better here. Can fix it in a major version of helm. $0.02
