### ISSUE TITLE
 cannot re-use a name that is still in use

### ISSUE THREAD

**Issue by publicocean0** [helm/helm#7527]
Output of `helm version`:3.0.3

Output of `kubectl version`:Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

platform rke

 helm install rancher rancher-latest/rancher   --namespace cattle-system   --set hostname=rancher.comune.intranet 

error  cannot re-use a name that is still in use

**Comment by mattfarina** [comment]
In the namespace cattle-system there is an existing application named `rancher`. Helm is protecting you from installing two applications with the same name in the same namespace. If you fun `helm ls --namespace cattle-system` you should see an existing application with the name `rancher` already there.

You can use a different name, different namespace, or if the application named rancher should not longer be there you can delete it. Unless you meant to upgrade the application rather than install a new one.

**Comment by publicocean0** [comment]
helm ls --namespace cattle-system
NAME   	NAMESPACE    	REVISION	UPDATED                                STATUS	CHART        	APP VERSION
rancher	cattle-system	1       	2020-02-05 10:10:23.144025441 +0100 CETfailed	rancher-2.3.5	v2.3.5

**Comment by publicocean0** [comment]
it seems be ok now. I reinstalled the package

**Comment by Legym** [comment]
Just wanted to comment on what I did. I just ended up deleting the namespace and trying again

1. helm ls --all-namespaces
2. kubectl delete namespace cattle-system
3. kubectl create namespace cattle-system
4. helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher.DOMAIN --set ingress.tls.source=letsEncrypt --set letsEncrypt.email=EMAIL

**Comment by sven5** [comment]
for Helm 3 we need to add the namespace for deletion:

`helm delete -n my-namespace my-release`

**Comment by ferasawadi** [comment]
@sven5  saved the day, thanks
