### ISSUE TITLE
Install Helm plugins globally

### ISSUE THREAD

**Issue by mkjpryor-stfc** [helm/helm#7528]
It would be great if Helm could have two levels of plugins - global and per-user. Currently, we only have per-user. This makes, for example, building a re-usable Docker image containing Helm tricky.

**Comment by mattfarina** [comment]
You can do this today and it needs better docs. I've filed a feature request which I think would make this easier via #7529.

You can sorta do this today using the `HELM_PLUGINS` environment variable. This can accept a list of directories to look in for plugins using the systems path separator for the different directories. If you run `helm env` you can see where the current home directory for the user is.

Does this help?

**Comment by bitdancer** [comment]
Not really.  IMO the point here is that there should be a *global* directory, AKA a Well Known system directory (such as /var/lib/helm) where global plugins are installed, and which helm would check without needing any alteration to the user's environment.  This is how most tailorable systems work in unix.

**Comment by technosophos** [comment]
This will be fixed via support of XDG_DATA_DIRS.

**Comment by bitdancer** [comment]
What does desktop environments have to do with helm?  I don't use a desktop, and the concern raised here is for installing helm in a *container*, which certainly doesn't have a desktop.

I don't think support XDG_DATA_DIRS fixes this request.

**Comment by technosophos** [comment]
The XDG base dir specification seems to be widely, if not universally, accepted as the new location for what used to be dotfiles in the home directory. https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Over the last few years, we have observed most other tools supporting this convention. So we switched as well.

One thing that XDG_DATA_DIRS offers us is a convention for where we can place system-wide plugins, which is exactly what this issue is discussing.

AFAIK, the presence or absence of a "desktop environment" has no bearing on usage XDG Base Dir specification, though many desktop environments do have additional support for this specification.

All of this is part of the effort to not have a mess of specialized environment variables that Helm users need to learn and tweak in order to get Helm to work the way they want.

**Comment by bitdancer** [comment]
OK, that doesn't seem crazy :)  I've looked at the XDG spec a bit more (though still not in detail) and the linked PR, and it seems like there are still a couple missing pieces.  I also see that gcloud supports XDG, so it makes sense for helm to do so as well, regardless.

The PR doesn't (yet) contain enough documentation to tell how this is going to work.  If I'm understanding the proposal correctly, after the PR it will be possible to install helm plugins in one of /usr/share/helm or /etc/xdg/helm.  Or maybe a subdirectory of one of those?  (Unless of course the system or the user actually sets the corresponding XDG environment variable, in which case the base directory would be something else, but those would be the defaults).

What I'm confused about is whether plugins are 'data', or 'config'.  I don't think they are either one, so I don't think they are actually covered by the XDG spec.  I tried to look for examples of what other packages are doing, but the only candidate I could find on my system was glcoud, and that installs its components in its software directory: if you install glcloud globally components are installed globally, and you don't get a choice about that as far as I can tell.

Thinking about this a bit more, it *is* true that /usr/share is often used for 'script' files that are platform independent, so putting the plugins in the data dir probably makes the most sense.  For some values of "sense" :)  (Naming is Hard.)

I'm also wondering how one will go about installing the plugins in those system directories.  Will the helm command support that (if it has write permission when the install is run)?  How does a user differentiate between wanting to install globally versus installing locally?  After all, just because there are plugins installed globally doesn't mean all users necessarily want all plugins installed globally (that's one reason it is a path, after all).  I'm not personally asking for this feature, by the way; I'd be happy if it worked like gcloud and a global helm install implied global plugins only.  But if you did that I'm guessing what the next feature request would be.... :)

**Comment by jodavis-suse** [comment]
I just hit an additional use case for global plugins.  I'm working with a rpm based installer for Helm and would like to have some plugins ready out of the box.  However, this is difficult with the plugins being installed per-user.

**Comment by bitdancer** [comment]
I don't think the global-install/RPM install issue has been addressed, but I'm not sure because we didn't get any response to our questions.

**Comment by bitdancer** [comment]
I don't think the global-install/RPM install issue has been addressed, but I'm not sure because we didn't get any response to our questions.

**Comment by bacongobbler** [comment]
Set your XDG_* environment variables to whatever you wish to store config. So if you want Helm to store configuration in /etc/helm, set $XDG_CONFIG_DIR to `/etc`.

More info can be found in the specification, as @technosophos pointed out above.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

You can also refer to the documentation for more information.

https://helm.sh/docs/glossary/#helm-configuration-files-xdg

Finally, `helm env` is another place to look for where Helm stores its configuration data.

**Comment by bacongobbler** [comment]
> What I'm confused about is whether plugins are 'data', or 'config'

Plugins are data and are stored in Helm's data directory. Prior to install, they are installed in the cache.

**Comment by jdemeyer** [comment]
What worked for me to install plugins system-wide was setting the environment variable
```
HELM_DATA_HOME=/usr/local/share/helm
```
Of course, all users of Helm will also need this variable (or `XDG_DATA_DIRS`) set.

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by bitdancer** [comment]
We've finally reached the point in our project where we are actually trying to move to helm3, so I've finally had an opportunity to try this.

The current *implementation* does not do what was requested here, because apparently helm isn't fully following the XDG spec.  I'll open a new issue for this.  Short version: The XDG *defaults*  are not followed, nor is the XDG_DATA_DIRS environment variable respected.
