### ISSUE TITLE
helm v2.16.1 CVE-2019-1551

### ISSUE THREAD

**Issue by boat-33** [helm/helm#7576]
libcrypto1.1 and libssl1.1 are impacted by [CVE-2019-1551](https://nvd.nist.gov/vuln/detail/CVE-2019-1551). Are there any Helm v2 patches slated to be released in the near future that will update these packages to remediate these vulnerabilities?

**Comment by mattfarina** [comment]
@boat-33 thanks for your concern. Helm is not impacted by that CVE.

Helm is written in Go and Go has it's own crypto libraries. These are either part of the standard library or golang.org/x/crypto which is maintained by the Go team. Go is not using openssl which is what that CVE covers.

**Comment by mattfarina** [comment]
As this CVE does not impact Helm (due to Go's custom crypto implementations and not using openssl) I'm going to close this. If there are further questions or comments please feel free to bring them up.

@boat-33 I do appreciate you bringing this up. If you find another in the future could you please use the security contact documented at https://github.com/helm/community/blob/master/SECURITY.md when you report it. This will ensure we jump on it quickly and it's handled using the security policy.
