### ISSUE TITLE
range and global scope in helpers.tpl

### ISSUE THREAD

**Issue by srisurya777** [helm/helm#7634]
Output of `helm version`:  2.13.1

Output of `kubectl version`: 1.13

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

Not sure if this is an issue or I am missing something in my template.  I have a service template in which I have setup a range and calling all the global scopes using dollar "$"
```
{{- range .Values.ServiceConfig }}
kind: Service
apiVersion: {{ .apiVersion | default "v1" }}
metadata:   
  labels:
    app/kubernetes.io/name: {{ template "globalcharttemplate.name" $ }}
    app.kubernetes.io/version: "1"
> "using dot here to get the scope from range and template this value"
    newname: {{ template "globalcharttemplate.newname" . }} 

  name: {{ .name }}
  namespace: {{ $.Values.ApplicationConfig.namespace }}
 selector:
    appName: {{ template "globalcharttemplate.name" $}}{{ .suffix }}
    release: {{ $.Release.Name }}
```

My helpers.tpl, I defined a new template action like this:

```
{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "globalcharttemplate.newname" -}}
{{- if .names -}}
{{- .name -}}
{{- else -}}
{{- $.Chart.Name. -}} 
{{- end -}}
{{- end -}}
```

For the label new name, "." looks for the scope in range and gets the exact value from the array and successful.  However, for the if-else case, the chart name cannot be retrieved

error: executing "globalcharttemplate.newname" at <$.Chart.Name>: can't evaluate field Name in type interface {}

Please suggest me any better way for this if else case.

**Comment by bacongobbler** [comment]
FYI, I edited your comment to surround your examples in backticks. Makes it easier to read.

In a `define` function, the root (`$`) will become whatever was passed along from the template. In your first example, you passed the following:

```
newname: {{ template "globalcharttemplate.newname" . }}
```

The scope of the dot variable at that time was the value of `.Values.ServiceConfig`, so that was passed to the template.

In the template, it then looks for a value called `.Chart` at the root of that variable. It did not exist, and therefore did not execute.

If you need to pass along something further down the chain as well as the root context to a function, use [`dict`](http://masterminds.github.io/sprig/dicts.html) to construct a new variable that will contain the expected values.

Try this in your example:

```
newname: {{ template "globalcharttemplate.newname" (dict "names" .names "Chart" $.Chart "name" .name) }}
```

**Comment by bacongobbler** [comment]
closing as answered. Please let me know if you run into further issues. Thanks!

**Comment by vfiset** [comment]
Just so it's clear to other n00b-level people like me, from @bacongobbler awesome tip at the end of this [comment](https://github.com/helm/helm/issues/7634#issuecomment-617276047), if you want to use that you'll need to add this to your helper:
```
{{- $names := .names -}}
{{- $Chart := .Chart -}}
{{- $name := .name -}}
```

**Comment by Belorus** [comment]
This looks more like a bug, not a question

**Comment by sayan-biswas** [comment]
An absolute way is to merge both the scopes..

`{{ template "template-name" (merge . $) }}`

But you need to make sure that no common variables are there. Usually that's a known set of keys like "Values", "Charts", "Release" etc.
