### ISSUE TITLE
Provide automated plugin install/update downloads

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#7646]
Many pluigins have an install and update script that downloads a binary. For examples see [helm-diff](https://github.com/databus23/helm-diff), [helm-gcs](https://github.com/hayorov/helm-gcs), and many others that all use the same pattern (thought slightly different directory names).

In each install script case the script is a shell file that does not work on Windows.

How about we automate that so it works across all platforms and each plugin does not have to repeat the same pattern when they want to download things.

**Comment by bacongobbler** [comment]
I think this is the same problem [krew](https://github.com/kubernetes-sigs/krew) was attempting to solve for kubectl. It includes a bunch of kubectl-specific integrations, but we could utilize much of the same system for unpacking and installing plugins. [gofish](https://github.com/fishworks/gofish) was originally created from the same idea of fetching and unpacking packages in a universal way, and is another area where we could take inspiration from (disclaimer: I am the author of gofish).

The main issue with the current system has to deal with the format of the plugin.yaml: namely the install hook as well as the exec args. If we instead mentioned that a plugin.yaml defined where the plugin packages existed (like how a chart repository index tells us the URL to fetch the chart), we could provide a unified way to fetch and install plugins.

This was also the reason for #5514: by enabling a way to read plugins from across the filesystem, we could circumvent the `helm plugin install` system and rely on the OS's traditional package manager to install a plugin, though it boiled back down to the same issue: how do we look up the plugin.yaml for the plugin's exec args?

GoFish and Krew solved this problem by providing those metadata files in a central repository, much like a chart repository. For GoFish, these are lua files as [fish-food](https://github.com/fishworks/fish-food/ (see [helm.lua](https://github.com/fishworks/fish-food/blob/master/Food/helm.lua)), and krew's [krew-index](https://github.com/kubernetes-sigs/krew-index), which look very similar to Custom Resource Definitions.

I'm partial to the lua system for these metadata files, as it allows you some simple scripting abilities while providing the runtime some sandboxing guarantees, which is a sweet spot for giving users the capability to DRY up their metadata without compromising the OS.

Either way, by changing the format of the plugin.yaml to describe where to fetch the package URLs instead of describing the steps to install the package, we could provide a way to automate the install/update process across all three operating systems.

What do you think about that approach?

**Comment by bacongobbler** [comment]
closing as stale.
