### ISSUE TITLE
unable to rollback in helm v3

### ISSUE THREAD

**Issue by vinayus** [helm/helm#7676]
i'm trying explore the helm rollback as documented [here](https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches)

Here's what i'm trying. I deployed a helm chart. Using `kubectl edit ` i updated one of the deployment with a new env variable and also updated number of replicas to 5(from 1).

Now when i rollback, I don't see any change(remains as updated) in deployment or pod clearing themselves. They remain at 5 replicas and new env variable is still retained. Is this expected? Or am i missing something?

I even tried with a stable chart and they also end up same. Kindly suggest.

> helm history haproxy -n atom
REVISION        UPDATED                         STATUS          CHART           APP VERSION     DESCRIPTION
1               Tue Feb 25 01:12:33 2020        superseded      haproxy-0.1.0   1.0             Install complete
2               Tue Feb 25 06:31:35 2020        superseded      haproxy-0.1.0   1.0             Rollback to 1
3               Tue Feb 25 06:32:31 2020        superseded      haproxy-0.1.0   1.0             Rollback to 1
4               Tue Feb 25 06:35:01 2020        superseded      haproxy-0.1.0   1.0             Rollback to 1
5               Tue Feb 25 06:35:36 2020        superseded      haproxy-0.1.0   1.0             Upgrade complete
6               Tue Feb 25 06:35:58 2020        superseded      haproxy-0.1.0   1.0             Rollback to 1
7               Tue Feb 25 06:54:46 2020        superseded      haproxy-0.1.0   1.0             Rollback to 1
8               Tue Feb 25 06:55:37 2020        deployed        haproxy-0.1.0   1.0             Rollback to 1

Output of `helm version`: `version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `Centos kubeadm`

**Comment by mattfarina** [comment]
My first thought is that this has to do with the new [3-way merge patch](https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches) in Helm v3. This is important because of things like service meshes altering applications and needing those to live on.

I wonder if we need an option or documentation on forcing details from the chart to be restored.

**Comment by technosophos** [comment]
If you directly edit the objects in Kubernetes, then the rollback will try to consider those changes when rolling back. (As @mattfarina noted, this is the way the 3-way diff works). Once you've manually edited, rollback will be difficult because essentially it will run the "upgrade" logic with an old release, the current release, and the version you edited.

It is hard for us to be able to say what the desired behavior should be, since your manual editing (outside of the chart) does not give us any indication of what you _intend_ during a rollback. If, for example, we ignored your changes and just overwrote them, others would complain that their manual changes were overridden by Helm against their wishes. So we go with the safest route we can, and run a 3-way merge patch.

**Comment by bridgetkromhout** [comment]
The above explanations of how the three-way merge patch works seem to answer this question, so I'm resolving this issue.
