### ISSUE TITLE
Can't install plugins in Docker Container from upstream other than github. Error: Cannot detect VCS

### ISSUE THREAD

**Issue by Galileo1** [helm/helm#7679]
Unable to install helm plugins in docker container. The upstream setup in my organization is artifactory and we have a remote setup for github.  

When I try to install the helm plugins using the below command - 
`helm plugin install https://artifactory.xxx.xx.xx/generic-github-remote/databus23/helm-diff --version v3.0.0-rc.7`

Error I get is `Error: Cannot detect VCS`

KUBECTL_VERSION 1.15.0
HELM_VERSION 3.0.1
HELMFILE_VERSION 0.98.2

**Comment by mattfarina** [comment]
@Galileo1 I'll start by explaining what's happening and what you can do about it.

When you try to install a plugin Helm tries to figure out how to get it. It first looks for those on the local file system based on the path, then looks for those that are downloaded over http/https as tarballs. If neither of those cases are true it tries to fetch from the remote as it's a version control system (VCS).

The VCS support can fetch from 4 different VCS so it needs to figure out which it is. There are a number of rules and detection method. GitHub and Bitbucket, for example, are ones it can detect by name. In your case it was unable to detect the VCS from the available information.

**What you can do...** is give a little more help to Helm. For example, you can try modifying your URL to add `.git` to the end. Helm knows to try as a git repository in that case.

```
helm plugin install https://artifactory.xxx.xx.xx/generic-github-remote/databus23/helm-diff.git --version v3.0.0-rc.7
```

Or, you can change the scheme to `git://`.

Does either of these methods work?

I've marked this as a docs issue because it wasn't clear in the docs when I looked to provide a pointer.

**Comment by technosophos** [comment]
Closing this because the question was answered and the issue has been active for a long time.
