### ISSUE TITLE
Is there a way of getting release with 3-way merge computed manifest?

### ISSUE THREAD

**Issue by nij4t** [helm/helm#7694]
As I understood, `helm get` command fetches release object from the cluster?

https://github.com/helm/helm/blob/4c55073da4576782b6e3d70489713e7d2f74ddb1/pkg/action/get.go#L40-L46

https://github.com/helm/helm/blob/4c55073da4576782b6e3d70489713e7d2f74ddb1/pkg/action/action.go#L156-L166

https://github.com/helm/helm/blob/4c55073da4576782b6e3d70489713e7d2f74ddb1/pkg/storage/storage.go#L202-L214

**Comment by mattfarina** [comment]
I'm not entirely sure what you are asking for. Helm v3 uses a 3 way merge. So, an upgrade in Helm v3 will use it. Are you asking if there is a way see the 3-way merge patch that was created for a release? Helm does not store this information or even a separate list of manifests in a cluster because there is a finite amount of storage for each record as set by etcd.

As a feature it may be possible to add this on dry run. Or, a plugin could be created to figure this out. Is this the kind of thing you're asking about?

**Comment by bridgetkromhout** [comment]
Hi, @nij4t - we have resolved your issue due to inactivity. If you'd like to suggest feature changes, please file a [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md) to discuss it with the community. Thanks!
