### ISSUE TITLE
Support for .yml extension for Chart.yaml/value.yaml

### ISSUE THREAD

**Issue by Tom-Br** [helm/helm#7747]
Output of `helm version`: version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVe
rsion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVe
rsion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

I am trying to lint a local Helm chart. 

```
helm lint ./zookeeper
==> Linting ./zookeeper
Error unable to check Chart.yaml file in chart: CreateFile zookeeper\Chart.yml: The system cannot find the path specified.

Error: 1 chart(s) linted, 1 chart(s) failed

```

However if I run the same command with .yaml it works. Thus Helm is not handling .yml the same as .yaml

```
Y:\brecourt\infra\zookeeper\chart>helm lint ./zookeeper
==> Linting ./zookeeper
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist

1 chart(s) linted, 0 chart(s) failed
```

**Comment by anshulvermapatel** [comment]
Hello @Tom-Br 

Actually, as far as I know it has to be 'Chart.yaml' , you cannot have 'Chart.yml'.
You can check this [Doc page](https://helm.sh/docs/topics/charts/) .
@bacongobbler must agree with me.

**Comment by jdolitsky** [comment]
Certain files such as values.yaml, Chart.yaml are required by name (as noted above). Files in templates/ dir should be able to use the .yml extension if necessary.

@Tom-Br Going to close, renaming file to Chart.yaml should be the fix you need.

**Comment by astropuffin** [comment]
Every program I've every used has accepted `.yml` or `.yaml` as interchangeable. Why doesn't helm? It took me an hour to figure out what happened after I standardized my configs on the `.yml` extension. After doing so, helm just errored out with `Error: validation: chart.metadata is required`. Not helpful. It's not like "tabs vs spaces", but lots of folks prefer `.yml` because it's shorter. I can confirm that literarily _any other yaml file that helm references can use the `.yml` extension except Chart.yaml_ because it's using a standard yaml library.

Happy to open a PR against this if it will be accepted. Based on my (very quick) review, It would just need 1 line changes here: https://github.com/helm/helm/blob/0cb0eaca948d55da1c824f201aa78f9313763f69/pkg/chart/loader/load.go#L79 and here: https://github.com/helm/helm/blob/d0422e6d82b9d7ddc9c24f02ed1f7d321f9e2646/pkg/action/lint.go#L113, plus a few unit tests. There might be a couple other locations where `Chart.yaml` is hard coded.

**Comment by hickeyma** [comment]
@astropuffin Open an issue and it can then be considered by the maintainers.

**Comment by astropuffin** [comment]
@hickeyma I'm confused. I commented on _this_ issue rather than create a duplicate. Can you clarify?

**Comment by hickeyma** [comment]
@astropuffin I thought it would be better to raise a new issue whereby you ask explicitly for Helm support on .yml extensions on values and Chart files. This issue got closed out whereby the change to. yaml extension seems to have closed the issue.

**Comment by jdolitsky** [comment]
This might have some implications, I'm suspicious that it's not already the case. I'm thinking this might affect third party tooling looking for these file names. Maybe we can just show a more helpful warning if Chart.yml is detected?

**Comment by hickeyma** [comment]
I agree @jdolitsky, that there might be a reason for not supporting 'yml' extension. I would like to open it up to other @helm/helm-core-maintainers to see if there is a reason behind the decision. @bacongobbler @technosophos you might be best placed to shed some light on this.

**Comment by hickeyma** [comment]
ok, thanks for the background @bacongobbler

**Comment by hickeyma** [comment]
@astropuffin some background from @bacongobbler in https://github.com/helm/helm/issues/7747#issuecomment-651809839

**Comment by bacongobbler** [comment]
closing as something we do not plan to implement as described above.

**Comment by nathanbudd-geotab** [comment]
If it isn't worth the trouble to allow Chart.yml to be used, perhaps at least a more informative error can be thrown when this is the problem? I've just started using Helm. I was putting together my own chart and the error I saw was 
```
Error: validation: chart.metadata is required
```
It took a lot of searching and experimenting to figure out the source of the error was using Chart.yml instead of Chart.yaml.

**Comment by bacongobbler** [comment]
No, because then every program that consumes charts must now conform to this extension. It breaks backwards compatibility with programs that expected the .yaml extension as described in the chart package specification.

**Comment by bacongobbler** [comment]
Again please see my earlier comment: https://github.com/helm/helm/issues/7747#issuecomment-651809839

**Comment by nathanbudd-geotab** [comment]
Perhaps as something to be considered for the next major version then?

**Comment by bacongobbler** [comment]
Not enough of a demand for this feature, and there's a security risk to allowing multiple file types anyways. Consider that allowing multiple file extensions for a file could potentially allow a chart author to write a Chart.yaml, but an attacker could write a Chart.yml that would take priority over the first, resulting in a chart that could download dependencies the author did not intend.

**Comment by technosophos** [comment]
I will explain in more detail why there is no support for `Chart.yml` and why we are not going to add it. I am also working on improving the error message--which should definitely be better.

When you are supporting ad-hoc user files, it is good practice to support a broad variety of permutations. But when you are creating a specification, the opposite is true: You want to support a _very specific_ set of constraints, not a broad and loose set. The reasoning for this is to limit the amount of ambiguity required when dealing with the spec.

For example, imagine that we supported both `Chart.yaml` and `Chart.yml` in a chart. Now suppose that some chart supplied both a `Chart.yaml` AND a `Chart.yml`. Which one gets precedence?

First, the answer to that question is non-obvious. One can't simply say "the common sense answer is...." And that means that different implementations may choose different answer.

With that in mind, there are at least four answers to the question:

1. `Chart.yaml` always takes precedence
1. `Chart.yml` always takes precedence
1. The two should be merged (by some strategy that would then have to be defined)
1. A processor should fail with an error in this case

I am sure that readers of the above will have lots of differing ideas as to which of those three is the "correct" one, and opening that can of worms is a chore in itself. But even assuming we answered that question, it then has to be uniformly adopted by all of the tools in the Helm ecosystem. Failure to do so could lead to, in the worst cases, security problems (where bad stuff is hidden in one of the two, targeting just some tools in the ecosystem). But even in less serious cases, it will lead to confusion/bugs.

Regardless of which we chose, people would be unhappy and we would end up with issues complaining that we should have picked `.yml` or we should have done a merge, etc. So in some sense, while we might "solve" one person's inconvenience, we would certainly not "solve" the situation once and for all. We'd merely shift the debate to another question.

In addition, adding support for both extensions does introduce additional code to Helm, which means more opportunities for things to break inside of Helm.

So if we were to support both extensions, we would introduce at least two new problems (difficulty of implementing consistent behavior across all Helm tooling and increased code weight to Helm) while only moving the debate over whether it should support `.yml` to a debate on whether any one solution to how we handle it is better than the other three solutions.

Just to quickly address the `values.yaml` one -- for the file _inside_ the chart, all of the same considerations for Chart.yaml apply to values.yaml. For _outside_ the chart (e.g. with the `-f` flag), we accept any extensions. Why? because in that case, the user handles the ambiguity for us. If a user says "my values are stored in values.foo", we don't have to ask any additional questions. We can just proceed to the next step and try parsing the file.

In the end, while I agree that error messages could (and should) be improved, supporting more file extensions is not something we are likely to do now or ever.

**Comment by aleksandaratanasov** [comment]
@technosophos  Something like "Are you using the correct file extension?" would be much appreciated Frankly, now that I know that `yml != yaml` in Helm and if I encounter this issue on a regular basis I will be able to find the source of the problem easily. However for first time encounter as well as rare encounters all together it is very easy to not see the problem with the file extension.
