### ISSUE TITLE
helm 3.1.2 --> upgrade command --set flag does not override the supplied value

### ISSUE THREAD

**Issue by fortanu82** [helm/helm#7864]
Output of `helm version`: v3.1.2+gd878d4d

Output of `kubectl version`:
Client Version: v1.17.0
Server Version: v1.16.4

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

My requirement is to update an image tag generated at run time in Azure Devops though when I try to execute upgrade command with --set flag option it does not override the specified value.
I knew it was working in Helm2 but having an issue running in Helm3. Does this feature work in Helm3?

Deployment manifest file looks like

![image](https://user-images.githubusercontent.com/48510516/78350965-ab3a0400-75c3-11ea-95b5-90708bbc548f.png)

Running these commands don not override the image.tag:

> helm upgrade resources-dev resources --set image.tag=72615 --reuse-values
![image](https://user-images.githubusercontent.com/48510516/78351307-31eee100-75c4-11ea-8dec-a63cb07d900e.png)

> helm upgrade resources-dev resources --set-string image.tag=72615

![image](https://user-images.githubusercontent.com/48510516/78351374-4af79200-75c4-11ea-84dd-fd5b5773b1a3.png)
![image](https://user-images.githubusercontent.com/48510516/78351556-9dd14980-75c4-11ea-80c0-3f79f47d3ac8.png)

**Comment by bacongobbler** [comment]
I cannot appear to reproduce the latter issue, but I was able to reproduce the issue with `--reuse-values`.

Here is what I tested:

```
$ cat test-7864/values.yaml | head -n 10
# Default values for test-7864.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: "1234"
  pullPolicy: IfNotPresent

$ cat test-7864/templates/deployment.yaml | grep "image:"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

$ helm template test-7864/ --show-only templates/deployment.yaml | grep "image:"
          image: "nginx:1234"

$ helm template test-7864/ --set image.tag=4321 --show-only templates/deployment.yaml | grep "image:"
          image: "nginx:4321"

$ helm template test-7864/ --set-string image.tag=4321 --show-only templates/deployment.yaml | grep "image:"
          image: "nginx:4321"
```

But when I try your `--reuse-values` example:

```
$ helm upgrade test-7864 test-7864 --reuse-values --set image.tag=4321
Release "test-7864" has been upgraded. Happy Helming!
NAME: test-7864
LAST DEPLOYED: Fri Apr  3 08:11:43 2020
NAMESPACE: default
STATUS: deployed
REVISION: 3
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=test-7864,app.kubernetes.io/instance=test-7864" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:80

$ helm get values test-7864
USER-SUPPLIED VALUES:
null

$ k get po test-7864-d44cdb876-q2p9c -o jsonpath='{.spec.containers[0].image}'
nginx:1234
```

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/pull/6917 seems relevant here.

**Comment by fortanu82** [comment]
Thanks for your response. In my case even without the --reset-value flag, --set value does not override the image.tag mentioned in the deployment file.

I hope you have tested this on the latest version of 3.1.2. Please see the steps performed in the screenshot below.
1. Uninstall the releases if any.
2. Check history to ensure no release exist
3. upgrade/install with --set variable
4. Verify the results in deployment file where it does not override the value though, it shows in the User supplied value.

**UnInstall and Upgrade**
![image](https://user-images.githubusercontent.com/48510516/78452235-c8480300-76a7-11ea-9ae5-f703c0b18710.png)

**Get Results**
![image](https://user-images.githubusercontent.com/48510516/78452251-e1e94a80-76a7-11ea-93f2-322261cf26fe.png)

**Deployment Results**
![image](https://user-images.githubusercontent.com/48510516/78452324-502e0d00-76a8-11ea-9a93-b96343ab4ce4.png)

**Helm - Values.Yaml file**
![image](https://user-images.githubusercontent.com/48510516/78452398-b3b83a80-76a8-11ea-85fc-b8ae5f997a54.png)

**Comment by technosophos** [comment]
Text would be preferred to screenshots. We cannot copy and paste the text from a screenshot.

Okay, here are the steps I took to reproduce:

```console
$ helm version
version.BuildInfo{Version:"v3.1+unreleased", GitCommit:"c12a9aee02ec07b78dce07274e4816d9863d765e", GitTreeState:"clean", GoVersion:"go1.14.1"}
```

(I am running on `master`)

1. `helm create test-7864`
2. Delete all the default templtes: `rm -rf test-7864/templates/*.yaml test-7864/template/NOTES.* tests`  
3. Create a new template called `example.yaml` whose content is `tag: {{.Values.image.tag}}`
4. Create a new values.yaml that sets `images.tag` to `1234`

Okay, with those steps, I can run `helm template ./test-7864` and get this:

```
---
# Source: test-7864/templates/example.yaml
image: 1234
```

Now I can do a `--set image.tag=4321`:

```console
$ helm template test-7864 --set image.tag=4321
---
# Source: test-7864/templates/example.yaml
image: 4321
```

So the core `--set` logic is overriding the correct field. I can do the same with `--set-string`:
```console
$ helm template test-7864 --set-string image.tag=4321
---
# Source: test-7864/templates/example.yaml
image: 4321
```

I can also override from a values file:

```yaml
image:
  tag: 5678
```

Then:

```console
$ helm template ./test-7864 -f values-7864.yaml --set image.tag=72615
---
# Source: test-7864/templates/example.yaml
image: 72615
```

Note that in the above case, `--set` overrode both the built-in value and the value in the supplied `values-7864.yaml` file.

So far, so good. So how about on a `helm upgrade --install`? First, `helm upgrade` will validate the schema, so I need to use a valid Kubernetes object. `Secret` is the easiest. So here is my new template:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-7864
stringData:
  image: {{.Values.image.tag | quote }}
```

Having verified that all still looks right with `helm template`, I can run `helm upgrade --install`

```console
helm upgrade --install --dry-run MYTEST ./test-7864 -f values-7864.yaml --set image.tag=72615
Release "MYTEST" does not exist. Installing it now.
NAME: MYTEST
LAST DEPLOYED: Mon Apr  6 17:29:52 2020
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: test-7864/templates/example.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-7864
stringData:
  image: 72615
```

Once again, the output is as we expect. So now I will install and then upgrade.

```console
$ helm upgrade --install mytest ./test-7864 -f values-7864.yaml --set image.tag=7777
Release "mytest" does not exist. Installing it now.
NAME: mytest
LAST DEPLOYED: Mon Apr  6 17:33:57 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

That worked, and using `kubectl get secret test-7864, I can verify that the value was set to 7777. And now an upgrade:

```console
$ helm upgrade --install mytest ./test-7864 -f values-7864.yaml --set image.tag=8888
Release "mytest" has been upgraded. Happy Helming!
NAME: mytest
LAST DEPLOYED: Mon Apr  6 17:34:50 2020
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
```

Once again, I can use `k get secrets -o yaml` to verify that the data is now 8888.

So I can't reproduce the error either. But I have just given you a detailed way for you to test and see if you can isolate the issue. It is possible that you have found a bug on Windows that does not impact UNIX/Linux/macOS.  Or it may be as simple as you not using `{{ .Values.image.tag | quote}}` on the `.Values.image.tag`. But our next step in solving the problem is testing to see if the process I just gave you will cause the error on your environment or not.

**Comment by fortanu82** [comment]
I tested it and identified the problem. Your step by step explanation helped a lot.
The problem is not with a --set flag but with the kind of directory structure I have for charts.

while executing the command  **helm upgrade resources-dev resources --set image.tag=72615** from one level up where resources (charts) folder is, it looks for image.tag in "Values.yaml" file of resources folder and not the "Values.yaml" file of backend folder and thus the tags are not replaced.

By executing the below command with **backend.imge.tag** worked

> helm upgrade resources-dev resources --set **backend**.image.tag=72615

 ![image](https://user-images.githubusercontent.com/48510516/78971978-5863cd80-7b2a-11ea-8754-a5555e1acc56.png)
 
Thanks for your help.
