### ISSUE TITLE
Potential issue: --atomic --cleanup-on-fail invoke a rollback without --cleanup-on-fail

### ISSUE THREAD

**Issue by consideRatio** [helm/helm#7876]
I think a `helm upgrade --atomic --cleanup-on-fail` that results in a rollback could run into an unexpected issue.

- `--atomic`'s rollback operation is not influenced by `--cleanup-on-fail` passed to the upgrade command (ref: [code](https://github.com/helm/helm/blob/c12a9aee02ec07b78dce07274e4816d9863d765e/pkg/action/upgrade.go#L318-L331)).
- If the `--atomic` invoked rollback fail, it will not `--cleanup-on-fail` (ref: [code](https://github.com/helm/helm/blob/c12a9aee02ec07b78dce07274e4816d9863d765e/pkg/action/upgrade.go#L353-L359))
- It is possible to have `--cleanup-on-fail` be part of a rollback operation (ref: [code](https://github.com/helm/helm/blob/c12a9aee02ec07b78dce07274e4816d9863d765e/pkg/action/rollback.go#L34-L45))

I expected the `--cleanup-on-fail` to pass through also to the rollback operation if used in conjunction with `--atomic`. I'm not confident it will matter, but could perhaps the rollback operation render new templates that would fail to be cleaned up?

To figure that out, i guess it may be relevant to consider the [built in objects](https://helm.sh/docs/chart_template_guide/builtin_objects/) and [chart hooks](https://helm.sh/docs/topics/charts_hooks/).

---

Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Comment by technosophos** [comment]
I am not sure I follow the logic there. Can you produce a proof-of-concept?

It is definitely (under a wide variety of circumstances) possible to have a rollback fail. But when a rollback-on-failure fails, the behavior of the cleanup is very tricky. It is not at all clear what a user expects in that scenario. Our strategy in these cases is to not clean up after a failed rollback because a failed rollback may indicate that something is really wrong. We treat `--cleanup-on-fail` as only applying to the requested release, not the rollback if the requested release fails.

I am not sure if you are suggesting a way to improve this, or merely suggesting that we should change the meaning of `--cleanup-on-fail` to include cleaning up failed rollbacks (which sounds possibly too destructive to me). But an example case might help clarify things for me.

**Comment by consideRatio** [comment]
@technosophos my main personal concern was that it was too much ambiguity of how --cleanup-on-fail worked.

I've not experienced an issue from a failing rollback with `--atomic` and have no input on what is the best default behavior. But, if the default doesn't involve `--cleanup-on-fail` for the atomic rollback operation even though `--cleanup-on-fail` was specified (and applied for the upgrade operation), I think that should be documented within the CLI's --help text that it only applies to the new resources in the upgrade, but not the potential rollback caused by `--atomic`.

**Comment by technosophos** [comment]
Yeah, for sure it should be documented.

It is possible that our assumptions about rollbacks are wrong. Recovery is definitely a tangled web.

**Comment by bridgetkromhout** [comment]
Removing `stale` label as I intend to document.
