### ISSUE TITLE
Why to need specify CHART for upgrade operation?

### ISSUE THREAD

**Issue by heckad** [helm/helm#7877]
I have a chart wich described my microservice app and I want to update image tag. I expect something like `helm upgrade my_app_relese --set=microservice_name.image.tag=$image_tag` but this not correct. I should add the chart for this command. To do this, I will have to add the chart to all my microservice repositories. 

1) Is there a better way to avoid this? 
2) Why doesn't helm keep the chart with the release? 
3) Why does `--set` option overrides all values?

**Comment by hickeyma** [comment]
@heckad Some answers to your question below.

> Why doesn't helm keep the chart with the release?

Yes, it keeps the chart manifests from the previous deployment. You need to pass the chart again during an upgrade so that Helm can work out the delta.

> Why does --set option overrides all values?

It should not override all values. It will only set the values you specify and use the default (`values.yaml`) values otherwise. If you set specific values in the previous deployment then use `--reuse-values` flag to reuse them. 

You can get more background from the [Helm docs](https://helm.sh/docs) in [sections like this](https://helm.sh/docs/intro/using_helm/#helm-upgrade-and-helm-rollback-upgrading-a-release-and-recovering-on-failure)

**Comment by heckad** [comment]
Thank you for your answer!

> Yes, it keeps the chart manifests from the previous deployment. You need to pass the chart again during an upgrade so that Helm can work out the delta.

If I want to change the only image teg why helm needs chart? I didn't change the chart. Can it be a feature request?

**Comment by technosophos** [comment]
The Helm chart is required because it Helm must render all of the templates in order to calculate the diff. Without inspecting the chart, it can't tell if your one `--set` function will change a single thing, or many many things. So it must render the templates.

Rather than storing the chart in every Git repo, we suggest storing the chart in a Helm chart repository and adding that repository to the Helm client's list of chart repositories.

https://helm.sh/docs/topics/chart_repository/

**Comment by hickeyma** [comment]
@heckad I hope this has helped to answer your questions? Let me know if you have any other questions.

**Comment by heckad** [comment]
> The Helm chart is required because it Helm must render all of the templates in order to calculate the diff.

Why you can't use chaced chart version if a user does not specify chart? More clearly question: Why is the chart a required field, not optional?

**Comment by bacongobbler** [comment]
[As mentioned earlier](https://github.com/helm/helm/issues/7877#issuecomment-609642995), Helm does not save the pre-rendered templates from your chart in Kubernetes. The only objects saved are the [rendered manifests](https://github.com/helm/helm/blob/c12a9aee02ec07b78dce07274e4816d9863d765e/pkg/release/release.go#L32-L33), which are needed to compute the delta between the chart you are upgrading from (the manifests) with the chart you are upgrading to (the chart provided with `helm upgrade`).

That is why the chart is a required field.

Hope this answers your question.

**Comment by bacongobbler** [comment]
Since there are no action items to follow up on, I'm going to go ahead and close this. Thank you for your question.

**Comment by omkensey** [comment]
Helm does seem to save the raw templates in the release's history.  I have a release of the Bitnami redis chart in my cluster -- if I run:

```
kubectl get secret sh.helm.release.v1.redis.v2 -o json | jq -r .data.release | base64 -d | base64 -d | gunzip | jq -r '.chart.templates[] | select(.name == "templates/redis-with-sentinel-svc.yaml").data' | base64 -d
```

...I see an unrendered template of a service.  (Omitting `| select(.name == "templates/redis-with-sentinel-svc.yaml").data` and the final pipe to `base64 -d` shows the base64 blobs of all the templates.)
