### ISSUE TITLE
dry-run does not validate helm chart

### ISSUE THREAD

**Issue by RomanDvorsky** [helm/helm#7880]
Hi,

I did set up in our azure pipeline the `helm upgrade` command with `--dry-run` to validate the helm chart before it is used. I have discovered that this is not the best approach - is there any better way how to validate the helm chart in azure pipelines?

I have discovered a few things which are not validated - is this intended - the dry-run should not be used for validation?

**1. issue: wrong secrets name** 
`
Error: create: failed to create: Secret "sh.helm.release.v1.ncboilerplate-dev-BuildHelm.v1" is invalid: metadata.name: I
nvalid value: "sh.helm.release.v1.ncboilerplate-dev-BuildHelm.v1": a DNS-1123 subdomain must consist of lower case alpha
numeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used fo
r validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
`
with the `--dry-run` all went fine

**2. issue: missing spec.containers in the pod specification**
`
Error: Pod "ncboilerplate-dev-buildhelm-ncboilerplate" is invalid: spec.containers: Required value
`
again with `--dry-run` all went fine

Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersio
n:"go1.13.5"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aefa
ce6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/a
md64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe
4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/am
d64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

thx,
R.

**Comment by glueric** [comment]
Dry-run merely checks if the manifest output is valid yaml. To verify your chart you can use helm lint.

**Comment by technosophos** [comment]
The reason for this is that `helm template` and `helm ... --dry-run` do not require that you be attached to a Kubernetes cluster. However, to validate the YAML, a client must use the Kubernetes Discovery API to fetch the object types that are supported by the instance of Kubernetes you are validating against.

Here are two examples of why this is so:
- CRDs: We cannot validate whether a YAML document matches a CRD unless we can connect to the server and fetch the CRD, then validate against it.
- Changing APIs: In Kubernetes 1.17, several objects that used to be legal (extensions/v1beta1 Deployments, for example, but many others as well) were no longer legal. Helm has to connect to a cluster to see what version of Kubernetes is running, and which API versions/kinds are allowed.

In general, it is undesirable for a client to connect to a live cluster during "dry run" operations because that requires that the client have credentials.

So, that's the reasoning. As @glueric  says,`helm lint` is probably your best choice for doing more validation. But I am not totally sure that it validates content, either. It does check for a few common mistakes, though.

**Comment by bacongobbler** [comment]
There's `helm template --validate` which can be used against live clusters, too. That flag will connect to the cluster and validate your templates against the cluster's OpenAPI schema.

**Comment by technosophos** [comment]
Okay, I have to reverse what I said before: `helm template` does NOT validate, `helm install --dry-run` DOES validate. However, it only validates the scheme. It cannot validate the values provided. So the error initially reported has passed schema validation, but fails because a value is incorrect. That failure comes from the Kubernetes API server directly.

**Comment by RomanDvorsky** [comment]
Ok, I had an impression from azure pipelines (from HelmDeploy@0 task) that it's validated against the cluster - because the task requires the cluster connection even for the dry run but I guess the task does not know whether it is a dry run or not.

@bacongobbler (or any other experienced enough) - hi :) - how the `helm template --validate` works? Does it take the current default cluster connection? any tip on how to plug this to the azure pipeline? 
The set of commands for helm is quite limited there 
![image](https://user-images.githubusercontent.com/36188474/78634778-fc3c4780-78a4-11ea-9d1e-6f85c8536126.png)
If I use some bash command I would need to insert the cluster credentials I guess or any tip on how to use the service connection for the cluster? I would like to avoid to insert the cluster credentials into the pipeline again.

Anyway, thx to all a lot for your responses - it helped me to understand the problem I'm facing.

**Comment by RomanDvorsky** [comment]
So I did some testing and neither `helm lint` or `helm template --validate` does validate these issues 😞.

however `helm lint` gives me a nice hint instead 😄:
![image](https://user-images.githubusercontent.com/36188474/78635469-99e44680-78a6-11ea-877b-cc4b7e86414c.png)

**Comment by technosophos** [comment]
Helm does _schema validation_, but does not have the ability to determine if a given value will cause Kubernetes to reject it.

To clear up any confusion:

- `helm install` turns has validation on by default, even when you add `--dry-run`
- `helm template` has validation off by default
- `helm template --validate` turns on validation
- All three of these just call into the same object (`pkg/action.Install`), passing it different flags. You can trace the `ClientOnly` flag through there.

But all validation there is just _schema_ validation, not data validation.

`helm lint` has a number of special purpose linters that catch common mistakes. It can often catch things that `helm install|template` would not catch. In your case, it happens to not catch your error.

Now, on to the error you are seeing:

Your error comes from the Kubernetes API, which enforces constraints on fields that are not part of the schema validation. We do not test for those because they are not part of the schema (and we'd just be guessing in many of the cases, since those constraints are not "frozen" in Kubernetes, but occasionally change from release to release). And what do we use to do our testing? The upstream Kubernetes validation logic that `kubectl` uses. So any issue you have here will be reproducible in `kubectl` as well.

If you would like to take a look at the schema validation logic, it is in the Kubernetes libraries here: https://github.com/kubernetes/kubectl/tree/master/pkg/validation. Perhaps you can persuade them to improve the validation logic to do what you are asking above.

If you want to open a PR that adds a _linting test_ for your issue, that would be welcomed. But we do not have plans to add on our own layer of validation, as it will become a major burden to keep it in sync with Kubernetes changes version-to-version.

**Comment by RomanDvorsky** [comment]
Thx guys for your comments and especially thx to @technosophos for the detailed explanation - all is clear and I'm closing my question.
