### ISSUE TITLE
Embedding The Icon

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#7976]
There is a use case to embed an icon in the chart.

The case is for charts that could be used offline (e.g., airgapped environments).

I can see two ways to accomplish this.

1. Use a [DataURL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) and embed it on the `icon` property in the `Chart.yaml` file.
2. Add the ability to have an icon file to the packaged chart.

Thoughts? Implications?

**Comment by bacongobbler** [comment]
duplicate of https://github.com/helm/helm/issues/2943?

**Comment by bacongobbler** [comment]
Given the discussion in https://github.com/helm/helm/issues/2943#issuecomment-331515888, I'm wondering if the chart icon should be part of the chart repository index instead of the chart itself, and if so, perhaps the proposal of a localized icon reference should be part of that discussion.

Then again, that would be a breaking change and would likely warrant a change in Helm 4. Hopefully that gives some extra food for thought.

**Comment by mattfarina** [comment]
@bacongobbler I can head over there and comment. It shouldn't be part of the repository because that will not work for OCI registries.

I'll close this as a duplicate.
