### ISSUE TITLE
etcdserver: request timed out

### ISSUE THREAD

**Issue by ghost** [helm/helm#7992]
Hello team,

I recently started to hit on my k8s cluster "etcdserver: request timed out" issue during deployment with helm.

Is there any option that helm has to be resilient to failure? (ex: retry x times before)

```
[centos@k8s-master-worker ~]$ helm history metrics-server -o yaml
- appVersion: "1.0"
  chart: metrics-server-0.1.3
  description: 'Release "metrics-server" failed: etcdserver: request timed out'
  revision: 1
  status: FAILED
  updated: Wed Mar 25 13:10:24 2020
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"524294565799aba901a242fb7a12cef454c9cb10", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:40:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): **OpenStack/kubespray**

Thanks,
Alex

**Comment by technosophos** [comment]
Not enough information to reproduce/troubleshoot/etc. You will need to provide substantially more information.

Helm never touches etcd directly. That's a Kubernetes implementation detail that is bubbling up from the Kubernetes API server. You may have to experiment with reproducing this using `kubectl` and trying to pinpoint why etcd is timing out.

**Comment by alita91** [comment]
An etcd server is very sensitive to disk latencies. Because I have a slow disk, I can easily reproduce the **etcdserver: request timed out** issue when I try to deploy a service to my cluster, one example is oracle-xe-11g-r2. 

This issue can be also reproduced if we deploy the service using kubectl.

I was looking for a solution in helm that is able to recover from such issues and have the ability to retry until it reaches a given timeout period.

If nothing can be done from your perspective and you think that this needs to be addressed from the Kubernetes API server itself, we can close the issue.

**Comment by bridgetkromhout** [comment]
Hi, @alita91 - have you looked into `--wait`? Perhaps that may help in this case: https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback

**Comment by invidian** [comment]
We also hit this sometimes when installing charts, for example on AKS. It's a transient error, it would be great to actually retry on it.

**Comment by invidian** [comment]
Another issue "solved" by @github-actions :disappointed:

**Comment by minhnguyenvan95** [comment]
so sad
