### ISSUE TITLE
Improve configuration ergonomics for the v3 library

### ISSUE THREAD

**Issue by lucperkins** [helm/helm#8030]
I'm attempting to use Helm v3 as a library to build a Go deployment client for a Kubernetes project I'm hacking on. One stumbling block I've run into thus far is configuration. The Helm CLI currently uses a heavily [environment-variable-centric approach](https://github.com/helm/helm/blob/master/pkg/cli/environment.go#L61-L83) to client configuration (`HELM_NAMESPACE`, `HELM_PLUGINS`, etc.).

This is totally fine from an end user perspective, as far as I can tell, but it's not ideal for using Helm as a library. I think a more ergonomic approach for library users would be to:

1. Create a `Settings` struct with all the required options that devs can populate however they like (env vars, YAML, hard-coded values, etc.)
2. Retain the current env var system as the default for the current Helm CLI.

I think this approach would entail *zero* perceptible changes to end users while helping to fulfill one of the stated goals of the v3 effort.

To be clear, I'm happy to take on this work myself if such a decoupling were blessed by project maintainers.

cc @lachie83

**Comment by bacongobbler** [comment]
We'd appreciate efforts to improve the situation. If you can write test cases and/or documentation to demonstrate how users should use these changes would be much appreciated.

For example: https://helm.sh/docs/topics/advanced/#simple-example

**Comment by mattfarina** [comment]
@lucperkins can you share a little of what you're trying to do? What you linked to is in the `cli` package which is tooling to support CLIs rather than using the Helm package in another form.

There are two flows for environment variables. Environment variables coming in and environment variables going out. Any solutions needs to preserve them going out so that things like plugins can have them passed. The big issue is the configuration coming in.

For the configuration coming in there are a couple ways this could be handled (thinking off the top of my head). First, there could be a new constructor to go alongside `New`. Second, the EnvSettings could be turned into an interface. The other places in the code that consume it could consume the interface and the `cli` package could be the one place that pulls it in using environment variables. Another one that sets things up differently could be created.

This is just me spit balling. Hope it helps.

**Comment by bridgetkromhout** [comment]
Hi, @lucperkins - I understand you may be working on other things at this point. If we can help you move forward with your ideas, I would suggest filing a proposal: https://github.com/helm/community/blob/master/hips/hip-0001.md - until such a time, I'll resolve this issue. Thanks!
