### ISSUE TITLE
[bug] invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dineshkumar181094** [helm/helm#8045]
I have two file to override the values.
file1.yaml file2.yaml

when I am using command  helm command it crashes.
helm install ./ --dry-run --debug--values file1.yaml --values file2.yaml.
**Error: rendering template failed: runtime error: invalid memory address or nil pointer dereference**
later i realised I was passing wrong key in file2.yaml was not there in base values.yaml in chart.
Ideally it should throw me useful error message instead of crashing.
It took me couple of to realize that error in file2.yaml.

Output of `helm version`: v2.12.1

Output of `kubectl version`: v1.15.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS

**Comment by bacongobbler** [comment]
@dineshkumar181094 have you tried this with a more recent version of Helm? We ask for users to please attempt to reproduce the bug with the most recent version of Helm 2 or Helm 3.

Let us know what you find out. If you can try and reproduce an example that demonstrates the issue, that would be helpful. Based on what has been provided here, we cannot share much else as we cannot reproduce the issue without a better understanding of the problem. Thanks.

**Comment by bridgetkromhout** [comment]
Hi, @dineshkumar181094 - thanks again for reaching out. As stated above, we will be happy to help, but we need to be able to reproduce the error in a more recent version of Helm. As Helm 2 is now getting security fixes only (but no more bugfixes - see https://helm.sh/blog/helm-v2-deprecation-timeline/), we would need to see this happening in Helm 3. Please let us know if you can reproduce it in Helm 3; we'll close this issue now due to lack of further information.
