### ISSUE TITLE
I'm trying to install ibm/chart using helm in minikube on my window 10

### ISSUE THREAD

**Issue by bztech1** [helm/helm#8049]
when I run the below command, I'm getting d/t response error. any idea ?C:\Windows\system32>helm install C:\Users\user\Desktop\charts-master\charts-master\stable\ibm-ace-server-dev\charts\ibm-sch-1.2.16.tgz Error: release xrayed-lambkin failed: no objects visited 
 C:\Windows\system32>helm install C:\Users\user\Desktop\charts-master\charts-master\stable\ibm-ace-server-dev\charts\ibm-sch-1.2.16.tgz Error: release tailored-octopus failed: no objects visited 
 C:\Windows\system32>helm install C:\Users\user\Desktop\charts-master\charts-master\stable\ibm-ace-server-dev\charts\ibm-sch-1.2.16.tgz Error: release roiling-waterbuffalo failed: no objects visited 
 C:\Windows\system32>helm install C:\Users\user\Desktop\charts-master\charts-master\stable\ibm-ace-server-dev\charts\ibm-sch-1.2.16.tgz Error: release dangling-duck failed: no objects visited

**Comment by bacongobbler** [comment]
hi @bztech1. First things first. Can you please share what version of Helm you are using? Please make sure you are testing with the latest version of Helm 3 (at the time of writing, Helm 3.2.0 is the latest).

Let us know how it goes. Thanks.

**Comment by bridgetkromhout** [comment]
Hi, @bztech1 - it is difficult to diagnose this accurately without the helm version and the chart.

A few things to think about:  `Error: no objects visited` sometimes happens if your chart is missing a required value or if Helm has no resources (in this case, Kubernetes manifests) to install into the cluster. If rendering the chart is not producing any Kubernetes resources, you may be able to diagnose this with `helm lint`.

Finally, it appears (based on the generated release names) that you may be using Helm v2. Please be sure to test with Helm v3: https://helm.sh/blog/helm-v2-deprecation-timeline/

I'll resolve this issue now; please let us know if you can provide the helm version and chart in question.
