### ISSUE TITLE
Installing v3.1.0 through the get-helm-3 script installs v2.16.7

### ISSUE THREAD

**Issue by dv-bv** [helm/helm#8069]
**Issue description**
Bash script that is used to install v.3.1.0 for some reason tries to install v2.16.7 of Helm.

**Steps to reproduce**
`$ curl https://raw.githubusercontent.com/helm/helm/v3.1.0/scripts/get-helm-3 | bash`

**Expected behaviour**
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6617  100  6617    0     0  11803      0 --:--:-- --:--:-- --:--:-- 11795
Helm v3.1.2 is available. Changing from version v3.1.1.
Downloading https://get.helm.sh/helm-v3.1.2-darwin-amd64.tar.gz
```

**Actual behaviour**
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6617  100  6617    0     0  11803      0 --:--:-- --:--:-- --:--:-- 11795
Helm v2.16.7 is available. Changing from version v3.1.2.
Downloading https://get.helm.sh/helm-v2.16.7-darwin-amd64.tar.gz
```

**Comment by bacongobbler** [comment]
please use master.

**Comment by dv-bv** [comment]
I'm locking to specific version of helm in CI since helm is not backward compatible across minor versions and using master is probably not really an appropriate solution. 

I understand what the issue was and why it won't be fixed in previous versions but at least proper communication would be sufficient - this script is primarily used within the CI pipelines, and currently might be breaking stuff for people without obvious for them reasons.

**Comment by omkensey** [comment]
You can still use the master-version script to install any arbitrary version of Helm 3 -- e.g.:
```
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | DESIRED_VERSION="v3.1.0" bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6822  100  6822    0     0  12132      0 --:--:-- --:--:-- --:--:-- 12138
Downloading https://get.helm.sh/helm-v3.1.0-linux-amd64.tar.gz
Preparing to install helm into /usr/local/bin
[sudo] password for kensey:
...
```

If you want to make sure you can pin to a specific master script, you can either copy it to your own repo somewhere, or just refer to it by commit hash:

```
curl https://raw.githubusercontent.com/helm/helm/8e1c34e/scripts/get-helm-3 ...
```

**Comment by bacongobbler** [comment]
Apologies for the short answer. I'll provide a longer explanation for why you should use master.

The reason why I don't recommend pinning to a particular version of the `get-helm-3` script is because the script relies on scraping github's `/releases` page to fetch the latest version. The web page output is not documented, and as a result, the "fetch me the latest version" functionality that script provides can be unstable at times.

Before anyone asks: we cannot use `api.github.com`. Clients at companies downloading Helm more than 60 times per hour (like in a CI pipeline) would be IP blocked, as github's public API will not allow you to make more API calls than 60 per hour unless you authenticate with an API key. So we're relying on the public web pages instead to work around this limitation.

The issue you experienced in the OP is because after Helm 3 was released, we released patches for Helm 2. Helm 2.16.7 was released earlier this week, and so it was the last release to be published, which the script then took to be the latest Helm 3 release. Both https://github.com/helm/helm/commit/0087d838073abcc93fb9ea694256e0b93238ae23 and https://github.com/helm/helm/commit/8e1c34ef045b350c68974f8ca12e2cb6d245d3f3 were committed to the script after Helm 3.1.0 was released, both of which fix up certain misunderstandings with the web page's output.

@omkensey is right as well, and in fact that same reason can avoid this issue altogether. If you set `DESIRED_VERSION` prior to running `get-helm-3`, all of the web scraping functionality is bypassed as `get-helm-3` will not have to scrape github's release page to determine what release to fetch. However that may a blocker depending if you rely on the "fetch the latest release" functionality the script provides.

Hope this helps.
