### ISSUE TITLE
Upgrade only subchart

### ISSUE THREAD

**Issue by davorceman** [helm/helm#8103]
Output of `helm version`: 
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

Hello, recently I started using helm, and I'm a little bit confused about subcharts.
My initial idea was to have everything related to application I need in one chart, in it's subcharts. And after that doing CI/CD for applications referencing only to subcharts.

What I did so far.
I created chart with subcharts like this.
```
$ tree
.
├── charts
│   ├── adminapi
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   └── adminapi.yaml
│   │   └── values.yaml
│   ├── backendapi
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   └── backendapi.yaml
│   │   └── values.yaml
│   ├── ingress
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   └── ingress.yaml
│   │   └── values.yaml
│   ├── mongo
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   └── mongodb.yaml
│   │   └── values.yaml
│   ├── secrets
│   │   ├── Chart.yaml
│   │   ├── templates
│   │   │   └── secrets.yaml
│   │   └── values.yaml
│   └── frontend
│       ├── Chart.yaml
│       ├── templates
│       │   └── frontend.yaml
│       └── values.yaml
├── Chart.yaml
├── templates
│   └── namespace.yaml
└── values.dev.yaml
```
I deployed this with
`helm install my-app . --values values.dev.yaml`

after this I have everything up and running, and I just wanted to update image tag of my frontend application.
I tried with this
`helm upgrade my-app charts/frontend/ --values values.dev.yaml --set global.Frontend.Docker.Tag="latest"`
But this does not works. It's deleting complete namespace.

I  see that there is some "umbrella" way, and dependencies but I don't get it.

So... My initial idea was to have everything on one place just in case of disaster recovery, and when I want to update only my application, secrets, or ingress, I just wanted explicitly to run only subchart.

Can someone direct me how to do this, with referencing some live example?

Thx

**Comment by technosophos** [comment]
An upgrade should not be deleting a namespace. So something is wrong there. 

The usual way Helm works during upgrade is by reading your current Helm installation, and then generating the updated version, comparing them, and only installing the changes. So, in a nutshell, Helm does by default what you are asking for.

Probably the best way to fix this is to try to find out why it is deleting things on upgrade.

**Comment by davorceman** [comment]
Upgrade is only on one subchart, as you can see from the command above.
Namespace template is in the parent chart, deployed together with the rest of the resources with install command above.
With upgrading only frontend subchart, with —debug I see in output that only 2 resources are deployed, frontend service and deployment.
So I understood that the rest resources are deleted because that.

If you said that this should works, then great, will try to see why I have this problem.
Can you direct me how to troubleshoot it?

**Comment by depeele** [comment]
I'm not sure if this is related, but I have noticed that making use of a parent `values.yaml` to deploy a sub-chart does not work as expected.

Settings in `values.yaml` meant to over-ride sub-chart values are not properly applied.

In the above example, if the top-level `values.dev.yaml`  contains:
```yaml
frontend:
  image: 123.jpg
```

And `frontend/values.yaml` contains:
```yaml
image: 456.jpg
```

Running the following will use the value for `image` from `frontend/values.yaml` (`456.jpg`) ignoring the over-ride in `values.dev.yaml` (`123.jpg`):
> `helm upgrade my-app charts/frontend/ --values values.dev.yaml`

I believe this is because `frontend.image` from `values.dev.yaml` is not considered a match for the `image` value in `frontend/values.yaml` even though it *will* over-ride the value in a "normal" upgrade...


I've submitted a separate, more detailed report for this particular issue #8597.

**Comment by wawa0210** [comment]
/assign 

i can try to fix this

**Comment by bhagya29m** [comment]
@davorceman : Did you find the solution for this? I am also searching for the exactly same solution on how to upgrade only subchart without terminating/upgrating the entire release which has multiple subchart. it will be helpful if you could share

**Comment by davorceman** [comment]
@bhagya29m , unfortunately I did not. At the end I gave up to use subcharts.

**Comment by vtgn** [comment]
Hi!
I'm particularly disturbed too with the fact that it is impossible to upgrade one given subchart only, particularly when this subchart uses global values defined in the parent chart.
Because the subchart uses these global values, you can launch no install no upgrade no template on this subchart because it doesn't know the global values.
And the helm install/upgrade/template commands launched on the parent chart don't seem to allow to generate/apply the templates of only one given subchart. I found totally incredible that this feature is not possible.

The only way I found to define global values shared by several independent charts is to create a simple file of values, and to apply it in the helm command to overload the values of each chart. This is very dirty solution, because nothing in the code of the chart indicates this file of global values is necessary.

I'm very disappointed by this.

**Comment by zengqingfu1442** [comment]
Can i use helm to only update subchart?
