### ISSUE TITLE
Completion for shells supported by cobra

### ISSUE THREAD

**Issue by kri5** [helm/helm#8109]
I took a quick look at the code handling completion in the helm command, and there seems to be a slight issue with renamed binaries, where the generated completion would not have a proper name.

Nowadays fish completion is derivated from the bash one, and there is a bash snippet in case the binary has been renamed from the default.

A Better way of handling it might be to pass the binary name as the name passed when creating the Root cobra command, and so it will propagate everywhere else.

Feel free to comment on this, and i'll try to make a PR to implement this

**Comment by marckhouzam** [comment]
Thanks for your interest @kri5!

> Nowadays fish completion is derivated from the bash one, and there is a bash snippet in case the binary has been renamed from the default.
>
> A Better way of handling it might be to pass the binary name as the name passed when creating the Root cobra command, and so it will propagate everywhere else.

When I originally added the bash snippet, I had played around with passing a different binary name to cobra.  But there are other consequences to that.  For example, the help messages and error messages would now use the new binary name, IIRC. Then I got worried that it may cause some other side-effect that I wasn't aware of.  I felt that kind of change would make the maintainers justifiably nervous, so I decided to isolate the change into the completion script alone.

What is you scenario for renaming the binary?  Is it helm v2 vs helm v3?  I'm asking because it may be better to try to make cobra officially support such a renaming.

What do you think?

**Comment by kri5** [comment]
I think you are right.

As you can see in #8111 i went for what i previously proposed at first, ie changing to the name of the binary when creating the cobra command, but coverage tests on the PR failed because of what you expected.

Many tests hardcodes the 'helm' binary names, so i went to the approach you mentionned where i change the binary name in the command just before using it for completion, to narrow down the scope of my changes.

I have no scenario for that but a comment in the code that seemed to be related to installation of helm2 and helm3 at the same time.

I took a look at cobra and basically the public API use for completion is basically just a thin wrapper getting the name of the command and passing it to an underlying function that takes the name as parameter, so there might be room for discussion on the cobra side.

**Comment by marckhouzam** [comment]
We can mark this as done: helm 3.4 now has fish completion and helm 3.5 will have native zsh completion.
