### ISSUE TITLE
Parser crash

### ISSUE THREAD

**Issue by AdamKorcz** [helm/helm#8116]
Sending the following payloads to the parser causes crashes:

1. `Â«Â^A))=,)==,¦=,¦.ÿ[67`
2. `=f1^K,ò¸=?0Ôu==,ÕÕ[0]´<81>ÿ^Q^@÷0]5õu^HÃ`
3. `Ãï=ï{^[ï?s{i^@ÿ^@<91>^QÉ^?^?^?^?,<85><85>..<9b>^N\ï<9b>.ñ`
4. `=, =, .=,=,==,.^G=,`

Specifically the crashes occur on line 211 in `pkg/strvals/parser.go` from the master branch:
https://github.com/helm/helm/blob/bf12ae39344aef012927ab391eb26ddd3a30ae30/pkg/strvals/parser.go#L209-L213

The crash was found with [this fuzzer](https://github.com/helm/helm/pull/8114), and calling 

```
func Fuzz(data []byte) int {
	_, err := Parse(PAYLOAD_HERE)
	if err != nil {
		return 0
	}
	return 1
}
```

will reveal the crashes.

Output of `helm version`:
The parser is tested via `go get`'ting helm.

Output of `kubectl version`:
The parser is tested via `go get`'ting helm.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
None

**Comment by bridgetkromhout** [comment]
Thanks again for bringing up this topic here and in https://github.com/helm/helm/pull/8124, @AdamKorcz. We're closing this specific issue due to lack of activity, but a great path forward for anyone who'd like to introduce something like fuzzing is to write it up as a Helm Improvement Proposal: https://github.com/helm/community/blob/master/hips/hip-0001.md
