### ISSUE TITLE
Check inside a chart if installed with helm v2 or v3 ?

### ISSUE THREAD

**Issue by eddycharly** [helm/helm#8150]
Is there a recommended way for checking inside a chart if a release is installed using helm v2 or v3 ?

I have a chart with CRDs in templates and want to exclude them when using v3 but include them when using v2. 

Thanks.

**Comment by hickeyma** [comment]
@eddycharly If you use `crd-install` hooks then Helm v3 will ignore the CRD templates. Otherwise, you can pas `skip-crds` flag with Helm v3. Some more details in docs: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

Apart from that, I am not aware of any other ways of checking this.

**Comment by eddycharly** [comment]
@hickeyma i'm not using hooks yet, i do something like this:

```
{{- if .Values.customResourceDefinitions.create }}
{{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
{{ $.Files.Get $path }}
---
{{- end }}
{{- end }}
```

Thanks for the hooks suggestion, i will read about it.

**Comment by hickeyma** [comment]
@eddycharly Ok, let me know how you get on.

**Comment by eddycharly** [comment]
@hickeyma Adding the `crd-install` hook annotation works like a charm.
Thank you !
