### ISSUE TITLE
Remove completions.bash file?

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8186]
`scripts/completions.bash` used to be used for shell completions but it has been replaced in how completions work and are documented to be used. Can we remove it now?

**Comment by bacongobbler** [comment]
I'm assuming yes, but @marckhouzam might know if there's a particular reason it still exists (backwards compatibility, maybe?)

**Comment by mattfarina** [comment]
@bacongobbler I asked @marckhouzam about it first. He said it wasn't in use any longer when he started working on completions.

**Comment by marckhouzam** [comment]
Nuke it. 

I feel it should never have been used for completion (and maybe it was just a reference) since `helm completion bash` should be used by helm users to generate the latest version of the script.

It is a maintenance 'nightmare' to remember to keep it up to date and there's no zsh version checked in also. Let's just remove it.
