### ISSUE TITLE
helm install --set have a question

### ISSUE THREAD

**Issue by chaochao3113** [helm/helm#8205]
Output of `helm version`: v3.0.2

Output of `kubectl version`: 1.14

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  GKE

helm install --set service.resources.cpu=0.1 --set service.resources.memory=128 test/nginx --generate-name
Error: values don't meet the specifications of the schema(s) in the following chart(s):
nginx:
- service.resources.cpu: Invalid type. Expected: number, given: string

Why number parse to string?

**Comment by bacongobbler** [comment]
This could be due to the template taking the input of `service.resources.cpu-0.1`, coercing it into a string.

Do you have a link to the chart causing this issue?

**Comment by bridgetkromhout** [comment]
Hi, @chaochao3113 - thanks for opening this issue. We would need an example chart in order to be able to reproduce, understand, and fix this issue. If you're able to provide a sample chart which allows us to see the issue, please do so, but for the time being, we'll close this as we cannot move forward without additional info. Thanks!
