### ISSUE TITLE
Helm go-SDK v3.2.1 OCI registry support

### ISSUE THREAD

**Issue by gapariha** [helm/helm#8255]
Hi, need inputs here:

I'm using the Helm SDK for go v3.2.1 https://pkg.go.dev/helm.sh/helm/v3@v3.2.1/pkg/action?tab=doc#Install for being able to programmatically pull, export and install helm charts from an container registry.

Say take the example of "helm chart pull", someone can use API action.NewChartPull() followed by ChartPull.Run().  
However, action.Configuration.RegistryClient needs to be set for invoking these APIs but the "registry" package is still internal so we can't create registry client by invoking registry.NewClient().

Upon, trying to import "registry" package, I get this error:
"**use of internal package helm.sh/helm/v3/internal/experimental/registry not allowed**"

How to go about it? When will the OCI registry will be migrated from "internal/experimental" mode for consumption?

Thanks!

**Comment by gapariha** [comment]
Please note that this is currently a blocker item for my current project work and hence would really appreciate any help here.

**Comment by jdolitsky** [comment]
@gapariha - there are a number of items still needed prior to dropping experimental. We are working on determining the final list. Here's a list of items at least for Helm 3.3: https://github.com/helm/helm/issues/8252

I recently had the same exact issue as you're having. The short-term solution is to copy the internal/experimental/registry directory in its entirety into your projects pkg/ directory. Not pretty, but works. 

You might also create a fork of this repo, move things out of internal, then use a "replace" statement pointing to your fork in go.mod. Hope this helps.

**Comment by gapariha** [comment]
Thanks @jdolitsky for your response.

Let me try out these suggestions.

BTW, I couldn't find a release timeline for Helm v3.3. When is it targeted for?

**Comment by bacongobbler** [comment]
We do not have an expected date for Helm 3.3. Helm 3.2 was released mid-April so we are due for a release. Please [track the 3.3.0 milestone](https://github.com/helm/helm/milestone/89) for updates.

The reason we are not exposing the registry package for public consumption is because OCI support is unstable at this time (#8252 lists a few of these issues, but there are more). Helm follows a strict backwards-compatible guarantee. We cannot make that same guarantee for experimental features. We intentionally made it unusable outside of Helm to prevent people from attempting to use unstable features in a production scenario.

see also #8259 for more context around the OCI feature's status.

Hope this answers your question.

**Comment by tx19980520** [comment]
I'm also use 3.2.4 to development about helm application and I wanna use pullChart api in hurry, so when the v3.3.0 will release?

**Comment by bacongobbler** [comment]
Helm 3.3.0 will not be unmasking the registry APIs as stable. That being said, the release is scheduled for release within the next week or so.

**Comment by Jiawei0227** [comment]
/open

Hello, I am wondering if there is a timeline to move it out of experiment?

**Comment by sTb1337** [comment]
@bacongobbler / @jdolitsky 

I would like to write a Unit Test for my K8s custom operator which installs / upgrades helm charts programmatically during reconcile process.

I found your test setup at install_test.go and action_test.go very helpful but sadly I am not able to use this because I am unable to import "registry" package. I get this error:

"use of internal package helm.sh/helm/v3/internal/experimental/registry not allowed"

Is there a way to achieve this?

Thanks a lot for your time and help,

Cheers
