### ISSUE TITLE
When will Helm OCI support be out of Experimental

### ISSUE THREAD

**Issue by sammym1982** [helm/helm#8259]
In order to use Helm OCI support today, we need to run `export HELM_EXPERIMENTAL_OCI=1`. Now given 3.2.1 is in stable what is the expected timeline we are looking at to bring helm OCI support out of experimental phase?

Output of `helm version`: V3.2.1

Output of `kubectl version`: v1.14.8

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

**Comment by bacongobbler** [comment]
hi @sammym1982. This was discussed a few weeks ago during the May 14th helm developer call.

From the meeting notes:

> Artifact stability/OCI: where are we? Let’s make a checklist and get there - there are open issues but I don’t see a summary of the status. [Bridget]

> Josh D: This was main part of OCI meeting discussion yesterday: https://www.youtube.com/watch?v=E9WNkklCmuc

> Josh: Farina was named - the OCI meeting said it needed a list from us of what it takes to remove the experimental flag

> Bridget: yes - let’s figure out our plan/make sure it’s visible

> Josh D: OCI dependency PR? https://github.com/helm/helm/pull/7613

> Farina: is this a spec waiting for everyone to use it, or can it be depended on? (Is it “trusted” or “already there”?)

> Farina: Distribution spec is concerned with container images. Is the artifact spec something we can stably rely on?

> Josh: Helm will drive a lot of this - we could call it a best practices guide and say “this is how helm is using the API”

> Farina: we’ll be going off the documented beaten path if we stick things that aren’t images in 
Fisher: Docker Distribution can be more compliant

> Butcher: the main reason we don’t want to move the experimental flag off is that there is a lot of documentation to do because not all repositories are OCI-compliant and allow chart types. We shouldn’t remove an experimental flag and confuse average users.

> Farina: The alternative option here is to discuss pulling the artifacts proposal out of OCI entirely and rely on chartmuseum/harbor to support that functionalit y But then we lose out on those OCI compatibility guarantees we were touting at Helm 2

> Josh: will take action to try to explain more clearly.

Recording of that meeting is [available on YouTube](https://www.youtube.com/watch?v=XoUqlxzmyHw).

The quick answer here is that we do not have an expected timeline when OCI support will become stable. There are many factors at play here.

Hope this answers your question. If you have further questions after watching the recording, please reach out on Slack.

**Comment by bacongobbler** [comment]
see also https://github.com/helm/helm/issues/8252.

**Comment by sammym1982** [comment]
Thanks @bacongobbler  for pointing #8252 . Does this list contained in that is what we are looking at to remove experimental flag? I wanted both videos and feel positive that there is eagerness to get this done, but I also hear kind of a circle.

**Comment by bacongobbler** [comment]
The work being proposed for Helm 3.3 is a start, but it will not mean that we will be ready to release it as a stable feature. There's more work to be done on the non-technical side.

As mentioned in the call, not all repositories are OCI-compliant and allow arbitrary file types. DockerHub and query.io are two such example (see #5861). As @mattfarina pointed out, we need to discuss our options before marking this as a stable feature.

**Comment by SteveLasker** [comment]
Hi folks,
There's a chicken/egg problem here, not cart/horse.
- OCI Artifacts is _stable_ and a thing to be relied upon. The reviews leading up to the the latest work were merged [Artifact Authors Guidance](https://github.com/opencontainers/artifacts/blob/master/artifact-authors.md)
- Yes, there's some historical verbiage in the image and distribution spec, but the spec is a spec and OCI Artifacts conforms to the existing specs, including the expansion of `mediaTypes`. Yes, we're working to reword some of the spec/docs, but as you can imagine, as developers, it's almost more complex to change wording than code. However, the spec already supports artifacts.

As for the chicken/egg problem, registries will open their `mediaTypes` as customers require them to do so. 
- Azure acr supports [OCI Artifacts](aka.ms/acr/artifacts]
- AWS ecr now supports [OCI Artifacts](https://twitter.com/cra/status/1281281162489495553)
- Project Harbor supports [OCI Artifacts](https://www.cncf.io/blog/2020/05/13/harbor-2-0-takes-a-giant-leap-in-expanding-supported-artifacts-with-oci-support/)
- GitHub Package Registry is adding, or added OCI Artifacts support. 
- Docker Hub is adding support, but not yet available: (https://github.com/helm/helm/issues/5861#issuecomment-656765911)
- Quay.io has committed to supported artifacts

As for google and JFrog, I can't speak directly to their plans, but this is where Helm can break the loop. While there are many other artifact types, one could argue Helm is the most popular. It's an opportunity for Helm support to push the remaining registry providers to expand OCI Artifact support. 

The problem is expanded as other projects like Terraform and Puppet (i forget if it was puppet or another deployment technology) are waiting for Helm registry support to be released for them to support helm 3 deployments.

Sorting out the internals are great things for how helm 3 implements charts and plug-ins as those would be great artifact types as well. I'd just suggest the debate on OCI artifact support not being ready is a non-issue and someone has to lead the way to the remaining registries.

If there's some other blocking issues, I'm happy to help facilitate any OCI or Artifact issues, or connect folks with the various registry operators. 

Steve

**Comment by bacongobbler** [comment]
> As for google and JFrog, I can't speak directly to their plans, but this is where Helm can break the loop.

https://cloud.google.com/artifact-registry

**Comment by SteveLasker** [comment]
Google called it "artifact registry", but I wasn't able to push and OCI artifact to it. I wasn't able to push an image either, so I might have been doing something wrong. I believe Google was shooting for the unified package manager approach, but would love to know if anyone has successfully pushed OCI content to google artifacts.

**Comment by jesselang** [comment]
> As @mattfarina pointed out, we need to discuss our options first before marking this as a stable feature.

Is there somewhere that the community can follow the discussion of these options, and the roadmap to consider this a stable feature? Thanks much. 😄

**Comment by gillesdouaire** [comment]
Now supported in Google Cloud: https://cloud.google.com/artifact-registry/docs/helm/quickstart

**Comment by maxvt-tonal** [comment]
It appears that JFrog is on the bandwagon as well, although I haven't tested this personally. https://jfrog.com/blog/steer-oci-to-kubernetes-with-artifactory-and-helm-3/

Perhaps it would be prudent to not have OCI hosting be the _only_ supported chart retrieval method for the sake of users who still use non-OCI compliant registries, but it does seem in this corner that this is now widely supported and it might be time to consider again what would it take to move Helm off the "experimental" support and towards full adoption.

**Comment by scottrigby** [comment]
@jesselang @gillesdouaire @maxvt-tonal 
Follow meta issue https://github.com/helm/helm/issues/10393

**Comment by bridgetkromhout** [comment]
For those interested in OCI support, it's planned to be out of experimental as of v3.8. You can test the release candidate now: https://github.com/helm/helm/releases/tag/v3.8.0-rc.1

**Comment by SteveLasker** [comment]
> For those interested in OCI support, it's planned to be out of experimental as of v3.8.

Huge kudos to @sabre1041, @scottrigby, @jdolitsky, @deitch, @shizhMSFT for bring this home!

**Comment by jdolitsky** [comment]
just awesome
