### ISSUE TITLE
How to build Restful API interface for Helm 3

### ISSUE THREAD

**Issue by lkusnadi** [helm/helm#8322]
I need to build web hook using Restful API to clean up Helm 3 deployment when a branch is closed in GitHub. Anyone can point me to the right direction for this? Since Helm 3 is tillerless and there's no more GRPC, I'm not sure how to communicate with Helm 3 deployment. Thank you.

**Comment by bridgetkromhout** [comment]
Hi, @lkusnadi  - thanks for your question. Are you able to accomplish the desired cleanup by accessing the REST API for the Kubernetes cluster where you're using Helm? https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

**Comment by lkusnadi** [comment]
Thanks Bridget for your reply.
I was thinking if there's a way to perform clean up similar to the helm
command line: helm delete deployment_name.
Using k8s API, I'm afraid each component from a single deployment has to be
dealt with individually.

**Comment by bacongobbler** [comment]
https://helm.sh/docs/topics/advanced/#simple-example demonstrates how to invoke `helm list` using the Go SDK. You could embed the helm client within a webserver and call [`NewUninstall`](https://github.com/helm/helm/blob/d71f0e6a8a39ea62ce45e8f5af90b7b8e0054bc5/pkg/action/uninstall.go#L44) instead of `NewList`.

Here's how `helm uninstall` invokes the uninstall action:

https://github.com/helm/helm/blob/d71f0e6a8a39ea62ce45e8f5af90b7b8e0054bc5/cmd/helm/uninstall.go#L56-L70

Hope this helps.

**Comment by mattfarina** [comment]
@lkusnadi there is no Helm service running in the cluster.

When a branch is closed on GitHub you could have CI (e.g., GitHub Actions) use Helm to run the delete command. If you need a container image with Helm on it, Lachie (one of the Helm charts maintainers) has one at https://hub.docker.com/r/lachlanevenson/k8s-helm.

**Comment by opskumu** [comment]
@lkusnadi https://github.com/opskumu/helm-wrapper, it's a helm http wrapper with Go SDK. with helm-wrapper, you can use RESTful API like helm commandline install/uninstall charts. 

Hope this helps.

**Comment by lkusnadi** [comment]
Thanks this is very helpful.

**Comment by bacongobbler** [comment]
Closing as answered.
