### ISSUE TITLE
End of Life v2

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8343]
The end of support for Helm v2 is approaching. This issue is here to cover the details we need to do as part of the EOL process.

**Changes to v2:**

- [x] Provide a flag skip adding stable as it will no longer be available. #7868
- [x] Provide a new download location for Tiller? The Google Cloud location will likely be turned off. While not required, this could provide for fewer support requests. #8346

**Documentation Changes:**

- [ ] Add a notice to the v2 docs page that support has ended.
- [ ] Update installation docs for the new situation to alleviate some support requests
- [ ] Remove v2 from the version menu?

**Notify The Community:**

- [ ] ~~Blog post when bug fix EOL has happened with timelines and guidance~~
- [ ] Blog post when EOL has happened

**Clean-up:**

- [ ] Close v2 issues

**Comment by bridgetkromhout** [comment]
> Remove v2 from the version menu?

Since we know there will be people trying to self-support v2, seems like keeping the (unmaintained, non-updated) docs would be a kindness? That would prevent them from having to go to github or the wayback machine. If we want to clean them up we can generate the final v2 version and drop the static files in the `helm-www` repo so `helm/helm` no longer has to be involved.

**Comment by bacongobbler** [comment]
Playing devil's advocate here, "Keeping the documentation around as a kindness" implies that we are committing to the community that - should the site go down - we will bring it back up. That to me sounds like support.

If there are users out there that still wish to use software that is no longer supported, it should be up to them to maintain the project, and because the Helm project is open source, the source code is freely available and they're free to run their own fork of the documentation.

On the other hand, netlify's services have been free (so far), and the site nearly never goes down, so the amount of overhead required to keep the site up is nearly zero.

I think a middle-ground stance is nice here:

- remove v2 from the version menu on https://helm.sh
- keep https://v2.helm.sh up

That way users can still reach Helm 2's documentation should they choose to do so.

Should we choose to keep the site up, I think we should make it very clear to the community that this is a "kindness" effort, and the site may be taken down at any point after November 2020. Our stance has been quite clear up to this point that Helm maintainers are going to support Helm 2 after its active support cycle is finished.

The same could be argued for both the Tiller download location as well as the Helm CLI downloads.

The point I'm trying to make here is that by keeping things around (sites, downloads, etc.) without clearly stating these assets can be removed at any point sets a very dangerous precedent. I think it's unfair for a foundation (CNCF) and the project's maintainers to keep paying and maintaining services well after a product has past its own support life cycle.

Our monthly billing for Helm 2 downloads costs thousands of dollars. How long will the CNCF allow us to keep spending that much on a product we no longer support?

**Comment by mattfarina** [comment]
In the new download location for Tiller area we have looked at Docker Hub who has recently changed their direction. Should we use GitHub registry instead?

**Comment by marckhouzam** [comment]
> In the new download location for Tiller area we have looked at Docker Hub who has recently changed their direction. 

What are you referring to exactly as a change of direction?  I fear I have missed some big news 😨

**Comment by marckhouzam** [comment]
Ok, I just saw that Docker Hub is introducing a 6-month retention policy for the free plan for images that have not been pulled or pushed:
https://hub.docker.com/pricing

**Comment by hickeyma** [comment]
FYI, [CNCF position on new Docker policy limiting image retention](https://github.com/cncf/foundation/issues/106).

The much bigger issue seems to be the "free" image/user pull limits rather than the  image retention issue: https://github.com/cncf/foundation/issues/106#issuecomment-674129151

**Comment by hickeyma** [comment]
Thanks @estesp for pointing me https://github.com/helm/helm/issues/8343#issuecomment-679121398 ^^

**Comment by rsicart** [comment]
Hi,
is that normal that https://charts.helm.sh/stable/index.yaml still contains references to deprecated stable repo https://kubernetes-charts.storage.googleapis.com/ ?

**Comment by bacongobbler** [comment]
For the moment, yes. AFAIK the chart maintainers are still working on rewriting the URLs in the index and are working on a migration plan in preparation for Nov 13th.

**Comment by bacongobbler** [comment]
For reference, this information is embedded in the charts themselves, so they need to be updated to the correct location.

For example: https://github.com/helm/charts/blob/b9278fa98cef543f5473eb55160eaf45833bc74e/stable/airflow/requirements.yaml#L4

**Comment by rsicart** [comment]
Given that this repo should not be updated anymore I suppose,
doing a sed to replace old urls by new repo url would do the trick ?

**Comment by bacongobbler** [comment]
opened https://github.com/helm/charts/issues/23971 to track this work.
