### ISSUE TITLE
Environment variable for max release history

### ISSUE THREAD

**Issue by hickeyma** [helm/helm#8367]
Environment variable for setting the max history for an environment. This would remove need to set it on each upgrade with the `--history-max` flag. Similar to `TILLER_HISTORY_MAX` variable in Helm 2.

Output of `helm version`:
Helm 3

**Comment by marckhouzam** [comment]
Another value to this is that it would make the `history-max` concept global again instead of limited to `helm upgrade`.  

For example, currently (helm 3.2), doing a `helm rollback` will create a new release but will not respect `history-max` since there is no global value and no `--history-max` flag for the`rollback` command.

**Comment by wawa0210** [comment]
/assign

If ok, I hope to pull a pr to adapt this feature

**Comment by hickeyma** [comment]
Go for it @wawa0210
