### ISSUE TITLE
Newline is added in configmap when using AsConfig

### ISSUE THREAD

**Issue by elieifrah** [helm/helm#8382]
When using AsConfig using tpl to add a configmap, newline is added to wrap to break long lines and fails when newlines exist inside {{ }}
Temporarily, we set a workaround by removing spaces before $.Values to avoid wrapping and in the ConfigMap we add spaces before $.Values once the configuration files are read:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . -}}-config
data:
{{- tpl ((.Files.Glob "conf/**").AsConfig | replace "$.Values" " $.Values") . | nindent 4 }}
```

Output of `helm version`:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
RancherLabs

**Comment by mattfarina** [comment]
I think this is the first time I've seen `AsConfig` used with `tpl`.

If there was a public example of this problem, I would be interested in seeing it.

`AsConfig` (source [here](https://github.com/helm/helm/blob/97774ee13cf9289918555a46948532f8ae313c9d/pkg/engine/files.go#L104-L117)) expects the source to be something that can be converted into YAML cleanly. I wonder if there is something about the source that doesn't cleanly translate. 

If the source is already YAML templates you might consider using ` Lines` instead of `AsConfig`. This will read the raw lines from the files.
