### ISSUE TITLE
OCI: Always derive namespace base from chart name and tag from chart version

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm#8387]
The basename of the namespace for the manifest representing a Helm chart as stored in an OCI registry should always be derived from the chart's name. Likewise, the manifest tag should always be derived from the chart's version.

In parts of the experimental `helm chart` subcommand where tags are parsed out the the URL, these should be changed to accept a `--version <version>` flag which allows overriding the chart version and thus the tag (similar to `helm package`).

The existing UX allows for this:
```
$ helm chart save mychart/ r.mysite.io/myorg/xyz:1.2.3
ref:     r.mysite.io/myorg/xyz:1.2.3
digest:  1b251d38cfe948dfc0a5745b7af5ca574ecb61e52aed10b19039db39af6e1617
size:    2.4 KiB
name:    mychart
version: 1.2.3
1.2.3: saved
```

which will override the tag as "1.2.3" despite the version found in `Chart.yaml`, and allow for any arbitrary base namespace ("xyz").

Instead, the syntax should be changed to the following:
```
helm chart save mychart/ r.mysite.io/myorg --version 1.2.3
ref:     r.mysite.io/myorg/mychart
version: 1.2.3
digest:  1b251d38cfe948dfc0a5745b7af5ca574ecb61e52aed10b19039db39af6e1617
size:    2.4 KiB
1.2.3: saved
```

On the question of whether arbitrary tags such as "latest" or "stable" could be used, I think the answer should default to "what does `helm package` do"? Let's see:
```
$ helm package mychart/ --version latest
Error: Invalid Semantic Version
```

so, no. Perhaps after we fix the design of `helm chart` we can have a discussion on what it means to override the tag with a separate `--tag <tag>` flag.

---

Regarding how this affects `helm chart push`, `helm chart pull`  for uploading and downloading charts - the version should be auto-determined using the same logic as using `helm install myrepo/mychart`.

The OCI spec provides a tag listing endpoint (`GET /v2/<name>/tags`) with pagination that we can use to list tags and infer the latest semantic version. If the registry being used does not support this endpoint, then the user must provide a specific version that will be used as the tag to locate:

```
$ helm chart pull r.mysite.io/myorg/mychart
Auto-determining version from namespace tag list...
1.2.3: Pulling from r.mysite.io/myorg/mychart
ref:     r.mysite.io/myorg/mychart
version: 1.2.3
digest:  1b251d38cfe948dfc0a5745b7af5ca574ecb61e52aed10b19039db39af6e1617
size:    2.4 KiB
Status: Downloaded newer chart for r.mysite.io/myorg/mychart
```

If the registry doesn't support it:
```
$ helm chart pull r.mysite.io/myorg/mychart
Error: registry does not support tag listing, cannot determine chart version
```

then the operator must use syntax like:
```
$ helm chart pull r.mysite.io/myorg/mychart --version 1.2.3
1.2.3: Pulling from r.mysite.io/myorg/mychart
ref:     r.mysite.io/myorg/mychart
version: 1.2.3
digest:  1b251d38cfe948dfc0a5745b7af5ca574ecb61e52aed10b19039db39af6e1617
size:    2.4 KiB
Status: Downloaded newer chart for r.mysite.io/myorg/mychart
```

---

I think this small UX change takes us further away from the Docker UX that inspired this, but is also more in line with the way that Helm works. This still allows us to leverage everything that OCI provides, with just an extra layer of validation specific to the Helm client. This is OK, and I would argue it ensures stability as chart repos and chart registries converge.

The OCI support was marked experimental as it is still considered to be that - an experiment. We are experimenting. Through this experiment it is becoming more and more clear that the design of this feature should be more tightly integrated with the way that Helm handles chart versions.

**Comment by TBBle** [comment]
We could reverse it, and treat
```
helm chart save mychart/ r.mysite.io/myorg/xyz:1.2.3
```

as eqiuvalent to passing `--version 1.2.3` (i.e. overriding the chart version as we can do with `helm package`) and also treat `xyz` here as overriding the chart _name_, i.e. effectively modifying `Chart.name` in a similar way to `Chart.version`. You could also support this with `helm package --chartname` for example.

I don't have a clear use-case for `--chartname`, but we already have a similar behaviour in the sub-chart alias system, although for different reasons. So maybe save that for future discussion.

I wouldn't necessarily change `helm chart push` and `pull` to exclude the full registry path use-cases. If `save` always creates a local entry with a registry and version matching `Chart.yaml` (modulo `--version` and `--chartname`), then push and pull can continue to operate on full `registry/repository:tag` syntax.

For `helm chart push`, I would either not support 'default tag', or take the latest known SemVer for local entries created with `helm chart pull` or `helm chart save`.

It might be handy for CI to write `helm chart push myrepo/chartname --devel` which given it's CI, probably means pushing the only known chart, since you just `helm chart save`'d it. But ideally your CI also knows the version it's publishing, so the full reference should not be hard to construct.

For `helm chart pull` when the tag-list API exists, I would take the latest known SemVer that matches the supplied `--version` SemVer match (default `>0.0.0`), and/or the `--devel` parameter that turns that default into `>0.0.0-0`. Otherwise I'd require the explicit path for `helm chart pull`.

I think we should avoid having special behaviour for `--version` in `helm chart pull` when it's an exact SemVer versus a SemVer matching operator, but it might be convenient to internally translate
```
helm chart pull r.mysite.io/myorg/mychart --version 1.2.3
```
into
```
helm chart pull r.mysite.io/myorg/mychart:1.2.3
```

but encourage the latter if you know the exact version you want.

That way, if you know your registry doesn't support the tag-list operation, you can just "not use `--version` with `helm chart pull`", which is a simpler distinction than "some forms of `--version` still work"

**Comment by jdolitsky** [comment]
Closing this for now. Larger discussion here: https://github.com/helm/community/pull/136
