### ISSUE TITLE
Feature Request: Expose Helm command arguments as built in objects `.Args`

### ISSUE THREAD

**Issue by paulczar** [helm/helm#8472]
When building a chart that is expected to use an advanced feature like `--post-renderer` it would be great to actually test whether that it has been used.  with `.Args` I could then do something like this in my `NOTES.txt`:

```bash
{{ required "this chart requires the use of--post-rendererer=./hook.sh" .Args.postRenderer }}
```

I'll look to implement this in the coming weeks, but I wanted to put it out there to open the discussion in case someone thinks its a bad idea :tm:

**Comment by scottrigby** [comment]
Looks legit to me. An internal chart could even use this to ensure a specific renderer is used consistently (to force reproducible builds) , etc 👌

**Comment by mattfarina** [comment]
What would one want to do in a post render hook that they cannot do as the creator of the chart?

I ask because there is a little bit of a role difference here. One role creates a chart that another role can then run. These may be the same person or they may be different people in different organizations. The post render feature is in the hands of someone who installs and operates a chart. https://github.com/helm/community/blob/master/user-profiles.md

I'm curious of the use cases.
