### ISSUE TITLE
What is the Purpose of the Index.yaml file 

### ISSUE THREAD

**Issue by snyderdb** [helm/helm#8552]
What is the purpose of the index.yaml file?  After packaging child charts it has been indicated that I should run the helm repo index command and then push the tgz’d chart files and the index.yaml file to the chart repository. I read the helm documentation and searched the web but couldn’t find a substantive description of this files purpose. 

Can someone provide some explanation of the purpose of this file?

Thank you!

VR,

Dave

**Comment by marckhouzam** [comment]
The `index.yaml` file is the list of charts available in a chart repository.  When you package a chart, the assumption is that you want to put it in a repository to make it available to others.  In that case, you have to update the `index.yaml` file so that it knows about your new chart (and all the others already on the repository), and then you must put the `tgz` package and the new `index.yaml` file on the chart repository serving the chart.

If you don't plan on putting your chart package in a repository, you don't need to worry about the `index.yaml` file.

I hope this helps.

**Comment by bacongobbler** [comment]
See also https://helm.sh/docs/topics/chart_repository/ for further information. Thanks @marckhouzam for the in-depth explanation!

**Comment by snyderdb** [comment]
Thank you Marc!  Tremendously appreciated!
