### ISSUE TITLE
Helm commands lint and template consume additional values differently

### ISSUE THREAD

**Issue by kislitsyn** [helm/helm#8554]
Helm commands have common arguments to pass/override additional values to chart.
For instance, if template in a chart contains `{{ .Values.someValue }}`, then to setup this value for the template engine you need to specify it in argument like:
```
helm template . --set-string someValue=testValue
``` 
If this template is in a sub chart, then the name of the `subchart` should be specified:
```
helm template . --set-string subchart.someValue=testValue
```
Otherwise the value of `.Values.someValue` will be absent for subchart

It works as expected for command `template`, but unfortunately works differently for `lint`.
For `lint --with-subcharts` the keys of values ignore subchart prefixes and you need to call:
```
helm lint . --with-subcharts --set-string someValue=testValue
```
, without `subchart` name prefix.

The difference between `template` and `lint` commands in a source code. 
When `lint` command runs linting for all sub charts with the same arguments and values: https://github.com/helm/helm/blob/master/cmd/helm/lint.go#L56-L83
`template` command calls `install` which coalesce values for dependencies like this: https://github.com/helm/helm/blob/master/pkg/chartutil/coalesce.go#L60

As a result `lint` command applies common values for all charts, when `template` and `install` try to extract values by name of the subcharts and use them only for these subcharts.

I wrote a simple test for `lint`:
https://github.com/kislitsyn/helm/pull/1

Output of `helm version`: 
`version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}`

Output of `kubectl version`: not applicable

Cloud Provider/Platform (AKS, GKE, Minikube etc.): not applicable

**Comment by aleksf** [comment]
Just hit the same issue with both helm versions I am using (below) in my helm lint pipeline stage:

`version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`

`version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}`

Validated it is the exact same case by removing subchart name from values:

`helm lint --debug --with-subcharts -f env/dev/values.yaml -f env/dev/amqp-values.yaml -f env/dev/db-values.yaml --set-string datasource.secret.path=foo --set-string api.oauth2.secret.path=bar .`
`
20 chart(s) linted, 0 chart(s) failed
`

As mentioned in this issue by the reporter, template and install commands both work fine, because they reference values via subchart name however lint command is failing.

**Comment by bacongobbler** [comment]
This is a duplicate of #8026.

**Comment by kislitsyn** [comment]
@bacongobbler I believe it was closed accidentally, cause it looks like this issue doesn’t duplicate #8026 . The issue is in the differences of how two different helm commands work with values. Probably the example is misleading, I can rework it. Could you reopen the issue?

**Comment by bacongobbler** [comment]
Sure. Thank you for looking into clarifying the issue you're experiencing.

**Comment by kislitsyn** [comment]
@bacongobbler I've updated first comment with general description of the issue with some links to the source code, that I believe are explaining it better. 
The linked issue #8659 contains another example of the same issue, but the cause is common.
Feel free to contact me in case of any question!
