### ISSUE TITLE
Helm lint throws an error where a warning should be thrown instead

### ISSUE THREAD

**Issue by kofan** [helm/helm#8596]
As a result of these 2 PRs:

1. **https://github.com/helm/helm/pull/7986 - feat: implement deprecation warnings in helm lint**
1. **https://github.com/helm/helm/pull/8011 - feat: lint the names of templated resources**

now `helm lint` validates  whether resource `metadata.name` complies Kubernetes naming rules and whether the `apiVersion` is up to date. And these are great features, thank you for implementing them! 

However, these rules are having ERROR severity instead of WARNING. These should be warnings because these are NOT errors from the Kubernetes perspective - Kubernetes API still accepts resources with deprecated API versions as well as resources with metadata names that, for example, contain `:` in them. If these are warnings instead of errors, then it will be up to a client to decide whether he wants to fail lint (via using `--strict` flag for `helm lint` command) or not.

Setting the error severity level for these issues also complicates the migration of automated deployments 
 to helm 3.3, especially form Helm 2.x.

_How to fix?_ - I believe [these lines](https://github.com/technosophos/k8s-helm/blob/2d1ce6d7866e1edc2431eb637864f0bdc7e6a0a7/pkg/lint/rules/template.go#L133-L134) of code should be rewritten to:

```go
linter.RunLinterRule(support.WarningSev, path, validateMetadataName(&yamlStruct))
linter.RunLinterRule(support.WarningSev, path, validateNoDeprecations(&yamlStruct))
```

**Comment by bacongobbler** [comment]
As of Kubernetes 1.16, those APIs were deprecated and are no longer accepted even with a `kubectl create`, so it is correct for `helm lint` to report an error in those cases.

See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ for more details.

**Comment by kofan** [comment]
@bacongobbler, maybe it is true for some APIs but certainly not for all - here is an example... The helm chart has a `ClusterRole` resource defined using the deprecated API version:

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "example-chart.fullname" . }}
  labels: {{ include "example-chart.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.clusterRoleRules | nindent 2 }}
```

If you run an installation/upgrade of this chart, it will succeed and there will be no errors. However, `helm lint` command in Helm 3.3 fails for it with the error:

```
[ERROR] templates/clusterrole.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRole" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRole"
```

**Comment by kofan** [comment]
The same applies to 
**https://github.com/helm/helm/pull/8011 - feat: lint the names of templated resources**
For example, [prometheus-adapter](https://github.com/helm/charts/tree/master/stable/prometheus-adapter) gets successfully installed/upgraded, but `helm lint` command in Helm 3.3 fails for it with the error:
```
[ERROR] templates/custom-metrics-apiserver-auth-delegator-cluster-role-binding.yaml: object name does not conform to Kubernetes naming requirements: "prometheus-adapter:system:auth-delegator"
```

**Comment by mattfarina** [comment]
@bacongobbler I'm reminded that numerous people are still running production systems older than 1.16. I know people using 1.13. This is going to mess with things like `NetworkPolicy` which have a much smaller deprecation window. Some people will have environments that don't have the new version yet. I wonder about the deprecation policy being a warning for some and an error for others. To add more nuance.

The name issue is one that's been called out in a few places. Some resources have different allowed lengths. I wonder if we should try to catch for those when we know them.

Thoughts?

**Comment by kofan** [comment]
Yes, and here is another example...
The helm chart has an `Ingress` resource defined using the deprecated API version:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  # ...
spec:
 # ...
```

If you run an installation/upgrade of this chart, it will succeed (the cluster's Kubernetes version is **1.18.7**) and there will be no errors. However, `helm lint` command in Helm 3.3 fails for it with the error:

```
[ERROR] templates/ingress.yaml: the kind "extensions/v1beta1 Ingress" is deprecated in favor of "networking.k8s.io/v1beta1 Ingress"
```

**Comment by ganto** [comment]
I also think this error should be turned (optionally?) into a warning. We still write Helm charts for OpenShift 3.11 which uses Kubernetes 1.11 where the new APIs don't exist yet. In this case the linting from helm-3.3.0 breaks our CI and shows useless information.

**Comment by bacongobbler** [comment]
> I'm reminded that numerous people are still running production systems older than 1.16. I know people using 1.13. This is going to mess with things like `NetworkPolicy` which have a much smaller deprecation window. Some people will have environments that don't have the new version yet. I wonder about the deprecation policy being a warning for some and an error for others. To add more nuance.

Thanks @mattfarina. I see where you're coming from, and I fully understand this point of view. If I may play devil's advocate for a moment here...

We have documented and discussed that a given version of Helm has a version support policy of N-3 Kubernetes versions, where N is the client version that Helm was compiled against. https://helm.sh/docs/topics/version_skew/

According to that document, Helm 3.0 was compiled against Kubernetes 1.16, so Helm 3.0 supports Kubernetes versions 1.13-1.16. Shouldn't users running Kubernetes 1.13 use Helm 3.0, and upgrade their Kubernetes clusters when upgrading to a newer version of Helm?

From my point of view, there's a balance that we need to strike here: we need to provide a good experience for users running Helm against a supported version of Kubernetes, so that they "fall into a pit of success". Helm 3.3 supports Kubernetes 1.18-1.15, and those versions of Kubernetes (asides 1.15, I believe) do not allow users to install `apps/v1beta1` Deployments, so an error seems appropriate for those users. If there are cases (like what @kofan mentioned in https://github.com/helm/helm/issues/8596#issuecomment-675305111) where an error should NOT be reported, then perhaps we should revisit that particular case, but in general I believe it is right for Helm to report linting errors for kubernetes APIs that have been deprecated and are no longer supported.

Happy to hear your thoughts as well. I know there is a bit of a balancing game here.

As others have mentioned, reducing the severity to a warning works around this (and users can use `--strict` to promote warnings to errors), but I fail to see the case why a Helm chart using deprecated API versions with a newer cluster should only warn users when they're using API versions that will fail upon `helm install`.

**Comment by bacongobbler** [comment]
> The name issue is one that's been called out in a few places. Some resources have different allowed lengths. I wonder if we should try to catch for those when we know them.

I think that seems fair. I have not yet looked that far into the second case (the naming issue) yet.

**Comment by mattfarina** [comment]
@bacongobbler I like your counter agreement and point about version skew. Version skew very much matters because Helm's interactions with Kubernetes happen via Kubernetes packages that have a version skew of their own. Some details are at https://github.com/kubernetes/client-go#compatibility-client-go---kubernetes-clusters.

Yet, there is a security element to it. [Helm 3.0 has a security vulnerability in it](https://github.com/helm/helm/security/advisories/GHSA-qq3j-xp49-j73f). This is just one example. I can imagine more coming up. This would complicate me recommending someone use an older version of Helm for their older cluster. Especially if the newer version could work (client-go does work).

Part of this is also about being practical. There are people using Kubernetes 1.13 in production. I know of multiple cases. This is no longer supported by the community. Unless it's been patched, it has known issues. Yet, it is in use. So, we need to decide how easy we want to make it for people to use Helm with it. Even Helm using unsupported versions of k8s.

The other day I was reading about reading a post where [someone said they think Google's deprecation policy is hurting them](https://medium.com/@steve.yegge/dear-google-cloud-your-deprecation-policy-is-killing-you-ee7525dc05dc). I want to make sure that Helm handing older versions of Kubernetes that are in use doesn't hurt Helm.

Note, since this is already an error... don't we need to keep it an error and have a flag to make it a warning?

**Comment by bacongobbler** [comment]
I agree that there is a practicality element to all of this, and I have heard the same sentiment about Kubernetes' support policy not matching up with the community's usage of the Kubernetes project. On the flip-side of this argument, this data is all anecdotal, and we do not have a concrete evidence to suggest otherwise. What I'm wondering is how do we - as core maintainers - make informed decisions about what Kubernetes versions we need to support, and when we can drop support for these older versions, or do we keep supporting Kubernetes 1.13 users in perpetuity? Is there a metric out there that tells us what versions of Kubernetes are used with Helm?

Perhaps that's a really solid argument to bring back the topic of anonymized metrics for Helm as was discussed at the first Helm Summit.

> Yet, there is a security element to it. [Helm 3.0 has a security vulnerability in it](https://github.com/helm/helm/security/advisories/GHSA-qq3j-xp49-j73f).

To be totally fair, this same argument could be flipped around with regards to Kubernetes as well. Kubernetes 1.13 is no longer considered "supported", and there are [known CVEs](https://groups.google.com/forum/#!topic/kubernetes-security-announce/JAIGG5yNROs) for those versions as well. From the linked CVE, it affects all versions prior to 1.16. So should we really be supporting those clusters?

> Note, since this is already an error... don't we need to keep it an error and have a flag to make it a warning?

Prior versions of `helm lint` would accept the API versions and return an exit code of zero. With the changes to Helm 3.3, these resources now trigger an error, returning a non-zero exit code. I think there's an argument to be made that this could be considered a regression, which would warrant downgrading it to a warning to fix that regression. That being said, it may be worth giving other maintainers an opportunity to weigh in here.

**Comment by hickeyma** [comment]
The idea behind making these lint checks of ERROR severity is as follows:

- Deprecated/Removed APIs: Helm will no longer be able to manage a release if it contains a Kubernetes resource with an API which is no longer supported by the Kubernetes version. This can happen by just upgrading Kubernetes to a certain version with existing releases. See [Deprecated Kubernetes APIs doc](https://helm.sh/docs/topics/kubernetes_apis/) for more details
- Metadata names: Following the `kubectl` naming rules is good practice

My thought on this is that the lint severity should mirror Helm's opinionated view. This view is continually developing from experience and best practices, helping users to avoid potential pitfalls. It then is up to the user to decide whether to heed the errors or not. The severity matches the potential of how bad the outcome can be for the user.

As @mattfarina @bacongobbler have mentioned, I am also a practical person and understand that users will be using Kubernetes in different ways and with different version which won't always align to the Helm opinion. This is why there has been  a lot of issues raised against linting and how people think it should best work. @technosophos has given a lot of feedback on the topic in other issues and also in https://github.com/helm/helm/pull/8608#issuecomment-677913757 and https://github.com/helm/helm/pull/8608#issuecomment-677937877.

I agree then that the severity for both check should be downgraded to warning. I have added a suggestion to provide more information to the user for APIs in https://github.com/helm/helm/pull/8608#pullrequestreview-474374924.

**Comment by hickeyma** [comment]
> Note, since this is already an error... don't we need to keep it an error and have a flag to make it a warning?

@mattfarina I agree with @bacongobbler on this that it is probably should be considered a regression as it worked prior to Helm 3.3. I am therefore going to set it to a bug but open to change on this.

**Comment by hickeyma** [comment]
PR #8621 pushed by @joejulian to fix this.

**Comment by allen-servedio** [comment]
The PR that is fixing this is #8608 and specifically https://github.com/helm/helm/pull/8608/files#diff-c708830a32a0f702f8307935ad3c4137R133-R138. NOTE: the scope of that PR is larger than this issue in that it is trying to provide the user with more detailed information about when an API is deprecated and when it is removed vs. just reducing the level from error to warning.

**Comment by hickeyma** [comment]
@allen-servedio Thanks for the update. I did indeed type the wrong number. It is slightly expanded in scope but it is solving this issue.

**Comment by carlpett** [comment]
>Is there a metric out there that tells us what versions of Kubernetes are used with Helm?

A decent/better-than-nothing proxy might be what the major managed Kubernetes providers are defaulting to. As of today, GKE defaults to 1.15, EKS 1.17 and AKS 1.17 (I think - I don't have any engagements on Azure ATM, so interpretation from [their docs](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions)). So basically, the policy outlined above would mean a GKE default cluster is not a supported Helm usage, which seems overly strict? 

Another angle would be looking at the recently announced extended support window for Kubernetes itself from 9 to 12 months, which would mean a 4 step version skew.

**Comment by carlpett** [comment]
>Metadata names: Following the kubectl naming rules is good practice

It looks to me like this is an overly strict reading of the [naming docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names)? While the docs mention three name constraints (DNS subdomain, DNS label and Path segment), Helm's linter appears to only consider the subdomain constraint, which will be overly strict for some types, and too liberal for those that work with the label constraint. 
As an example of where this is too strict, Kubernetes built-ins roles and bindings use colon-separation for organization, which has thus been a pattern repeated in the community. This is now disallowed, breaking several charts.

**Comment by allen-servedio** [comment]
There is a solution for this in #8608 - it just needs to correct some merge conflicts and get released.
