### ISSUE TITLE
Umbrella chart value overrides are ignored when directly templating/installing/upgrading a sub-chart

### ISSUE THREAD

**Issue by depeele** [helm/helm#8597]
Output of `helm version`:
> version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}

Output of `kubectl version`:
> Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
> Docker Desktop 2.3.0.4 with Kubernetes v1.16.5

---
It seems that value overrides from a parent are ignored when directly templating/installing/upgrading a sub-chart.

Given an umbrella chart structure as follows:
```
$ tree
.
├── Chart.yaml
├── charts
│   └── frontend
│       ├── Chart.yaml
│       ├── templates
│       │   └── frontend.yaml
│       └── values.yaml
├── templates
│   └── namespace.yaml
└── values.dev.yaml
```

The content of `charts/frontend/values.yaml` is a simple `image` value along with a nested value to show how things seem to be applied:
```yaml
image: 123.jpg

frontend:
  image: 789.jpg  # nested value test
```

The content of the top-level `values.dev.yaml` contains a single over-ride for the `image` value in the frontend chart:
```yaml
frontend:
  image: 456.jpg
```

The content of `charts/frontend/templates/frontend.yaml` is a simple test service that uses the `image` value along with a test for the nested value:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image }}
  metaname: {{ .Values.frontend.image }}
spec:
  ports:
  - port: 1234
```

---
Example 1: When templated as a full chart, the over-ride value is applied as expected:
```bash
$ helm template test . --values=values.dev.yaml 
---
# Source: test/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: default
  annotations:
    helm.sh/resource-policy: keep
---
# Source: test/charts/frontend/templates/frontend.yaml
apiVersion: v1
kind: Service
metadata:
  name: 456.jpg
  metaname: 789.jpg
spec:
  ports:
  - port: 1234
```

Example 2: On the other hand, templating *just* the sub-chart does **not** apply the override as expected:
```bash
$ helm template test charts/frontend --values=values.dev.yaml 
---
# Source: frontend/templates/frontend.yaml
apiVersion: v1
kind: Service
metadata:
  name: 123.jpg
  metaname: 456.jpg
spec:
  ports:
  - port: 1234
```

---
I would expect the templating of `charts/frontend/templates/frontend.yaml` to result in identical output for the two examples.
In particular, the values of `metadata.name` and `metadata.metaname`.

As it stands, there is no simple way to test individual sub-charts from an umbrella chart to make sure top-level over-rides are applied as expected.

**Comment by depeele** [comment]
If you filter the top-level `values.dev.yaml` to include **just** the content of the `frontend` section, templating works as expected.

For example, `values.frontend.yaml` with content:
```yaml
image: 456.jpg
```

Templating with this filtered values file works as expected:
```bash
$ helm template test charts/frontend --values=values.frontend.yaml 
---
# Source: frontend/templates/frontend.yaml
apiVersion: v1
kind: Service
metadata:
  name: 456.jpg
  metaname: 789.jpg
spec:
  ports:
  - port: 1234
```

It seems `frontend.image` from `values.dev.yaml` is not matched to / applied against the `charts/frontend` sub-chart when the sub-chart is templated independently.

Since `helm` properly does this matching when the umbrella chart is templated, I expected this to also occur when templating an individual sub-chart (given that the target chart is in the `charts` sub-directory of the directory containing the target values file -- presumably the same logic used when templating sub-charts for the umbrella chart)...

**Comment by wawa0210** [comment]
@depeele
It seems to be in line with expectations, the scope specified by the helm values ​​file

**Comment by mconner** [comment]
> @depeele
> It seems to be in line with expectations, the scope specified by the helm values ​​file

@wawa0210 
I don't understand.  How is this "in line with expectations".  One would expect that when templating, installing, or upgrading a subchart, it would use the same values that were used if templating, installing or upgrading the entire chart.   This is not the case.  Additionally, if you have a subchart that relies on [global variables](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values), as defined in the helm docs, this will fail.

Surely, there must be a way to perform template, install, and upgrade commands on subcharts and pick up the correct context?  Simply including the values.yaml from the parent won't do it, because it won't be [pruned](https://helm.sh/docs/topics/charts/#scope-dependencies-and-values).    It would be really clunky (and error prone) to have to transform the values.yaml just to do something helm already does.

**Comment by mconner** [comment]
@wawa0210, @hickeyma 
After playing with this for a bit, this is a misunderstanding of what subcharts can do.  As a developer (or even a deployer), I want to install, upgrade or uninstall one component -- that is, one helm subcharchart -- of my system at a time:  Maybe I'm having issues with initialization order.  Or maybe I've got some configuration in one subchart that isn't right, but I want to upgrade a change I've made to another.  

The [documentation ](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/) does state that "A subchart is considered "stand-alone".  However, when helm is run on a parent chart, helm processes the subcharts by only including the  global values, as is, and the values under the subchart from the parent chart's values.yaml (and other .yaml included with -f).   So there is some special handling there.

So, I (and I presume the op,  @depeele), was assuming that running helm directly on the subchart somehow (e.g.: by path) caused helm to treat it like a part of the parent chart, and upgrade (or install, or uninstall) only that  portion of the parent chart.  
However, you literally meant: It can be run as a separate chart, and will install a separate chart, under a separate name.  

If I understand correctly now, all it does is upgrade (or install, or uninstall) the subchart as the name you give it.  If you give it a different name, it is a new chart (not part of the parent chart).  If you give it the same name as the parent chart, it will **_remove_** whatever is not in the subchart, because in this context, it is not actually a subchart.

I think it would be helpful to enhance the documentation surrounding this to be a bit more explicit to indicate something to the effect of:  

1. Run `helm install parentchart parentchar`    <-- Installs the parent chart and all its subcharts as "parentchart"
2. Run `helm upgrade parentchart parentchart/subchart`  <-- "Upgrades" chart "parentchart" to have only subchart's elements.
That is, operating on subchart directly does not allow you to partially install or upgrade a parent chart.

It would also be helpfull to more clearly address the issue of how you actually handle the use case of installing a subchart as part of the parent chart.  As far as I can tell, the only support for this is using dependencies with condition in Chart.yaml, then providing values to define those conditons, the enable or disable the subcharts you want. That is, it is a declarative, rather than procedural process.  The Helm Dependency documentation on this is pretty sparse, and using the preferred form:

`condition: somechart.enabled`

seems questionable, because it pollutes the values for somechart, which might conceivably use `enabled` for its own purposes.

Somewhat related (and maybe this is/should be a separate issue):  This does not address dependencies _between_ subcharts, and I'm not sure if or how that is addressed by helm.  It seems dependencies are only hierarcical.  Say I've got a subchart for a  db, scdb, used by two other subcharts, sca and scb.  If I define dependencies in each of sca and scb on scdb, then do a helm dependency update, it would pull in the scdb under both, right? Is there a way to reference, rather than copy, a subchart?

**Comment by vtgn** [comment]
@depeele 
Hi!

This behavior is normal, because you launch the helm command on the subchart, and by setting a values file in the command, you just overload the default values of your subchart by this file contents, and so the values inside this file are loaded as they are, ie. in your example it overloads _frontend.image_ value by _456.jpg_: so this is a normal result.

By launching the helm command on the parent chart, helm knows this is a parent chart, because its _charts_ folder contains a subchart. So, helm applies the parent charts specific feature which consists of interpreting differently the values it loads, by considering an object named by the name of one of its subcharts as a set of values to overload only in the chart with this name. And that's why in your example, in this case the contents of _values.dev.yaml_ overloads the _image_ property of the subchart only by _456.jpg_ during the generation.
If you want to overload the _image_ property of your subchart in this case, you have to define the _image_ property in the yaml file you references in the command.

A parent chart knows it is a parent chart, but a subchart doesn't know it is a subchart and so that it has a parent chart. So launching the command on the subchart just works as it is a simple independent chart.

However, I find illogical that helms doesn't allow to install/upgrade/template correctly only one or several given subcharts, particularly when they use global values defined in their parent chart.
It could be fixed by at least one of these solutions:
- allow to launch the helm command on the parent chart and be able to select only the subcharts you want to install/upgrade/template. Similarly, it should also be possible to choose not to install/upgrade/template the templates of the parent chart.
- allow to launch the helm command on a subchart, and helm should be able to detect it is a subchart, and so to load the global values defined in the values file of the parent chart.
