### ISSUE TITLE
Command to extract CRDs from chart

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8607]
It would be handy to have a command that enabled extracting CRDs from a chart. Two possible use cases...

1. A user needs to upgrade the CRDs in the cluster. They need to extract them to pipe them into kubectl to perform the upgrade
2. The person installing the chart does not have permission to install CRDs. They need to provide them to someone else to install. An easy manner of extracting them would be helpful.

**Comment by TBBle** [comment]
For the second use-case, perhaps `helm install --only-crds` would contrast nicely with `--skip-crds`?

Although if we don't track the releases, `helm install` is a really a weird place to run it.

And if we do track releases of CRD-only installs... Is that just automating the split of a CRD/RestOfTheApp pair of charts? Also weird.

**Comment by mattfarina** [comment]
A few thoughts...

First, there are many ways one can hurt themselves and others when upgrading CRDs. I don't want to make it easy. It's like editing the windows registry. You can really break things. Not just for yourself but for other users of the cluster.

Second, CRDs are more like kernel extensions than workloads or applications. On an operating system you can often install per user versions of applications. But, there is just one version of a kernel extension that everyone needs to share.

In the case of Helm, the person installing the CRD and other people using it may not have access to the release information. That complicates the experience.

Third, in the second situation I hope the person who installs the CRD reviews it and doesn't just blindly install it. I wonder, what would be a good experience for the person in case 2.

I was wondering if this would be a good subcommand of `helm show`

**Comment by wondersd** [comment]
Hi all, i just came across this issue as i was also looking for a `--crd-only` type option for `helm install`

I'm starting to use several charts that include crds (cert-manager, prometheus-operator, etc). prom-operators servicemonitor specifically is commonly used in other charts, including cert-manager. So it's natural to install it first. Assuming other crds such as cert-managers `Certificate` become as popular and commonly make their way into community charts, its not unreasonable for them to be included in prom-operator for example. In the event that happens one wouldn't be able to install a fully configured prom-operator (with the `Certificate` resource enabled) or to install a fully configured cert-manager (with the `ServiceMonitor` enabled) since both charts will require the other's crds to already be installed. One would have to install each chart with options to disable the other charts included crd usages and then an upgrade to turn them on.

```
$ helm install prometheus-operator stable/prometheus-operator --values=prom-partial-configured-values.yaml
$ helm install cert-manager stable/cert-manager --values=cert-partial-configured-values.yaml
$ helm upgrade prometheus-operator stable/prometheus-operator --values=prom-fully-configured-values.yaml
$ helm upgrade cert-manager stable/cert-manager --values=cert-fully-configured-values.yaml
```

In an attempt to work through a way to do this, it seemed natural to be able to have alternate releases where only the crd resources were installed:

```
$ helm install --crd-only prometheus-operator-crds stable/prometheus-operator
$ helm install --crd-only cert-manager-crds stable/cert-manager
$ helm install --skip-crds prometheus-operator stable/prometheus-operator --values=prom-fully-configured-values.yaml
$ helm install --skip-crds cert-manager stable/cert-manager -operator --values=cert-fully-configured-values.yaml
```

The above usage could be separated by role, e.g. crd installations is done by an administrator ahead of time. The crd versions are tracked and managed like any other release and separate from any one usage of the crds (for better or worse but this does at least line up with the "only one version of a crd per cluster"). This would also play nice with declarative tools using helm since the installation of the crds and the charts usage of those crds can be explicitly managed.

Hope this helps, thanks!
