### ISSUE TITLE
How to keep local changes to configmap during helm upgrade in Helm3

### ISSUE THREAD

**Issue by qi-min** [helm/helm#8624]
I have a Configmap which might be changed by application or `kubectl`, so I need to keep the changes during helm upgrade. In Helm 2, Helm upgrade will not impact the content of this Configmap. After upgrade to Helm 3, Helm upgrade will reset the Configmap with the values in values.yaml. 

I tried to upgrade with `--reuse-values`,  but it does not work with Helm3, Configmap is still reset. I also tried to add `pre-install` hook to mv this Configmap out of management, but this will only delete the Configmap during Helm upgrade.

So is there any way to keep the local changes to Configmap during helm3 upgrade or is there any way to make this Configmap out of Helm release management?

**Comment by mattfarina** [comment]
I am surprised Helm v2 did not change the ConfigMap.

> is there any way to make this Configmap out of Helm release management?

Is this part of a chart you created or someone else did? If you created the chart than you can choose not to include the configmap in the chart but rather include it's name so that something else can use it.

> I tried to upgrade with --reuse-values, but it does not work with Helm3

The `--reuse-values` flag re-uses the values from the last release and not those that changed in between.

I would suggest that a configmap changing while an application is running means the configmap is not part of the running application but rather being used for data storage by the application. Like when an application uses the windows registry. I would not include it in the chart. Instead, I would have the application manage it.

**Comment by qi-min** [comment]
@mattfarina I can not delete the helm release, so I can only do helm upgrade. Is there any way to keep the configmap object but remove it from helm chart?

**Comment by qi-min** [comment]
Thanks @mattfarina , this is what I want. I will try this annotation to see does it work.
