### ISSUE TITLE
--atomic flag is not working as expected: Timeout on rollback

### ISSUE THREAD

**Issue by maateen** [helm/helm#8675]
I am using `--atomic` flag to actually roll back changes to the last successful release to avoid downtime. But every time, any new release failed, I suck at `pending-rollback` state. I applied this command:

```
$ helm upgrade $RELEASE_NAME $CHART -n $NAMESPACE --atomic --create-namespace -i --timeout 5m --set image.tag=$IMAGE_TAG
```
And I got this:

```
Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: timed out waiting for the condition: release mars failed: timed out waiting for the condition
```

This seems to be a repetition of [#6978](https://github.com/helm/helm/issues/6978) which supposed to be fixed already.

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.6-eks-4e7f64", GitCommit:"4e7f642f9f4cbb3c39a4fc6ee84fe341a8ade94c", GitTreeState:"clean", BuildDate:"2020-06-11T13:55:35Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS

**Comment by bacongobbler** [comment]
this looks to be a duplicate of https://github.com/helm/helm/issues/4558.

**Comment by liuming-dev** [comment]
It seems that the upgrade option failed, then the release roll back to last successful release because `atomic` flag is set, but waiting for the specified resources to be ready has timeout. 

Since the target release revision to be roll back to has deployed successfully once, When rolling back to this specified revision, it will almost be successful finally. Therefore, could we do not set the `wait` and `timeout` flag for the rollback option?

https://github.com/helm/helm/blob/04fb35814f64122c0aa08165f6fdb7b67c216558/pkg/action/upgrade.go#L413-L423
