### ISSUE TITLE
Feature request: Ability to install kubernetes resources from yaml file as Helm release

### ISSUE THREAD

**Issue by kristinnardal2** [helm/helm#8765]
I've been using `Helm` as well as `Helmfile` to manage my Kubernetes resources.

One thing that I've been struggling with is that I have a bunch of Kubernetes resources, for example, RBAC or configmaps, that aren't part of a Helm release but are important for my Helm releases to work. This has lead me to use the [incubator/raw](https://github.com/helm/charts/tree/master/incubator/raw) chart to deploy my extra resources instead of using `kubectl`.

This adds all of Helm's benefits, such as revision support, and allows me to automate my setup more with Helmfile.

Since the incubator repository is being deprecated I will have to move to some other chart that does a similar thing but it would be really nice if deploying from a single yaml file without using a Helm chart would be possible.

This is a bit of a strange feature request since Helm is a package manager and I'm asking for a no-package install being added but I still think it has some merit to it as I would be able to easily manage all my Kubernetes resources with Helm.

**Comment by mattfarina** [comment]
@kristinnardal2 I understand where you are coming from. To add some context...

- You are right that Helm is a package manager and we are trying to not scope creep into other spaces. Instead, we want to see complementary tools do the other work. Helmfile is an example of one of those.
- The incubator/raw chart could be moved elsewhere so that it can still be used afterwards. Is that something you'd be interested in hosting (you could use GitHub pages)? We could help you set that up.

I don't expect this to go into Helm itself. It's a little out of scope.

**Comment by kristinnardal2** [comment]
I completely understand that and kind of expected that answer.

I'm not really sure where this would fit in the tools that currently exist, there is a chance that Helmfile would be able to add better support for plain Kubernetes resources but I think that it's also a bit out of scope for helmfile.

Maybe we're just missing a new tool that does something similar to what I suggested and could be integrated with helmfile.

Regarding the incubator/raw chart I will probably be self-hosting it or creating my own chart that fits my use case better once incubator is removed. I appreciate the offer to help but I think I'll be able to manage on my own.

**Comment by mattfarina** [comment]
@kristinnardal2 If you do self host something would you mind listing it in the Artifact Hub for others to discover as well.
