### ISSUE TITLE
Feature: ready command to report the readiness of a release

### ISSUE THREAD

**Issue by joejulian** [helm/helm#8768]
The code used in the wait loop could be moved out of the loop and exported to be used as a `ready` command:

```bash
$ helm ready --namespace foo myapp
false
```

Additional options _could_ be verbose and machine readable output that reports the readiness details for each of the resources.

As users of the helm API, we have a project that installs sets of charts that are all configured to work together. Currently, we have to use wait to know the state of the installation or upgrade. If we didn't have to wait, we could expect eventual consistency and poll for readiness while doing other work.

**Comment by joejulian** [comment]
@bacongobbler I'm not sure how it can be a plugin without changes to `helm.sh/helm/v3/pkg/kube`. The readiness check code that is in the wait loop would need to be moved out of the loop (probably into a utils file) and enhanced to give a list of results (in addition to bool and error) and made public.

Can you give a little more guidance on this?

**Comment by bacongobbler** [comment]
When we talk about implementing new feautures in Helm, we have to consider whether the community would see value in it Otherwise we end up with a bloated Helm client with features re-implemented in different solutions. We try to follow the UNIX approach of doing one thing well.

I would suggest implementing a `helm ready` plugin first to see if there's utility in de-coupling `--wait` as its own feature.

> I'm not sure how it can be a plugin without changes to `helm.sh/helm/v3/pkg/kube`

A plugin could re-implement the code present in pkg/kube without having to import it straight from Helm. If there are parts of the codebase that can safely be refactored into its own package, that is also an option. This is how experiments like a plugin helps improve the usability overall - we can determine what needs refactoring, and how to slice it up so clients can re-implement core parts of Helm.

Hope this helps provide some guidance.

**Comment by joejulian** [comment]
I'm working on this.

**Comment by joelanford** [comment]
I just mentioned in https://github.com/operator-framework/operator-sdk/issues/4102#issuecomment-717315042 that we need this feature for the Operator SDK Helm operator. Would love to see it in the core Helm SDK.

**Comment by joejulian** [comment]
My idea is to split the readiness check into its own function. In the copy that I forked for our internal project, that function optionally takes a flag and return the readiness of every resource instead of exiting early if any resource is not ready.

I suspected that I should probably do this as two PRs, one just moving the tests into a function without changing any behavior, and one that adds the new behavior.

**Comment by joejulian** [comment]
I should have some time again soon (release push happening now).

**Comment by joejulian** [comment]
/reopen

... doesn't work, does it...

**Comment by joejulian** [comment]
thank you

**Comment by joelanford** [comment]
@joejulian I think I've made the changes that you describe in https://github.com/helm/helm/issues/8768#issuecomment-695333291 in #9425.

Let me know what you think!

**Comment by joejulian** [comment]
Closed by #9425. Will do the rest as a plugin.
