### ISSUE TITLE
Is it possible to have empty value for collection/list item?

### ISSUE THREAD

**Issue by gyang1129** [helm/helm#8784]
Output of `helm version`: v3.3.1

Output of `kubectl version`: v1.18.5

Cloud Provider/Platform (AKS, GKE, Minikube etc.): local

Hi helmer:

I just encounter a problem with writing helm script.

What I trying to do is define a collection of item as follow, and for the value of each entry, it is referencing a yaml file from the template folder:

configMaps:
  - map1:
  - map2:
  - map3:

However, the problem is if I leave empty value for map1 to map3, the deployment would failed with this error:
"
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[2]): missing required field "name" in io.k8s.api.core.v1.VolumeMount, ValidationError(Deployment.spec.template.spec.volumes[2]): missing required field "name" in io.k8s.api.core.v1.Volume]
"

As a work around, I have to provide default value for map1 to map3.

So my question is, is it possible to have empty value for map1 to map3? if yes, how can i do it?

Thank you very much for your assistant, and I wish you all a good day.

**Comment by mattfarina** [comment]
@gyang1129 That's a good question. Let me first say, that this error isn't something to do with Helm but rather something to do with Kubernetes.

Helm is validating the generated YAML against the Kubernetes API. Kubernetes supplies an OpenAPI schema that can be validated against. The error you're seeing is because the generated YAML from the templates is invalid per Kubernetes. If you manually generated the same YAML and tried to upload it to Kubernetes using kubectl you should see a similar error for the same issue.

Without seeing more of your templates I can't come up with a suggestion for how you can proceed. Is that something you can share?

**Comment by gyang1129** [comment]
> @gyang1129 That's a good question. Let me first say, that this error isn't something to do with Helm but rather something to do with Kubernetes.
> 
> Helm is validating the generated YAML against the Kubernetes API. Kubernetes supplies an OpenAPI schema that can be validated against. The error you're seeing is because the generated YAML from the templates is invalid per Kubernetes. If you manually generated the same YAML and tried to upload it to Kubernetes using kubectl you should see a similar error for the same issue.
> 
> Without seeing more of your templates I can't come up with a suggestion for how you can proceed. Is that something you can share?

Hi,

Thanks for the reply, I am sorry that the script is not something I can share because it is internal. 

I know exactly what goes wrong, it is the collection entry can't have empty value. But it worked if I provided default value.
