### ISSUE TITLE
float64 - how to prevent no to convert float with 0 fraction to integer

### ISSUE THREAD

**Issue by laplasz** [helm/helm#8799]
Output of `helm version`:
Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
Output of `kubectl version`:
 version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5

in values.yaml there is a parameter with zero fraction
`param1: 10.0`
when this param is used the output will be converted to int
`{{ .Values.param1 }}  //printout will be 10`

is it possible to disable this conversion? thx

**Comment by mattfarina** [comment]
I figured out what's going on. Helm uses the Kubernetes yaml parser that build on gopkg.in/yaml.v2. There is an issue with it that causes whole number floats to be parsed as integers. The issue is at https://github.com/go-yaml/yaml/issues/430.

A workaround, if you need to change the type in a Helm template, is to use the [`float64`](https://helm.sh/docs/chart_template_guide/function_list/#type-conversion-functions) type conversion template function.

Does that help?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Comment by yjbdsky** [comment]
Is the issue resolved?
