### ISSUE TITLE
Add Docker authentication to CircleCI jobs

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm#8848]
Starting November 1, 2020, Docker Hub will impose rate limits based on the originating IP. Since CircleCI runs jobs from a shared pool of IPs, it is highly recommended to use authenticated Docker pulls with Docker Hub to avoid rate limit problems.

This configuration will have to be applied to both the `dev-v2` and `master` branches to prevent CI from failing. More information on how to apply authentication to CI jobs can be found here: https://circleci.com/docs/2.0/private-images/

**Comment by mattfarina** [comment]
@bacongobbler for pushing tiller images to docker hub, I started to setup a helmbot account. I will share the details with the org maintainers when the setup is done. I have a support ticket open because I'm unable to verify the email address. Credentials for that account are something we should be able to use.
