### ISSUE TITLE
Helm dep build/update doesn't inherit --insecure-skip-tls-verify from helm repo add

### ISSUE THREAD

**Issue by tsfullman** [helm/helm#8868]
Output of `helm version`:
3.3.4

When using "helm repo add" with the --insecure-skip-tls-verify flag it works as expected. However, when trying to then helm dep build with a Chart.yaml that references that repository, it throws the x509: certificate signed by unknown authority error and doesn't carry over the flag. Helm dep build/update doesn't actually have that flag as a separate option either

**Comment by bacongobbler** [comment]
Marking as a feature enhancement.

**Comment by yxxhero** [comment]
can I add this feature for helm？ @bacongobbler

**Comment by bacongobbler** [comment]
sure.

**Comment by yxxhero** [comment]
@bacongobbler  Anything should I do for this issue?

**Comment by yxxhero** [comment]
@bacongobbler ping

**Comment by kofl91** [comment]
This is still needed. 
"Helm dep update" is virtually useless for self hosted enviroments due to this bug. Non of the configurations of helm are used in "helm dependencies update". 

- Not "insecure_skip_tls_verify: true"
- Not the configured "- caFile: ????.crt"

And there exists no cli parameters for this either, making self hosted/local repositories inaccessible for helm dep up. 

However helm fetch, helm search repo, etc. have these options and have no problems accessing the exact same repo.
This bug has been around for quite a while and is super useful if fixed.

- Local dependency testing
- enterprises with private clouds and own certificate infrastructure

**Comment by yxxhero** [comment]
ping

**Comment by hickeyma** [comment]
Changing this to a bug as it is something that is not working as expected.
