### ISSUE TITLE
Templating issue template: base:92: bad character U+002F '/'

### ISSUE THREAD

**Issue by nmathew** [helm/helm#8898]
I am trying to substitute

annotations:
                 metallb.universe.tf/address-pool: system-pool

In template

annotations:
      sharedVIPLabel:
      addressPoolName: {{ .Annotations.metallb.universe.tf/address-pool }}

This gives me an error 
**template: base:92: bad character U+002F '/'.**

Any idea how to solve this?

**Comment by hickeyma** [comment]
@nmathew The template parser is baulking at the `/` in your example above. What is this `{{ .Annotations.metallb.universe.tf/address-pool }}` meant to do? I am asking because I am unaware of a helm bulit-in object `Annotations`

**Comment by nmathew** [comment]
Annotations is a map[string]string map, this we forms and passed to template engine.

One of the key in that map is "metallb.universe.tf/address-pool", and the value is "system-pool"

**Comment by bacongobbler** [comment]
Can you please demonstrate using an example? I.e. something we can use to reproduce or recreate your example so we can test it out for ourselves. Thanks.

**Comment by nmathew** [comment]
will update by tomorrow

**Comment by bacongobbler** [comment]
ping.

**Comment by mattfarina** [comment]
I'm guessing that this is the [`annotations` property in the `Chart.yaml` file](https://helm.sh/docs/topics/charts/#the-chartyaml-file).

Finding a good way to get at the information is hard, it turns out. You can't use `get` in templates because that expects a `map[string]interface{}` but gets a `map[string]string`. So, I wrote a template function that would do this...

```
{{/*
Get an annotation value
This can accept a name with a . or a / in it
*/}}
{{- define "example.annotationValue" -}}
{{- $annotations := first . -}}
{{- $key := last . -}}
{{ range $i, $e := $annotations -}}
{{- if eq $key $i }}
{{- $e }}
{{- end }}
{{- end }}
{{- end }}
```

Then you use it like...
```
{{ include "example.annotationValue" (list .Chart.Annotations "foo.io/bar") }}
```

Be sure to change "example" to the name of your chart. You can put that function in the `_helpers.tpl` file.

Does this help?

**Comment by bacongobbler** [comment]
closing as answered/inactive. Let us know if you need further assistance.
