### ISSUE TITLE
Using secrets to store releases can stress api server limits.

### ISSUE THREAD

**Issue by paulgmiller** [helm/helm#8977]
So I've seen a couple of clusters with large amounts of helm releases stored as secrets.

However kubelet seems to list all secrets when it first starts up (presumably to start a watch) at start up. So on large scale up events like adding 100 nodes to a cluster you have a good chance to OOM the api server and it may not recover as kubelets continue to pound it as it comes back up.  Once the list is processed api server memory comes back down as caches some of it and tossses the rest.  We've seen an api server that normally runs at about 2G spike over 6G.

Could probably repro this taking the largish prometheus helm chart. Cranking up max history to 200 and then upgrade/release on a loop or just use different release names/namespaces. Then start/restart a bunch of nodes.  Have not actually tried this though.

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by bacongobbler** [comment]
Wouldn’t this be considered a kubelet bug? Not sure how Helm should “fix” this to work around the kubelet’s current limitations.

**Comment by bacongobbler** [comment]
To clarify: how is this any different from any other cluster admin creating a ton of secrets and then restarting their kubelets? Why is this issue particular to Helm?

**Comment by paulgmiller** [comment]
Yep could also be considered a kubelet bug. Really depends on if watching
secrets across all namespaces predates helm v3. But I'm guessing kubelet
would also say what's up with these large "secrets"

Could also say api server should dedupe better or be given more memory.

Just wanted to start a discussion somewhere since I saw it in multiple
places. Not trying to point blame.

**Comment by mattfarina** [comment]
This sounds like an issue with k8s worth working on for scaling.

I'm reminded of CronJobs. There have been issues for people who scale up to large numbers of CronJobs (10's of thousands). This is one of the things that has blocked CronJobs from going GA. It's currently being worked on.

**Comment by juan-lee** [comment]
> To clarify: how is this any different from any other cluster admin creating a ton of secrets and then restarting their kubelets? Why is this issue particular to Helm?

@bacongobbler @mattfarina 

kubelet is doing what it's supposed to do, bind secrets to pods, based on the intended use of secrets. I'd argue that helm is misusing secrets as a metadata store since the secrets it creates are never bound to a pod.

The impact of this design decision is that users of helm will have challenges running clusters at scale. Was this considered during the design of helm 3? If so, I'm curious why we still went this route considering similar issues with configmaps in helm 2.

**Comment by bacongobbler** [comment]
> I'm curious why we still went this route considering similar issues with configmaps in helm 2.

This was never brought to our attention until just now. How were “we” made aware of this limitation?

For historical reference, Helm 3 was originally slated to use CRDs as storage. After experimentation we moved to Secrets. More info can be found in the archives. https://github.com/helm/community/blob/master/hips/archives/helm/helm-v3/003-state.md

**Comment by mattfarina** [comment]
> kubelet is doing what it's supposed to do, bind secrets to pods, based on the intended use of secrets. I'd argue that helm is misusing secrets as a metadata store since the secrets it creates are never bound to a pod.

We've put some thought into our decision here. It's about trade-offs and how things have changed over time. I'll try to explain.

When kubelet starts up it lists secrets and configmaps. Helm used configmaps prior to secrets being an option. Now Helm uses secrets. Helm has been using one of these that's listed by the kubelet at startup for years. This is the first time I've seen an issue be brought up about this. That doesn't mean there isn't an issue but it does mean it's an edge case issue rather than a typical situation.

We also need to ask, what are Secrets (and ConfigMaps) for? There is both the original intent and the current use. They were intended for passing information to pods/containers. I've read the original design proposals which are a great place to get original intent. But, original intent is only a start. These resources are now used to store more information than that which is directly passed to containers.

Why doesn't Helm use something different like a custom resource based on a CRD? These aren't loaded at startup by the kubelet. This is where the trade-off comes in. Many of Helm's users do not have cluster access to install a CRD into the cluster. They are allowed and sometimes encouraged to use Helm. There are many organizations who do not want to give their developers access to extend the API. So, Helm can't use CRs/CRDs and meet the needs of end-users. So, we make the trade-off to use secrets.

To over communicate on CRDs, when Helm v3 development started I expected Helm to move to CRDs. It was through talking with end-users that we learned they would not be a good fit.

Folks having issues with kubelet and Secrets is very rare. Setting a max history to 200 is highly unusual making it an edge case. I think this is the first time I've heard someone bring this up as an issue and Helm has been using configmaps or secrets for years.

Now, on to some practical things...

1. Helm is serious about backwards compatibility and supporting the community long term. So, a change from secrets can't be made in v3 and it will be some time before we release v4. We have looked at things like the cost to switch when applied to end users needing to make changes.
2. If you have a proposal for a change I would ask that you create a [Helm Improvement Proposal](https://github.com/helm/community/tree/master/hips). I'm interested in hearing other ideas. They just need to be pragmatic and meet the needs of end-users.

**Comment by technosophos** [comment]
Those who have specialized requirements might be better served by not trying to store their releases in Kubernetes. Use an alternative backend, like [SQL Storage](https://helm.sh/docs/topics/advanced/#sql-storage-backend).

This is in fact the reason DB support exists. The trade-off is runtime complexity (you have to manage your DB). But then you can tune performance and configuration to meet whatever needs you have.

The mechanism for storing secrets is extensible, so those wanting some other backend could write their own storage layer.  Here's where you would start if you want to look at the code: https://github.com/helm/helm/tree/master/pkg/storage/driver

**Comment by paulgmiller** [comment]
@mattfarina  Thanks for the great/thorough response. The concept that some customers wouldn't have access to add new CRD's totally makes alot of sense. 

I always kind of assumed we helm wouldn't move away from secrets in any short/medium time frame but I still wanted to get this out there so people would be aware of the possible consequences of having "lots" of releases. I think my only short term goal is awareness  and maybe trying to document what a given number of releases/node restarts might require from api server and linking this from the max history count. 

Your response also makes me realize that it'd probably be hard for helm to tell when an API server has a "dangerous" number/size of releases if the user running it only has access to their namespace.

I also want to start an issue in the Kubernetes repo to talk about best practices for clusters with large size/count secrets but wanted to have this first so they didn't just say "why do you have such big secrets you're silly"

Is there any desire to have the backend for release storage be pluggable in anyways so users could use other data stores besides the api server? Not sure if that's a road you even want to go down. Looks like @technosophos  answered that while I was typing 

I'm still trying to get a private repro. The cluster I saw this on this monring had about 80megs of secrets and 42 nodes that they restarted all at the same time to go up above 6 gigs of memory. So I'm hoping to have more data here.

For AKS we think we're seeing this because we're finally seeing larger scale customers and are considering things like throttling but we're just getting started there. We might also be able to warn customers when secret count gets large and redirect them to helm docs about max history.

**Comment by technosophos** [comment]
@paulgmiller in the AKS-specific world, a CosmosDB backend would be an awfully enticing possibility! Imagine the data resiliency you'd be able to achieve with that. The storage API is not terribly complex, so you would be able to prototype something pretty quickly, I think.

**Comment by mattfarina** [comment]
@paulgmiller I really like the idea of using a different backend. I wonder if the existing [SQL backend](https://helm.sh/docs/topics/advanced/#sql-storage-backend) would work with CosmosDB.

**Comment by paulgmiller** [comment]
I wonder if making the secrets immutable in supported k8s versions would be helpful from a performance perspective. (Might be nice even if it doesnt).
https://kubernetes.io/docs/concepts/configuration/secret/#secret-immutable

**Comment by paulgmiller** [comment]
@mattfarina @technosophos  you a precahing to the choir but unfortunately cosmos db's golang client support isn't.... great. @imiller31 also saw this. You basically have to use a mongo shim or the old table store api. The latter could work but it's client isn't getting updates. You are preaching to the choir though I've long wanted to actually put more k8s state into cosmos db. 

We might be able to help make that driver work with azure sql though. I don't think our scale needs are **huge** here just not etcd.

**Comment by technosophos** [comment]
I don't think the immutable flag has been tried, so it might be worth experimenting. Because of our backwards compat guidelines, we wouldn't enable that behavior by default. But it might be worth testing under a feature flag.

**Comment by paulgmiller** [comment]
I don't think immutable will get us much (though still might be more "correct".

Played around some with storage driver and azure blob. https://github.com/helm/helm/pull/8998
Still owe data on what releases size * node reboots look like in terms of api-server memory usage.

**Comment by juan-lee** [comment]
Thanks @mattfarina @technosophos for the context. For users that are managing the state of their clusters using source control, is there any benefit of having helm history beyond what's currently deployed?

**Comment by bacongobbler** [comment]
The ability to roll back to a prior known state is something that's important to a number of users. See `helm rollback`.

**Comment by paulgmiller** [comment]
I should back this up somewhat as pointed out on https://github.com/kubernetes/enhancements/issues/1412 kubelet doens't actually list all secrets because it uses fieldselector metadata.name which gets translated into a get. On my repro cluster rebootin a bunch of kubelets didnt spike memory so I believe this. On clusters with large numbers of secrets where we see this memory spike we do see other components listing secrets (helm, brigade and apiserver(?)). @juan-lee  and I are still trying to get to the bottom of this. I'm trying to repro by replaying some these lists but thought I should give an update.
