### ISSUE TITLE
Feature: Ask for confirmation before uninstalling a chart

### ISSUE THREAD

**Issue by InsOpDe** [helm/helm#8981]
I live in a constant fear of accidentally uninstalling a chart.

I would suggest that the cli asks for confirmation before uninstalling.
As this would break pipelines which are relying on deleting charts without being asked, it would be necessary to enable this setting with either a config file or an environment variable like `HELM_UNINSTALL_SAFEGUARD` which has to be set.

One could then overwrite these settings with `helm uninstall some-chart -y`

As a workaround I use this in my `.zshrc` (which is not *that* robust)

```zshrc
#helm
alias hi='helm install'
#alias hun='helm uninstall'
function helm {
        if [[ "${@:1:1}" == "uninstall" ]]; then
                hun "${@:2}"
        else
                command helm "$@"
        fi
}
function hun {
        read "?Are you sure ?"
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            command helm uninstall "$@"
        fi
}
alias hug='helm upgrade'

```

**Comment by bacongobbler** [comment]
A similar request was made for `helm install` back for Helm 2 via #2269. In short, we debated whether adding a confirmation prompt in front of `helm install` would break backwards compatibility, and we agreed that it would indeed break compatibility and therefore could not be introduced during Helm 2's development cycle. Instead we shared a workaround by writing a wrapper script around Helm.

> As this would break pipelines which are relying on deleting charts without being asked, it would be necessary to enable this setting with either a config file or an environment variable like `HELM_UNINSTALL_SAFEGUARD` which has to be set.

I agree. Because of the precedent mentioned earlier in #2269, we cannot introduce a confirmation prompt in front of `helm uninstall` without breaking backwards compatibility. Once Helm 4 development begins, we can remove this safeguard and make prompting for confirmation the default.

Is this something you're willing to work on? There's some code around prompting for user input for `helm registry login --password-stdin`, which would be a good place to start looking.

**Comment by bacongobbler** [comment]
> Is this something you're willing to work on?

ping.

**Comment by wawa0210** [comment]
@bacongobbler 

Is anyone else following up on this issue? If not, I am willing to mention a pr. If I am developing now, which branch should I merge to? You mentioned that this feature is best in the helm 4 version

**Comment by jwenjian** [comment]
Any update on this feature?

**Comment by luk-sam** [comment]
Any update?

p.s.
this thread is a sad place of those, who removed something from prod and got task to find a way to prevent it in the future.. I'm one of you guys.

**Comment by nchicong** [comment]
Such important feature has not been having enough attention

**Comment by Freddo3000** [comment]
I'll just add a `.bashrc` version after running into this for the second time within a week:
```bash
helm() {
  if [[ "$1" == "uninstall" ]]; then
    helm_uninstall "${@:2}"
  else
    command helm "$@"
  fi
}

helm_uninstall() {
  echo "[>] Current kubectl context: $(kubectl config current-context)"
  read -r -p "Are you sure you want to uninstall '$*'? [y/N] " answer
  if [[ $answer =~ ^[Yy]$ ]]; then
    command helm uninstall "$@"
  else
    echo "Cancelled"
  fi
}
```
