### ISSUE TITLE
Proposal: Add flag `--ignore-kubeversion`to install/upgrade command

### ISSUE THREAD

**Issue by crunchtime-ali** [helm/helm#8986]
Some chart maintainer are quite aggressive when it comes to setting their chart's `kubeVersion` range.
Here is a reference discussion illustrating this problem: https://github.com/kokuwaio/helm-charts/issues/21

We can't upgrade our cluster to the required `1.16` yet but want to use the helm-chart which only requires Kubernetes 1.16 for the `PodSecurityPolicy` which can also be disabled.
However, we can't install it without forking the repo because we can't disable the `kubeVersion` check knowingly.

Therefore, I propose adding a flag called `--ignore-kubeversion` to the install and upgrade command of Helm. I would also be willing to create a PR for it + tests + docs.

What do the Helm maintainers think about this?

**Comment by hickeyma** [comment]
@crunchtime-ali Helm has a process for proposal called [Helm Improvement Proposal](https://github.com/helm/community/blob/master/hips/hip-0001.md). Do you mind creating a HIP for this proposal?

**Comment by bacongobbler** [comment]
I agree that a HIP would be a great way to iron out some of the design concerns.

In particular, I'm concerned that the chart author clearly set their `kubeVersion` range to restrict which Kubernetes versions this chart is supported on, then by "breaking out" of that supported range, the consumer is bypassing the restrictions which the chart author clearly set upon the chart. This seems like a concerning design case: the author clearly did not design the chart to work with that version of Kubernetes, and now the consumer is trying to bypass that control.

For example, one of our assumptions when we wrote up [Helm User Profiles](https://github.com/helm/community/blob/master/user-profiles.md) is that the chart author (Application Distributor) knows more about the internal workings of the chart than the chart consumer (Application Operator). This proposal appears to break that assumption, which I do not agree with.

If it's just a matter of "some chart maintainer set their `kubeVersion` too aggressively", then perhaps a PR or a test case to confirm that the chart works with future iterations of Kubernetes is more appropriate, in which case this is not a technical issue, but an issue with their process or test infrastructure.

Again, a write-up in a HIP might be more helpful to carefully consider these design cases and how the author of said feature intends to address them.

**Comment by doug62** [comment]
+1 - I need this feature, I use k3s and this catches most charts.

**Comment by deefdragon** [comment]
I encountered a situation that needs this, and it appears no HIP has been made. The authors of a chart set restrictive versions, only going up to the latest release at the time when setting the version. I would normally just upgrade to the chart to latest, but due to how this particular operator works, the resource upgrade has to be done in stages. 

With my kubernetes being upgraded to 1.31, I could only support the operator 1.13, but operator 1.13 required resources to have been upgraded to 1.11, something that Id not done as I didnt realize it was a requirement. Installing chart 1.11 was not possible as I had already upgraded my k8s. Thus I was in a deadlock.

I managed to get out of this situation by downloading the chart and manually setting the kube-version. The kube-version restriction was entirely un-necessary (on the chart maintainers side), and the ability to bypass it would have saved me several hours.
