### ISSUE TITLE
Make sources field mandatory in charts and show link to it in bold in artifacthub

### ISSUE THREAD

**Issue by 123BLiN** [helm/helm#9011]
Every time I find myself spending a lot of time trying to find the source code for helm chart to check values.yaml and known issues.
It might be good to make source code link mandatory in Chart.yaml and to show it artifacthub in the header near REPO and ORG.

**Comment by mattfarina** [comment]
There are two asks here.

First, for the element with Artifact Hub, can you file an issue with that project for it. It is a different project from Helm. You can find it at https://github.com/artifacthub/hub

Second, this is the kind of change that would need a [Helm Enhancement Proposal](https://github.com/helm/community/tree/master/hips). Could you please create one. This is the kind of issue that needs to be well thought out for the various roles and the technical implications.

This can't happen until Helm v4 at the earliest due to backwards compatible guarantees in semver.

**Comment by bacongobbler** [comment]
See also #4256.
