### ISSUE TITLE
Sub-charts files and folders permissions do not match defined umask

### ISSUE THREAD

**Issue by donatelloOo** [helm/helm#9036]
Output of `helm version`: 
```console
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

Output of `umask`: 0002

As a reminder, with this umask 0002, when creating files and directories from user shell, the files and dirs will automatically get **group write** access:
- files: 0664 (-rw-**rw**-r--)
- dirs: 0775 (drwx**rw**xr-x)

Suppose we have a "helm" folder shared between several users.

When generating helm dependencies from user shell `user-01`, it produces the following helm files and folders:
```console
-rw-r--r--   1 user-01 users      Chart.lock
drwxr-xr-x   1 user-01 users      charts/
-rw-rw-r--   1 user-01 users      ` local-sub-chart-1.0.tgz
-rw-r--r--   1 user-01 users      ` remote-sub-chart-1.0.tgz
```

Here created files and folders do not match default permissions defined by umask (surprisingly, except for sub-charts built from local disk).

Next, here come one use-case issue : when generating helm dependencies from **another user** shell `user-02` (which belongs to same group), it will fails because **remotely downloaded** files are strictly owned by `user-01`, and cannot be deleted.

```console
Could not delete /path/to/helm/tmpcharts/remote-sub-chart-1.0.tgz: permission denied
```

```console
-rw-r--r--   1 user-01 users      Chart.lock
drwxr-xr-x   1 user-02 users      charts/
-rw-rw-r--   1 user-02 users      ` local-sub-chart-1.0.tgz
-rw-r--r--   1 user-02 users      ` remote-sub-chart-1.0.tgz
drwxr-xr-x   1 user-01 users      tmpcharts/
-rw-rw-r--   1 user-01 users      ` local-sub-chart-1.0.tgz
-rw-r--r--   1 user-01 users      ` remote-sub-chart-1.0.tgz
```

So it seems helm use hard-coded permissions which does not follow default permissions defined by umask, and causing the error:
- 0644 for files downloaded from the internet
- 0644 for Chart.lock
- 0755 for charts/ and tmpcharts/ directories

**Comment by bacongobbler** [comment]
What's the suggested fix here? Do you have an example where Helm can respect current umask permissions?

There are many places in the code where 0644 and 0755 are hardcoded.

https://github.com/helm/helm/blob/55fbd985dd79fd8fad9c0f7e0c851ce1183321d3/pkg/repo/repotest/server.go#L128

**Comment by TBBle** [comment]
Per [stack overflow](https://stackoverflow.com/a/59434424/166389) and [a documentation update](https://github.com/golang/go/issues/35835), umask will be applied to the permissions specified to `ioutil.WriteFile` (and other related APIs) so the only way to address this would be to pass 0666 for files and 0777 for directories, and trust the user's umask to be correct.

I'd be surprised if anyone has a faulty umask and if they do, it's more than just Helm that will have issues, so I think that's not Helm's problem to solve; so that seems like a reasonable change to me.

On Windows, the perms are only relevant to [set the read-only flag if the user-write flag is not set](https://github.com/golang/go/blob/20f50bba49e6338793a5711dc1c6ed60e4b10df8/src/syscall/syscall_windows.go#L340-L362), e.g. 0444, which is not really relevant to Helm.

**Comment by donatelloOo** [comment]
as for almost all bot managed issues, it's closed without any change... maybe next time I won't take time to enter an issue.

**Comment by TBBle** [comment]
The bot left a note a month ago about this. If you wanted to keep this issue alive, a message in that time would have shown that it was still interesting to you.
