### ISSUE TITLE
Helm upgrade --install doesn't restart/recreate the pod if the image revision is the same

### ISSUE THREAD

**Issue by Emixam23-FCMS** [helm/helm#9041]
Output of `helm version`:
`3.2.0`

Output of `kubectl version`:
`latest`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

**GKE - Google Kubernetes Engine**

# ISSUE

Hey guys! I am coming today because I am facing a situation where I didn't find any workaround yet.. So here I come!

## Context

I have a pod running in a GKE which got deployed throught HELM strategy (using Cloud Build).

*deploy.yaml*
```
steps:
- name: 'gcr.io/${_PROJECT_ID}/helm'
  args: ['dependency', 'update' , 'deployments/helm/${_PROJECT_NAME}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - 'TILLERLESS=true'
  - 'TILLER_NAMESPACE=${_PROJECT_NAMESPACE}'
- name: 'gcr.io/${_PROJECT_ID}/helm'
  args: ['upgrade',
         '${_RELEASE_NAME}', 'deployments/helm/${_PROJECT_NAME}', '--install', '--force', '--reset-values',
         '--wait', '--timeout', '120s',
         '--namespace', '${_PROJECT_NAMESPACE}',
         '--values', 'deployments/helm/${_VALUES_ENV}.values.yaml',
         '--set-string', 'image.tag=${_IMAGE_VERSION}',
         '--set-string', 'key1="${_VALUE}_1"',
         '--set-string', 'key2="${_VALUE_2}"']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - 'TILLERLESS=true'
  - 'TILLER_NAMESPACE=${_PROJECT_NAMESPACE}'
  - 'HELM_TILLER_STORAGE=secret'
  - 'HELM_TILLER_HISTORY_MAX=10'
```

Everything works like a charm but the following situation.

## Problem

I have a version *master-123456a* running. I am now deploying an update of my code which got as revision tag *master-9802ale*. It gets deployed like a charm and the pod is working as well after a clean restart.

Now, for some reason, someone just kills a service we are listening to!! The retry system we developed is shit and doesn't work! (sorry for my words). We so want to just restart the pod and so, we run the command above and.. **NOTHING HAPPENS**

If we do an edit on the code and commit the changes (then of course rebuild the image), it does get deployed.

`helm upgrade --install` ([as stated in the doc](https://helm.sh/docs/helm/helm_upgrade/#options)) doesn't restart the pod (or redeploy) a version that already exists. So what would be the best approach for me?
- Change the naming approach for each built images 
- Add a flag that goes against --install policy/logic

Because what I want is redeploy my built image without loosing time to rebuild it

Thanks for any feedback!

**Comment by bacongobbler** [comment]
Most (if not all) workload types in Kubernetes allow you to specify an image pull policy. By changing that pull policy to "always", any time a pod is restarted, it will re-fetch the container image from the registry.

That way when you "just restart the pod", it will attempt to re-grab the image.

Hope that helps.

**Comment by bacongobbler** [comment]
That being said most software applications are built with some form of versioning system in mind. With proper version control, you should be releasing a new version of the image each time a new release is available. In doing so, you ensure that an upgrade of your system will pick up the new image and you circumvent this issue altogether.

In other words, I would suggest adopting some form of versioning system for your container images.

**Comment by TBBle** [comment]
I don't think this is an image-pull-policy problem.

If I understand the request, the desire is to restart the pod, because logic in the pod is failing to retry to another service which went down, so you just want to kill it. The `helm upgrade` command is just trying to trigger that by redeploying an _unchanged_ chart.

In this case, @Emixam23-FCMS, I think you don't need to `helm install`. You just want to trigger the Pods in the Deployment to restart, so use
```
kubectl rollout restart deployment <deploymentname>
```
for whatever the `Deployment`'s name is that contains the Pods you want to restart. See [the kubectl reference](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-restart-em-) and [a similar answer on Stack Overflow](https://stackoverflow.com/a/57559438/166389) for more details.

If it's just one Pod you want to restart, you can just `kubectl delete pod <podname>`, and the Deployment will recreate it.

**Comment by nixancha** [comment]
Have you checked your `UpdateStrategy` in Values.yaml?. If it is set as `OnDelete` then change it to `RollingUpdate` and if not then please use as suggested by @TBBle

**Comment by cglacet** [comment]
I'm still confused about this discussion, isn't `helm upgrade --install` command supposed to start a rolling update? Do I need to call `kubectl rollout restart deployment` everytime I upgrade?

In my case I have a pipeline that builds the "latest" image and then I call the helm command to start using the updated version in production.

**Comment by TBBle** [comment]
`helm upgrade --install` updates the deployed resources to match the chart. (Since it's a 3-way merge, it's slightly more complicated, but this is accurate enough for our purposes here).

If the resulting resources are different, then kubernetes naturally does a rolling upgrade, the same as for any other system that modifies a Deployment or similar, including manually editing with `kubectl edit`. Helm doesn't do any of the actual rolling upgrades etc, that's all up to kubernetes. As noted in https://github.com/helm/helm/issues/9041#issuecomment-1146019668, it's possible to disable this in some cases, e.g. `UpdateStrategy`, but that's still a kubernetes thing, not Helm-specific.

If the resources are _unchanged_ (as is the case here, because it's doing an "upgrade" to the version that's already deployed) kubernetes doesn't see any difference and doesn't roll anything, by design of kubernetes (as a state-reconciliation system).

So if you use `helm upgrade --install` to _actually change_ the resources (new chart version, changed values, etc), then a rolling update will happen as you'd expect.

If you are trying to use `helm upgrade --install` to just restart some pods (as the original poster was), it probably won't work with a bunch of noisy messing about; that's what `kubectl rollout restart deployment` is for.
