### ISSUE TITLE
cmd arguments for post-renderer

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#9045]
Hi,

currently its not possible to pass arguments to post-render.

```
jkr@joe-nb charts % helm upgrade -i -n kube-system calico "calico" --post-renderer kubectl kustomize calico/kustomize 
Error: "helm upgrade" requires 2 arguments

Usage:  helm upgrade [RELEASE] [CHART] [flags]
```
```
jkr@joe-nb charts % helm upgrade -i -n kube-system calico "calico" --post-renderer "kubectl kustomize calico/kustomize"
Error: invalid argument "kubectl kustomize calico/kustomize" for "--post-renderer" flag: unable to find binary at kubectl kustomize calico/kustomize: exec: "kubectl kustomize calico/kustomize": stat kubectl kustomize calico/kustomize: no such file or directory
```

A shell file could be a workaround, but it isn't flexible.

Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

**Comment by marckhouzam** [comment]
This sounds reasonable to me. You would need to use the form using quotes to make it a single argument to the `--post-render` flag.  And after that it should just be about splitting on spaces.

Care to submit a PR @jkroepke ?

**Comment by jkroepke** [comment]
I try, I may need help.

**Comment by faizanf47** [comment]
+1

**Comment by zees-dev** [comment]
I have a `scratch` based docker image - which contains the `kubectl` binary.
Unfortunately i cannot use a script (due to absence of a shell).
The ability to pass in CLI args to the post-renderer would be great.
Looking at the codebase, rather than performing a binary lookup, we could just make it execute the `post-rendered` command (this way it could be a binary or a string command)?
