### ISSUE TITLE
helm 3 does not honour podAntiAffinity changes in Deployments when installing an initial Release

### ISSUE THREAD

**Issue by octplane** [helm/helm#9049]
This bugs happens when you install a release over previously existing Deployments in the cluster:

- A Deployment was created using kubectl earlier
- It has been patched to have the correct `Helm` release annotation attached
- Upon initial install, the `podAntiAffinity` rules are not correctly updated and the final live object contains a mix of the first and second release.

We believe this bug also happens for other fields of other resources but is difficult to characterise. I'll open other issues with more details if this is verifiable.

(This bug also happens for CRDs in a reproductible way in our environments but given the large difference in the code paths for CRDs, we have worked around that by `Replacing` the resource at cluster level)

Use the attached [tc.zip](https://github.com/helm/helm/files/5582579/tc.zip) to reproduce:

## Render and apply manually the default release

```
./helm template first tc > manifest.yaml
kubectl apply -f manifest.yaml
```

## Patch the deployment to add the Helm annotations

```
kubectl patch deploy anti-affinity-broker -p '{"metadata":{"annotations":{"meta.helm.sh/release-name":"first", "meta.helm.sh/release-namespace": "delivery-platform"}}}'
```

## Install the release and change its podAntiAffinity

```
./helm install first tc -f tc/values/breaking.yaml
```

## Check that the resulting Deployment is ill-configured

```
kubectl get deploy anti-affinity-broker -ojson | jq ".spec.template.spec.affinity"
```

```json
{
  "podAntiAffinity": {
    "preferredDuringSchedulingIgnoredDuringExecution": [
      {
        "podAffinityTerm": {
          "labelSelector": {
            "matchExpressions": [
              {
                "key": "app.kubernetes.io/instance",
                "operator": "In",
                "values": [
                  "crd-first"
                ]
              }
            ]
          },
          "topologyKey": "topology.kubernetes.io/zone"
        },
        "weight": 1
      }
    ],
    "requiredDuringSchedulingIgnoredDuringExecution": [
      {
        "labelSelector": {
          "matchExpressions": [
            {
              "key": "app.kubernetes.io/instance",
              "operator": "In",
              "values": [
                "crd-first"
              ]
            }
          ]
        },
        "topologyKey": "topology.kubernetes.io/zone"
      }
    ]
  }
}
```

🐛 We only expect `preferredDuringSchedulingIgnoredDuringExecution` here and not `requiredDuringSchedulingIgnoredDuringExecution `.

### System info

Output of `helm version`:

```
./helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.11-beta.1-dd.2", GitCommit:"aad6faa4b873b634be466d2801e37ae39e849874", GitTreeState:"clean", BuildDate:"2020-01-03T13:42:24Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

- On prem.

**Comment by bacongobbler** [comment]
Hi @octplane. A couple of notes to point out here:

The workflow described here where a deployment is "patched" to contain the correct release annotation then updated via a chart upgrade is not a support path we have tested nor demonstrated as a workable solution at this time, so it's unsurprising to me that there may be issues with that particular use case. It's simply not a workflow we have recommended at this time for this very reason.

It's best to start with a better understanding of the three-way merge patch strategy. During an upgrade, Helm renders the "source" release manifests (the previous install), fetches the live state of each manifest, then renders the "target" release manifests (the one provided via `helm upgrade`). During the patch process, Helm performs a three-way merge patch strategy between the three to determine the patch results. In this particular case, because there is no "source" release manifest to speak of, it is likely that the system assumes that the live state as correct. I could be wrong here, but this is my understanding of the system.

Hope this helps in your search.
