### ISSUE TITLE
Upgrade fails with existing service with zero changes

### ISSUE THREAD

**Issue by brianharwell** [helm/helm#9062]
Output of `helm version`: v3.4.1
Output of `kubectl version`: v1.19.1
Cloud Provider/Platform (AKS, GKE, Minikube etc.): On Prem

I am trying to deploy a helm package and when I do I get the following error...
```
Upgrade "your-cool-app" failed: failed to replace object: Service "your-cool-app" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

My helm command looks like...
```
helm upgrade "your-cool-app" "your-cool-app-1.0.23.tgz" --kube-apiserver "server" --kube-token "********" --install --force --wait --description "Release: 1.0.27" --history-max 10 --namespace "cool-app" --values "values.yaml"
```

If I remove the `--force` flag it works but it then leaves my deployment in a different state from what I want deployed.

I am not making any changes to the service so I am not sure why this is failing.

**Comment by bacongobbler** [comment]
Have you had a chance to read through #6378 yet? I explained in more detail on what happens during an upgrade and why this can occur in https://github.com/helm/helm/issues/6378#issuecomment-557746499.

As for why removing `--force` works, this is also expected behaviour from Kubernetes' point of view. `--force` tells help to make a PUT request against the Kubernetes API instead of a PATCH. The default `helm upgrade` behaviour is similar to `kubectl apply` and `helm upgrade --force` is similar to `kubectl apply --overwrite`. You would find kubectl would behave identically if you used `helm template | kubectl apply --overwrite` for example.

When you apply `--force`, you are asking Kubernetes to replace the current service manifest with the one Helm is providing, as opposed to just patching the difference. Because the Service you are templating does not specify the cluster IP, Kubernetes assumes that you are attempting to remove the cluster IP from the service, hence the error.

**Comment by brianharwell** [comment]
Thanks for the clarification.
