### ISSUE TITLE
The helm update failed

### ISSUE THREAD

**Issue by NadamHL** [helm/helm#9099]
ENV:

```
k8s： 1.15.12

[root@1111 yaml]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"archive", BuildDate:"2020-09-23T09:27:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"archive", BuildDate:"2020-09-23T09:27:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

[root@1111 yaml]# helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Update the chart package，The following update commands are executed separately

The update was not successful

```
helm upgrade node-exporter node-exporter -n test
```

The update was successful

```
helm upgrade node-exporter node-exporter -n test -f node-exporter/values.yaml
```

##### Updated here and previous version, only the resources.requests.cpu finger has been modified

As follows：

```
diff
118c118
<       cpu: 124m
---
>       cpu: 125m
```

**Comment by mattfarina** [comment]
When you upgrade to the latest version of a chart it will use the `values.yaml` file in that version as the default. You don't need to pass the location of the `values.yaml` file in. This is important because you can pass a URL as the chart location like `helm upgrade foo https://example.com/path/to/chart-1.2.3.tag.gz`. There is not way to pass the location of the values file inside of that remote archive.

If you want to override a default value than you can pass in a YAML file with just that difference or set it at the command line. Use `help` to see the flags for that as there are a few.

If you want to reuse the values from the last release (and not get them from the newer version of the chart) there is the `--reuse-values` flag.

Does that help?

**Comment by NadamHL** [comment]
When I use the --reset-values-true parameter, the value.yaml file takes the value.yaml file inside the newchart package, otherwise the previous version of the value.yaml file will continue to be used
