### ISSUE TITLE
Clarification on adding annotation for Helm resource-policy to k8s resources

### ISSUE THREAD

**Issue by Danny-SCNX** [helm/helm#9147]
Hi!

We are in the progress of migrating Helm from v2 to v3 but wanted to take a much safer approach.

According to this reference for helm v2,
https://v2.helm.sh/docs/charts_tips_and_tricks/#tell-tiller-not-to-delete-a-resource

we can use this to specific resources that should not be deleted when running helm delete.
`
metadata:
  annotations:
    "helm.sh/resource-policy": keep
`

But I noticed that when I tried to add the annotation via `kubectl edit` or `kubectl annotate`,
helm doesnt respect the annotations I added.

I am aware that there's a special note on keeping the double quotes but I cannot seems to get this correct.

What is the proper way to add the annotation here with the quotation marks, to any existing resources created by helm charts? Will anyone be able to enlighten me on this please?

Thank you!

**Comment by mattfarina** [comment]
This is a good question. When you make changes using kubectl, Helm v2 ignored them. The next time you would use `helm upgrade` the changes would be removed. This is something we fixed in Helm v3. If you want to add an annotation you may want to alter the chart you are using and perform an upgrade.

Have you seen the [helm-2to3 plugin](https://github.com/helm/helm-2to3) to help with the migration?

**Comment by Danny-SCNX** [comment]
Thank you for confirmation on this with HelmV2.

Using helm upgrade might not be an option because some of our resources were altered outside of helm.
In those cases, helm was used as an initiator, and then we continue adding some changes which is not supported by the charts. These resources are pretty problematic right now when it comes to helm version upgrade.

Please help me understand correctly.
For using the plugin helm-2to3, if a release did not have chart releases that's compatible with helm v3, what will happen when we use the plugin?

**Comment by mattfarina** [comment]
The helm-2to3 plugin doesn't alter the resources for the running workload in the cluster.

Instead, it migrates the configuration Helm uses to keep track of a release and it moves configuration on your location system to the new location.

In Helm v3 we use a new storage format in the cluster for configuration about the running instances of the chart. This helps with things like Helm rollback and other commands. The migration tool can test run a migration to the new format, perform the migration, and cleanup the Helm v2 resources that had held the same information.

This makes it possible for Helm v3 to take over something that was installed and managed in Helm v2.

Note, while you should test this... Helm v3 can perform upgrades on resources that were altered outside of the Helm workflow while retaining the outside changes. That is because it now uses [a strategic merge patch](https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches) to update.

Helm v3 now keeps it's local configuration in a new location. It is following specifications for different systems like AppData on Windows, the Library on Mac, XDG on supported systems, etc. The plugin will migrate the local configuration to the new location to carry over your settings.

**Comment by Danny-SCNX** [comment]
Great! I just tested this on one AKS. Migration was done pretty smoothly.
While I continue monitor the status and doing this one by one for my AKS, I think we can close this for now.

Thank you for the explanations. Very much appreciated!
