### ISSUE TITLE
Helm 3.4.1 --wait doesn't work with Openshift resources

### ISSUE THREAD

**Issue by alexandrsemak** [helm/helm#9154]
Hello there,

I was trying deploy openshift resources with Helm 3 but Helm doesn't wait result of release.

We don't use 'DeploymentConfig' just `Deployment` but with `ImageStream` without `ImageStream` Helm wait result of release in openshift.

**Comment by alexandrsemak** [comment]
looks like if you even not apply Openshift resources from Helm Chart it not respected to status of Helm release and `--wait`

**Comment by alexandrsemak** [comment]
pods was not deployed successfully but Helm 3 in openshift marked as deployed.
With Helm Chart which doesn't contained any Openshift resources Helm works with `--wait` and marked release with correct status

**Comment by mattfarina** [comment]
This is a good question. Helm only waits for resources shipped as part of Kubernetes. These are the resources tested as part of [certified Kubernetes](https://www.cncf.io/certification/software-conformance/). If a distribution, like OpenShift, adds or alters Kubernetes resources than Helm isn't able to test for them.

The reason for this is that different resources have different methods to test when they are ready. If you [look in the Helm code](https://github.com/helm/helm/blob/ba9cad9379f33d909bff8e85a85c935ab727482b/pkg/kube/wait.go#L52) you'll find logic for the different resources types.

I think the Helm docs could use an update to better explain this situation.

I would also be interested in discussing ways to enable people to extend wait (like Helm does with downloads) so that additional resource waiting could be supported without it being built in to Helm. There is no way for the Helm team to maintain and test all the different resources shipped with all the distributions.

**Comment by alexandrsemak** [comment]
as I understood Openshift backcapable with Kuberentes resources and we use `appsv1.Deployment` just with `ImageStream ` which not need to be verified by `wait` if I delete `ImageStream` from chart Helm works fine. 

Second point that even without `--wait` Helm should have correct release status? because even if release failed it marker as deployed.

also as I can see Helm has list of resources and sequence of apply like ConfigMap before Deployment it would be nice to be able extend for example:  `ImageStream` should be created before `Deployment`

**Comment by mattfarina** [comment]
> as I understood Openshift backcapable with Kuberentes resources and we use appsv1.Deployment just with ImageStream which not need to be verified by wait if I delete ImageStream from chart Helm works fine.

`ImageStream` is part of OpenShift and not Kubernetes. This is why Helm does not have handling for it built in.

> also as I can see Helm has list of resources and sequence of apply like ConfigMap before Deployment it would be nice to be able extend for example: ImageStream should be created before Deployment

Agreed. But, Helm isn't going to add custom resource provided by one distribution. That would favor one distribution over another. Any method added to Helm would need to be extensible so that it would work for any distro without Helm needing vendored code for it.

> Second point that even without wait Helm should set correct release status? because even if release failed it marker as deploye or it is the same question to validated method as for wait?

You can find a list of [status here](https://github.com/helm/helm/blob/ba9cad9379f33d909bff8e85a85c935ab727482b/pkg/release/status.go#L23-L42).

Deployed mean "the release has been pushed to Kubernetes". It does not mean that the application came up properly. That is outside of the control of Helm and quite often there is not a common method to reliability test for that.

Are you saying that Helm pushes the resources and Kubernetes does not accept them but the release is marked as Deployed?

**Comment by alexandrsemak** [comment]
> Are you saying that Helm pushes the resources and Kubernetes does not accept them but the release is marked as Deployed?

in Openshift any Helm release marked as deployed even if release failed. I understood that it is not reliable method just mentioned it.

**Comment by sbose78** [comment]
@mattfarina I totally agree that Helm should not be shipping custom logic for high-level workload abstractions by specific distributions.

At the most, we(as a community) could consider defining a good way for folks to contribute/maintain/develop such extensible capabilities. Example, https://github.com/argoproj/argo-cd/blob/master/resource_customizations/kafka.strimzi.io/KafkaConnect/health.lua .

Hi @alexandrsemak ,

Thank you for the report!

Would you have a detailed example of the issue you are facing in OpenShift with steps for reproduction of the same ? In my opinion, the logic [here](https://github.com/helm/helm/blob/ba9cad9379f33d909bff8e85a85c935ab727482b/pkg/kube/wait.go#L77) shouldn't care if the Deployment was triggered by an imagestream trigger :)  I am therefore curious to learn more on the issue you are seeing.
