### ISSUE TITLE
Helm dependency build  fails the second time

### ISSUE THREAD

**Issue by yelhouti** [helm/helm#9164]
When I run `helm dependency build ` on a chart with a dependency, no matter if the repository was added (`helm repo add`) is succeeds, but when I repeat the same command, if the repo was not added, it fails with:
Error: no repository definition for ...

Output of `helm version`: 3.4.2

Output of `kubectl version`: 1.19.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.): On premise

**Comment by mattfarina** [comment]
When using `helm dependency build` Helm requires that the repositories referenced have been added. This provides a means to opt-in to them. We do this for security purposes. So that a chart you use isn't altered to reference a 3rd party you are not aware of.

**Comment by yelhouti** [comment]
I don't get it, if you added the url of the repo in the Chart.yaml I am kind of opting in, if you are talking about nested dependencies repos, maybe i should be able to list them in the Chart.yaml. Anyway, the first time it works without the add (so maybe you should fix this).
Also, Is there a way a flag to ignore the check, would be pretty useful in pipelines...

**Comment by mattfarina** [comment]
First, there is an inconsistency between `helm dep up` and `helm dep build`. We are going to fix this in Helm v4. We cannot make the change until then due to backwards compatibility.

We recently had a security audit and this was one of the things they recommended going forward. We made some short term changes for this with plans for long term changes.

The use of repos should always be opt-in for security.

Second, With Helm there are multiple roles. There is the Helm user, the chart author/distributor, etc. In many situations the chart creator and the person who uses Helm to install the chart don't know each other. They are at different companies or organizations. Helm users can range from people who don't use Kubernetes to companies with an intimate knowledge. For example, a pulls an upstream chart and rebuilds it itself to make sure the dependencies all come from known locations. That company is under regulation and very careful for security.

Helm is a package manager, like apt, yum, zypper, homebrew, etc. Much of the time those are used to share packages between organizations and those use cases need to work well.

Third, depending on your pipeline it's possible to cache your repo config and local cache of information between steps. This might help with your issue.

Fourth, if you want to propose a feature this is something you could do. We will ask lots of questions and take it under careful consideration.

**Comment by yelhouti** [comment]
I don't get it, there is clearly a bug now, you just need to call:
```
helm dependency build
```
twice in a row. either both should work or none should.

**Comment by bbotto-pdga** [comment]
Sorry to wake the dead, but the response here (no offense intended) doesn't address the bug nor explain why it's not a bug.  I don't understand why `helm dep up` is relevant, nor the comments about Helm users and their competencies.

> When using `helm dependency build` Helm requires that the repositories referenced have been added. This provides a means to opt-in to them.

That does not appear to be the case.  `helm dependency build` does not require opt-in on the first run.  But, when run a second time, it fails with the error message provided by the OP.

Consider this snippet from a Chart.yaml:

```
dependencies:
- name: metrics-server
  version: "3.12.*"
  repository: "https://kubernetes-sigs.github.io/metrics-server/"
```

Without adding the Metrics Server repository, `helm dependency build` works just fine: it downloads the chart into the `charts` directory, and creates `Chart.lock`.

```
$ helm dependency build
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://kubernetes-sigs.github.io/metrics-server/" chart repository
Hang tight while we grab the latest from your chart repositories...
[... SNIP ...]
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading metrics-server from repo https://kubernetes-sigs.github.io/metrics-server/
Deleting outdated charts
```

Running `helm dependency build` again results in a failure.

```
$ helm dependency build
Error: no repository definition for https://kubernetes-sigs.github.io/metrics-server/. Please add the missing repos via 'helm repo add'
```

> there is clearly a bug now, you just need to call `helm dependency build` twice in a row.  either both should work or none should.

That sure seems accurate.  If this is not in fact a bug, can someone shed some light on why?
