### ISSUE TITLE
Support reading values from stdin for template

### ISSUE THREAD

**Issue by dbatten5** [helm/helm#9166]
Given that `helm install` supports reading values from STDIN as of https://github.com/helm/helm/pull/2809 it would be nice if `helm template` could do it too so I can do something like
```
sed 's/foo/bar/g' values.yaml | helm template --debug -f - .
```

**Comment by mattfarina** [comment]
`helm template` already works for reading from stdin. I just tested it to make sure it was working and had no issues. `helm template` and `helm install` share the same code paths around this functionality.

What happens when you try use stdin?

I just tried running

```
helm create foo
helm template ./foo -f -
```

**Comment by dbatten5** [comment]
ah ok maybe that's more my lack of understanding of stdin then. my use case here is that my `values.yaml` file has some values which `helm template` complains about if they're null (but i'd ideally like to keep them null in `values.yaml`). so in order to debug the template i need to comment out the values, which i'm trying to do with the following:
```
sed 's/bad_value/# bad_value/g' values.yaml | helm template . --debug -f -
```
but running that helm complains that `bad_value` is null. if i manually comment out all the `bad_value`s in `values.yaml` and run `helm template . --debug` then i get my desired output. if i replace the `helm template` bit in the pipe above with a `grep "# bad_value"` i can see the commented out lines so i think the `sed` part is working fine. maybe it's something else i'm missing?

**Comment by mattfarina** [comment]
Helm doesn't replace the default values with the values you pass in. Instead, it merges them. This enables the values passed in to just have to be those you want changed. When you comment out a value then the default is used because there is nothing to merge. I think this is what's happening here.

Null values are not a problem with YAML or Helm automatically. If a problem shows up it usually means there is something going on in the templates where this is used. I would need to see the template to know further about what's going on.

**Comment by dbatten5** [comment]
ah yes think that's right, if i do the following i get the desired output

```
sed 's/bad_value:/& "whatever"/' values.yaml | helm template . --debug -f -
```

i think the null value issue was coming from a chart schema.

interestingly, running `helm template . --debug -f values.yaml` doesn't throw any errors and i get the desired output.
