### ISSUE TITLE
`helm lint --strict` failed for charts created with `helm create ...` with ingress enabled with helm v.3.5.0

### ISSUE THREAD

**Issue by eugenekainara** [helm/helm#9246]
Lint with strict are failing on `apiVersion: networking.k8s.io/v1beta1` but helm create still use this apiVersion.

STR:
- `helm create example`
- `helm lint example` - this passed
- `helm lint --strict example` - this is also passed
- `helm lint --set ingress.enabled=true example` - this also passed
- `helm lint --strict --set ingress.enabled=true example` - this is failing now

For v3.4.0 - all lint executions are passing. Just warnings generated about `apiVersion: networking.k8s.io/v1beta1` deprecation.

Output of `helm version`:
on Mac OS via brew - version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.6"}
on docker via alpine/helm:3.5.0 - version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

**Comment by bacongobbler** [comment]
`helm lint --strict` fails on ANY linter warnings. Deprecated API versions fall under the scope of a warning as the API version will soon be deprecated.

If you do not wish for these linter rules to report an error, use `helm lint` without the `--strict` flag.

There has also been discussion on breaking up `helm lint` into linter rulesets which can be enabled or disabled upon request. That ticket is available in https://github.com/helm/helm/issues/2694, but it was closed due to inactivity.
