### ISSUE TITLE
Importing existing Helm resources.

### ISSUE THREAD

**Issue by nsaud01** [helm/helm#9279]
How on earth do you import and/or update deployed helm resources? It can't always be a matter of deleting and recreating with Helm. That's a major inconvenience in production systems.

I'm inheriting an environment which had resources deployed by helm but they were deployed from a different machine leaving me to figure out how to upgrade them with Helm. Any help would be appreciated.

**Comment by bacongobbler** [comment]
Hi @nsaud01. It's not totally clear what you're asking, so I'll start with a generic answer...

Have you had a chance to read through the documentation on using helm?

https://helm.sh/docs/intro/using_helm/

Let me know if you have any further questions.

**Comment by nsaud01** [comment]
@bacongobbler If I have resources deployed by helm, from a different machine, how do I go about importing and controlling those resources on a different machine with a new installation of helm? Helm doesn't recognize those deployments through `helm ls -A` . Is there a way of importing those deployments so that I may once again control/upgrade them through helm?

**Comment by marckhouzam** [comment]
Hi @nsaud01.  If resources were deployed with helm, running helm from any machine should be able to see them.  There is no data stored locally (all the data is stored on the kubernetes cluster).

Could it be that your resources were installed with helm v2?  Helm v3 will not report releases done with v2.
You can check this in a couple of ways.  For example you can do:
```
kubectl get -A cm -l OWNER=TILLER
kubectl get -A secret -l OWNER=TILLER
```

If you see anything, it would imply you have helm v2 releases.
Do deal with them you will need to install helm v2 on your machine.  You can find the binaries here https://github.com/helm/helm/releases/tag/v2.17.0
Once installed you should do `helm init --client-only` (as I assume you will have tiller already installed).
Then you can check releases with `helm list`

You would also need to start thinking about migrating them to helm v3 since v2 is no longer supported.
You can find docs here:
https://helm.sh/docs/topics/v2_v3_migration/

Let us know if that helps.

**Comment by nsaud01** [comment]
Thanks for that advice @marckhouzam! Some of the resources indeed had the TILLER owner flag. I have an ingress deployed with these labels, though. Shouldn't helm detect them? There is no OWNER=TILLER to be found.

```
Labels:              app.kubernetes.io/component=controller
                        app.kubernetes.io/instance=ingress-nginx
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=ingress-nginx
                        app.kubernetes.io/version=0.30.0
                        helm.sh/chart=ingress-nginx-2.0.0
```

**Comment by marckhouzam** [comment]
If you have some resources with OWNER=TILLER it indicates helm v2 for those resources.
But as you guessed, you can have both helm v2 resources and helm v3 resources at the same time.
I believe `app.kubernetes.io/managed-by=Helm` does imply a resource deployed by helm v3, which should be listed by your helm v3 `helm list -A` command.

If it is not, then it could mean the metadata of helm that is stored on the cluster has been modified.
For helm v3 the metadata is usually stored in a kubernetes secret in the same namespace as the deployed resources.
You can try:
`kubectl get secret -A | grep sh.helm`
to see if you have any helm v3 metadata on your cluster.
