### ISSUE TITLE
Error: validation: chart.metadata.version is required on helm package even though --version is used

### ISSUE THREAD

**Issue by s-spindler** [helm/helm#9298]
Output of `helm version`:
`version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}`

Output of `kubectl version`: n/a

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

`helm package` always requires the `version` field to be set in the Chart.yaml, even if the `--version` flag is set. Otherwise helm exits with `Error: validation: chart.metadata.version is required`.

Since `helm package` ignores the version from the Chart.yaml anyway if it is provided via command line it seems unnecessary and a bit confusing to still require it.

**Comment by mattfarina** [comment]
There are two roles or parts in this.

First, there is defining a chart (package). This is done by the chart creator. Often times the people who do this are at a different company from those who consume the charts. The charts that are released for consumption need a version and it is supplied here. Think of using apt, yum, or zypper. The packages you consume there are versioned. Same with Helm charts and the version is specified in the _Chart.yaml` files `version` field. This field is a semantic version.

Second, there is someone consuming a chart. If they use a command like `helm install` on a chart in a repository and do not specify a version then Helm will pick the most recent semantic version. It uses semantic version rules to determine the latest stable version in that repository. When the `--version` flag is used you can chose a specific version.

When you specify the version at the command line to use a chart then Helm needs to have the version of the chart available to check the version to determine the right version to use.

The `version` property is propagated around the Helm tooling. For example, this property is used when generating the index used in a Helm repository.

If the `version` property were not specified, how would the `--version` flag be able to work in getting a specific version?

**Comment by s-spindler** [comment]
Thanks for the explanation @mattfarina !
And apologies, I just realized that my original issue description was not particularly clear.
My issue is only with `helm package`. Of course with other commands it doesn't make much sense.

Basically what I want to do is define the version somewhere else. In my case in a Makefile variable which is then passed to all necessary build steps, among others `helm package` via the `--version` flag. This was possible with helm 2 but gives the above mentioned error since I upgraded to helm 3.

**Comment by s-spindler** [comment]
I updated the description of the issue accordingly.

**Comment by SleepyBrett** [comment]
It is not just --version though that applies directly to the error but given a chart file that looks like...

```
apiVersion: v2
name: foo
description: |
  foo
type: application
```

the following package command fails as follows
```
$ helm package --app-version <version from build tooling> --version <version from build tooling> -u foo
Error: validation: chart.metadata.version is required
```

This is also the case if the `version` and `appVersion` keys are supplied in the Chart.yaml but left blank, but the command will succeed if any value is provided in those keys.

Leaving these keys blank or absent seems the cleanest setup for a helm chart that will get versioned with the underlying code as it's built. the values of app-version and version being passed down through the build system.

**Comment by manno** [comment]
We used an invalid 'x.x.x' version and put a valid version when building the chart and running `package`. With helm 3.5 this fails. We put 'v0.0.0' into the chart instead, should still be invalid, but works.

**Comment by SleepyBrett** [comment]
Feature Request:

`helm package` should not validate the chart.metadata.version or chart.metadata.appVersion if their "setter" cli flags are passed.

**Comment by bacongobbler** [comment]
re-labeling as a bug. I agree that the following use case should be valid:

```
><> cat Chart.yaml
apiVersion: v2
name: test-9298
description: A Helm chart for Kubernetes
type: application
appVersion: "1.16.0"
><> helm package --version 0.1.0 .
Error: validation: chart.metadata.version is required
```

Unfortunately I believe this case is blocked because due to security issues with Go's YAML parser, we had to enable strict validation.

For reference, the strict parser is in place to prevent cases where a field can be overridden by re-declaring it a second time:

```
><> cat Chart.yaml
apiVersion: v2
name: test-9298
description: A Helm chart for Kubernetes
type: application
appVersion: "1.16.0"
version: "1.0.0"
version: "2.0.0"
><> helm package .
Successfully packaged chart and saved it to: /tmp/test-9298/test-9298-2.0.0.tgz
```

There's no way to tell the YAML parser to check for duplicate keys without enabling strict parsing. Fix that, and we can handle cases like the one raised by the OP.

**Comment by bacongobbler** [comment]
My apologies. It's actually because when loading the chart from disk, we validate the contents before overlaying things like the `--version` flag.

https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/chart/loader/load.go#L161

In most cases this makes sense as a chart loaded from disk should have a valid `version` field present. But perhaps we can handle this case differently... Either by loading the contents from disk, overlay the new values, THEN call `.Validate`. But this will likely require a new function signature.

**Comment by urton** [comment]
Any updates on this? I ran into this issue today after upgrading my client from 3.2.1 to 3.6.2 and trying to package a chart. We use placeholders in our Chart.yaml for version and then set the version when packaging, but this failed with both the 3.6.2 and 3.5.2 clients:

`$ helm package . --app-version 2.6.0.1 --version=2.6.4
Error: validation: chart.metadata.version "2.6.x" is invalid
`

I downgraded to 3.4.2 and was able to package again.

**Comment by kimba74** [comment]
@bacongobbler it looks like this issue got introduced with version v3.5.2

The `Validate()` function in `pkg/chart/metadata.go` looks like the following in **v3.5.1**:
```go
func (md *Metadata) Validate() error {
	if md == nil {
		return ValidationError("chart.metadata is required")
	}
	if md.APIVersion == "" {
		return ValidationError("chart.metadata.apiVersion is required")
	}
	if md.Name == "" {
		return ValidationError("chart.metadata.name is required")
	}
	if md.Version == "" {
		return ValidationError("chart.metadata.version is required")
	}
	if !isValidChartType(md.Type) {
		return ValidationError("chart.metadata.type must be application or library")
	}

	// Aliases need to be validated here to make sure that the alias name does
	// not contain any illegal characters.
	for _, dependency := range md.Dependencies {
		if err := validateDependency(dependency); err != nil {
			return err
		}
	}

	// TODO validate valid semver here?
	return nil
}
```

While the same function in **v3.5.2** has the SemVer check built in:
```go
func (md *Metadata) Validate() error {
	if md == nil {
		return ValidationError("chart.metadata is required")
	}

	md.Name = sanitizeString(md.Name)
	md.Description = sanitizeString(md.Description)
	md.Home = sanitizeString(md.Home)
	md.Icon = sanitizeString(md.Icon)
	md.Condition = sanitizeString(md.Condition)
	md.Tags = sanitizeString(md.Tags)
	md.AppVersion = sanitizeString(md.AppVersion)
	md.KubeVersion = sanitizeString(md.KubeVersion)
	for i := range md.Sources {
		md.Sources[i] = sanitizeString(md.Sources[i])
	}
	for i := range md.Keywords {
		md.Keywords[i] = sanitizeString(md.Keywords[i])
	}

	if md.APIVersion == "" {
		return ValidationError("chart.metadata.apiVersion is required")
	}
	if md.Name == "" {
		return ValidationError("chart.metadata.name is required")
	}
	if md.Version == "" {
		return ValidationError("chart.metadata.version is required")
	}
	if !isValidSemver(md.Version) {
		return ValidationErrorf("chart.metadata.version %q is invalid", md.Version)
	}

	...

	return nil
}
```

While the `Run()` method of the `helm package` command would actually respect the provided `--version` flag:
```go
func (p *Package) Run(path string, vals map[string]interface{}) (string, error) {
        ...

	if p.Version != "" {
		ch.Metadata.Version = p.Version
	}

	if err := validateVersion(ch.Metadata.Version); err != nil {
		return "", err
	}

       ...
}
```

it never gets to that point because the `metadata` of the Chart is being parsed AND validated at the time the files are being loaded. 

While the early validation certainly works for most of the other, if not all of the other commands it doesn't work for `package` where you can provide a version via the `--version` flag. 

To fix this there would only really be two options I could see:
1. Make the parsing "aware" of what command has been invoked (i.e. disable the version check for `package` via flag)
2. Turn it off by default and have the individual command validate it like `package` is actually trying to do

Cheers,

Kimba

**Comment by kimba74** [comment]
Looks like the "Fix" [#2bf5c28](https://github.com/helm/helm/commit/2bf5c280d56e0043bf1870f84d63e82d5c5d4230) is what "broke" it for for `helm package`

**Comment by bacongobbler** [comment]
@kimba74 yes, however the fix was put in place to fix a security issue. Please have a read through https://github.com/helm/helm/security/advisories/GHSA-c38g-469g-cmgx.

If you can determine a fix without re-introducing that security issue (I mentioned a potential solution [in an earlier comment](https://github.com/helm/helm/issues/9298#issuecomment-850568389)) that would be helpful. But with the current architecture in the code that was the only way to fix the security issue. So a new code path may have to be introduced to provide this feature.

**Comment by jzangari** [comment]
@bacongobbler I'm a little confused, because of #9 and #10 on https://semver.org/ relating to pre-release versions of something. 

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.
> 
> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3—-117B344092BD.

I know I am getting errors, but my pre-release versions follow this pattern, and you link directly to the semver site that states this information here: https://helm.sh/docs/chart_best_practices/conventions/#version-numbers

An example of one of my pre-release versions is: 1.1.25-dev.1-mcp-3583.0874667 , and yet when I try to use the latest versions of helm I get errors like this:: 

> index.go:339: skipping loading invalid entry for chart "webhook-service" "1.1.25-dev.1-mcp-3583.0874667" from https://my.artifactory.url : validation: chart.metadata.version "1.1.25-dev.1-mcp-3583.0874667" is invalid

**Comment by bacongobbler** [comment]
Pre-release version numbers cannot containmore than ONE hyphen. The [Backus-Naur Form Grammar](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) section defines this in pseudo-code.

The relevant sections:

```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>

<pre-release> ::= <dot-separated pre-release identifiers>

<dot-separated build identifiers> ::= <build identifier>
                                    | <build identifier> "." <dot-separated build identifiers>

<build identifier> ::= <alphanumeric identifier>
                     | <digits>
```

In other words, this is NOT valid:

1.1.25-dev.1-mcp-3583.0874667

But this is:

1.1.25-dev.1.mcp.3583.0874667

**Comment by jzangari** [comment]
Then number 9 is wrong, because one of the examples is clearly, but thanks for the response. 

> 1.0.0-x-y-z.–

**Comment by bacongobbler** [comment]
I'm sure the semver.org maintainers would appreciate the heads up if you'd like to raise it with them, as that's in direct conflict with the specification.

**Comment by bacongobbler** [comment]
Hmm... Looking at https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string it would appear 1.1.25-dev.1-mcp-3583.0874667 is considered valid semver. Looks like the specification is unclear on this section.

Please feel free to submit a bug report to https://github.com/Masterminds/semver. That is the library Helm uses to validate semantic versions.

**Comment by jzangari** [comment]
Thanks again @bacongobbler, I have actually created and issue for them here if you would like to comment as well: https://github.com/semver/semver/issues/743

**Comment by bacongobbler** [comment]
Oh, and it looks like numerical values with leading zeroes are invalid too. So you have to remove the leading zero from the last part of the version number.

1.1.25-dev.1.mcp.3583.874667

**Comment by jzangari** [comment]
I noticed that as well just now.

**Comment by SleepyBrett** [comment]
Ignore it long enough and it goes away?

**Comment by bacongobbler** [comment]
Happy to review suggestions in the form of a PR. [Your earlier suggestion](https://github.com/helm/helm/issues/9298#issuecomment-818013500) seems like a good use case.

Helm’s development is purely driven by the community. If you want something fixed, you’ll have to do the work yourself, hire a contractor, or find other like-minded individuals who are also interested in collaborating on a solution. :)

**Comment by jwdonahue** [comment]
The spec clearly states that prerelease characters are [0-9A-Za-z-], so multiple hyphens are allowed. The test data we developed for the regex's includes `1.2.3----RC-SNAPSHOT.12.9.1--.12` in the valid list, which clearly contains multiple hyphens. 

You are not reading the BNF correctly if you think that it does not allow multiple hyphens. Working our way up from the basic elements we have:

```
<non-digit> ::= <letter>
              | "-"
```

Then:

```
<identifier character> ::= <digit>
                         | <non-digit>
```

Followed by

```
<identifier characters> ::= <identifier character>
                          | <identifier character> <identifier characters>
```

Notice this is self referential, which allows for multiple <identifier character>, which we've already established includes hyphens. Climbing further:

```
<alphanumeric identifier> ::= <non-digit>
                            | <non-digit> <identifier characters>
                            | <identifier characters> <non-digit>
                            | <identifier characters> <non-digit> <identifier characters>
```

Followed by

```
<pre-release identifier> ::= <alphanumeric identifier>
                           | <numeric identifier>
```

So when we get to:

```
<dot-separated pre-release identifiers> ::= <pre-release identifier>
                                          | <pre-release identifier> "." <dot-separated pre-release identifiers>
```

Which is self referencing, so that we can have multiple dots. Be careful with string that contain UNICODE characters: 

`1.0.0-x-y-z.–`

Notice the width of the trailing hyphen? Somebody's editor converted sequential hyphens `--` in into the long bar character `–`, which is definitely NOT legal.
