### ISSUE TITLE
validation: chart.metadata.version is invalid (breaking change in v3.5.2)

### ISSUE THREAD

**Issue by arcln** [helm/helm#9342]
Changelog for version 3.5.2 (which is a PATCH update) states the following :

> WARNING: Helm is now stricter about sanitizing data in Chart.yaml, index.yaml, and plugin.yaml. In particular, we are stricter about SemVer strings.

This definitely is a breaking change. In our CI/CD, we create deployments using `helm`. For deploying our feature branches environments, we use branch names as the chart version string. Since this update, our CI/CD is failing with the error :

```
Error: validation: chart.metadata.version "master" is invalid
```

I am not sure what measure should be applied now, as the update is already publicly available, but I though it was worth mentioning it.
This commit actually breaks semantic versioning rules while it is supposed to enforce them :^)

Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Bare metal ubuntu server, cluster installed using kubeadm.

**Comment by bacongobbler** [comment]
Hi @arcln. We have documented in multiple locations the fact that branch names as chart version strings are an invalid use of the `version` field. Only valid Semver 2 versions are allowed.

As per our policy on backwards compatibility:

> Any chart that worked on a previous version of Helm 3 MUST work on a new version of Helm 3 (barring the cases where (a) Kubernetes itself changed, and (b) the chart worked because it exploited a bug)

This would be construed as the latter case of exploiting a bug.

It's important to note that Semver 2 does have some guidelines when it comes to pre-release branch versioning. I would suggest reading the specification at https://semver.org/#semantic-versioning-specification-semver, specifically the sections around pre-release versions, which is used often when referring to commit SHAs.

I'm closing this as an intentional change. The security release fixed a bug where the version field was not checked if it was valid Semver 2. We do not intend to change this behaviour to accommodate cases that exploited this behaviour.

**Comment by sincejune** [comment]
Hi @bacongobbler. This SemVer 2 sanitize check looks cool! But looks like the version `>0.0.0-0` which is used in `helm upgrade --devel` is also an invalid version for SemVer 2.

Does that mean I should stop using the `--devel` option since then?

**Comment by cforce** [comment]
related https://github.com/helm/helm/issues/9728
