### ISSUE TITLE
[Feature Request] helm package should get package.tgz as an input

### ISSUE THREAD

**Issue by dsaydon90** [helm/helm#9361]
I have a scenario which I need to update (promote) my chart version from 1.0.0-rc0 to 1.0.0 but to use the same `chart.tgz` file (same artifact) in order to avoid issues like getting different dependencies and etc..
so if I'm trying to run the command:
```
helm package --version 1.0.0 chart-1.0.0-rc0.tgz
```
I'm getting the error: 
```
Error: Chart.yaml file is missing
```

any way to use `helm package` command to get `chart.tgz` as an input so I'll not need to extract the `chart.tgz` and re-package it?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

**Comment by bacongobbler** [comment]
> any way to use helm package command to get chart.tgz as an input so I'll not need to extract the chart.tgz and re-package it?

No, not really. You can use `helm pull --untar` to automatically unpack a chart after fetching it, but there is no way to "re-package" a chart that has already been packaged. You will have to unpack the chart with `tar -zf` before calling `helm package`. Re-packaging an existing package as another version is not a very common use case.

Have you checked out the Helm Plugins guide yet? This seems like a good opportunity to write a plugin that will cater to your needs. It's unclear whether this workflow would be useful for others, which is why it'd be great as a plugin.

https://helm.sh/docs/topics/plugins/
