### ISSUE TITLE
oci: reconsider to remove the restriction of image tag must match the chart version.

### ISSUE THREAD

**Issue by dsaydon90** [helm/helm#9378]
please reconsider to remove the restriction of **image tag must match the chart version**:

> To successfully pull dependencies, the image name in the registry must match the chart name and the tag must match the chart version. The repository entry in Chart.yaml is specified as the repository name on the registry without the image name.

from: https://helm.sh/docs/topics/registries/

why?
flows on **cicd** with artifact promotion from `dev` to `integration` to `staging` to `production` are very useful and has been used as a possible and working **cicd** flow.
This flow is heavily in use with `docker images`.
so why to limit the helm `oci` chart image with this restriction too?

benefits:
* add tag like `dev` and `stg` to the same `oci` chart image (artifact promotion)
* can install chart like `latest` version without the need of mention the chart version (good for dev environments)
* probably there are more benefits

**Comment by mattfarina** [comment]
@dsaydon90 This is a good question.

There are a number of reasons. Here is one of them...

Helm does more than manage templates that are turned into Kubernetes manifests. It does package management which includes things like dependency management. In order to handle dependency management Helm uses semver for versions. This enables it to work out updates which is a common task. Other package managers do something similar.

In order to add support for `dev`, `staging`, etc then Helm would need to rework the way it handled versions which is not a small task.

The Docker use case of of using `dev`, `staging`, and so forth for floating tags is considered an anti-pattern by some as it causes problems. For example, if you deploy to production and there is an issue you need to roll back... how do you do that? You're following a floating tag and don't have the previous version. Using a tag like `production` also means you can't leverage caching well in a Kubernetes cluster. You have to always fetch from the registry. The constant pulling of images causes delays in launching, scaling, and causes hidden bandwidth costs.

> can install chart like latest version without the need of mention the chart version (good for dev environments)

If you use a helm command without specifying a version you can get the latest today. This is already solved for.

I understand your desire for the floating tags. If you want to try to convince us I would ask that you show your use case is beneficial and that it's something we could do well in helm.

**Comment by dsaydon90** [comment]
Hi @mattfarina , if using semver is a must also for OCI by design, I'm not sure that I'll be able to influence here.
But, in my opinion, I still think that it will be great to leave the power for the env user to decide how to manage his helm oci chart images (with sem ver or with env patterns ot whatever he wants).

My scenario is to let the developers to have easier life by picking the right helm oci chart version like helm oci chart image with the tag `dev` and if they will want to install the `stg` version they will just need to choose that tag.
probably there are more scenarios that the community can share.

This issue was just to keep the versioning by floating tags in mind, Let me know if currently nothing will be done and l will close this case..

**Comment by pmorch** [comment]
Here is a serious drawback of semver: It implies a sortable array of versions. But that is simply not the case when you have independent feature branches being developed in an enterprise.

Say I have branchA and branchB feature branches running in parallel, and there are changes to both of them. How do we coordinate between them who gets to use which versions? And which versions are `<` than which other versions during development?

Here, only non-sortable "tags" have meaning as versions. Things like "branchA-234", "git-commit-123abc" and so on.

**Comment by bacongobbler** [comment]
I believe the same comment @mattfarina posted earlier applies here as well @pmorch:

> In order to add support for `dev`, `staging`, etc then Helm would need to rework the way it handled versions which is not a small task.

While I sympathize with your use case here, Helm is a package manager. A package manager's primarily focus is on published releases. In-development branches or pre-release versions are a secondary focus. Or in some cases, not considered at all.

Semantic versioning helps us address many of the issues that come with release management like sorting and version lookups (e.g. `^1.0.3`). The tradeoff is that it does not help sort through pre-release versions such as a branch name, as you astutely point out.

If you can determine a way where we can apply the same feature set we get with semantic versioning for pre-release versions, we are open to suggestions in the form of a PR or a [HIP](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea). So far we have not found any similar solutions in other package managers. Or at least, they require significant time and investment to rework parts of Helm to address.

**Comment by pmorch** [comment]
Point taken, @bacongobbler.

If you've decided:

> In-development branches or pre-release versions are a secondary focus. Or in some cases, not considered at all.

then my point is moot. And I guess semver has proven its validity in the field already ;-)

**Comment by bacongobbler** [comment]
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Comment by zchenyu** [comment]
One workaround is to publish the chart to:
```
oci://myregistry.com/my-project/my-artefact/dev:0.0.0
oci://myregistry.com/my-project/my-artefact/prod:0.0.0
```

This also has the added benefit of letting you track the history of the floating 0.0.0 label is, assuming your OCI registry keeps around un-tagged versions and their creation times.
