### ISSUE TITLE
Helm lookup not working with empty namespace

### ISSUE THREAD

**Issue by thernstig** [helm/helm#9435]
I am adding an annotation like this, using the `lookup` template function, which does not work.

```helm
{{- if (lookup "apps/v1" "Deployment" "" "some-deployment-name") }}
test: "test"
{{- end }}
```

But this works:

```helm
{{- if (lookup "apps/v1" "Deployment" .Release.Namespace "some-deployment-name") }}
test: "test"
{{- end }}
```

I  use the default namespace in both scenarios. According to https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function the first example should work.

Output of `helm version`:
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-06-03T10:06:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Custom

**Comment by bacongobbler** [comment]
By omitting the third parameter, you are requesting that the `lookup` function performs a lookup at the global scope. Kubernetes' `apps/v1/Deployment` API cannot look up deployments at the global scope, which is why it cannot work in this situation.

The documentation you linked to only describes how to use the Namespace API at the global scope. It does not describe how to use the Deployment API because Kubernetes does not support an API like `kubectl get deployment foo --all-namespaces` at a high level doe to namespace conflicts/lookups at the global scope for a namespaced resource.

Hope that helps clarify the behaviour.

**Comment by thernstig** [comment]
Great description @bacongobbler! I feel the docs is not clear here, they just say that `namespace` can be omitted as the third parameter.

To me then, in context of `apps/v1/Deployment` if I omit it, would it not be ideal it actually looks up in the current namespace by default? And if not, I cannot see these even implicitly described in the documentation.

What I mean is that I understand the technical reasons you say why it works how it works _right now_, but I do not see the reason why the lookup function cannot be changed to work by looking up things like `Deployment` in the current namespace if omitted. In essence, could `lookup` be extended as a functionality to gracefully handle this case?
