### ISSUE TITLE
Is there a way to import content from a URL?

### ISSUE THREAD

**Issue by antoineozenne** [helm/helm#9454]
This is not an issue, but a question : is there a way to import content from a URL?

Use case :
With the [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack), we can automatically import a dashboard from a configmap labeled by default `grafana_dashboard: "1"` into Grafana. This is very useful because all dashboards about a release are in this one.
For example, I can deploy [rabbitmq](https://www.rabbitmq.com/kubernetes/operator/operator-overview.html) with a configmap containing the official dashboards (https://grafana.com/rabbitmq). For that, I have to copy the dashboards in json format in my chart, then import them into the configmap with `Files.Get`. Is it possible to directly import the file from the internet with an equivalent like `URL.Get`?

**Comment by mattfarina** [comment]
This is a good question and the answer is not in templates. To have something like that would open the door to security issues.

**Comment by bacongobbler** [comment]
@antoineozenne is there some action item you are looking for here? I'm curious what further answers you're looking for here given @mattfarina's answer.

To clarify, the question asked here was "is there a way to import content from a URL?", and the answer is "due to security design issues, no". Is there something else you'd like to know?
