### ISSUE TITLE
Checksums does not match

### ISSUE THREAD

**Issue by denissabramovs** [helm/helm#9460]
[Container] 2021/03/10 17:08:03 Running command curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
--
672 |  
673 | [Container] 2021/03/10 17:08:03 Running command chmod 700 get_helm.sh
674 |  
675 | [Container] 2021/03/10 17:08:03 Running command ./get_helm.sh
676 | Downloading https://get.helm.sh/helm-v3.5.3-linux-amd64.tar.gz
677 | Verifying checksum... SHA sum of /tmp/helm-installer-50BstH/helm-v3.5.3-linux-amd64.tar.gz does not match. Aborting.
678 | Failed to install helm
679 | For support, go to https://github.com/helm/helm.

**Comment by denissabramovs** [comment]
it seems it is resolved

**Comment by denissabramovs** [comment]
You are right, it seems it is really not verified...

**Comment by denissabramovs** [comment]
This is kind of critical security point...Will overview this and add a task to hardcode a specific version download... Without that script...

**Comment by bacongobbler** [comment]
There was a slight hiccup in which the github release was released, but the release assets were still being uploaded to the blob store. Helm 3.5.3 has now been released so the script should work now.

https://github.com/helm/helm/releases/tag/v3.5.3

Thanks for raising the issue about the tag being unsigned. Generally speaking, all of our tags have been signed in the past. Signing off on the tag is part of our release checklist, so perhaps a step was skipped in the release checklist or we need to update the documentation.

For reference: https://helm.sh/docs/community/release_checklist/#6-finalize-the-release

**Comment by mattfarina** [comment]
> The 3.5.3 release isn't tagged as latest

It is tagged as the latest now. I'm not sure how GitHub works to update that. This is part of GitHub's automatic handling and not something we can control. The most recent release is marked by GitHub as the latest and it does not matter what version is used for that release.

> or committed as verified

I see this happening and I'm not entirely sure what GitHub's intent is here.

The tag is signed and I manually verified it. I cut the release and the key used to tag is uploaded to GitHub to verify.

The last commit on the release is by a contributor who has not signed their commit. This may be why it's not verified.

In any case, the PGP signature for the download is different from the sig on commits itself. The get script doesn't verify a commit id signature. Instead it verifies a signature on a package download.

> Verifying checksum... SHA sum of /tmp/helm-installer-50BstH/helm-v3.5.3-linux-amd64.tar.gz does not match. Aborting.

We can double check the scripts because there appears to be some race condition on things becoming available. I'm not sure if this is in our script or on GitHub making assets available.

**Comment by doctorwu** [comment]
Seems to be back...

#9 0.620 Downloading https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz
#9 1.467 Verifying checksum... SHA sum of /tmp/helm-installer-gxsftx/helm-v3.7.0-linux-amd64.tar.gz does not match. Aborting.
#9 1.481 Failed to install helm
#9 1.481 	For support, go to https://github.com/helm/helm
