### ISSUE TITLE
Feature request: lint rules exceptions file

### ISSUE THREAD

**Issue by lindhe** [helm/helm#9463]
## Background

Many linting systems (e.g. `Flake8` for Python and `hadolint` for Dockerfile) have ways to inhibit certain linting rules on a case-by-case basis. This typically takes at least one of three forms:
* An exception file, similar in style to `.gitignore` or `.helmignore`, for linting rules.
* A flag: `--ignore E123`
* Inline: `# ignore E123`

## Use-case

The concrete use-case I want to have it for is to be able to run `helm lint` in a very early step in our CI, before we do `helm dep up`, as a very quick initial sanity check. But today, that complains (rightly so) of missing dependencies in the `chart/` subdirectory. It would be nice for us to be able to disable that particular check in that particular place.

## Proposal

I'm not aware of any such functionality in Helm, so I propose that we introduce it. Since there's not very many rules, and I assume there may be some implicit rules that are not really Helm specific (YAML syntax perhaps?), I can see why it's not in place already. But I think it would be worthwhile to have, as long as we deem the linting function valuable in itself.

If we introduce it, I think it would be good to first make an authoritative dictionary of rules, similar to the other systems, so they can be easily referred to. Then we can introduce the rule exception mechanism.

Output of `helm version`:
```console
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

Output of `kubectl version`: n/a

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

**Comment by bacongobbler** [comment]
A similar request was asked in https://github.com/helm/helm/issues/2694 that was eventually closed due to inactivity. It was opened on Jul 2017, and never saw any community development since then.

If you're interested in writing this feature, I would highly recommend looking at the [Contributing Guide](https://github.com/helm/helm/blob/master/CONTRIBUTING.md), specifically the section on [Proposing an Idea](https://github.com/helm/helm/blob/master/CONTRIBUTING.md#proposing-an-idea). That would be the first step to take to move this proposal forward.

Hope this helps.
