### ISSUE TITLE
Why unneeded data packaged within chart? Works as designed?

### ISSUE THREAD

**Issue by rpasche** [helm/helm#9530]
I am not sure, if this is working as designed. I thought, once all data has been rendered by `helm / helm3`, that only that rendered data is then packaged and installed within k8s.

But what we found out is that *everything* (that it not excluded via `.helmignore`) within the chart directory and also everything that has been passed via `--set` or `--set-file` or `--set-string` is also - in the end - stored and packaged within the final chart (even if this information is not needed anymore, after the data has been rendered).

Not only that the size of the resulting chart increases....this could lead to a security issue, in case you pass sensitive data via `--set` or `--set-file` that is just needed to render the templates (to create k8s `secrets`) but - in the end - should NOT make it into the final package.

Everybody with access to the chart `secret` (created by `helm3`) could then view this data.

See this comment https://github.com/helm/helm/issues/3050#issuecomment-341576612

Output of `helm version`:

`version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

- GKE

**Comment by mattfarina** [comment]
I'm not entirely sure of your use case and situation. So, I'm going to provide some context and ask some questions to try and narrow it down.

Helm is a package manager. As part of that there is a step to take directories and turn them into archives that can be shared. There is also the ability to install archives or directories.

When you talk about packaged and final chart are you talking about directories or something generated from `helm package`?

Or, are you talking about what's stored just in the secret in the cluster?

If you are just talking about the secret, and I will assume you are, there are some things going on here. Note, I would be curious to learn about your setup to better understand the situation.

First, Helm has some commands that need to know the previous values in order to work. The set family of flags are designed to set values right from the console app. An example is `helm upgrade` with the `--reuse-values` flag. It needs to old values which are, in part, set by the set family of flags in order to work.

So, Helm stores this data in a secret because a secret is the place to store sensitive information in Kubernetes. Helm does this by default but there are other storage back-ends (e.g., PostgreSQL). A secret can be tied to encryption setups that store the sensitive information securely.

This still does not solve the problem of access control, as you note. This is where things get harder. If an application has sensitive information the Kubernetes way to store that is a secret. It can then be exposed through a filesystem mount or an environment variable to an application running in a container. Access controls work around RBAC and namespaces to limit who and what can see the information (e.g., secrets). This is why the helm secret is stored in the same namespace as the application and its secrets. If someone can access the applications secrets they can get the same information as the information in Helm's secrets.

Helm needs a way to store information in a cluster without installing anything to the cluster. This is a hard requirement which has pushed us to secrets. But, we know people want to store this data in different ways which is why the storage mechanism is pluggable and we are open to more and new plugins.

I imagine you have some more context you can share based on your situation. This is a bit of the context on why things work they way they do now.

**Comment by rpasche** [comment]
Hi @mattfarina,

thank you for your feedback. I'll try to explain, how we might have misused helm so far.

We are deploying many components with helm in many regions. So far, we have stored all our credentials within a separated, encrypted git repo. Just before doing a `helm upgrade --install ...` we placed that file somewhere within the chart directory. Within a `template` file, we are parsing this file and - in the end - are generating k8s `secrets`.

We gained access to the contents of that file via the `Files.Get` function. And for this to work, that file (with all our credentials) could not be added to the `.helmignore` file, because then, the `Files.Get` does not work anymore.

Until a few weeks, we truly didn't know, that *everything* that is lying around within the chart directory is also packaged and stored within k8s. We thought, that only the finally rendered data would be packaged and put into k8s.

Now that you also pointed me to the `--reuse-values` option, I now know, why the `values` are also somewhere needed.

However, since we recognized this, we are heavily redesigning our setup. But maybe, you could also tell, if there is a way to cleanup the chart directory *after* the chart has been rendered but *before* it is packaged and *then* loaded into k8s. That way, we could at least make sure, that *unneccessary* files could be removed (and not packaged) into the helm chart release.

Would that be possible?

Thanks for any hints.

**Comment by rpasche** [comment]
So my - personal, and maybe pretty mad - idea how to maybe fix this, would be to implement another `ignore` file...maybe something like `.helmdonotpackage`. Files matching this pattern should then be removed from the `Chart.Files` section, *after* all resources have been rendered within the `install` and `upgrade` phase.
So files not listed in `.helmignore` BUT listed in that new `.helmdonotpackage` files, could still be used within template files (loaded with `Files.Get`) but once the data is rendered, remove it from the Chart (and also from the release) just before it gets stored.

If I read the code correctly (I'm a golang beginner), the 2 points are within the `install.go` (https://github.com/helm/helm/blob/213a7df2dcd07e8d49fc6acf8a53a540c661ed53/pkg/action/install.go#L251) to remove the files from the `rel.Chart.Files` map and within the `upgrade.go` (https://github.com/helm/helm/blob/213a7df2dcd07e8d49fc6acf8a53a540c661ed53/pkg/action/upgrade.go#L219) to modify `chart.Files` before that is put into `upgradeRelease`.

As mentioned....just an idea (and maybe a bad one)
