### ISSUE TITLE
The command `helm package` does not quote appVersion, where `helm create` does (since 3.5.0)

### ISSUE THREAD

**Issue by luigidifraia** [helm/helm#9541]
Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

The value of `appVersion` in Chart.yaml is often set to a commit hash when using CI pipelines, using `helm package`. Would it make sense to double quote the value when running `helm package`, as it is the case with `helm create` since version 3.5.0?

If the commit hash is not double quoted when used as value for `appVersion`, there are circumstances during which it is interpreted as a scientific notation number, which causes issues with `helm repo add` and `helm repo update` commands, e.g.:
```
Error: looks like "xxx/helm/charts/" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go struct field ChartVersion.entries.appVersion of type string
```

Again, it seems sensible to align the behaviour of `helm package` to the one of `helm create` and double quote `appVersion` in order to prevent this issue from happening.

The proposed change also seems in line with the documentation for `helm package` that states the `--app-version` option is followed by a string:

```
--app-version string       set the appVersion on the chart to this version
```

**Comment by mattfarina** [comment]
This is a really observant catch on your part.

If you follow the source for `helm create` to where `appVersion` is set you'll end up [here](https://github.com/helm/helm/blob/d55c53df4e394fb62b0514a09c57bce235dd7877/pkg/chartutil/create.go#L103). This is a template for the `Chart.yaml` file as a string. The YAML isn't generated by a library but rather generated using Go text templates.

If you look into the `helm package` command to see where it sets the `appVersion` you will find it's happening a little differently. You can find the setting code [here](https://github.com/helm/helm/blob/d55c53df4e394fb62b0514a09c57bce235dd7877/pkg/action/package.go#L73-L75). Here you see an object in Go having a value set. Elsewhere you'll find that [this object is written to YAML](https://github.com/helm/helm/blob/d55c53df4e394fb62b0514a09c57bce235dd7877/pkg/chartutil/save.go#L176).

So, when you set the `appVersion` using `helm package` isn't the serializing library choosing the appropriate way to represent it in YAML form. Many times it won't quote it because it doesn't need to be quoted.

It's safe to have the string not be quoted where it's not quoting it.

The reason the value is quoted in the template used by `helm create` is because many people have manually edited these files rather than using a flag to change the value. Sometimes they use values like `1.0` for the version which evaluates to a float rather than a string. We wanted to, by default, lower the possibility for issues.

But, the YAML writing library doesn't let us configure if the string is surrounded by quotes or not when it generates the YAML string. That's why the flag doesn't add the quotes around it.

So, that's the context.

**Comment by luigidifraia** [comment]
Thank you for taking the time, @mattfarina. Very insightful feedback.

> It's safe to have the string not be quoted where it's not quoting it.

That's certainly safe within the context of YAML parsing. However, not quoting an **appVersion** such as `1964e005` or `0703e003` or even `0e808683` in the index file of a Helm chart repo (index.yaml) causes `helm repo add` and `helm repo update` to fail with the previously mentioned error.
All of the above are short commit hashes I have stumbled on while running CI pipelines.

**Comment by luigidifraia** [comment]
The command:
```
helm package deploy/helm --dependency-update --app-version 08359976 --version 0.0.0-08359976
```
Errors out with:
```
Error: Version segment starts with 0
```

**Comment by luigidifraia** [comment]
@mattfarina Can you please give the last comment a thought?
