### ISSUE TITLE
Flag `--dependency-update` in install command does not act as `helm dependency update`

### ISSUE THREAD

**Issue by mladedav** [helm/helm#9545]
The flag `--dependency-update` for `install` does not work as advertised. It was originally introduced based on issue #2879 (4 years ago) to run `helm dependency update` before installing. This is also documented in the helptext `run helm dependency update before installing the chart`.

However this happens only in cases when a dependency is missing, not when a dependency is out-of-sync with Chart.yaml. (see in [code](https://github.com/helm/helm/blob/213a7df2dcd07e8d49fc6acf8a53a540c661ed53/cmd/helm/install.go#L216) and the function it calls).

To make this worse, *all* packages are updated based on Chart.yaml if and only if at least one package is missing.

This was (or is) already worked on in #9335, but as this is a breaking change there were questions about introducing this to v3 as it is not backwards compatible. However I would like to make the case that this indeed is a bug as the behavior is not very clear and is documented wrong in the help text. If this should not be changed in v3, at least the help text (and documentation) should be clear that it happens only when a dependency is missing without version checks.

Repro steps (some outputs are omitted for brevity):
```
helm create foo
$ cd foo
$ vim Chart.yaml
$ cat Chart.yaml
apiVersion: v2
name: foo
version: 0.1.0

dependencies:
  - name: mongodb
    version: "9.0.0"
    repository: "https://charts.bitnami.com/bitnami"

$ helm install --dependency-update foo # installed with 9.0.0
$ helm dependency list
NAME    VERSION REPOSITORY                              STATUS
mongodb 9.0.0   https://charts.bitnami.com/bitnami      ok

$ vim Chart.yaml # change dependency version to 10.0.0
$ helm dependency list
NAME    VERSION REPOSITORY                              STATUS
mongodb 10.0.0  https://charts.bitnami.com/bitnami      wrong version

$ helm uninstall foo
$ helm install --dependency-update foo # installed with 9.0.0
$ helm dependency list
NAME    VERSION REPOSITORY                              STATUS
mongodb 10.0.0  https://charts.bitnami.com/bitnami      wrong version

$ helm dependency update
$ helm dependency list
NAME    VERSION REPOSITORY                              STATUS
mongodb 10.0.0  https://charts.bitnami.com/bitnami      ok

$ vim Chart.yaml # set mongodb dependency to 9.0.0 and introduce another one
$ helm dependency list
NAME    VERSION REPOSITORY                              STATUS
mongodb 9.0.0   https://charts.bitnami.com/bitnami      wrong version
redis   12.9.0  https://charts.bitnami.com/bitnami      missing

$ helm uninstall foo
$ helm install --dependency-update foo . # installs mongodb 9.0.0 and redis 12.9.0
$ helm dependency list
NAME    VERSION REPOSITORY                              STATUS
mongodb 9.0.0   https://charts.bitnami.com/bitnami      ok
redis   12.9.0  https://charts.bitnami.com/bitnami      ok
```

Output of `helm version`:
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:46:15Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Civo/k3s

**Comment by mattfarina** [comment]
@mladedav Thanks for providing such thorough detail. This is very helpful in helping to figure out what's going on here.

**Comment by mattfarina** [comment]
A few things to note for those looking into this.

- #2880 is where the dependency flag was introduced. It was release in v2.8.0.
- The docs do not match the feature. One or the other needs to be updated.
- Changing to behavior of the flag would be a breaking change.

I'm adding this to the agenda for the next weekly meeting so we can talk further.

**Comment by mattfarina** [comment]
Marking as a bug for the time being. It's either a functionality or a docs bug.

**Comment by bacongobbler** [comment]
One of my main concerns with #9335 was that while it does address some of the concerns raised here, it breaks compatibility with the way the original feature was written. And it is difficult to understand whether the original `--dep-up` flag was intentionally written that way (as in, it addressed @rocky-nupt's use cases), or these cases were not considered when it was originally written.

The argument in my mind comes down to interpretation: if there is belief that the feature was intentionally written this way, then changing its behavior now would break compatibility for some users, in which case all we can do is update the docs. Otherwise it would be a bug and we can fix the behavior to better match `helm dep up`.

Unless we have a concrete idea how `--dep-up` is being used, I would be concerned changing its behavior in a 3.x release. Even if changing the behavior better matches `helm dep up`.

**Comment by mattfarina** [comment]
We discussed this in the Helm developer call. The general consensus was...

- This is a functionality bug
- We can't change the behavior of this flag until Helm v4

What we can do now...

- Create a flag and process for "fetch my missing sub-charts"
- Create a flag and process for "update my sub-charts"
- Add a deprecation notice to the existing flag

This would preserve the functionality for people who depend on it while making the two behaviors it appears we want to be explicit.

Folks have had the current situation since Helm v2.9.0 and we don't want to break people in their current usage.

**Comment by mladedav** [comment]
@mattfarina  I agree with everything, I just want to add one clarification here. The current functionality is "update all my sub-charts, iff at least one is missing", not simply "fetch missing".

Therefore the two flags would not preserve the current functionality in v4. If you meant we want to preserve it in v3 only, then everything is perfect.

Also the documentation and helptext of the current feature should probably be changed now as that doesn't have to wait for development of the new flags.
