### ISSUE TITLE
Helm silently aborts nested templates if a binary file is processed

### ISSUE THREAD

**Issue by davidmichaelkarr** [helm/helm#9550]
We're currently using Helm v2.11, but this does the same thing in v3.5.3.

We have a template with the following in it:

```
data:
{{ tpl (.Files.Glob "configs/*").AsConfig . | indent 2 }}
```

This is in a template for a k8s ConfigMap.  It produces an element in the data object for each text file in the "configs" directory.  This works perfectly fine when all of the files in the directory are text files.  Anything else doesn't make sense for this purpose.  However, what we find is that if someone does manage to put a non-text file into this directory, the result is very unhelpful.  I would almost prefer it would attempt to dump the contents of the binary file into the result.  It will be extremely obvious that is wrong and clearly point to the presence of the binary file as the cause of the problem.

However, what actually happens in this case is that the entire result of that entire double-brace expression is just an empty string.  If a single binary file is present, it ignores all the other text files and does nothing.  No error message.  Nothing.

From experience, we now recognize this pattern, but I would appreciate a better indicator of this mistake than simply silently aborting the entire expression.

**Comment by mattfarina** [comment]
I understand your frustration.

I went to look at the description of the `AsConfig` function. What I found reads:

> // AsConfig turns a Files group and flattens it to a YAML map suitable for
// including in the 'data' section of a Kubernetes ConfigMap definition.
// Duplicate keys will be overwritten, so be aware that your file names
// (regardless of path) should be unique.
//
// This is designed to be called from a template, and will return empty string
// (via toYAML function) if it cannot be serialized to YAML, or if the Files
// object is nil.
//
// The output will not be indented, so you will want to pipe this to the
// 'indent' template function.
//
//   data:
// {{ .Files.Glob("config/**").AsConfig() | indent 4 }}

The empty string is on purpose. This means we cannot change the behavior until Helm v4 and due to backwards compatibility we are not likely to change it then.

That being said, there are two possible paths forward.

1. It could be possible to have a template function that could detect the glob pattern returns files and that the response for the glob pattern is empty. Then it could cause a template error. This could be useful no matter what version of Helm someone uses.
2. A new function (e.g., `MustAsConfig`) could be created to handle an error response differently.

**Comment by davidmichaelkarr** [comment]
Point 1 sounds like something that users could produce, as opposed to necessarily being a part of the release. I think you'd likely want something like this in a "toolchest" in the release, but in the meantime, could you give me some ideas about what that would look like? I only just read the docs yesterday.

**Comment by mattfarina** [comment]
Consider this psuedo code as I've not tested it. It's just an idea...

```
{{- $files :=  .Files.Glob("config/**") }}
{{- $cfg := $files.AsConfig() }}
{{- if and (gt (len $files) 0) (eq $cfg "") }}
  {{- fail("Error message here") }}
{{- end -}}
{{ indent 4 $cfg }}
```

- No `tpl` is needed to make any of this work.
- The first line gets the glob pattern as a slice (array) of files
- The second line gets the config section for those files as a string
- The 3rd line looks funny but the statement comes before the parts of it (e.g., `A and B` is done as `and A B`). This is saying that if the length of the files list is greater than 0 and the config string is "" do the block before the end.
- The `fail` statement causes the template processing to end and an error to bubble up to Helm.
- The last like prints the config as it's all indented 4 spaces.

This is just some quick untested code. It could be turned into a template function for reuse.

**Comment by davidmichaelkarr** [comment]
This code was pretty close.  My helm instance (v2.11) complained about the parens on "Glob" and "AsConfig".  Removing those two paren pairs made it work.  The error message is a little annoying, as it appears to emit it twice, but at least the message is seen.
