### ISSUE TITLE
How to debug syntax errors in files that don't appear to exist?

### ISSUE THREAD

**Issue by davidmichaelkarr** [helm/helm#9552]
Currently using Helm v2.11, but I see a similar symptom in v3.5.3.

I find it very difficult to diagnose syntax errors in "helm template", because it seems to reference files that I can't see, even when I have the entire directory tree available.

For instance, here's a very paraphrased output I'm looking at right now:
```
helm template /.../playbook/taxms_helm -f /.../playbook/taxms_helm/values.yaml --values /.../playbook/roles/taxms_configrole/templates/helm/values.yaml --values /.../playbook/inventory/dev/group_vars/all_global --values /.../playbook/inventory/dev/group_vars/Dev2FF_global --values /.../playbook/inventory/dev/group_vars/all --values /.../playbook/inventory/dev/group_vars/Dev2FF_local --set 'msname=taxms,msname_wr=taxms-blue,kube_namespace=...,target_role=blue,appname=TaxMs,version=0.0.1,buildnumber=5,buildtimestamp=,deployment_date=2021-03-31T00-20-32.878,branch_name=...,gitCommit=...,gitProject=...,imagename=...,replica_count=1,bg_status=deployment,min_replicas=,max_replicas=,target_cpu=70,target_env=dev,resource_type=deployment' '--output-dir=/.../playbook/taxms_helm'
Error: render error in "idpchart/templates/k8s/configmap.yaml": template: idpchart/templates/k8s/configmap.yaml:25:3: executing "idpchart/templates/k8s/configmap.yaml" at <tpl (.Files.Glob "co...>: error calling tpl: Error during tpl function execution for "AAFUserRoles.properties: \"#/users/v1=...api.access|guest-user|* POST\\n#/users/v1/*=....api.access|registered-user|*\n  GET\\t\\t\\n\"\napplication.properties: \"#----------------------
```

Ok, so this is saying there's an error in "idpchart/templates/k8s/configmap.yaml" on line 25, character 3.  The name "idpchart" is the "name" property in the "Chart.yaml".  We do have a "configmapl.yaml" at "playbook/taxms_helm/templates/k8s/", and line 25 is this:

`{{ tpl (.Files.Glob "configs/*").AsConfig . | indent 2 }}`

I also tried running this with Helm v3.5.3, and the error message is slightly different.  It says this:
`parse error at (idpchart/templates/k8s/configmap.yaml:2): unexpected "(" in operand`

If it matters, this is line 2 of our existing "configmap.yaml":
`{{- range $path, $bytes := .Files.Glob "configs/*/***" }}`

However, if I edit that file and add a blank line at  the top of the file, which obviously comes before this line, and then rerun the command, it doesn't change at all.  It still says ":2".

Very confusing.

**Comment by mattfarina** [comment]
The `tpl` function is used to evaluate templates inside of other templates. You don't need to use it in the examples you've given me. Because of the way it's used to evaluate templates in templates you may get some harder to use line numbers. You can find the docs on that function at https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function. It should be a rarely needed function and it is a slow performing function.

The template system Helm uses is built on [the one included in the Go standard library](https://golang.org/pkg/text/template/). This handles the parsing, generates the errors, etc. We have little direct control over the error messages you are seeing.
