### ISSUE TITLE
is it possible to access the old release values ​​from the template

### ISSUE THREAD

**Issue by elkh510** [helm/helm#9592]
hi
how can i get the value from the previous release from the template files (or from _helpers.tpl file).
i mean how i can get output of this command "helm get values RELEASE_NAME" from chart template.

**Comment by bacongobbler** [comment]
There is no command currently available to fetch values from an older release. That being said, the metadata is still available in the release ledger.

This would be a good candidate for a plugin.

**Comment by HamzaZo** [comment]
Hello @elkh510 
I've created a simple helm plugin for that purpose if you want to give it a try [helm-val](https://github.com/HamzaZo/helm-val)

**Comment by jaredjennings** [comment]
What's needed, judging from @elkh510's original comment and issue title, is not a `helm` subcommand, but a function usable when writing templates ("from the template files"). Suppose there's a Helm chart for a piece of software, ProfaneGreeter. ProfaneGreeter version 2 stores its data in a MySQL database. ProfaneGreeter version 3 stores its data instead in a PostgreSQL database. A migration tool is supplied, which needs to connect to _both the old and new databases_. When upgrading ProfaneGreeter using Helm, a Kubernetes Job should be created to run the tool. But to define that Job properly, you need both the old (MySQL) and new (PostgreSQL) configuration values, accessible _from within the template_.

**Comment by jaredjennings** [comment]
https://github.com/helm/helm/issues/1227 and https://github.com/helm/helm/issues/3655 are related.

`--reuse-values` is somehow related. As far as I was reading when searching the `#helm-users` channel on the Kubernetes Slack, it defaults to on sometimes, and off for others.

The reason I began researching this issue is [TheHive](http://thehive-project.org/), which moved from storing data solely in Elasticsearch in major version 3, to storing data in Cassandra and indexing it in Elasticsearch in major version 4. The migration tool needs to know details about all three databases, and in fact TheHive 4 also supports storing data in a local Berkeley database and indexing it in local files using Lucene, and there's another database cloner tool that can move the data between these. You would use the local files for a simpler, quicker small deployment, but then when scaling from one replica of TheHive to multiple replicas, you would need to use that tool and move the data.

In both the case of database migration to a new version, and database cloning because of a configuration change, connection details for the old way of storing the data are not a configuration item for the new version/configuration of the application. So it may be possible to keep the old values, `--reuse-values` (if I understand it right), and make a new place in values.yaml for the new values. But it lacks simplicity and requires too much pre-planning.

Also, it's pretty easy for the set of migration steps that need to happen to depend on both the installed app version and the one we are upgrading to. For an app that's had a sane release history, you can tell these from the `image.repository` and `image.tag` values. But these are pretty well entrenched as a convention. Without being able to look into previous versions of the values, what would you do to make both old and new ones visible? Add a `newImage.repository` and `newImage.tag`? And in a few years `newNewImage`? Perhaps you could keep an `imageHistory` list, onto which new entries are tacked. But writing such a history of your own in your values.yaml is an [ad-hoc, informally-specified implementation of half of](https://en.wikipedia.org/wiki/Greenspun%27s_tenth_rule) the history functionality that already exists, but is merely inaccessible from the templating environment.
