### ISSUE TITLE
BUG: helm validates the pre-run values of chart.metadata.version/appVersion when using `helm package` even if the flags to set those values are present and compliant.

### ISSUE THREAD

**Issue by SleepyBrett** [helm/helm#9596]
Output of `helm version`: v3.5.x+

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  N/A

Feature Request:

Helm package should not validate the chart.metadata.version or chart.metadata.appVersion if their "setter" cli flags are passed (as long as the values passed are valid semver). The workaround is to put 0.0.0 into each in the Chart.yaml but this seems like a needless constraint.

See: https://github.com/helm/helm/issues/9298

**Comment by bacongobbler** [comment]
https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea

**Comment by SleepyBrett** [comment]
Ya'know what. This isn't a feature request. This is a bug.

**Comment by loomsen** [comment]
Definitely bug. Basically means for us: either rewrite ALL charts and deployments or not upgrade helm beyond 3.4... Why would you force something on people and break literally everything that was done? I'd have to change every single pipeline definition for all of our services...

**Comment by loomsen** [comment]
Why would we even care which versioning scheme someone uses? Why do we have to force SemVer on everyone? What's wrong with having a commit hash as a version? 

For me it means I cannot upgrade helm from 3.3.1 anymore. I didn't to the introspection to find out which helm version exactly breaks literally every CI/CD pipeline I set up, but yeah. 
Why?
 Just let **me** pick my own versioning scheme myself, which fits for **me**.

**Comment by derekpedersen** [comment]
> Why would we even care which versioning scheme someone uses? Why do we have to force SemVer on everyone? What's wrong with having a commit hash as a version?
> 
> For me it means I cannot upgrade helm from 3.3.1 anymore. I didn't to the introspection to find out which helm version exactly breaks literally every CI/CD pipeline I set up, but yeah.
> Why?
> Just let **me** pick my own versioning scheme myself, which fits for **me**.

Running into the same problem.

`Error: validation: chart.metadata.version "2021.05.09.1758" is invalid`

**Comment by SleepyBrett** [comment]
I agree that I actually don't think helm should be validating these values at all. I don't see an actual purpose. But if it has a purpose besides just scolding people who don't use semver, I see semver as a decent selection.

**Comment by bacongobbler** [comment]
By enforcing semantic versioning, Helm can support cases like [version constraints in chart dependencies](https://helm.sh/docs/chart_best_practices/dependencies/#versions), `helm install bitnami/wordpress` fetching the latest version of wordpress, or `helm install bitnami/wordpress --version ^1` constraining Helm to install only 1.0.0<2.0.0 chart versions. So there is a valid reason why we use it. We can't provide support for those cases otherwise.

**Comment by loomsen** [comment]
Ok, fair enough, but why do these cases have precedence over other cases? Who get's to decide what's more important? 
This means a lot of extra work for a lot of people. So that's fine for you? Just to support one case where this might be useful? 

Horrible decision, imo. If you take away the freedom, people might opt for something else...

**Comment by derekpedersen** [comment]
> By enforcing semantic versioning, Helm can support cases like [version constraints in chart dependencies](https://helm.sh/docs/chart_best_practices/dependencies/#versions), `helm install bitnami/wordpress` fetching the latest version of wordpress, or `helm install bitnami/wordpress --version ^1` constraining Helm to install only 1.0.0<2.0.0 chart versions. So there is a valid reason why we use semver. We can't provide support for those cases otherwise.

Seems strange `2021.05.09.1758` (`YYYY.MM.DD.HHmm`) is a legal pattern as soon as a I drop `HHmm`, it still follows an incremental pattern that `SemVar` uses just with an additional 4th field (sometimes referred to as the build number field).

**Comment by bacongobbler** [comment]
From https://semver.org/#spec-item-2:

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

From https://semver.org/#spec-item-10:

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3—-117B344092BD.

If you want to reference build numbers, use the format `YYYY.MM.DD+HHmm`.

**Comment by loomsen** [comment]
Ok, so this is decided an there's no going back? I guess that's it for me with helm then.

**Comment by bacongobbler** [comment]
Helm has used semantic versioning since 2.0.0. I’m not sure what you mean by there being a breaking change in a minor release.

Can you please demonstrate the issue you’re experiencing?

**Comment by loomsen** [comment]
Sure, no problem. I'm having commit hashes as versions for my custom helm charts. Usually, a helm chart lives in the same repo as the microservice it is supposed to deploy. So it makes sense to use the commit hash as a version for dev/preprod deployments. A prod deployment is triggered by a git tag, so prod deploys will have a SemVer version. So up until 3.3.1, this was no problem.
Now, with `helm upgrade -i` I get:

```
Error: validation: chart.metadata.version "317e9b5589a190117285ef9ca181e3077284d960" is invalid
```

And this is big problem for me, as I have used this pattern in tens or even hundreds of microservices, which I set up the CI/CD pipelines for.

**Comment by bacongobbler** [comment]
In any case @loomsen, I don't think your issue is the same as the one @SleepyBrett reported. Please open a new ticket with your findings and we can investigate further.

@SleepyBrett I had a closer look at https://github.com/helm/helm/issues/9298 and I think it's the same issue as the one you described above. Can we close this issue in favour of that one, or is this distinctly different than that report?

**Comment by bacongobbler** [comment]
closing for now; let me know if we need to re-open this.

**Comment by kimba74** [comment]
@bacongobbler it looks like this issue got introduced with version v3.5.2

The `Validate()` function in `pkg/chart/metadata.go` looks like the following in **v3.5.1**:
```go
func (md *Metadata) Validate() error {
	if md == nil {
		return ValidationError("chart.metadata is required")
	}
	if md.APIVersion == "" {
		return ValidationError("chart.metadata.apiVersion is required")
	}
	if md.Name == "" {
		return ValidationError("chart.metadata.name is required")
	}
	if md.Version == "" {
		return ValidationError("chart.metadata.version is required")
	}
	if !isValidChartType(md.Type) {
		return ValidationError("chart.metadata.type must be application or library")
	}

	// Aliases need to be validated here to make sure that the alias name does
	// not contain any illegal characters.
	for _, dependency := range md.Dependencies {
		if err := validateDependency(dependency); err != nil {
			return err
		}
	}

	// TODO validate valid semver here?
	return nil
}
```

While the same function in **v3.5.2** has the SemVer check built in:
```go
func (md *Metadata) Validate() error {
	if md == nil {
		return ValidationError("chart.metadata is required")
	}

	md.Name = sanitizeString(md.Name)
	md.Description = sanitizeString(md.Description)
	md.Home = sanitizeString(md.Home)
	md.Icon = sanitizeString(md.Icon)
	md.Condition = sanitizeString(md.Condition)
	md.Tags = sanitizeString(md.Tags)
	md.AppVersion = sanitizeString(md.AppVersion)
	md.KubeVersion = sanitizeString(md.KubeVersion)
	for i := range md.Sources {
		md.Sources[i] = sanitizeString(md.Sources[i])
	}
	for i := range md.Keywords {
		md.Keywords[i] = sanitizeString(md.Keywords[i])
	}

	if md.APIVersion == "" {
		return ValidationError("chart.metadata.apiVersion is required")
	}
	if md.Name == "" {
		return ValidationError("chart.metadata.name is required")
	}
	if md.Version == "" {
		return ValidationError("chart.metadata.version is required")
	}
	if !isValidSemver(md.Version) {
		return ValidationErrorf("chart.metadata.version %q is invalid", md.Version)
	}

	...

	return nil
}
```

While the `Run()` method of the `helm package` command would actually respect the provided `--version` flag:
```go
func (p *Package) Run(path string, vals map[string]interface{}) (string, error) {
        ...

	if p.Version != "" {
		ch.Metadata.Version = p.Version
	}

	if err := validateVersion(ch.Metadata.Version); err != nil {
		return "", err
	}

       ...
}
```

it never gets to that point because the `metadata` of the Chart is being parsed AND validated at the time the files are being loaded. 

While the early validation certainly works for most of the other, if not all of the other commands it doesn't work for `package` where you can provide a version via the `--version` flag. 

To fix this there would only really be two options I could see:
1. Make the parsing "aware" of what command has been invoked (i.e. disable the version check for `package` via flag)
2. Turn it off by default and have the individual command validate it like `package` is actually trying to do

Cheers,

Kimba
