### ISSUE TITLE
Get script for helm does not work since latest release

### ISSUE THREAD

**Issue by simonseyock** [helm/helm#9607]
The get script searches the github releases page for a matching tag if no desired version is provided:

```bash
release_url="https://github.com/helm/helm/releases"
# ...
TAG=$(curl -Ls $release_url | grep 'href="/helm/helm/releases/tag/v2.[0-9]*.[0-9]*\"' | grep -v no-underline | head -n 1 | cut -d '"' -f 2 | awk '{n=split($NF,a,"/");print a[n]}' | awk 'a !~ $0{print}; {a=$0}')
```
https://github.com/helm/helm/blob/main/scripts/get#L83

to be precise it searches for a `v2` tag which since the latest release appears only on page 2 of the release pages. This way it does not seem to find a usable tag.

**Comment by dbsanfte** [comment]
Just hit this issue myself.

**Comment by bacongobbler** [comment]
For background context, we dropped support for Helm 2 back in November. It was only a matter of time before things like the install script would begin to fail.

https://helm.sh/blog/helm-2-becomes-unsupported/

The workaround described by @dbsanfte will work as it bypasses the "smart checks" used in the install script to scrape the latest release from the GitHub releases page.

Because we are no longer providing fixes for Helm 2, I'm going to close this as a wontfix.

Please migrate to Helm 3 as soon as possible. There are a number of significant security issues addressed in Helm 3 since October that likely affect Helm 2 users.

Thanks.

**Comment by kurkop** [comment]
For those who haven't migrated to helm3 so far

`curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get | sed 's/$TAG-$OS-$ARCH/v2.17.0-linux-amd64/' | bash`
