### ISSUE TITLE
oci: reconsider to remove the restriction of image name must match the chart name

### ISSUE THREAD

**Issue by pmorch** [helm/helm#9627]
please reconsider to remove the restriction of image name must match the chart name:

> To successfully pull dependencies, the image name in the registry must match the chart name and the tag must match the chart version. The repository entry in Chart.yaml is specified as the repository name on the registry without the image name.

from: https://helm.sh/docs/topics/registries/

(this is analogous to #9378 that is about tags/versions)

It is a super common situation that we want the container image and a helm chart that deploys it to have the same name. With OCI the container image name and the helm chart name in the registry share the same name space, so they can't have the same name. In our case, the container "wins". That forces us to postfix all charts and dependences e.g. with "-helm". 

It would also make it impossible to host e.g. both a copy of an upstream `nginx` container image and an `nginx` helm chart in the same registry because of the name clash.

**Comment by bacongobbler** [comment]
Hi @pmorch!

Thank you for providing your use case along with the proposal. It really helps us understand the motivation behind your ask so that we can consider these use cases going forward.

Currently the roadmap for the OCI experimental feature is laid out in [HIP 6](https://github.com/helm/community/blob/main/hips/hip-0006.md). That document explains what work is needed to unmark it as experimental. The goal is to complete the MVP and mark the feature as stable, then once implemented the community/maintainers can start to consider other use cases.

Have you reached out to @jdolitsky yet? I would start a conversation with him as he's most familiar with the HIP. From there we can determine next steps and see whether this is something we should consider prior to GA or if it's something that can be addressed at a later date.

Let me know if I can be of any assistance. Thanks!

**Comment by pmorch** [comment]
No I didn't reach out to @jdolitsky yet. I'm still wrapping my head around how to setup a CI/CD pipeline including helm and for the time being, I'll accept that:

> To successfully pull dependencies, the image name in the registry must match the chart name and the tag must match the chart version.

For that reason, feel free to close this issue if it doesn't contribute to your project. I'll likely have moved on by the time you're ready to consider it.

**Comment by pmorch** [comment]
I suggest that given:

> To successfully pull dependencies, the image name in the registry must match the chart name and the tag must match the chart version.

and assuming `Chart.yaml` has:

```
name: mychart
version: 0.1.2
```

Then:

    helm chart save . harbor.example.com/dev/mychart:0.1.2

should work, but these should fail:

    helm chart save . harbor.example.com/dev/othername:0.1.2
    helm chart save . harbor.example.com/dev/mychart:0.1.3
    helm chart save . harbor.example.com/dev/mychart:foobar

Otherwise you can push, pull and export the chart, but it cannot be used as soon as somebody wants to use it as a dependency for another chart. This is similar to how you don't get to decide the file name with `helm package $dir`.

Perhaps `helm chart save` shouldn't even accept the chart name and tag/version so the only legal variation in the above circumstances should be:

    helm chart save . harbor.example.com/dev

It is just weird that you can create and push a chart that *cannot* later be used as a dependency.

Let me know if you want me to open a separate issue for this. Also, feel free to ignore this comment or the entire issue, if I'm just spamming you guys with noise.

**Comment by bacongobbler** [comment]
FYI, HIP 6 talks about removing `helm chart save` in favour of `helm package`, so most of those discussion topics would likely fall under `helm push` with the new model. I'd highly suggest giving the proposal a read.

**Comment by pmorch** [comment]
You're right. I've been too lazy. 

It is just much easier to have an uninformed opinion :-)
