### ISSUE TITLE
Add option to helm template to generate meta.helm.sh annotations

### ISSUE THREAD

**Issue by ArgTang** [helm/helm#9630]
We are using ArgoCD to deploy our helm chart and it works really good. 
ArgoCd uses `helm template` cmd to render all manifests, but we regurarly get errors when we need to do "manual" deploys with `helm upgrade/install` because the annotations  `meta.helm.sh/release-name: myrelease` and  `meta.helm.sh/release-namespace: test` are missing. Fixing the manifests by adding these manually works, but is a bit tedious, therefore it would nice if we could add a flag to make `helm template` to add these automaticly.

We could add the annotations to all our helmchart definitions but it feels like that is an antipattern for metadata that should be added by the tool.

**Comment by bacongobbler** [comment]
As per the original PR, these labels are meant to be used as "ownership" labels. In other words they're used to declare that these resources have been installed and are being managed by Helm.

When you run `helm template` and piped that out to ArgoCD, Helm is no longer part of the process. To say that "helm" deployed a resource when it was actually ArgoCD could lead to further design issues with upgrades down the road, so I am concerned about the ask here.

To clarify: why should Helm own resources it did not own in the first place?

**Comment by ArgTang** [comment]
We have two workflows to deploy a helm chart. 
1. sync with argo
2. install from localhost with helm --install

We use mainly Argo but we have to resolve to workflow 2 when ex. testing chart changes in our staging environments. For us these both deployments are owned and installed by helm, but since argo uses the helm template cmd, one can break the other. We have not experienced any deployment issues with mixing these other than manually having to add the annotations if they are missing.

The issue you linked to has quite a few posts so i am not sure what the end propsal would look like. Either `helm template --add-owner-annotation` or running `helm comandeer ` before `helm upgrade` should work for us. but for our usecase i think the first option would be simpler overall, and we could create a `kubetcl annotate` script to do the other one.

**Comment by hanseltime** [comment]
I hate to bump a long dead issue, but I would like to ask the rationale behind not allowing an opt-in option for this.  

Aside from ArgoCD, there are a plethora of use cases and flows where something like this could happen.  For instance, let's say that I am doing beta testing of some additional  resource (let's just say a service for the sake of simplicity).  This could be because of security upgrades or changes to a helm chart that need to be tested in the larger K8s cluster because we don't trust simulating that testing locally, etc and we would like to test this critical configuration before committing everything that might change from the helm chart update.

In a zero-downtime deployment, we would have this service configured after some manual tweaking and then have it run successfully in perpetuity from then on.  Right now though, because there is no option to run helm like this for our CI/CD synchronization mechanism (doesn't have to be Argo, it could literally just be a manual process to run helm update), I either need to have the know-how to manually apply these ownership annotations or I need to take downtime by doing the most recommended option in searches, which is to delete the resource in question and redeploy.

Another valuable use case for this would be with strict IAC deploy pipelines that render out snapshots of helm charts so that we can see if a small change cascades out to X number of configurations for X releases that are variations of the single chart.  Since release name is something that can fundamentally break the deployment, we would want to render that out when generating templates for snapshotting with some tool like helm-unittest.

In general, it feels weird that there is no option to even see the configuration for something that can shut down continuous deployment pipelines at runtime.  This particular problem has led to a fair bit of lost developer time because you want to trust that your deployments will work by the time they get past dry-run.

I would not be opposed to pushing a feature PR, but I also don't want to add clutter to something if helm is adamantly against considering an opt-in flag.
