### ISSUE TITLE
Helm create defaults to overwiting existing files when creating a new chart

### ISSUE THREAD

**Issue by PerArneng** [helm/helm#9657]
When issuing `helm create .`  then Helm will create a chart and overwrite any files that is conflicting and just issue a warning. This is quite dangerous if you are new to Helm or are playing around with uncommitted changes and then accidentally issue that command or pick it up from command history.  Many other tools that have create or init command complain that the directory is non empty or that files exist and then they exit and allow the user to take action.

Here are some alternatives:

1.  Warn the users about existing files and then exit without overwriting anything
2. Warn the user and prompt and ask the user if overwrite is ok
3. Warn the user. Create `.bak` files of existing files and then create the new ones

I think Warn and then just overwrite is not an acceptable behavior because if you end up having those files its most likely unintentional that you run the create command again and in the cases its not it would be easy for the use to take action or perhaps have a `--force` flag that will force an overwrite.

See line:
https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/chartutil/create.go#L634

Thanks for an awesome product!

**Comment by brskq** [comment]
I (a Helm novice) recently lost half a days worth of work when I was trying figure out which command did what I was after. I ran `helm create .` in my project dir and then nearly got a heart attack when I saw:
```txt
>>> helm create .
Creating .
WARNING: File "/home/path/to/project/Chart.yaml" already exists. Overwriting.
WARNING: File "/home/path/to/project/values.yaml" already exists. Overwriting.
WARNING: File "/home/path/to/project/templates/_helpers.tpl" already exists. Overwriting.
```

Did nobody consider a --force flag? Despite my loss I still thank for a great product. :-)

**Comment by bacongobbler** [comment]
Borking out when files were already present might have been the old behavior. I can't recall if it was an intentional change to this behaviour, and if so why. But to change it now could potentially break some user's workflow, so unfortunately this cannot be changed until Helm 4.

There has been other discussions around rewriting `helm create` for other purposes as well, so perhaps this issue could be relevant to the discussion already taking place. See https://github.com/helm/helm/pull/9585#issuecomment-822687539 for more detail.
