### ISSUE TITLE
Chart.lock file should also contain a hash of the actual dependency chart

### ISSUE THREAD

**Issue by patrickhuy** [helm/helm#9662]
Currently there seem to be no mechanisms in place to ensure that the dependency referenced by the `Chart.lock` file is still the same dependency when installing it. To my understanding the `digest` in the `Chart.lock` file is only created over the versions of the resolved dependencies. 

When a Chart dependency in an upstream repository is changed after being created (maliciously or otherwise) there is no mechanism in place to detect such a change.
It would be ideal if this could be covered in the normal dependency installation process as well, at least as an option. To realize this the `tar` file of the dependency chart could be hashed and added to the `Chart.lock` file which could then be verified on dependency installation.

**Comment by technosophos** [comment]
This would probably benefit from a HIP proposal for Helm 4, at which point we could change the content of the lock file.

**Comment by rd185276** [comment]
#9686 https://github.com/helm/helm/issues/9686#issue-883744688 I think this heirarchical depedency issue is because of chart lock. I think it  is modifying while installing. @technosophos You can refer this issue like it should be locking the file at the bottom level

**Comment by patrickhuy** [comment]
@technosophos: I can attempt to draft a HIP but I'm not involved in the Helm development process and I'm not sure whether I can invest the amount of time that might potentially be needed to "steward" this. Is this in general something that could be wanted/needed? Am I missing something here?

**Comment by technosophos** [comment]
@patrickhuy it is up to you how involved you want to be. Right now, we are just starting to put together the new feature set for Helm 4, and the process is that each new feature has to have a HIP. It's not necessarily the case that the person who writes the HIP will be on the hook for much more than getting the HIP merged.

While it tends to take a long time to get a HIP merged (because we all have to read it etc., and we're all busy), it doesn't take that much work once the HIP is written. Typically it's an initial proposal, one to two rounds of revision spread over a few months, and then merging.

So, if you want to tackle it, that'd be great. If not... I'll just leave this issue open and hope someone else jumps in to author it.

**Comment by sebastianblunt** [comment]
Please consider reopening this issue as this is highly unexpected behavior from a file named Chart.lock. Supply-chain compromises are a big issue and dependency locking is an important part of mitigating supply-chain risk.

This is an issue both in chart repositories and OCI repositories.

I understand there are provenance-verification tools available but I would consider that an orthogonal solution.

Separately it appears that the sha256sum in chart repositories' index.yaml does not get checked either. The repository operator can naturally change the index.yaml freely so it's not a security concern for users but it would be a natural guard against errors in transmission.

If an HIP is needed to address this I would be happy to attempt drafting an HIP.

**Comment by tollsimy** [comment]
Hi @patrickhuy , @sebastianblunt , thanks for raising and reviving this thread.
I'm also strongly in favor of this proposal. The `Chart.lock` file should pin the actual dependency content, not just resolved versions, and nowadays that's a must-have for supply-chain security.

I've opened #32243 as a first step toward that goal. It records a SHA256 digest of each dependency tarball in `Chart.lock` on `helm dependency update`, and `helm dependency build` fails if upstream content no longer matches the lock.
That solves the main scenario: a chart republished under the same version with different bytes, but it also helps when you don't semver every publish (common with CD): the lock tracks content instead of just the version. When upstream pushes new bytes under the same version, `helm dependency update` updates the digest in `Chart.lock`. Downstream repos can use that change as the signal to refresh dependencies, or tooling like Renovate can pick it up, even when the semver in `Chart.yaml`/`Chart.lock` hasn't changed.

There's still a gap this PR does not close, which I think is worth follow-up discussion:
OCI registries tags can be mutable, so version pins alone aren't enough. This change records content digests after download, but it doesn't yet let you pin an OCI dependency by digest in `Chart.yaml` (see #32133 ).
I think that's the natural next step for proper OCI locking support.

@technosophos Happy to hear your feedback on this.

**Comment by tollsimy** [comment]
up

**Comment by sturivny** [comment]
We also need this in CKI. It would help us detect republished dependencies and make `Chart.lock` much more reliable.

Hope this gets merged soon. Thanks for the great work!
