### ISSUE TITLE
Support or document existing mechanism to --append-hash to configmaps and secrets

### ISSUE THREAD

**Issue by kav** [helm/helm#9735]
I know the current recommended practice for rolling deployments is to use https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

However the kubernetes team seems to recommend a workflow that new configmaps are created and then old deleted a la
https://github.com/kubernetes/kubernetes/issues/22368
https://github.com/kubernetes/kubernetes/pull/49961#issuecomment-319440152

I know of course it all depends on the application and whatnot but is there an easy way to add the hash of the configmap data to the name? I know you could hash the relevant values and perhaps that's enough though it is inconsistent with --append-hash behavior. 

Perhaps also this whole workflow is more of a can of worms as helm may delete the previous configmap before the new pod is ready under current behavior, I've not tested that as yet.

Regardless the mismatch here seems worth looking it whether there is a feature missing, documentation of the values hash pattern or simply noting that helm doesn't recommend the same thing the kubernetes team does here. Especially with immutable configmaps coming down the pipe.

Thoughts?

**Comment by mattfarina** [comment]
There are cases to update the configmap or secret in place and there are times to create a second one and then remove the first. It kind of depends on your use case. This is important to note as the original intent of configmaps and secrets was for a more limited set of use cases than people use them for today.

In any case, being able to change the name when the contents change is possible but tricky.

First, you need to generate a hash of something. There's an example of generating a hash for a configmap at https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments. It's possible to generate the `data` section or some other information in a template function and then generate a hash of this.

Second, this hash would need to be used any place the reference to the configmap or secrets name is used.

This can all be done within template functions. It is the kind of thing you want as part of the chart instead of a flag because charts are packages and the business logic for that chart should be encapsulated in it.

**Comment by kav** [comment]
>It's possible to generate the data section or some other information in a template function and then generate a hash of this.

Yeah I think this is mostly my point in terms of "current" solutions that duplicate the behavior being pretty complex... Linking to the name using a template is pretty easy, hashing the data is pretty hard since as you note it's got to generate the content to hash before generating the hash.

In case it's not clear here the first request is not "add the flag to the CLI". It is rather to support or document how to achieve (ideally easily) the behavior of the kubectl flag in building charts . I'm with you 100% that adding a flag to the helm CLI doesn't make a lot of sense here.

Second of course I'd love a sense of how the different recommended best practices from kubernetes "use new names" vs helm "update existing and roll with an annotation" might ultimately be reconciled before they drift too much.

**Comment by kav** [comment]
@mattfarina any further comment? I'm not looking for "support" here so that tag isn't really correct. More a design discussion on how we might align the recommended approaches from Helm to update the configmap and roll the deployment vs the kubernetes team saying absolutely don't do that, instead make a new configmap hashed this way and reconfigure the deployment.
