### ISSUE TITLE
Feature: support cache repo setting for charts - f.ex. using OCI

### ISSUE THREAD

**Issue by KlavsKlavsen** [helm/helm#9740]
It would be VERY nice if Helm supported a helm-repo-cache option.. like --helm-repo-cache=oci://ghcr.io/example/  (githubs registry which supports OCI) - and then Helm would look for a dependency named traefik, with version 9.19.1 - in that repository (which is already how OCI works) - before trying upstream atleast (and with an option to not even try upstream path.. --fail-if-not-in-repo-cache )

Use case:
We are running in environments where we need to NOT have internet access - and also in general - we would like our helm charts to be hosted on our own equipment, so we can work with them - without having a problem if upstream is down/dead/compromised.

We're using the subchart pattern - so we have a Helm chart called traefik, which has a dependency on upstream traefik helm chart.
We've uploaded this chart to an OCI repo - and pointed the traefik dependency to this. 
This all works great.
BUT we also have other charts, that has dependencies of their own - where we currently need to pull the upstream chart (helm chart pull as it's OCI).. and to also have dependencies in OCI repo.. we'd need to edit upstream Chart.yaml, package that and then save that to OCI repo :(

**Comment by mattfarina** [comment]
I am not sure I entirely understand your request. When it comes to dependencies and charts, the dependency fetching is when you update a chart. The dependencies should be in the chart archive. So, if I fetch a Bitnami chart and put it into a private OCI registry it will have the chart and all of its dependencies. Only if I update the top level chart will have an opportunity to fetch dependency updates.

Could you please share your workflow where you are fetching dependencies so that we can better understand your situation.

**Comment by KlavsKlavsen** [comment]
I totally missed that the dl'ed argo-cd-3.6.1.tgz actually contains redis-ha-$version.tgz inside it - so yes this is actually solved that way..
