### ISSUE TITLE
helm repo add failure

### ISSUE THREAD

**Issue by jimmag** [helm/helm#9766]
helm repo add incubator http://mirror.azure.cn/kubernetes/charts-incubator/

WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
Error: looks like "http://mirror.azure.cn/kubernetes/charts-incubator/" is not a valid chart repository or cannot be reached: no API version specified

**Comment by hickeyma** [comment]
@jimmag Some feedback as follows.

> WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config

Helm connects to Kubernetes API server using [kubeconfig files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) similar to `kubectl`. Usually this configuration file is at user level rather than root level. It should therefore have limited permissions for that user only as its configuration details to that person's cluster(s). In your scenario  its at root level and you are getting the warning as it still checks for group access for a user not root. Check out #9115 for more details about the warning.

> Error: looks like "http://mirror.azure.cn/kubernetes/charts-incubator/" is not a valid chart repository or cannot be reached: no API version specified

This maybe because it's insecure HTTP. Does the warning disappear if you use HTTPS instead?

**Comment by yxxhero** [comment]
@jimmag I found the index.yaml in http://mirror.azure.cn/kubernetes/charts-incubator/ is empty.

**Comment by jimmag** [comment]
> @jimmag Some feedback as follows.
> 
> > WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
> 
> Helm connects to Kubernetes API server using [kubeconfig files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) similar to `kubectl`. Usually this configuration file is at user level rather than root level. It should therefore have limited permissions for that user only as its configuration details to that person's cluster(s). In your scenario its at root level and you are getting the warning as it still checks for group access for a user not root. Check out #9115 for more details about the warning.
> 
> > Error: looks like "http://mirror.azure.cn/kubernetes/charts-incubator/" is not a valid chart repository or cannot be reached: no API version specified
> 
> This maybe because it's insecure HTTP. Does the warning disappear if you use HTTPS instead?

Use the same warning as http，may be that the index file is empty

**Comment by jimmag** [comment]
> @jimmag I found the index.yaml in http://mirror.azure.cn/kubernetes/charts-incubator/ is empty.
maybe

**Comment by yxxhero** [comment]
> > @jimmag I found the index.yaml in http://mirror.azure.cn/kubernetes/charts-incubator/ is empty.
> > maybe

can you test it? add more info to the index.yaml.

**Comment by jimmag** [comment]
> more

I cannot add information to the index

**Comment by jimmag** [comment]
> > > @jimmag I found the index.yaml in http://mirror.azure.cn/kubernetes/charts-incubator/ is empty.
> > > maybe
> 
> can you test it? add more info to the index.yaml.

I cannot add information to the index

**Comment by yxxhero** [comment]
From the code point of view, because index.yaml is empty, I will add a more friendly prompt.@jimmag
