### ISSUE TITLE
Error: UPGRADE FAILED: create: failed to create: Secret "sh.helm.release.v1.prometheus.v9" is invalid: data: Too long: must have at most 1048576 bytes

### ISSUE THREAD

**Issue by Eljah** [helm/helm#9788]
Error: UPGRADE FAILED: create: failed to create: Secret "sh.helm.release.v1.prometheus.v9" is invalid: data: Too long: must have at most 1048576 bytes

was thrown on helm upgrade/install

The reason for this message had nothing to do with secret. It was a large xxxx.tgz file mistakendly placed in the working directory where the helm install was called. There were no dependency on values.yml and so on so they are not added to the issue.

Output of `helm version`:

helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

Output of `kubectl version`:

kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): DigitalOcean

**Comment by mattfarina** [comment]
The secret created by Helm is a record that helps Helm perform many tasks, such as rollback or to show information about a release. There are cases where that file could accidentally get added to the record Helm stores as data like that is sometimes stored because it's needed for other functions.

If it's something in there by accident, I would suggest deleting it. If it shouldn't be part of the delivered payload I would suggest adding it to the `.helmignore` file.

**Comment by Eljah** [comment]
@Eljah isn't it possible to do the file size check and if they are larger than 1Mb to handle that like a outside accidental file, definitely not the true Helm secret? And throw the error about the wrong file with its name and location?

**Comment by mattfarina** [comment]
@Eljah That's a great question. The problem is that the file size is not consistent. For example, the limit has to do with etcd rather than Kubernetes. k3s uses sqlite and it's possible to [configure etcd with a different size limit](https://etcd.io/docs/v3.4/dev-guide/limit/) (there are tradeoffs do doing this). There is not an easy way for Helm to query the size to know the limit ahead of time.

**Comment by Eljah** [comment]
@mattfarina ok, makes sense. But if there would be possible to have two reasons for the exception, the designed and the occasional one, would it be possible to add one more sentence to the error message and advice a user to check the directory for the accidentally placed tar files, not related to the helm secret?

**Comment by Nindaleth** [comment]
I also spent a bit too much time to find that the error actually is "Helm stores the full chart as a Secret into K8s to allow rollback and other Helm features, but this chart is too big to fit within your K8s's specific Secret size limits". Please consider this an additional vote for a more explanatory error message.

There are already tickets to prevent this issue altogether, I'm just asking for the error message to be clearer to the end user.

**Comment by Nindaleth** [comment]
I'm still interested in this getting improved.

**Comment by olahouze** [comment]
Hi, me too

**Comment by korenlev** [comment]
same here

**Comment by Nindaleth** [comment]
I'm still interested in the error message UX getting improved.

**Comment by Btijmen** [comment]
I too would very much like to see a better warning. I'm pretty experienced with Helm (~3 years professional experience) but this error still throws me for a loop every now and then.

**Comment by mloiseleur** [comment]
One of the recommendation of Helm is to provide [dedicated Chart with CRD](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts).

But with this limitation, it can not really happen.
