### ISSUE TITLE
Helm 3.6.1 breaks "helm pull" with repo/chartname

### ISSUE THREAD

**Issue by derkoe** [helm/helm#9820]
Helm 3.6.1 breaks `helm pull` with repo/chartname (after adding the repo with auth).

How to reproduce:

```
$ helm repo add myrepo https://example.com/myrepo --username *** --password ***
"myrepo" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "myrepo" chart repository
$ helm pull myrepo/mychart
Error: failed to fetch https://example.com/myrepo/mychart-1.0.0.tgz : 401 Unauthorized
```

Output of `helm version`:  
```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

**Comment by derkoe** [comment]
I've debugged the issue into `httpgetter.go` - when running `helm pull myrepo/mychart` the variable `u1` contains ` myrepo/mychart` - that's why this if does not work https://github.com/helm/helm/blob/release-3.6.1/pkg/getter/httpgetter.go#L74

**Comment by dol** [comment]
The same happens with any other command that's using httpgetter. Like `helm show values some/chart` . As @derkoe pointed out correctly, the `u1` doesn't contains a full url to compare with. Only the `some/chart`.  I did a similar debugging as Christian and came to the same conclusion.
Thank you @derkoe for raising the issue and root cause so fast.

**Comment by dol** [comment]
Not sure if this helps but it looks like that the url, once discovered from the repositories is not set as url to the options.

I made a small adjustment that resolves the issue: https://github.com/helm/helm/compare/v3.6.1...dol:patch/v3.6.1?expand=1

**Comment by derkoe** [comment]
@mattfarina please have a look at this issue (usually i wouldn't ping but this is a major issue).

**Comment by derkoe** [comment]
@dol tried your fix and it works - could your create a PR?

**Comment by iss0** [comment]
Could this be related to https://github.com/helm/helm/issues/9816#issuecomment-863868716? :thinking:

**Comment by iss0** [comment]
@dol I tried your fix for my problem mentioned in https://github.com/helm/helm/issues/9816#issuecomment-863868716 and it works for me as well!

**Comment by bacongobbler** [comment]
Thanks @dol. If you want to submit a patch along with a test case to help confirm the issue, that would be appreciated.

cc'ing @mattfarina

**Comment by dol** [comment]
I was looking into a corresponding test case. IMHO it doesn't look that easy. With the help of `repo/repotest` it might be possible to spin up two servers that will server the index.yaml file and the other the chart files. Both listening on a different port and server1 pointing to server2 in the index.yaml file.
Not sure if I have the time/knowledge to prepare proper test cases.

IMHO the security patch `3.6.1` was not really tested and skipped some QA steps. It was optimized for speed to fix a long standing security issue. And this is now causing problems.

The way forward would be to announce that `3.6.1` is utterly broken and consider removing the release entirely. Some package managers like brew already server `3.6.1` as a default. My guess is that a lot of people use the https://github.com/helm/helm/blob/main/scripts/get-helm-3 script on their CI/CD pipeline. If no version was defined, the most recent will be downloaded.
Because I had some regression in our CI/CD pipeline due problems and changes of helm we ended up manually increase the version number from time to time. This could be achieved by specifying a desired version:

```
curl -LsS https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | DESIRED_VERSION="v3.6.0" bash
```

With the patch that I provided I wanted to shorten the time that it will take someone to identify a possible solution. At the moment I'm not able to provide corresponding test cases. Sorry for that. I only did some tests in our CI/CD environments and everything started working again.

**Comment by bacongobbler** [comment]
> IMHO the security patch 3.6.1 was not really tested and skipped some QA steps. It was optimized for speed to fix a long standing security issue. And this is now causing problems.

While I sympathize with your frustration on this issue, the security audit was conducted by a number of members on the security list, including myself. We did not optimize for speed in any form. We identified the issue, tested the fix against all known use cases, then released it once we verified all known cases worked as expected. This took a number of weeks.

To clarify, the scenarios we were aware of include:

- relative URLs
- Absolute URLs served from the same hostname
- Absolute URLs from an alternative domain

We tested using the following examples, using `repotest` to help:

```
urls:
  - /charts/mychart-1.0.0.tgz
```

```
urls:
  - https://mydomain.com/charts/mychart-1.0.0.tgz
```

```
urls:
  - https://some-other-domain.com/charts/mychart-1.0.0.tgz
```

But we did not test for this (which apparently is accepted input according to [this test case in chartmuseum](https://github.com/helm/chartmuseum/blob/560b65158af4c367e9591fccacc3e0f94e6d8620/pkg/repo/index_test.go#L95-L99)):

```
urls:
  - charts/mychart-1.0.0.tgz
```

Had we known this was a valid use case, we would have accounted for it in our testing.

However I do not agree with the notion that Helm 3.6.1 is "utterly broken". The three scenarios listed above account for a VERY large majority of chart repositories available today.

However, I do acknowledge that there is an uncaught edge case we failed to address. We'll accept pull requests to fix that.

> With the patch that I provided I wanted to shorten the time that it will take someone to identify a possible solution. At the moment I'm not able to provide corresponding test cases. Sorry for that. I only did some tests in our CI/CD environments and everything started working again.

Fair enough. We appreciate you taking the time to look into this issue.

If someone has the time to look into this further, we'd appreciate a patch (along with an accompanying test case). Once complete we can schedule a Helm 3.6.2 with the patch.

In the meantime, if everyone could please share their chart repository's index.yaml files so we can investigate if there are other uncaught edge cases, that would be helpful as well.

Thanks all for understanding.

**Comment by KnechtionsCoding** [comment]
Here is an index.yaml from artifactory that fails with a 401 on helm pull with 3.6.1. I've replaced some variables.

```yaml
apiVersion: v1
entries:
  <chart-name>:
  - apiVersion: v2
    appVersion: "1.0.0"
    created: 2021-06-21T16:03:31.811852Z
    description: <description here>
    digest: 77831a2c79d411e3420d1cdc9cc7fe598b45315ab5c0e2921e6a053ded479c3b
    name: <chart-name>
    urls:
    - https://<artifactory-url>/artifactory/helm-prod-local/<chart-name>/<chart-name>-v2.0.3.tgz
    version: "v2.0.3"
    type: application
  generated: 2021-06-21T16:03:31.811946Z
```

Evidence:

```
hans.knecht:Repositories/ $ helm pull --untar --version 2.0.3 <repo-name>/<chart-name>                                                                                                                                                         [18:08:26]
Error: failed to fetch https://<artifactory-url>/artifactory/helm-prod-local/<chart-name>>/<chart-name>-v2.0.3.tgz : 401 Unauthorized
hans.knecht:Repositories/ $ helm version                                                                                                                                                                                                             [18:08:29]
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"dirty", GoVersion:"go1.16.5"}

hans.knecht:Repositories/ $ helm version                                                                                                                                                                                                             [18:09:56]
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
hans.knecht:Repositories/ $ helm pull --untar --version 2.0.3 <repo-name>/<chart-name> 
```

repositories.yaml
```yaml
  - name: <reponame>
    url: https://<artifactory-url>/artifactory/helm
    username: "<username>"
    password: "<api-key>"
  - name: <reponame>-local
    url: https://<artifactory-url>/artifactory/helm-prod-local
    username: "<username>"
    password: "<api-key>"
```

It's not just the case you described @bacongobbler

**Comment by bacongobbler** [comment]
Thank you for providing a test case. Have you identified whether @dol's patch fixes your issue, and why?

If you have the time to contribute a patch, we'd welcome a fix, and we can schedule a hotfix release.

**Comment by derkoe** [comment]
@dol please create a PR with the current code (or should I do that using your patch?) 

(And to everybody: please stop arguing who's fault this was - let's focus on the fix)

**Comment by dol** [comment]
@bacongobbler: Sorry for the negative wording on this issue. This was not ideal.

I did some further analyses of the issue and want to clarify my points.

The problem appears with to following simple example with the assumption that the repository list is empty:
```
helm repo add mychart https://my.helmrepo.com/helm --username 'test' --password 'somepassword'
helm show values mychart/basic-application --version 1.0.0 --debug
# The corresponding index.yaml points to https://my.helmrepo.com/helm-charts/basic-application-1.0.0.tgz
```
This simple example works in `3.6.0`, but stopped working with `3.6.1`. Even if the `index.yaml` and the helm chart are hosted on the same `schema://hostname:port`.
In `3.6.1` the debug output points out that the credentials are not sent while fetching the charts.
`Error: failed to fetch https://my.helmrepo.com/helm-charts/basic-application-1.0.0.tgz : 401 Unauthorized`

Regarding URL the `mychart/basic-application` is IMHO a common use case when using a repository. This is the basic example that most of the charts list in their documentation. Eg. https://artifacthub.io/packages/helm/bitnami/mysql

When talking about the URL's that are compared we need to distinguish between the URL that is entered in the command and the resulting http or local URL.
When using `mychart/basic-application` as an command URL the following steps are performed:

1. Determine if `mychart/basic-application` is a local path
2. Determine if `mychart` is in the repository list => if yes, step 3
3. Lookup the corresponding chart URL in the index.yaml of the repository
4. Check if the repository URL and the chart URL are on the same `schema://hostname:post`
5. Download the chart

The recommended patch fixes the step 4 because when `ResolveChartVersion` ( https://github.com/helm/helm/blob/v3.6.1/pkg/downloader/chart_downloader.go#L161 ) is used the URL `u1` will be set to `mychart/basic-application`. If `mychart` is a repository then the URL `mychart/basic-application` should be replaced with `https://my.helmrepo.com/helm`.
https://github.com/helm/helm/blob/7d28adbaf1fb0d053a469005b7a349965651e93b/pkg/downloader/chart_downloader.go#L224-L227

The test cases of 3.6.1 were adopted to simulate the behavior of repository that points to an other `schema://hostname:port`. But the test cases fall short for a basic example with `helm show values <reponame>/<application>`.

**Comment by dol** [comment]
With a little bit of copy & paste from other test cases I was able to add the corresponding test case that simulates a default behavior when using a repository and reference the helm chart with ` <reponame>/<application>`.

The result is https://github.com/helm/helm/pull/9844 .

**Comment by bor8** [comment]
On the Ubuntus - for example:

```
# Downgrade Helm from 3.6.1 to 3.6.0 with a Snap installation:
snap list helm --all
sudo snap revert helm --revision 341
```

**Comment by horihel** [comment]
I suspect that this problem also affects charts hosted with harbor (which is basically chartmuseum currently).

We're currently forced to either downgrade helm or use --pass-credentials even though the charts are hosted from the same domain, but are referenced as charts/my_chart in the index.

**Comment by derkoe** [comment]
@horihel  this affecty any Chart repo with authentication. 

Could any maintainer merge the PR from dol please and release 3.6.2? I guess we need a quick fix for this.

**Comment by bacongobbler** [comment]
There are a few issues conflated here. Some users are mentioning issues with relative URLs with no leading slash in the index. Others are reporting the `repo/chart` syntax with `helm install` is broken (as you mention in the OP).

We need to spend time distilling each into a separate test case, and verify whether @dol's fix applies to only some or all of the test cases. I don't want to release a Helm 3.6.2 knowing that we only caught a small handful of cases and have to release a Helm 3.6.3 a few days later.

It's not totally clear to me at first glance why appending the `getter.WithURL(r.Config.URL)` option fixes the issue. That part of the codebase was let untouched in the original patch, so we need to look into why there was a cascading failure several levels down the codebase. I need to try and reproduce a similar environment to test. If you have a chart repository with basic auth enabled that can be readily tested against, please feel free to send it my way and I'll try to debug the issue further.

I'll start looking into these issues on Monday. In the meantime, please continue to test and submit fixes. Thanks for being patient.

**Comment by mattfarina** [comment]
Can you please test #9871 to see if it fixes your issue.

**Comment by dol** [comment]
The PR #9871 is more or less the same approach that PR #9844 tries to fix. Different people in this thread already confirmed that the patch of #9844 resolved the issue. The PR also includes a corresponding unit tests.

I can withdraw my PR in favor of #9871.

**Comment by dol** [comment]
@mattfarina Since the #9871 was merged this issue can be closed. With the functionality is restored.
I see one improvement when comparing the hostnames. When using the helm registry Jfrog Artifactory there is a possibility to have a miss match on the hostname.
Artifactory produces a index.yaml that always contains a port. Most users add the repository without the port. This example highlights the problem => https://github.com/helm/helm/issues/9857#issuecomment-868508062

I tried to fix the issue by canonicalize the hostname. https://github.com/helm/helm/pull/9886
If you could take a look at it and probably add it to `3.6.2` would be nice.

**Comment by mattfarina** [comment]
Closing as this is fixed. #9886 was added to the 3.6.3 milestone.
