### ISSUE TITLE
cannot convert int64 to string-Exception ( Monitor Deploy ) Deploy failed: The request is invalid: patch: Invalid value:

### ISSUE THREAD

**Issue by MohammedIdris** [helm/helm#9831]
I have a `values.yaml` file in which I have given `spring_datasource_hikari_maximum_pool_size: "10"`

In `deployment yaml` I have used this value as 

```
 - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
    value: {{ .Values.spring_datasource_hikari_maximum_pool_size }}
```

However, when used inside the `deployment.yaml `file it fails with the below error. 

```

Deploy failed: The request is invalid: patch: Invalid value: "map[metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":
{
(helm values etc)
`{"name":"SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE","value":10}]` **(this is the incorrect value)** 
}
cannot convert int64 to string

```
What is the correct format of using an integer value from `values.yaml `file in a `deployment.yaml `file? 
I have also tried multiple combinations with quotes "" but nothing seems to be working.

**Comment by bacongobbler** [comment]
When your template is rendered, the output looks similar to this:

```
- name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
    value: 10
```

In YAML, an unquoted value is casted to a type. In this case, because it is the integral value "10", it is cast to an integer.

A Kubernetes deployment manifest expects environment variable values to be a string, not an integer. That is why you are receiving a "the request is invalid" error. Kubernetes is telling you that it cannot accept the information you provided as valid input according to the [reference specification](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables).

To fix this, wrap your value in double quotes, or pipe it to `quote`, like so:

```
- name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
    value: {{ quote .Values.spring_datasource_hikari_maximum_pool_size }}
```

Hope this helps.

**Comment by MohammedIdris** [comment]
Thanks _@bacongobbler_ for the advice, tried with `quote` and it worked as a String. 
```
- name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
  value: {{ quote .Values.spring_datasource_hikari_maximum_pool_size }}
               ^^^^
```
Also tried with double quotes around the value tag, it worked too. 
```
- name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
  value: "{{ .Values.spring_datasource_hikari_maximum_pool_size }}"
```

I also wanted to get a confirmation if the below options work too, if yes then which one is better to use? 
```
- name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
    value: !!integerEnv {{ .Values.spring_datasource_hikari_maximum_pool_size }}
               ^^^^^^^^
```
```
- name: FAVORITE_DRINK
    value: !!stringEnv {{ .Values.favoriteDrink }}
               ^^^^^^^
```
```
- name: TAKES_SUGAR
    value: !!booleanEnv {{ .Values.takesSugar }}
               ^^^^^^^^^
```

**Comment by MohammedIdris** [comment]
Closing this issue as I have got the resolution from @bacongobbler 

However, request you to provide your views on the above query regarding `!!integerEnv` 

```
- name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
    value: !!integerEnv {{ .Values.spring_datasource_hikari_maximum_pool_size }}
             ^^^^^^^^^^
```
