### ISSUE TITLE
Support for alternative templating engines

### ISSUE THREAD

**Issue by OndraZizka** [helm/helm#9855]
Could Helm support other templating engines?
After all, the goal is to convert a tree of data into a text.

The templating engine currently used is very verbose and lacks features present in other engines.

For instance, Freemarker - I could write the same template using way less constructs and around 30 % less lines.

Thanks for consideration.

**Comment by hickeyma** [comment]
@OndraZizka This is something that gets raised every now and again. 

Here is some feedback:

- In Helm v2 (previous release) there was the ability to add engines to Helm. Yet, no one used it or added any new engines as far as we know. This capability was removed in Helm v3. Some details about it mentioned in #5826.
- [Post Rendering](https://helm.sh/docs/topics/advanced/#post-rendering) was added in Helm v3 where rendered manifests could be manipulated, just before installing using tools like `kustomize` for example. Details of feature in #7260 and implementation in #7259.
- Pluggable template engines was a feature raised in #6184. It was closed waiting on a HIP.

The recommendation here is if you want to pursue this feature then to submit a Helm Improvement Proposal (HIP) so that the community can discuss the feasibility of this feature and if accepted get it on the next Helm major release backlog: https://github.com/helm/community/blob/master/hips/hip-0001.md

**Comment by OndraZizka** [comment]
@hickeyma, thanks for the links. I used Helm circa 2.5 years ago and I was not aware of the feature.

I will check the HIP process and try to find time to submit one.

**Comment by yuseferi** [comment]
I see [https://github.com/hairyhenderson/gomplate](https://github.com/hairyhenderson/gomplate) as a susceptible templating engine for the helm template
