### ISSUE TITLE
ability to idempotently deploy, no matter the state of the previous deployment

### ISSUE THREAD

**Issue by Morriz** [helm/helm#9877]
Hi, we are currently losing a lot of time on manually correcting helm secrets when an install fails for one reason or another. New employees that use helm also are confused initially as to why helm installs do not continue. The error given is also not very straightforward and says something about the deployment of the release already being in progress.

So the question is:

How can we instrument `helm upgrade --install` to not be bothered by that error, and instead always try to reconcile the state given with the one on the cluster?

Output of `helm version`: 3.5.4

Output of `kubectl version`: 1.19.7

Cloud Provider/Platform (AKS, GKE, Minikube etc.): any

**Comment by bacongobbler** [comment]
There are cases where Helm can enter a state that cannot be recovered through automation. In other words, Helm can take two different directions to "fix" the issue, but it cannot determine how to reconcile the issue according to the user's requirements.

We have discussed the idea of an idempotent `helm upgrade` in the past. It was argued that Helm is being used in a CI/CD pipeline, and idempotently handling upgrades is part of a CI/CD pipeline's job.

However I and other core maintainers have argued in the past that Helm is NOT a CI/CD pipeline tool, but a package manager. And in cases where two conflicting solutions arise, most package managers do not "assume" for the user. Instead they ask the user to intervene.

This is to prevent cases where Helm may run into cases where either a `helm rollback` or a `helm upgrade --force` would be applicable. Some use cases may call for a `helm rollback` before re-attempting an upgrade, as a `helm upgrade --force` could remove live resources from their cluster due to the nature of a forced update. In other cases, a forced update may make more sense because a `helm rollback` may cause potential data loss due to a database migration rollback. In many cases a user would DEFINITELY not want that to happen.

So instead, we chose to inform the user that Helm cannot make a decision, and it is up to the user to perform the upgrade as they see fit.

Hopefully that provides some context around why Helm does not always reconcile a release's current state.

See also https://github.com/helm/helm/issues/8415.

**Comment by bacongobbler** [comment]
> The error given is also not very straightforward and says something about the deployment of the release already being in progress.

If you can provide more information on the exact use case you're describing, I'd be happy to provide more information.

**Comment by Morriz** [comment]
Ha, it is about the `sh.*` secret that has a status kept in it. Subsequent deployments fail if the status does not meet certain criteria, and throw errors saying so. Like "a previous install is in progress". We are in need of a flag that tells helm to discard previous deployment status, and just forces reconciliation.

**Comment by bacongobbler** [comment]
Again, if you can provide more information about the issue you are experiencing, we can help point you in the right direction. Let's stop "solutioneering" and identify the problem first. Then we can start discussing options.

For example I'm aware of https://github.com/helm/helm/issues/7139 which is a bug. The state machine can enter an erroneous state due to an interrupted `helm upgrade` either due to an untimely CTRL+C or a client timeout.

If we solve that issue, the need to "discard deployment status" should not be required. But more information is required before we can make that assesment.

**Comment by Morriz** [comment]
> For example I'm aware of #7139 which is a bug. The state machine can enter an erroneous state due to an interrupted `helm upgrade` either due to an untimely CTRL+C or a client timeout.
> 

This is what I am referring to. It blocks subsequent deployments. But any faulty/broken (which can be expected) state that is left behind should be cleaned up by the follower, which would need to discard/repair/whatever that state and proceed with reconciliation.

**Comment by Morriz** [comment]
still bumping as there should come a mechanism to clean up before install for those of us who want stateless configuration and don't see subsequent deployments bork when previous one was leaving an invalid status (such as "pending install")

**Comment by agates4** [comment]
@Morriz did you land on a solution for your use case? I am having very similar problems

**Comment by Morriz** [comment]
No. Still annoying, and sad to see that helm leaves this to userland to reinvent every time ;(

**Comment by agates4** [comment]
I'm not sure why the default approach can't be used (deploy alongside the failed deployments, wait for deploy to succeed, if it succeeds, remove all previous deployments)

How can I achieve that described flow?
