### ISSUE TITLE
Integrate with Kubernetes Dashboard

### ISSUE THREAD

**Issue by migmartri** [helm/helm#990]
Hi,

In order to improve the chart discovery and reduce deployment friction I'd like to propose an integration with the [Kubernetes dashboard](https://github.com/kubernetes/dashboard).

I think that the Kubernetes dashboard is a good candidate because:
- It is enabled by default in 1.2+ version clusters.
- It already has the UI built-in concept of deployment.
- Since it is hosted in your own k8s cluster, end to end chart deployment should be doable. 

Some basic integration could look like:

1 - Click on Built-in Deploy functionality

![click on deploy](https://dl.dropboxusercontent.com/u/200236/helm/click_deploy.png)

2 - Deploy using a helm chart

![choose helm chart](https://dl.dropboxusercontent.com/u/200236/helm/select_helm.png)

3 - Retrieve the list of applications from the official HELM repository and show a list that can be similar to 
the [GCE Cloud launcher](https://console.cloud.google.com/launcher)
![choose app](https://dl.dropboxusercontent.com/u/200236/helm/list_app.png)

4 - Once you click in one of those apps we could:
- As a first version, delegate the deployment functionality to the CLI which will mean to just show the helm command (and probably some links to documentation on how to install helm) that needs to be executed to deploy the chart.
- Ideally, it would be great if we could provision the chart directly from the UI. Showing you a form with text fields to customize the values in values.yml.

What do you think?

**Comment by viglesiasce** [comment]
This is awesome! I think its a great way to surface the "golden" charts. It would be great for the detail page to have:
- Instructions on how to install
- A/the README for what the app actually does and how to use it
- A link/icon/logo for the maintainer and how to get get things changed/updated or provide feedback.

The set of charts repositories should be configurable so that this can be molded for a particular org.

**Comment by technosophos** [comment]
Fabulous idea. @runseb has already asked for us to put `logo: URL` back in the `Chart.yaml` file. He and I talked about how we could either do that, or just agree on a naming convention for logos inside of chart files (e.g. `icon.svg` or `icon.png`). I'm okay with either, provided we decide before Alpha.4. And the `home: URL` field in the Chart could be used as a link to documentation.

**Comment by sgoings** [comment]
> The set of charts repositories should be configurable so that this can be molded for a particular org. (@viglesiasce)

Would have been so killer to have at the last place I worked where people wanted to curate their own version of the company's product offering.

**Comment by jstrachan** [comment]
I'm super keen for this too ;). FWIW we added something like this a year or so ago to our [kubernetes console](http://fabric8.io/guide/console.html) but since it predates kubernetes/helm we use OpenShift Templates on OpenShift and ConfigMap on Kubernetes to store 'templates' (that are chart-like blobs of YAML/JSON). I much prefer using helm as the underlying repository/runtime though! :) There's a little demo of it in action below.

We've lots and lots of open source charts (the above is a small selection). I'm almost done porting them over to the new kubernetes/helm tarball+YAML structure. (e.g. [chaos-monkey](http://central.maven.org/maven2/io/fabric8/devops/apps/chaos-monkey/2.2.234/chaos-monkey-2.2.234-helm.tar.gz), [gogs](http://central.maven.org/maven2/io/fabric8/devops/apps/gogs/2.2.234/gogs-2.2.234-helm.tar.gz) etc). I hope to have an index.yaml + repository for them all soon so folks can easily play with them from helm & use it as test data for the new dashboard UI.


I guess the first step on the road to a helm UI in kubernetes dashboard is some REST APIs to query charts in the installed repositories and then a REST API to install a chart. 

Given our console doesn't use material design (Red Hat UIs have to use bootstrap); I'm not hopeful of being able to reuse much of the client side UI stuff; but hopefully we can all share the REST APIs and chart repos though! ;)

I'm more than happy to help beta-test / hack on the REST APIs for UIs to query charts when I'm back from vacation.

![fabric8-charts](https://cloud.githubusercontent.com/assets/30140/17780657/1c2aa864-6564-11e6-93e3-e7881c4e874d.png)

**Comment by bryk** [comment]
SIG-UI here. Thats great idea! Let's talk when you want to move this forward.

cc @kubernetes/dashboard-maintainers

**Comment by cheld** [comment]
CC @cheld

**Comment by jstrachan** [comment]
BTW if its any help we've created a little HTML rendering of our Helm chart repository:
http://fabric8.io/helm/ - if you want to see the YAML its in the usual place: https://fabric8.io/helm/index.yaml

I recently made a similar UI for folks using vanilla kubernetes manifests: https://fabric8.io/manifests/kubernetes.html so that if you click on a manifest and version, you get to see the CLI command to apply a manifest, can download it or can open it in a little web UI to apply it to a console (that parts not totally working yet ;).

Given a URL to a chart if we can figure out a CLI command to use to install it via helm #1158 then I could do the same for the helm chart repository - so at least folks could see at a glance the one liner to install it via the helm CLI.

What would be even cooler though would be if the Dashboard had an `Install Chart` page that takes a Chart URL query parameter so that we could link to it from something like [this helm chart repository page](http://fabric8.io/helm/) to install a given chart in one click in the Dashboard

**Comment by nicr9** [comment]
Hey everyone!

Myself and @joe2far have been working on dashboard integration for a proof of concept at work.

We'd love to get your opinion: kubernetes/dashboard#1332

**Comment by ligc** [comment]
@nicr9  @joe2far  Thank you for working on this super cool feature, I am looking forward to trying it, any estimation on which kubernetes release that this feature will be delivered? Thank you.

**Comment by nicr9** [comment]
Hey @ligc, glad you like it!

At this point in time I don't think we can be reasonably certain about a delivery date. There's still a lot of work to be done to discuss/design the full feature set that will be tackled in this integration and that will also take time to implement.

Also: I can't personally speak for the dashboard maintainers but I would imagine that they would want to hold off on merging this until helm itself is closer to release candidate status.

On the other hand, if you're hoping to preview it before it's wrapped up, @joe2far has included some instructions for deploying the unstable dashboard [here](https://github.com/kubernetes/dashboard/pull/1332#issuecomment-253448013). It goes without saying that the preview is nowhere near ready for production use yet! Your mileage may vary!

**Comment by ligc** [comment]
Thanks @nicr9.   As jstrachan commented at https://github.com/kubernetes/helm/issues/990#issuecomment-240769342, part of this effort is to add REST-APIs for the helm/tiller, will the implementation of these REST-APIs be in the Kubernetes dashboard or be available through the k8s apiserver?

**Comment by sebgoa** [comment]
FWIW, I think the use of gRPC for tiller is a barrier to making web clients. Plus it raises issues with authentication (we can't expose tiller via a regular service to the outside, ingress, nodeport etc, with proper auth).

I'd be in favor to discuss this in details after the first official release of HELM. Developing a REST wrapper around a gRPC based proto sound very strange (an API, around an API, around an API)

If we wanted to leverage the k8s api, we should actually write helm with third party resources, and make Tiller a controller of those 3rd party resources. That way the dashboard would keep talking to k8s api server normally...

**Comment by joe2far** [comment]
As part of the proof of concept integration work done in kubernetes/dashboard#1332, we already have implemented some REST APIs but they're served by the dashboard backend specifically for it's own use. It works by wrapping helm's library. @jstrachan said he'd like to have access to REST APIs but they aren't available either from helm's current implementation or our branch.

We like the idea of using 3rd party resources (3PR) but we weren't sure if this was planned for helm. This approach could be an easier integration point for the dashboard in terms of querying which releases are installed. From my understanding, I'm not sure if they could be used to provide a chart installation API. Do any of the helm folks know if taking advantage of 3PRs is part of future plans for helm?

We're also still in talks with dashboard folks (we [demo'd our latest](https://drive.google.com/open?id=0BwsH9arFx6LBTmx3eDhfX19vWHc) at the last sig-ui meeting). They seem really interested in the integration effort and have a lot of great ideas about how to tackle the UX.

Lastly helm is under heavy development; it might be best for us to wait until helm is out of beta to continue with this. I think what might happen is that we'll close our PR (keeping it for posterity as a proof of concept) so a better long term solution can be achieved.

**Comment by bryk** [comment]
@sebgoa

> I'd be in favor to discuss this in details after the first official release of HELM. Developing a REST wrapper around a gRPC based proto sound very strange (an API, around an API, around an API)

In Dashboard all communication goes through its backend and private. So it can be wrapping and unwrapping gRPCs. Either as a lightweight proxy or full fledged private API with business logic. This is pretty much what @joe2far did in their demo.

**Comment by technosophos** [comment]
I'm not sure what the current status is. Does anyone have an update?

**Comment by jstrachan** [comment]
@joe2far the 3PR idea is interesting. We could add a helm command that installs/updates all the charts from a repo into kubernetes as 3PRs. Each 3PR would store the main chart metadata (name, description, labels/tags, icon & URL to the chart  etc).

Then the dashboard can view/filter the charts as per the UI mockup above - plus folks could use kubectl to view them too ;)

We'd then just need a REST API in tiller so that the dashboard could install a selected 3PR. Where we POST to some endpoint the URL to the chart to run (with optional parameters).

Longer term having a REST API that lets the user add/remove chart repositories (to populate or remove the chart 3PRs) would be nice too

**Comment by InAnimaTe** [comment]
Hey all, just wanted to see if there was any January updates on this? Moving from Rancher into Kubernetes and starting to play with helm really mimic's their rancher-catalog idea: composable repeatable templates that are easy to engage with. Having Helm support in the UI would further make deployment super easy and fun. Furthermore, providing the ability to fill in certain variables or other fields of the configuration from the UI would be even more exciting.

**Comment by technosophos** [comment]
The definitive source on this is now https://github.com/kubernetes/dashboard/pull/1332

This ticket is just here for the linkage. Note also that the Helm Monocular project (web UI to repositories) is well underway.

**Comment by gyliu513** [comment]
Well, I was a bit confused here, how do we want to proceed this project? Enhance current Kubernetes dashboard or just leverage the Helm Monocular project? Actually, I do not have strong options for which one is better, I think that we may need to enhance the [Kubernetes dashboard backend](https://github.com/kubernetes/dashboard/tree/master/src/app/backend) to enable the Helm APIs, then everyone can just call the [Kubernetes dashboard backend](https://github.com/kubernetes/dashboard/tree/master/src/app/backend)  to customized their dashboard. Comments?

**Comment by floreks** [comment]
From dashboard perspective helm integration would be nice to have. I have done some initial work on integrating helm with dashboard based on existing PR https://github.com/kubernetes/dashboard/pull/1332. Currently I am working on integrations API and integrations page that will allow us to easily manage all dashboard integrations.

While working on integrating helm into the dashboard I have encountered some issues with your dependencies. This is currently a blocker because our client-go and apimachinery deps have different versions (newer) than helm's.

**Comment by gyliu513** [comment]
Thanks @floreks , so what is the problem of updating Helm to match the version deps?

**Comment by floreks** [comment]
On our side there is no problem. Helm needs to update their dependencies and everything should work. The problem is that `client-go` and `apimachinery` is constantly changing and we are trying to keep them up to date. On the other hand helm might want to keep stable version of deps not latest like dashboard.

**Comment by gyliu513** [comment]
Yes, it is a problem, but I  think that this should be a common issue for all Kubernetes projects, such as service catalog etc. The final goal should be all projects should use `client-go` and `apimachinery` in the future. I think that the `client-go` and `apimachinery` should also have stable version and helm should also have same release cycle and time as those projects, comments? @floreks

**Comment by floreks** [comment]
@gyliu513 Of course I agree. Right now `client-go` and `apimachinery` are unstable and constantly changing. Packages are moved from one to another and from kubernetes repo. Once everything will be stable and properly versioned then it will be much easier for all projects based on kubernetes to integrate with eatch other.

We are trying to sync our releases with kubernetes timeline and before the release update all deps so they are (mostly) in sync with k8s.

**Comment by gyliu513** [comment]
Good to know, thanks @floreks So what is the current plan for this issue? Using Monocular or update Kubernetes dashboard directly? Just want to know the direction for this ;)

**Comment by floreks** [comment]
From dashboard perspective I can say that we are planning to add helm integration anyway.

**Comment by wstrange** [comment]
It would be super helpful if Charts included standardized metadata that could give a Helm GUI hints on how to present values.yaml for editing.  You probably want a generic yaml editor, but for novice users it might be nice to give them more of a constrained experience.  
Something like:
```
metadata:
- name: service.database.type
  description: Choose the type of database for persistence
  label: Database Type
  type: choice
  values:  [ postgres, mysql, sqlite3]
```

**Comment by kfox1111** [comment]
Rather then inventing a new kind of language, is there an existing one that would work?

**Comment by bacongobbler** [comment]
@kfox111 which comment are you referring to here? Don't see any mentions about inventing a new language.

**Comment by kfox1111** [comment]
@bacongobbler Sorry, was responding to @wstrange's comment.

**Comment by gyliu513** [comment]
One question for the integration: for some charts, the `values.yaml` include some comment out keys, such as https://github.com/kubernetes/charts/blob/foxish-patch-1/stable/grafana/values.yaml#L87 , how does the dashboard get this value and enable the end user can set this value on the dashboard?

**Comment by gyliu513** [comment]
One related issue is here https://github.com/kubernetes/charts/issues/1539

**Comment by ryandawsonuk** [comment]
Is anyone able to offer an update on this? My impression from the comments is that this is a popular idea but no work is underway as yet. For now monocular addresses part of the requirement but not the deploy stage (except by giving a command to copy-paste). Was wondering if anyone could clarify or confirm.

**Comment by bacongobbler** [comment]
Closing this issue as stale for over a year. If you're interested to work on this, please comment here and we can re-open this. Thanks!

**Comment by kfox1111** [comment]
The sad thing is, kube-dashboard is finally getting a plugin framework soon. So it may  be possible in the near future to integrate finally. I think that was the major thing holding up this issue.
