### ISSUE TITLE
Issue getting file:// working as dependency repository.

### ISSUE THREAD

**Issue by mahgo** [helm/helm#9901]
I'm struggling to get a file:// repository for a dependency of my chart working. The chart folder is charts/foobar/chart relative to my chart folder (which contains my Chart.yaml), so I have the repository of my dependency as such: `repository: file://charts/foobar/chart`. However, when I go to install my chart (`helm install mychart .`) I get the following error: `Error: error unpacking foobar in mychart: Chart.yaml file is missing` What's the correct way to do this? 

I'm running helm in WSL2 on Windows 10.

Maybe it would be good to have https://helm.sh/docs/helm/helm_dependency/ updated with an example file structure. 

Output of `helm version`:
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

**Comment by bacongobbler** [comment]
If charts are embedded in your `charts` directory, there is no need to include it as a "dependency" as it's already included in the chart.

When you declare a dependency, `helm dependency update` will look for that chart in the specified location and download it into the `charts` directory. So in essence you are re-including the chart twice.

You have two options:

1. move the chart out of the `charts` directory, and reference it using the `repository: file://` notation
2. move `charts/foobar/chart` to `charts/foobar` and remove the `repository: file://` notation completely from your Chart.yaml, since it is already included in the dependency tree.

From https://helm.sh/docs/chart_best_practices/dependencies/#repository-urls:

> Helm cannot perform dependency management operations on the dependency when the repository field is left blank. In that case Helm will assume the dependency is in a sub-directory of the charts folder with the name being the same as the name property for the dependency.

Hope that helps.
