### ISSUE TITLE
Helm rollback removes the changes done prior to the rollback

### ISSUE THREAD

**Issue by raul1991** [helm/helm#9909]
Lets say I am at `Release 1` and I have a config map with the following data in it

# Change 1

```yaml

from: release-1

```

# Change 2

I do some changes to this map

```yaml

from: release-2
edited: true
```

and I transition to Release 2 via `helm upgrade`

Say the newer release updated another key in it

# Change 3

```yaml

from: release-3
edited: true
```
Now If I rollback, I go back to change 1 instead of change 2. Why is that ? Is there a way to preserve the changes I did before the rollback ?

**Comment by yxxhero** [comment]
How did you edit it? @raul1991 kubeclt edit???

**Comment by raul1991** [comment]
I use fabric8 to edit them when my rest endpoint is hit.

Not sure what fabric8 does internally, probably hitting the master api endpoints ?

**Comment by yxxhero** [comment]
Yes. I think use the master api endpint. if you want to save change into helm release. You should use `helm upgrade` command. @raul1991

**Comment by mattfarina** [comment]
@raul1991 `helm rollback` is designed to roll back to a previous version. This is useful if a release has gone wrong and you need to get back to what was there before. In order to do this, Helm stores the older versions that were applied to the cluster but that does not include out of band changes to those releases. The changes are not available for Helm to use as part of a restore.

`helm upgrade` can preserve changes because it can do a 3 way diff between the old version, the new version, and what's in the cluster.

I would also suggest what @yxxhero did and use `helm upgrade` to change that piece of configuration if you want to also rollback.

**Comment by raul1991** [comment]
@mattfarina thanks for the clarification. So that clears out why I am unable to get my results back.

Also, in order to preserve out of band changes done prior to upgrade I use a hack.

By this hack,  I copy the contents of what already exits in the config map in the cluster (which includes out of band changes) into the config map. In this way those values are retained during an upgrade operation. FYI, I do this via `lookup` function.

I am in search of something like or maybe completely diff hack that can help me keep the changes after the rollback too..
