### ISSUE TITLE
install action increases memory usage by significant amount

### ISSUE THREAD

**Issue by extbe** [helm/helm#9913]
Hi.

I use helm client in my containerized Golang web application. Each run of the `Install` action uses around 30MB of memory. If I run more than one request in parallel, the memory consumption will increase by `~30MB * NumberOfRequests` and as a result the container will stop with an `Out Of Memory` error. Is such memory consumption normal?

I've created [a sample project](https://github.com/extbe/helm-ram-usage) to reproduce such behavior.

I also used Pprof to investigate memory consumption and here are the results:

- After application start
![1](https://user-images.githubusercontent.com/20598171/124606904-06693f00-de76-11eb-8fd4-d6e22e8d3533.png)

- After first run of the `Install` action
![2](https://user-images.githubusercontent.com/20598171/124607164-42040900-de76-11eb-9dfa-799412fa0767.png)

-After second run of the `Install` action
![3](https://user-images.githubusercontent.com/20598171/124607213-4c260780-de76-11eb-841a-4be248d35507.png)

**Comment by mattfarina** [comment]
Thanks for putting this together.

I just want to make sure I have it right, when an install completes the memory is released, right? If not, there is a memory leak somewhere.

The memory path in red comes from packages produced by the Kubernetes project that Helm imports in order to interact with Kubernetes clusters. It looks like they have to do with the Open API Schema interaction. Disabling that may reduce memory but you would not be able to validate the schema before sending it to the cluster.

Unfortunately, as this is an upstream library we cannot directly make reduce its memory usage.

**Comment by extbe** [comment]
Thanks for the answer.

Yes, you're right, the memory is released. 

In this case I'll close this issue and try to get some help from the Kubernetes project.
