### ISSUE TITLE
How to switch connect to multipul k8s cluster when run helm?

### ISSUE THREAD

**Issue by hillbun** [helm/helm#9927]
How to switch connect to multipul k8s cluster when run helm?

I have multipul kube config files in /root/.kube/ directory.

**Comment by cndoit18** [comment]
You can switch the k8s cluster with the parameter `--kube-context` or `--kubeconfig`

**Comment by mattfarina** [comment]
Helm uses your kubeconfig and the current context, by default. You can use other tools to set the current context which will change the location Helm uses. This is the same as how kubectl works. You can use the `--kube-context` flag to specify a context other than the current context and the `--kubeconfig` flag to specify a kubeconfig file other than the default.

**Comment by hillbun** [comment]
Is it possible just simplely setup environment variable but not use --kube-context or --kubeconfig flag?

**Comment by mattfarina** [comment]
The `--kubeconfig` flag can be set as the environment variable `KUBECONFIG`. This affects other Kubernetes tools such as `kubectl`. The `--kube-context` flag can be set with the environment variable `HELM_KUBECONTEXT`. The `helm env` command will show you the Helm specific environment variables and their current values. `KUBECONFIG` isn't listed because it is not helm specific but helm uses it.
