### ISSUE TITLE
Custom resources should update with three way merge patch

### ISSUE THREAD

**Issue by wxdao** [helm/helm#9937]
Builtin resources like Deployment update with three way merge as expected. However custom resources like istio VirtualService update with two way merge patch which I think isn't expected.

Looking at the code it seems that custom resources are parsed as unstructured objects, an a two way merge patch is used for these objects.

https://github.com/helm/helm/blob/433b90c4b6010415524bfd98b77efca0e6ec7205/pkg/kube/client.go#L457

kubectl apply uses `jsonmergepatch.CreateThreeWayJSONMergePatch` to create three way merge patch for unstructured objects as well:

https://github.com/kubernetes/kubectl/blob/b83b2ec7d15f286720bccf7872b5c72372cb8e80/pkg/cmd/apply/patcher.go#L129

I'd like to file a PR for this if the current behavior isn't intended.

**Comment by mattfarina** [comment]
Nice catch. I think this is a bug.

In the [Helm 2 to 3 FAQ](https://helm.sh/docs/faq/changes_since_helm2/#improved-upgrade-strategy-3-way-strategic-merge-patches) it notes:

> In Helm 3, we now use a three-way strategic merge patch. Helm considers the old manifest, its live state, and the new manifest when generating a patch.

This section doesn't make a distinction between CRs and built-in resources. I've also added this to the Helm meeting discussion for this week.

**Comment by bacongobbler** [comment]
It is possible that a future update to kubernetes replaced the jsonpatch library with this new one to accommodate cases like CRDs. Taylor and I paired on this section of the code and we matched Helm’s code to be near identical with kubernetes, diverging only to handle certain error cases.

**Comment by wxdao** [comment]
> It is possible that a future update to kubernetes replaced the jsonpatch library with this new one to accommodate cases like CRDs. Taylor, Adam and I paired on this section of the code and we matched Helm’s code to be near identical with kubernetes, diverging only to handle certain error cases.

Speaking of this, I suggest a future Helm version to adapt server side apply to ease any further hassle to sync with kubectl apply's implementation. This approach has more stable behavior, and will sooner or later become their default strategy.

**Comment by bacongobbler** [comment]
Agreed, however the implementation details of server-side apply were still in beta when we were developing Helm 3. In addition we have to retain backwards compatibility so that users running older versions of Helm 3 with the client-side apply logic can upgrade to a newer version with the server-side apply logic WITHOUT introducing backwards-incompatible changes. When we were investigating that scenario in early versions of Helm 3, it was discovered some breaking changes to the release metadata would occur, so we stopped pursuing that further and decided to punt that down the road.

Once server-side apply has reached a more stable state we can look further into its details (or better yet, we'd welcome PRs/discussions on how to move forward with that).

**Comment by mattfarina** [comment]
From the Helm dev call...

- The three way merge was just for build-ins and not CRs. This has to do with what the underlying k8s libs could do when this code was written. The docs were not specific enough (a bug) and the change to add three way merge to CRs is a feature.
- Changing to three way merge for CRs would be a behavior changes (feature so a minor or major release to change). If this goes into a minor release it will need to sit behind a flag to opt-in. If this goes into Helm v3 than than in v4 the flag could be dropped and this could just happen automatically.
